Correctly handle non deterministic operators on top of replicated distribution
greenplum-db/gpdb pull request #10978
Opened 2020-10-14 17:47 UTC by asubramanya

When a query contains non deterministic operators on top of a replicated
distribution of tuples, the resulting distribution produced by these operators
is no longer replicated. Examples of such operators are global Limit, Window
Aggs, non trivial Aggs. They produce a "Tainted" form of replicated
distribution. ORCA does not have a way to represent this type of distribution.
In order to support this we require a "GeneralReplicated"
distribution spec and a "TaintedReplicated" distribution spec.

2020-10-15 17:26 UTC, chrishajas commented
Haven't reviewed code yet. Can you also mention the previous PR (https://github.com/greenplum-db/gpdb/pull/10505) in the PR message so it links back to the previous discussion. What is the new issue that is resolved using this PR vs the previous PR? Are the commits starting with "Derive tainted replicated for ComputeScalar if it contains" new to this PR compared to the previous PR? Please also add corresponding minidump tests for these new code paths (or icg if more applicable).

Does this PR fix issue https://github.com/greenplum-db/gpdb/issues/10419? If so, there's a FIXME in rpt.sql that might be resolved.

2020-10-15 22:14 UTC, zellerh reviewed
I am sorry for causing you to take a detour last time you submitted a similar PR!

Very good change to combine the required distribution spec and match type into a single method!

Overall looks good to me, with a few questions, e.g. on how we handle replication in unions, and the following question: I am wondering what happens when a strict replication requirement meets an operator that is tainted replicated. As far as I understand, this would generate a broadcast motion, but can the executor really handle such a motion from tainted replicated to strict replicated?

Note that other operators such as CPhysicalFilter have a similar problem with replication when they call volatile functions. Those operators use a different strategy, they just ask for singleton execution instead of deriving a tainted replicated distribution. I guess that could be changed in the future.

2020-10-15 22:14 UTC, zellerh commented on src/backend/gporca/libgpopt/src/base/CDistributionSpecReplicated.cpp
> +//	| GeneralReplicated       | T                | T                 |
Don't we also need a row for a required strict replication?

2020-10-19 19:36 UTC, zellerh approved these changes
Thanks for addressing the comments.

2020-10-19 19:36 UTC, zellerh commented on src/backend/gporca/libgpopt/src/base/CDistributionSpecReplicated.cpp
> +//	| Replicated              | T                | T                 |
I think there is another line missing for a "strict replicated" requirement:
```suggestion
//	| Replicated              | T                | T                 |
//	| Strict Replicated       | T                | F                 |
```

2020-10-19 19:38 UTC, zellerh commented
> I am wondering what happens when a strict replication requirement meets an operator that is tainted replicated. As far as I understand, this would generate a broadcast motion, but can the executor really handle such a motion from tainted replicated to strict replicated?

Just tried this out and it seems to work:

```
drop table if exists test_src, test_tgt;
create table test_tgt (a serial, b integer) distributed replicated;
create table test_src (b integer) distributed replicated;
insert into test_src(b) values (1), (2), (3);
insert into test_tgt(b) select * from test_src;
select * from test_tgt;
```

2020-10-20 21:27 UTC, chrishajas reviewed
The use of terminate() is new in the codebase. What are the implications of this?

2020-10-21 01:28 UTC, asubramanya commented on src/backend/gporca/libgpopt/src/operators/CPhysicalAgg.cpp
> +		// Aggregate functions cannot guarantee replicated data. If the child
Updated the comment.

2020-10-21 01:28 UTC, asubramanya commented on src/backend/gporca/libgpopt/src/operators/CPhysicalHashJoin.cpp
> +		return ped->PdsRequired();
I think you're right. I have updated the code to AddRef the distribution spec and release the ped object.

2020-10-21 01:28 UTC, asubramanya commented on src/backend/gporca/libgpopt/src/operators/CPhysicalSequenceProject.cpp
> +		// Sequence project (i.e. window functions) cannot guarantee replicated
Updated the comment.

2020-10-21 01:28 UTC, asubramanya commented on src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXL.cpp
> +	if (CDistributionSpec::EdtStrictReplicated ==
Done.

2020-10-21 01:28 UTC, asubramanya commented on src/backend/gporca/libgpopt/src/base/CDistributionSpecReplicated.cpp
> +//	pprs = requested distribution
Done.

2020-10-21 01:28 UTC, asubramanya commented on src/backend/gporca/libgpopt/src/base/CDistributionSpecReplicated.cpp
> +//	| GeneralReplicated       | T                | T                 |
Done.

2020-10-21 01:29 UTC, asubramanya commented on src/backend/gporca/libgpopt/src/operators/CPhysicalSequenceProject.cpp
> +		// Some sequence project (i.e. window functions) cannot guarantee replicated`
Done.

2020-10-21 01:29 UTC, asubramanya commented on src/backend/gporca/libgpopt/src/base/CDistributionSpecReplicated.cpp
> +//	| Replicated              | T                | T                 |
Done.

2020-10-21 01:29 UTC, asubramanya commented on src/backend/gporca/data/dxl/minidump/InsertNonSingleton.mdp
> +CREATE TABLE snackbox (a int) DISTRIBUTED REPLICATED;
Added the objectives for relevant mdps.

2020-10-21 01:29 UTC, asubramanya commented on src/backend/gporca/libgpopt/src/operators/CPhysicalLimit.cpp
> +		// guarantee that property and must now dervive tainted replicated.
Updated.

2020-10-21 01:32 UTC, asubramanya commented on src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalCorrelatedInnerNLJoin.h
> +		std::terminate();
Yes. Since we refactored the PdsRequired method into a Ped method for certain operators, we wanted to make sure that we don't end up calling the PdsRequired method accidentally. We can probably change this to an explicit fallback.

2020-11-02 18:06 UTC, d commented
The refactoring to eliminate `PdsRequired` and `Edm` and converge to `Ped` seems unfinished. When do we plan to finish it?

2020-11-02 18:32 UTC, d commented
> The use of terminate() is new in the codebase. What are the implications of this?

I think I added this when we were working on #10505. The point is twofold:

1. We were hopeful that we could "sweep" through the codebase and finish the refactoring to completely transition from PdsRequired + Edm to Ped(). A `std::terminate()` in the short term guarantees to catch any programming error that inadvertently calls an unimplemented `PdsRequired`
1. In the event we couldn't finish the refactoring, we need some way to more clearly mark the dead ends so we can make sure we come back

2020-11-02 18:36 UTC, d commented
I'm reviewing this

2020-11-02 18:48 UTC, d commented on src/backend/gporca/libgpopt/src/operators/CPhysicalUnionAll.cpp
> +			CDistributionSpec::EdtTaintedReplicated == edtChild)
I concur, with @zellerh . In fact, I'm surprised we didn't test this scenario. It's pretty easy to surface this like the following:

```sql
CREATE TEMP TABLE grandma (x int) DISTRIBUTED REPLICATED;
CREATE TEMP TABLE yolo (a int) DISTRIBUTED REPLICATED;
CREATE TEMP TABLE foo (c int) DISTRIBUTED REPLICATED;

EXPLAIN INSERT INTO foo
  SELECT * FROM yolo WHERE a > random()
  UNION ALL
  SELECT * FROM grandma;
```

2020-11-02 19:13 UTC, d commented on src/backend/gporca/libgpopt/src/operators/CPhysicalSequenceProject.cpp
> +		// Some sequence project (i.e. window functions) cannot guarantee replicated
I think this comment is misleading. The nature of replication tainting of windowing is not those functions but the window framing clauses. If the window framing combined with the function's input column is under-specified, we lose the "pure" replicated guarantee.

2020-11-02 19:20 UTC, d requested changes
The lack of rebase makes reviewing this locally a bit challenging. So far a couple points of comment:

1. I think we need more careful handling in `UNION ALL`. The previous assumption that "all replicated look alike" no longer holds.
1. The comment about sequence project need to be more clear. Unlike agg, windowed relations are inherently sensitive to ordering because window definitions may define ordering within the window partitioning.

Might be able to give another round of review after a rebase

2020-11-03 22:58 UTC, d commented
Travis CI reports that we failed the formatting check

2020-11-04 01:16 UTC, asubramanya commented
@d Thanks reviewing. We have a story in the backlog to get rid of the `PdsRequired` method altogether. We will get to it soon.

2020-11-04 01:16 UTC, asubramanya commented on src/backend/gporca/libgpopt/src/operators/CPhysicalSequenceProject.cpp
> +		// Some sequence project (i.e. window functions) cannot guarantee replicated
updated.

2020-11-05 01:44 UTC, asubramanya commented on src/backend/gporca/libgpopt/src/operators/CPhysicalHashJoin.cpp
> +			GPOS_ASSERT(CDistributionSpec::EdtStrictReplicated == pds->Edt());
You're right. I've updated the ASSERT.

2020-11-05 01:44 UTC, asubramanya commented on src/backend/gporca/libgpopt/src/operators/CPhysicalSerialUnionAll.cpp
> +	if (CDistributionSpec::EdtStrictReplicated == pdsOuter->Edt())
done.

2020-11-05 01:44 UTC, asubramanya commented on src/backend/gporca/libgpopt/src/operators/CPhysicalUnionAll.cpp
> +			CDistributionSpec::EdtTaintedReplicated == edtChild)
done.

2020-11-17 18:30 UTC, merged