docs - add content for the optimizer_enable_indexonlyscan guc
greenplum-db/gpdb pull request #11290
Opened 2020-12-17 21:07 UTC by lisakowen

add info about this config param to the guc reference.

doc review site link:  http://docs-lisa-gp-oeios.cfapps.io/6-13/ref_guide/config_params/guc-list.html#optimizer_enable_dml

2020-12-17 21:38 UTC, dgkimura approved these changes
Looks good to me.

2020-12-17 22:21 UTC, vraghavan78 requested changes

2020-12-17 22:31 UTC, dgkimura commented on gpdb-doc/dita/ref_guide/config_params/guc-list.xml
> +        Planner.</p>
It shouldn't fall back to planner.  If optimizer_enable_tablescan and optimizer_enable_indexscan are off then it could fall back.  Probably this is unnecessary to information for the docs.

2020-12-17 22:36 UTC, lisakowen commented
thanks for reviewing @vraghavan78 and @dgkimura - i removed the fallback part of that statement.

2020-12-18 18:00 UTC, dyozie approved these changes

2020-12-18 18:00 UTC, dyozie commented on gpdb-doc/dita/ref_guide/config_params/guc-list.xml
> +        <codeph>true</codeph> (the default), GPORCA generates index-only scan
generates -> can generate

2020-12-18 18:00 UTC, dyozie commented on gpdb-doc/dita/ref_guide/config_params/guc-list.xml
> +        (i.e. they are visible).</p>
i.e. -> for example,

2020-12-18 18:00 UTC, dyozie commented on gpdb-doc/dita/ref_guide/config_params/guc-list.xml
> +      <p>When disabled (<codeph>false</codeph>), GPORCA does not generate
Maybe add something like: (only the Postgres Planner generates index-only scans)

2020-12-18 18:44 UTC, lisakowen commented on gpdb-doc/dita/ref_guide/config_params/guc-list.xml
> +      <p>When disabled (<codeph>false</codeph>), GPORCA does not generate
not sure if that is relevant here; i think that there need to be a certain combination of guc settings in place for gporca to fallback to the planner.

2020-12-18 19:26 UTC, vraghavan78 approved these changes

2020-12-18 19:46 UTC, merged