Allow Orca to handle empty target list
greenplum-db/gpdb pull request #11302
Opened 2020-12-22 19:11 UTC by dgkimura

There existed several assertions that disallowed an empty target list
since pre-GPDB 4. This is likely due the lack of support in executor
pre-v10 (ref Postgres commit e1b8e0e4a61).

Postgres v10 fixed this issue (ref Postgres commit c4c2885cbb1). After
removing the assertions then Orca can also handle an empty target list
without falling back to Planner:

```
postgres=# EXPLAIN SELECT UNION SELECT;
                      QUERY PLAN
------------------------------------------------------
 Aggregate  (cost=0.00..0.00 rows=1 width=1)
   ->  Append  (cost=0.00..0.00 rows=2 width=1)
         ->  Result  (cost=0.00..0.00 rows=1 width=1)
         ->  Result  (cost=0.00..0.00 rows=1 width=1)
 Optimizer: Pivotal Optimizer (GPORCA)
(5 rows)
```

2020-12-22 22:21 UTC, d approved these changes
LGTM. :shipit: 

I noticed one thing, but it shouldn't be a showstopper:

1. When we are doing a non-`UNION` set operation (i.e. `EXCEPT` or `INTERSECT`) and at least one side is distributed, the plan seems to be busted

2020-12-22 22:53 UTC, d requested changes
Hmm, I changed my mind. I'm still not sure if any of the previous "couple of things" are showstoppers, but I've found one definite showstopper:

```sql
CREATE TEMP TABLE foo ();
EXPLAIN (COSTS OFF) SELECT * FROM foo UNION SELECT FROM foo;

                   QUERY PLAN                   
------------------------------------------------
 Aggregate
   ->  Gather Motion 3:1  (slice1; segments: 3)
         ->  Append
               ->  Seq Scan on foo
               ->  Seq Scan on foo foo_1
 Optimizer: Pivotal Optimizer (GPORCA)
(6 rows)

```

The above plan is wrong. It might be a bit subtle, but notice how we are doing a "plain aggregate":

```
   {PLANNEDSTMT 
   :commandType 1 
   :planGen 1 
   :queryId 0 
   :hasReturning false 
   :hasModifyingCTE false 
   :canSetTag true 
   :transientPlan false 
   :oneoffPlan false 
   :simplyUpdatableRel 0 
   :dependsOnRole false 
   :parallelModeNeeded false 
   :jitFlags 0 
   :planTree 
      {AGG 
      :startup_cost 0.00 
      :total_cost 862.00 
      :plan_rows 1 
      :plan_width 1 
      :parallel_aware false 
      :parallel_safe false 
      :plan_node_id 0 
      :targetlist <> 
      :qual <> 
      :lefttree 
         {MOTION 
         ...
         }
      :righttree <> 
      :initPlan <> 
      :extParam (b)
      :allParam (b)
      :flow <> 
      :operatorMemKB 0 
      :aggstrategy 0 
      :aggsplit 0 
      :numCols 0 
      :grpColIdx  
      :grpOperators  
      :grpCollations  
      :numGroups 1 
      :aggParams (b)
      :groupingSets <> 
      :chain <> 
      :streaming false 
      :agg_expr_id 0
      }
   :rtable (
      ...
   )
   ...
   }

```

Notice the `aggstrategy 0`, it's a plain agg, meaning that it's similar to an aggregate without any `GROUP BY`. This will lead to wrong results, when `foo` is empty: we expect the result set will be empty, but a plain agg will produce one row.

2020-12-22 22:54 UTC, d commented
The fact that ICW passes means that we have a small coverage gap here, also

2021-01-30 01:22 UTC, dgkimura commented
Thanks @d for the insight. Rather than leave this hanging much longer, I'm closing with intent to revisit later.

Notes for myself: I had explored adding logic into `CXformGbAgg2HashAgg::Exfp()` and `CXformGbAgg2ScalarAgg::Exfp()` to handle the case Jesse mentioned and prevent the bad plan.  It _seems_ to work, but probably needs more thought.

2021-01-30 01:22 UTC, closed without merging