Coerce unknown-type literals to type text instead of cstring
greenplum-db/gpdb pull request #11360
Opened 2021-01-13 06:43 UTC by adam8157

```
CREATE VIEW unknown_v1 AS SELECT '2020-12-13'::unknown AS
field_unknown;
CREATE VIEW unknown_v2 AS SELECT field_unknown::date FROM unknown_v1;
```

The definition was this before this commit:
```
SELECT unknown_v1.field_unknown::cstring::date AS field_unknown
  FROM unknown_v1;
```
Which would error out with `ERROR: cannot cast type cstring to date`.

This commit coerces unknown-type literals to type text instead of
cstring while converting stored expressions/querytrees back to source
text.

Upstream also chose text, Greenplum 7 too (PR #9655, #9686), but they
broke behaviors, we could not do that refactor on 6X_STABLE branch.

    commit 1e7c4bb0049732ece651d993d03bb6772e5d281a
    Author: Tom Lane <tgl@sss.pgh.pa.us>
    Date:   Wed Jan 25 09:17:18 2017 -0500

        Change unknown-type literals to type text in SELECT and RETURNING lists.

        Previously, we left such literals alone if the query or subquery had
        no properties forcing a type decision to be made (such as an ORDER BY or
        DISTINCT clause using that output column).  This meant that "unknown" could
        be an exposed output column type, which has never been a great idea because
        it could result in strange failures later on.  For example, an outer query
        that tried to do any operations on an unknown-type subquery output would
        generally fail with some weird error like "failed to find conversion
        function from unknown to text" or "could not determine which collation to
        use for string comparison".  Also, if the case occurred in a CREATE VIEW's
        query then the view would have an unknown-type column, causing similar
        failures in queries trying to use the view.

        To fix, at the tail end of parse analysis of a query, forcibly convert any
        remaining "unknown" literals in its SELECT or RETURNING list to type text.
        However, provide a switch to suppress that, and use it in the cases of
        SELECT inside a set operation or INSERT command.  In those cases we already
        had type resolution rules that make use of context information from outside
        the subquery proper, and we don't want to change that behavior.

        Also, change creation of an unknown-type column in a relation from a
        warning to a hard error.  The error should be unreachable now in CREATE
        VIEW or CREATE MATVIEW, but it's still possible to explicitly say "unknown"
        in CREATE TABLE or CREATE (composite) TYPE.  We want to forbid that because
        it's nothing but a foot-gun.

        This change creates a pg_upgrade failure case: a matview that contains an
        unknown-type column can't be pg_upgraded, because reparsing the matview's
        defining query will now decide that the column is of type text, which
        doesn't match the cstring-like storage that the old materialized column
        would actually have.  Add a checking pass to detect that.  While at it,
        we can detect tables or composite types that would fail, essentially
        for free.  Those would fail safely anyway later on, but we might as
        well fail earlier.

        This patch is by me, but it owes something to previous investigations
        by Rahila Syed.  Also thanks to Ashutosh Bapat and Michael Paquier for
        review.

        Discussion: https://postgr.es/m/CAH2L28uwwbL9HUM-WR=hromW1Cvamkn7O-g8fPY2m=_7muJ0oA@mail.gmail.com

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2021-01-14 09:00 UTC, zhangh43 approved these changes

2021-01-16 03:47 UTC, d commented
Hi @adam8157 what's the problem we are solving here? Please know that changing a core piece like the parser carries a significant risk of breaking the catalog or storage ...

> ```
> CREATE VIEW unknown_v1 AS SELECT '2020-12-13'::unknown AS
> field_unknown;
> CREATE VIEW unknown_v2 AS SELECT field_unknown::date FROM unknown_v1;
> ```
> 
> 
> The definition was this before this commit:
> 
> 
> ```
> SELECT unknown_v1.field_unknown::cstring::date AS field_unknown
>   FROM unknown_v1;
> ```
> 
> 
> Which would error out with `ERROR: cannot cast type cstring to date`.

I'm sorry but I cannot reproduce this error on the latest 6.13. To be clear, I _can_ get a similar error you described on the last release of Postgres 9.4 (unsupported now).

Jesse

2021-01-16 04:28 UTC, d requested changes
This patch doesn't include a correctly failing test. Specifically, the included test only fails with a cosmetically different output.

The one-line code change does *not* really change any functionality (hence it's not fixing any bug). In fact, for the motivating example, we are not even *really* generating the advertised coercion path of `unknown::text::date`. Instead, we are merely *markin* the output of function `unknownout` (which actually returns `cstring`) as returning `text`. The next function in the coercion path `date_in` takes a `cstring` as input and would ignore the advertised `text` type (it's fake news anyway).

2021-01-16 12:40 UTC, adam8157 commented
`\d+ unknown_v2` would show this without the patch, I was testing against 6X_STABLE.

```
SELECT unknown_v1.field_unknown::cstring::date AS field_unknown
  FROM unknown_v1;
```

`SELECT * FROM unknown_v2;` has no issue, but if we dump then restore,
the restored unknown_v2 would have `::cstring::date` for real (not just
dumping), which errors out. A customer reported it.

The better option is removing the Greenplum hack of the `unknown` type, but
it changes behavior. The other solution is coercing to `text`, I assume it would
be safe because upstream and master branch does a similar thing.

The test would fail because it shows a different definition without the patch.

And about your UDF concern, a function could not have `CString` as its input,
that's a PostgreSQL rule.

Sorry I haven't described it very clearly. How do you think now?

2021-01-21 22:47 UTC, d commented
> but if we dump then restore,
> the restored unknown_v2 would have `::cstring::date` for real (not just
> dumping), which errors out. A customer reported it.

Hmmm, thank you for clarifying, that sounds less troubling. I still have some doubts. Give me 2 hours.

2021-01-21 23:30 UTC, d commented
> Sorry I haven't described it very clearly. How do you think now?

To rephrase, the problem you're trying to solve is: if a view is casting an `unknown` column to another type that's not really convertible (as per the catalog), the view becomes impossible to dump-and-restore. Right? But your solution doesn't make such views any _more_ dumpable because even after applying the patch, we will need to _drop all offending views_ so that views created after the update are dumpable.

I don't think such a fix really fixes the problem. Requiring a `DROP` is not really acceptable here. What if it's a materialized view?

In fact, if one has to solve the problem by dropping a view and recreating it (in addition to a server upgrade), they might as well correct the issue of having an unknown column in the first place.

@ashwinstar thoughts?

2021-01-25 01:37 UTC, adam8157 commented
It doesn't need to drop, without this commit, it dumped as `unknown::cstring::date`, with this commit it dumps as `unknown::text::date`.

2021-02-17 18:12 UTC, d commented
> It doesn't need to drop, without this commit, it dumped as `unknown::cstring::date`, with this commit it dumps as `unknown::text::date`.

Sorry I wasn't clear about my comment: an offending view will dump as `unknown::cstring::date`, regardless of the presence of this patch, so fixing the problem still involves dropping the offending object and recreating them (with this patch). That said, I'm more concerned about `pg_upgrade` not guarding such views. It's important that we do a best-effort adaptation in `pg_upgrade` at the same time as this kind of change goes in, because it will be impossible to create an offending view in the first place once we land this change.

2021-02-18 06:57 UTC, asimrp commented
Indeed.  And pg_upgrade will fail to restore the schema on the new cluster if such views are present in the old cluster.  A guard to check for existence of such views will enable pg_upgrade to fail early.

2021-02-19 02:29 UTC, adam8157 commented
At a clean 6X_STABLE build:

```
CREATE VIEW unknown_v1 AS SELECT '2020-12-13'::unknown AS field_unknown;
CREATE VIEW unknown_v2 AS SELECT field_unknown::date FROM unknown_v1;
```

pg_dump -s -t unknown_v2：
···
CREATE VIEW public.unknown_v2 AS
 SELECT ((unknown_v1.field_unknown)::cstring)::date AS field_unknown
   FROM public.unknown_v1;
···

patch && make install && gpstop -ar && pg_dump -s -t unknown_v2:
```
CREATE VIEW public.unknown_v2 AS
 SELECT ((unknown_v1.field_unknown)::cstring)::date AS field_unknown
   FROM public.unknown_v1;
```

Ah, you are right, @d . I remembered it would change, which was clearly a mistake.

Seems 6X would keep going with this issue, closing.

2021-02-22 19:32 UTC, d commented
@adam8157 sorry was buried in a lot of work last week. Apologies for not making my opinion clear, and not in time:

1. I think we can still try to "fix" something like this, after all, we're cleaning after our own mess
2. A good compromise would be we add some best-effort check in `pg_upgrade` for such busted views on upgrade, while fixing this existing parser behavior.
3. I haven't thought this through, but does this give us a way out of continue supporting this hack in the parser? @ashwinstar What if we add in the `pg_upgrade` check, then just yank out the hack from parser?

2021-02-23 07:00 UTC, adam8157 commented
Reopen this, we still have the possibility to "fix" it, working with `pg_upgrade` changes.

2021-03-09 08:44 UTC, adam8157 commented
Updated the pg_upgrade codes, `pg_upgrade` could detect the views with `unknown::cstring` cast.

```
A list of views is in the file:
        view_unknown_casts.txt

Failure, exiting

$ cat view_unknown_casts.txt
Database: gpadmin
  public.unknown_v2
```

master and 5X branch need to backport corresponding parts of this.

2021-04-12 06:05 UTC, adam8157 commented
Hi, @d, am I OK to merge this? I completed the pg_upgrade part. Thanks.

2021-04-12 17:58 UTC, d approved these changes

2021-04-12 17:58 UTC, d commented
Be safe, be vaccinated! :mechanical_arm:

2021-04-12 23:25 UTC, merged