Fix that kill_9_segment_processes can not get a list of processes to kill.
greenplum-db/gpdb pull request #11378
Opened 2021-01-18 12:02 UTC by lchx1010

It can not get a list of postgres processes in the kill_9_segment_processes function when the gpdb system is running. Thanks for your review.
Please see the log below : 
[gpadmin@mdw ~]$ ps ux | grep "[p]ostgres:\s*port\s*5434" | awk '{print $2}'
[gpadmin@mdw ~]$ ps ux | grep "[p]ostgres:\s*5434" | awk '{print $2}'
8873
8876
8877
8878
8879
8881
8894
8896
8897
8941
[gpadmin@mdw ~]$ ps ux | grep "[p]ostgres:\s*5434" 
gpadmin  8873  0.0  0.0 239984  5264 ?        Ss   Jan16   0:02 postgres:  5434, master logger process   
gpadmin  8876  0.0  0.0 477124  8500 ?        Ss   Jan16   0:00 postgres:  5434, checkpointer process   
gpadmin  8877  0.0  0.0 477012  4960 ?        Ss   Jan16   0:00 postgres:  5434, writer process   
gpadmin  8878  0.0  0.0 477012  8648 ?        Ss   Jan16   0:00 postgres:  5434, wal writer process   
gpadmin  8879  0.0  0.0 242372  4864 ?        Ss   Jan16   0:01 postgres:  5434, stats collector process   
gpadmin  8881  0.0  0.0 545160 12304 ?        Ssl  Jan16   0:11 postgres:  5434, bgworker: ftsprobe process   
gpadmin  8894  0.0  0.0 242100  6992 ?        Ss   Jan16   0:03 postgres:  5434, bgworker: ic proxy process   
gpadmin  8896  0.0  0.0 477012  4360 ?        Ss   Jan16   0:04 postgres:  5434, bgworker: sweeper process   
gpadmin  8897  0.0  0.0 477012  4864 ?        Ss   Jan16   0:36 postgres:  5434, bgworker: stats sender process   
gpadmin  8941  0.0  0.0 477148  4856 ?        Ss   Jan16   1:20 postgres:  5434, bgworker: metrics collector 

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2021-01-18 12:02 UTC, pivotal-issuemaster commented
@lchx1010 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=11378)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=11378) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2021-01-19 08:07 UTC, lchx1010 commented
I sign the Contributor License Agreement! But I do not know if I have successfully signed the CLA, because the check of ci/pivotal-cla is not successful. Can you tell me? Thank you very much!

2021-01-19 09:17 UTC, pivotal-issuemaster commented
@lchx1010 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=11378)!

2021-01-20 01:20 UTC, asimrp reviewed
@lchx1010 thanks for your contribution, looks good to me.  One question - how did you discover this problem?  Is it possible to add a test case so that we can detect such a breakage in regex automatically?

2021-01-21 08:53 UTC, zhangh43 approved these changes
Good catch! This function only be called when pg_ctl stop failed. So it didn't reflected by the current regression test. 6X also has this issue.

2021-01-21 13:16 UTC, lchx1010 commented
@asimrp First of all, thanks for your reply. 
I encountered the problem while I was operating the GPDB database some time ago.
After analyzing the script, I found the postmaster process was killed, but its child processes were not killed and it would be handed over init process to deal with. Maybe something is wrong with the logic. And, before the child processes are not reclaimed by the init process, it will have problems when starting the database again.
Furthermore，what do you mean by adding a test case to detect such a breakage in regex automatically? Thank you very much. I am very happy to explore the gpdb.

2021-01-21 13:21 UTC, lchx1010 commented
@zhangh43 Thanks for your review!

2021-01-22 10:55 UTC, asimrp commented
> what do you mean by adding a test case to detect such a breakage in regex automatically?

@lchx1010 I mean adding a test to automate the scenario that you've encounter before.  We have quite a few existing tests that automate complex scenarios.  As an example, I would like to point out [gpstop behave tests](https://github.com/greenplum-db/gpdb/blob/master/gpMgmt/test/behave/mgmt_utils/gpstop.feature)  and the [implementation to back up the steps](https://github.com/greenplum-db/gpdb/blob/master/gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py) in the behave feature.

2021-01-25 12:43 UTC, lchx1010 commented
@asimrp Thanks for your illustration.  It is helpful and deserves a try. Thank you!

2021-04-26 09:51 UTC, gfphoenix78 commented on gpMgmt/bin/gppylib/commands/unix.py
> +                  cmdStr='ps ux | grep "[p]ostgres:\s*%s" | awk \'{print $2}\'' % (port))
I've tested this command on both `centos7` and `ubuntu18.04`, it only works on centos7. The output of `ps ux` is different on the two OSs.
`ps -ef | grep "postgres:\s*%s" | awk \'{print $2}\'` works on both OSs.

Could you add a test for this function?

2021-04-26 10:08 UTC, gfphoenix78 requested changes
This patch should fix the issue on ubuntu18.04

2021-04-26 10:23 UTC, gfphoenix78 commented on gpMgmt/bin/gppylib/commands/unix.py
> +                  cmdStr='ps ux | grep "[p]ostgres:\s*%s" | awk \'{print $2}\'' % (port))
`ps -aeo pid,cmd | grep "postgres:\s*%s" | awk \'{print $1}\'` also works on both OSs.

2021-04-26 12:10 UTC, lchx1010 commented
@gfphoenix78 Thanks for your review, I will test the function on ubuntu18.04.

2021-04-30 09:20 UTC, lchx1010 commented on gpMgmt/bin/gppylib/commands/unix.py
> +                  cmdStr='ps ux | grep "[p]ostgres:\s*%s" | awk \'{print $2}\'' % (port))
Hi，I have tested the command on ubuntu 18.04. However, The output of this command is the same as that of the command `ps -ef | grep "postgres:\s*%s" | awk \'{print $2}\'`. 
Could you tell me your test results? Looking forward to your reply. Thank you very much!

Here is my test log:
gpadmin@mdwubuntu:~$ ps -ef | grep "postgres:\s*5432" | awk '{print $2}'
10803
10806
10807
10808
10809
10810
10811
10818
gpadmin@mdwubuntu:~$ ps ux | grep "postgres:\s*5432" | awk '{print $2}'
10803
10806
10807
10808
10809
10810
10811
10818
gpadmin@mdwubuntu:~$ ps -ef | grep "postgres:\s*5432" | awk '{print $2}' | wc -l
8
gpadmin@mdwubuntu:~$ ps ux | grep "postgres:\s*5432" | awk '{print $2}' | wc -l
8
gpadmin@mdwubuntu:~$ ps -ef | grep "[p]ostgres:\s*5432"
gpadmin  10803 10802  0 15:46 ?        00:00:00 postgres:  5432, master logger process
gpadmin  10806 10802  0 15:46 ?        00:00:00 postgres:  5432, checkpointer process
gpadmin  10807 10802  0 15:46 ?        00:00:00 postgres:  5432, writer process
gpadmin  10808 10802  0 15:46 ?        00:00:00 postgres:  5432, wal writer process
gpadmin  10809 10802  0 15:46 ?        00:00:00 postgres:  5432, stats collector process
gpadmin  10810 10802  0 15:46 ?        00:00:00 postgres:  5432, bgworker: dtx recovery process
gpadmin  10811 10802  0 15:46 ?        00:00:00 postgres:  5432, bgworker: ftsprobe process
gpadmin  10818 10802  0 15:46 ?        00:00:00 postgres:  5432, bgworker: sweeper process
gpadmin@mdwubuntu:~$ ps ux | grep "[p]ostgres:\s*5432"
gpadmin  10803  0.0  0.0 201156  4548 ?        Ss   15:46   0:00 postgres:  5432, master logger process
gpadmin  10806  0.0  0.0 432720  7148 ?        Ss   15:46   0:00 postgres:  5432, checkpointer process
gpadmin  10807  0.0  0.0 432588  6032 ?        Ss   15:46   0:00 postgres:  5432, writer process
gpadmin  10808  0.0  0.0 432588  4628 ?        Ss   15:46   0:00 postgres:  5432, wal writer process
gpadmin  10809  0.0  0.0 203408  4936 ?        Ss   15:46   0:00 postgres:  5432, stats collector process
gpadmin  10810  0.0  0.1 507316 22580 ?        Ssl  15:46   0:00 postgres:  5432, bgworker: dtx recovery process
gpadmin  10811  0.0  0.1 500700 18368 ?        Ssl  15:46   0:00 postgres:  5432, bgworker: ftsprobe process
gpadmin  10818  0.0  0.0 432588  4640 ?        Ss   15:46   0:00 postgres:  5432, bgworker: sweeper process
gpadmin@mdwubuntu:~$
gpadmin@mdwubuntu:~$ ps -aeo pid,cmd | grep "postgres:\s*5432" | awk '{print $1}'
10803
10806
10807
10808
10809
10810
10811
10818

gpadmin@mdwubuntu:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
gpadmin@mdwubuntu:~$ psql -c "select version();"

  version

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------
-----------
 PostgreSQL 9.4.24 (Greenplum Database 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c Open Source)
 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit compiled on Apr 22 202
1 21:23:41
(1 row)

gpadmin@mdwubuntu:~$

2021-07-09 02:27 UTC, gfphoenix78 commented on gpMgmt/bin/gppylib/commands/unix.py
> +                  cmdStr='ps ux | grep "[p]ostgres:\s*%s" | awk \'{print $2}\'' % (port))
`ps ux` shows the processes owned by the current user. It's fine.

2021-07-09 02:27 UTC, gfphoenix78 approved these changes

2021-07-09 02:30 UTC, merged

2021-07-09 02:33 UTC, paul-guo- commented
We'd better backport this fix.

2021-07-09 03:03 UTC, gfphoenix78 commented
> We'd better backport this fix.

Sure, I've opened the PR for 6X and verifying whether we need to backport for GPDB 5X.