Do not increment modcount after AO compaction
greenplum-db/gpdb pull request #11423
Opened 2021-01-27 08:27 UTC by jimmyyih

After the change of having the primary segments self-managing their AO
segment files, external utilities (e.g. gpbackup and analyzedb) needed
to change the method of obtaining the modcount to determine if an
incremental change has been made (for incremental backup or
analyze). To do this, the utilities were simply updated to gather and
sum the modcounts directly off the primary segments. However, AO
compaction during a VACUUM would increment the modcount of the target
segment file entry (e.g. in pg_aoseg catalog) due to the bulk insert
and give the utilities a false positive of a DML/DDL change. This is a
minor regression from what was observed in older GPDB versions where
AO compaction would not send a modcount update to the coordinator
segment.

To fix the issue, simply change the final step of AO compaction to not
increment the modcount value.

GPDB commit reference:
https://github.com/greenplum-db/gpdb/commit/5778f31124d5
https://github.com/greenplum-db/gpdb/commit/67321b1ceebc

gpbackup commit reference:
https://github.com/greenplum-db/gpbackup/commit/d181e4c7bc76

2021-01-27 19:59 UTC, ashwinstar requested changes

2021-01-27 19:59 UTC, ashwinstar commented on src/include/cdb/cdbappendonlyam.h
> +extern void appendonly_insert_finish(AppendOnlyInsertDesc aoInsertDesc, bool incrementModCount);
Instead of changing the API for the `appendonly_insert_finish()` function, seems better would be to add `incrementModCount` to `AppendOnlyInsertDesc`. That would keep the change localized. `AppendOnlyCompact()` creates the `AppendOnlyInsertDesc` so can easily convey via this flag in desc. Also, negating the flag would be better like 'avoidModCountIncrement`. Default we do `palloc0()` hence will only need to set it to `true` for compaction case. This way very few places in code will be touched.

2021-01-27 19:59 UTC, ashwinstar commented on src/test/regress/output/appendonly.source
> +VACUUM ao_vacuum_no_increment;
Should we use `vacuum full` instead or query some way to make sure compaction is triggered? Like in future if threshold rules are changed maybe compaction is not triggered itself that would negate the test.

2021-01-27 19:59 UTC, ashwinstar commented on src/backend/access/aocs/aocsam_handler.c
> +	aocs_insert_finish(idesc, true);
Doesn't cluster fall in same bucket as compaction (where we don't need to bump modcount)?

2021-01-28 01:25 UTC, jimmyyih commented on src/include/cdb/cdbappendonlyam.h
> +extern void appendonly_insert_finish(AppendOnlyInsertDesc aoInsertDesc, bool incrementModCount);
Yeah, that's definitely much more preferable.  Changed.

2021-01-28 01:38 UTC, jimmyyih commented on src/test/regress/output/appendonly.source
> +VACUUM ao_vacuum_no_increment;
I deleted the new tests as I forgot there were AO compaction isolation2 tests that will cover this change.  Updated answer files.

As for ensuring compaction trigger on those AO compaction isolation2 tests, I don't think VACUUM FULL should be the answer as we would want to cover the regular VACUUM paths which may change in the future too.  If anything, a fault injector to always force compaction on all segment files might be useful maybe.

2021-01-28 02:02 UTC, jimmyyih commented on src/backend/access/aocs/aocsam_handler.c
> +	aocs_insert_finish(idesc, true);
Definitely an interesting question... CLUSTER operation on an AO table falling into the same buck as compaction is a bit debatable for this "false positive" scenario.  For CLUSTER, it could be considered as an intended modcount increment to trigger incremental backup or ANALYZE.  For backup, the new physical tuple order would be maintained on restore.  For ANALYZE, it could be to update the statistics after the reordering to make sure query plans are correct (not 100% sure about this, just stuff I read on the internet).  There might be some merit to keeping the modcount increment.

But if we do decide to skip the modcount increment for CLUSTER, it would not use the same logic from this PR.  Since CLUSTER recreates the table, the AO segment entries are fresh with special segno 0 (and modcount 1 since it's technically an index-sorted COPY into a new staging table).  If we wanted to preserve the summed modcount, we would have to sum all the modcounts from the previous AO segment table and update the new AO segment table.  It's definitely doable but we would have to decide if CLUSTER needs to skip or not first (and probably make a separate PR).

2021-01-28 18:21 UTC, ashwinstar commented on src/backend/access/aocs/aocsam_handler.c
> +	aocs_insert_finish(idesc, true);
Nice points. For AO I understand for now its the case. Though in generally considering SELECT and later INSERT would populate the tables physically in same order is incorrect assumption to carry. It totally depends on the storage layout and scan order etc...

Given the complication mentioned in second paragraph and also CLUSTER being such infrequent action. Seems not worth it to spend any cycles on optimizing for it.

2021-01-28 18:49 UTC, ashwinstar approved these changes
LGTM

2021-01-28 18:49 UTC, ashwinstar commented on src/test/regress/gpstringsubs.pl
> +	$psql_str .= " -X -t -A -c 'show LC_CTYPE'";
Nice catch!

2021-01-28 21:59 UTC, jimmyyih commented on src/backend/access/aocs/aocsam_handler.c
> +	aocs_insert_finish(idesc, true);
Yeah, I think it should be fine.  CLUSTER is meant to be used more for static data sets anyways (I'm assuming the user has to rerun CLUSTER every time there's an insert) so I don't see incremental backup/analyze being too useful for it.

2021-01-28 22:00 UTC, merged