Documenting --hba-hostnames flag. Story URL: https://www.pivotaltrack…
greenplum-db/gpdb pull request #11440
Opened 2021-01-29 01:13 UTC by VMWareJennyBeth

…er.com/story/show/176488739

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2021-01-29 17:42 UTC, dyozie requested changes

2021-01-29 17:42 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpaddmirrors.xml
> +                    <pd>Optional. Controls whether <codeph>gprecoverseg</codeph> uses IP addresses or host
This option description should be specifying `gpaddmirrors` instead of `gprecoverseg`, though. To generalize this so it can be used for all the utilities, maybe just say "Specifies whether this utility uses IP addresses or host names when modifying the `pg_hba.conf` file."

The description should also probably recommend something like: "For consistency, use the same value that was specified for `HBA_HOSTNAMES` when the Greenplum Database system was initialized."

2021-01-29 19:07 UTC, lenapivotal approved these changes
Just one comment about linking other docs to this location

2021-01-29 19:25 UTC, Nirali13 approved these changes

2021-01-29 19:25 UTC, Nirali13 commented on gpdb-doc/dita/utility_guide/ref/gpaddmirrors.xml
> +                        updating this file. For consistency, use the same value that was specified for
suggestion: updating this file -> updating the file

2021-01-29 20:28 UTC, VMWareJennyBeth commented on gpdb-doc/dita/utility_guide/ref/gpaddmirrors.xml
> +                        updating this file. For consistency, use the same value that was specified for
Good catch. Made that change.

2021-01-29 22:17 UTC, VMWareJennyBeth commented on gpdb-doc/dita/utility_guide/ref/gpaddmirrors.xml
>                  <plentry>
I think this is an interesting idea but is beyond the scope of this particular story. I will capture this elsewhere and we can discuss further.

2021-01-30 00:13 UTC, dyozie approved these changes

2021-01-30 00:13 UTC, merged