Imporve gpload merge performance
greenplum-db/gpdb pull request #11465
Opened 2021-02-03 09:49 UTC by fanfuxiaoran

In merge mode, when inserting the data from the staging
table into the base table, gpload uses a left join sql
to pick up the data which doesn't exist in the base
table. This leads to poor performance when the base
table is big (more than 1 billion): greenplum will hash
the base table and that generates a lot of spill files.

To improve the performance, we decided not to use the
left join sql. Instead, we delete the rows in staging
table which have already existed in the base table so
we can directly insert new rows left in staging table
and avoid left outer join.

Co-authored-by: XiaoxiaoHe <hxiaoxiao@vmware.com>

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2021-02-04 02:38 UTC, xiaoxiaoHe-E approved these changes

2021-02-10 04:43 UTC, beeender commented on gpMgmt/bin/gpload.py
> +                strE = str(str(e), errors = 'ignore')
why use `str` not `unicode` here?
Line 2794 is using `unicode`?

2021-02-23 01:46 UTC, fanfuxiaoran commented on gpMgmt/bin/gpload.py
> +                strE = str(str(e), errors = 'ignore')
> why use `str` not `unicode` here?
> Line 2794 is using `unicode`?

On master branch, gpload uses str instead unicode to process the error string.
@xiaoxiaoHe-E  Do you have any idea?

2021-02-24 02:32 UTC, lij55 commented on gpMgmt/bin/gpload.py
> +                strE = str(str(e), errors = 'ignore')
The reason is that there might be error of illegal unicode character of this statement `sql.encode('utf-8')`. Continue using `unicode` in the except part will make it raise exception again.

2021-02-24 02:36 UTC, xiaoxiaoHe-E commented on gpMgmt/bin/gpload.py
> +                strE = str(str(e), errors = 'ignore')
I think use `unicode` is better. Python version is 3  in the master branch and 2 in 6X. Python 2, 3 have different definitions to `str` and `unicode`. It's better to keep consistent in each branch.

2021-02-25 03:03 UTC, lij55 commented on gpMgmt/bin/gpload.py
> +                strE = str(str(e), errors = 'ignore')
I believe there is a customer jira that force us to change from unicode to str. Changing back to unicode will definitely introduce regression

2021-02-25 03:08 UTC, lij55 requested changes
unocide is not suitable in exception catching

2021-02-25 03:23 UTC, lij55 approved these changes

2021-02-25 03:38 UTC, merged