Limit anyarray coercion to INSERT statements
greenplum-db/gpdb pull request #11506
Opened 2021-02-10 20:42 UTC by soumyadeep2007

The anyarray coercion logic was added circa 2008 to accommodate INSERT
statements into catalog tables such as pg_statistic, which sport the
anyarray type - a pseudo-type that does not handle insertions.

However, `coerce_type()` is a very low level function that has a variety
of callsites. The logic added has an adverse effect on views, for e.g.
that have an OpExpr with array types:

```sql
CREATE VIEW fooview AS SELECT '{1}'::int[] = '{2}'::int[];

\d+ fooview
                 View "public.fooview"
  Column  |  Type   | Modifiers | Storage | Description
----------+---------+-----------+---------+-------------
 ?column? | boolean |           | plain   |
View definition:
 SELECT '{1}'::anyarray = '{2}'::anyarray;
```

We can see that the view definition includes incorrect downcasts to the
pseudo-type anyarray. (It should have been
`SELECT '{1}'::integer = '{2}'::integer;`)

Running the view definition inevitably yields:

```sql
ERROR:  cannot accept a value of type anyarray
LINE 1: SELECT '{1}'::anyarray = '{2}'::anyarray;
```

We fix this issue by restricting the scope of the type coercion logic to
INSERTs only, in line with what was originally intended.

Co-authored-by: Jimmy Yih <jyih@pivotal.io>

2021-02-10 20:42 UTC, soumyadeep2007 commented
This needs a backport to 5X. Coming soon.

2021-02-10 22:53 UTC, ashwinstar commented
Lets discuss the expectations with this fix

- Views with arrays created for GPDB6 versions before this fix will be in broken state
- Even after binary upgrading to the fixed version those views will stay in broken state
- Views dumped from gpdb6 versions without fix will also be in broken state
- Only new views created after upgrading to fixed version will have correct syntax

This raises the similar concerns as raised on PR #11360 by @d, that to really get the fix one have to drop and recreate such views. Which effectively kind of acts as catalog change bucket category fix (even though nothing really breaks directly after upgrading to newer version but doesn't fix either).

If we have no other route we might have to take this step, just flagging this makes it much harder as within same major version the behavior differs.

2021-02-10 23:39 UTC, jimmyyih commented
That's an interesting take.  The argument that drop/recreate after applying the fix is border-line unacceptable is hard to back since the stored view is technically corrupted due to a bug in CREATE VIEW (with no way to recover the original array type since it's been replaced by the pseudo-type anyarray).  It's kinda similar to when a table is corrupted due to a bug in CREATE TABLE (or some table related feature)... we fix the bug and may need to tell users to drop/recreate the table (usually with CTAS).  But with a view, it's much simpler since only the stored VIEW parse tree is corrupted.

There is a workaround... but that workaround involves dropping and recreating the view (recreate the view without explicit casts and let the parser choose the cast... instead of explicitly casting and having the explicit cast be replaced by a bad anyarray cast).  No matter what, the user has to drop and recreate the view anyways.  At least with this patch, the user only has to do it once and forget about it.  IMO, it's worth it to have these preventive patches merged in else we'll just get the same bug report over and over until GPDB 6 is EOL.

2021-02-17 01:52 UTC, ashwinstar commented
Agree @jimmyyih for now seems best we can do is fix this issue and help as much as we can. Even if the recovery is painful (view recreation) to take advantage.

2021-02-17 02:14 UTC, ashwinstar approved these changes
@d please take a look as well

2021-02-17 03:54 UTC, d requested changes
Hmm, this is a catalog change.

Can we at least update `pg_upgrade` to guard against views like this? Have a best effort detection for it and halt the upgrade, tell the user to drop the view, and good stuff like that?

J

2021-02-17 06:00 UTC, asimrp reviewed
Running the view definition in the PR description reports no error for me on 6X_STABLE:
```
postgres=# \d+ fooview
                 View "public.fooview"
  Column  |  Type   | Modifiers | Storage | Description 
----------+---------+-----------+---------+-------------
 ?column? | boolean |           | plain   | 
View definition:
 SELECT '{1}'::anyarray = '{2}'::anyarray;

postgres=# select * from fooview;
 ?column? 
----------
 f
(1 row)
```
However, dumping the view and then restoring it fails with `ERROR:  cannot accept a value of type anyarray`.

+1 to merge this patch, but I see Jesse's point.  We also need to ensure that `pg_upgrade` fails as early as possible, if views like this are found before upgrade.

2021-02-17 06:03 UTC, asimrp commented
In the same vein, PR #11360 can also be merged after changing `pg_upgrade` to look for offending views and abort if found.

2021-02-17 06:18 UTC, soumyadeep2007 commented
> However, dumping the view and then restoring it fails with ERROR: cannot accept a value of type anyarray.

Yes that too. What I meant by running the view definition was:
```
postgres=#  SELECT '{1}'::anyarray = '{2}'::anyarray;
psql: ERROR:  cannot accept a value of type anyarray
LINE 1: SELECT '{1}'::anyarray = '{2}'::anyarray;
```

I'll make that more clear in the commit message. Thanks for trying it out!

I assume that for pg_upgrade to detect a view with an anyarray cast like this, we would have to write some sort of walker that will traverse the query tree.

2021-02-17 06:20 UTC, soumyadeep2007 commented on src/backend/parser/parse_coerce.c
> +		   && pstate->p_expr_kind == EXPR_KIND_INSERT_TARGET)
Good catch!

2021-02-17 06:38 UTC, jimmyyih commented
> I assume that for pg_upgrade to detect a view with an anyarray cast like this, we would have to write some sort of walker that will traverse the query tree of the view (pg_rewrite.ev_action) we can do a query with LIKE against the catalog.

Could maybe do something like this fancy piece of work that's already in pg_upgrade checks:
https://github.com/greenplum-db/gpdb/blob/247402806820d36075e6d56f9902480c03c0d476/contrib/pg_upgrade/greenplum/check_gp.c#L1193

2021-02-17 19:20 UTC, d commented
> Could maybe do something like this fancy piece of work that's already in pg_upgrade checks:

Oh boy, #10849 was the bad example to mimic. Instead of a kludgy text search, we can install a server side function to properly walk the parse tree, no?

2021-02-18 00:36 UTC, d commented
Talked to @soumyadeep2007 off-Github. I think we explored options for `pg_upgrade` to detect the offending views:

1. We can do a kludgy text search à la #10849 as long as we can tolerate the fairly high chance of false positives
2. We can also inject a server-side function into the `pg_upgrade` support module that's loaded during binary upgrade, and let the `pg_upgrade` binary call that: as usual, this will bump the required minimum version of the "old server" in 6->6 and 6->7 upgrade

2021-02-19 02:04 UTC, soumyadeep2007 commented
@d @ashwinstar:

@kyeap-vmware and I added a commit with the pg_upgrade check. Please take a look.

@greenplum-db/cluster-management team: As a follow-up item to this PR and the 5x backport of this, we would need the min version bumped for GPDB6 and GPDB5 (this PR will be backported to 5X) for gpupgrade as this PR (and the 5X PR) includes a new UDF in pg_upgrade_support. (This UDF would need to be present on the 5X cluster during a 5->6 upgrade and a 6x cluster in a 6->7 upgrade)

2021-02-19 16:48 UTC, dkrieger-pvtl commented
> @greenplum-db/cluster-management team: As a follow-up item to this PR and the 5x backport of this, we would need the min version bumped for GPDB6 and GPDB5 (this PR will be backported to 5X) for gpupgrade as this PR (and the 5X PR) includes a new UDF in pg_upgrade_support. (This UDF would need to be present on the 5X cluster during a 5->6 upgrade and a 6x cluster in a 6->7 upgrade)

@soumyadeep2007  Thanks for the heads up.  We are now tracking this.  Please reference the 5X PR from this one, as we are watching this PR.   In general, we ask customers to migrate only from the latest version of 5X to the latest version of 6X, so this should not be an issue.  We also run [migration scripts](https://github.com/greenplum-db/gpupgrade/tree/master/data-migration-scripts) as a way to avoid our customers being in a pg_upgrade check loop, where they must re-run pg_upgrade check(run in `gpugprade initialize`) after every check that fails.  This was the least bad option we could come up with, as it did not seem reasonable to have pg_upgrade pick up from where it left off.  So we replicate many of the pg_upgrade checks in the data_migration scripts.  Those scripts pre-drop database objects that will cause pg_upgrade to fail, and then re-add them after a successful upgrade.  So we'll want to add that to gpugrade for these views as well.

2021-02-19 19:56 UTC, ashwinstar commented on contrib/pg_upgrade/greenplum/check_gp.c
> +	prep_status("Checking for views with corrupted anyarray casts");
"corrupted" sounds very negative and alarming term (even without upgrade will instill fear of data corruption). Maybe replace it with "Checking for views which can't be properly dumped" or something on similar lines.

2021-02-19 19:56 UTC, ashwinstar commented on contrib/pg_upgrade/greenplum/check_gp.c
> +		pg_fatal("Your installation contains views having corrupted anyarray\n"
In the same spirit as above avoid the usage of "corrupted" word here as well

2021-02-19 19:56 UTC, ashwinstar commented on contrib/pg_upgrade/greenplum/check_gp.c
> +									 "AS '$libdir/pg_upgrade_support' "
I am confused how this works. If we are upgrading from GPDB5 version which doesn't have this function to GPDB6 with this fix, won't this `CREATE FUNCTION` fail?

2021-02-19 19:56 UTC, ashwinstar commented on contrib/pg_upgrade/greenplum/check_gp.c
> +		PQclear(executeQueryOrDie(conn, "SET search_path TO 'public';"));
If you check `install_support_functions_in_new_db()` it creates `binary_upgrade` schema for such activity instead of creating functions in `public` schema. Seems we should follow similar pattern.

Did we have an where else in pg_upgrade pattern where upgrade installs anything in old cluster? I see it does on new cluster.

2021-02-19 19:56 UTC, ashwinstar commented on contrib/pg_upgrade/greenplum/check_gp.c
> +				 "casts. These views need to be dropped before proceeding to upgrade. \n"
Need to be dropped, how can they be recreated we need to provide recommendation even for that.

2021-02-19 19:56 UTC, ashwinstar commented on contrib/pg_upgrade/greenplum/check_gp.c
> +								"SELECT relname AS badviewname "
I think we need to emit namespace as well along with name of view

2021-02-19 19:56 UTC, ashwinstar commented on contrib/pg_upgrade_support/pg_upgrade_support.c
> +
this newline reads odd

2021-02-19 20:03 UTC, soumyadeep2007 commented on contrib/pg_upgrade/greenplum/check_gp.c
> +									 "AS '$libdir/pg_upgrade_support' "
The idea is that we will be backporting this fix to 5X as well. So it will have this function in pg_upgrade_support.c. So the CREATE FUNCTION will not fail. The minimum version requirement for 5x will be bumped in gpupgrade so that customers are notified.

2021-02-19 20:07 UTC, soumyadeep2007 commented on contrib/pg_upgrade/greenplum/check_gp.c
> +		PQclear(executeQueryOrDie(conn, "SET search_path TO 'public';"));
> If you check install_support_functions_in_new_db() it creates binary_upgrade schema for such activity instead of creating functions in public schema. Seems we should follow similar pattern.

We tried placing it in the `binary_upgrade` schema. However the schema is not created **before** the checks are performed, so we couldn't access it. This is why we opted to place it in the public schema and then take it out immediately after.

> Did we have an where else in pg_upgrade pattern where upgrade installs anything in old cluster? I see it does on new cluster.

I don't think so. Not anything that we saw.

2021-02-19 20:07 UTC, d commented on contrib/pg_upgrade/greenplum/check_gp.c
> +									 "AS '$libdir/pg_upgrade_support' "
We want this to fail, right? @ashwinstar

2021-02-19 20:09 UTC, soumyadeep2007 commented on contrib/pg_upgrade/greenplum/check_gp.c
> +				 "casts. These views need to be dropped before proceeding to upgrade. \n"
Yup we will say what is said here: https://github.com/greenplum-db/gpbackup/pull/489/files#diff-f01a32748b1a2a5e63014b0355e5729de4c2233c3b34f27c0560caacd16f5ea9R348

2021-02-19 20:32 UTC, soumyadeep2007 commented
We are opening a separate PR for the pg_upgrade changes and merging this now.

2021-02-19 20:32 UTC, merged

2021-02-24 22:01 UTC, soumyadeep2007 commented
> > @greenplum-db/cluster-management team: As a follow-up item to this PR and the 5x backport of this, we would need the min version bumped for GPDB6 and GPDB5 (this PR will be backported to 5X) for gpupgrade as this PR (and the 5X PR) includes a new UDF in pg_upgrade_support. (This UDF would need to be present on the 5X cluster during a 5->6 upgrade and a 6x cluster in a 6->7 upgrade)
> 
> @soumyadeep2007 Thanks for the heads up. We are now tracking this. Please reference the 5X PR from this one, as we are watching this PR. In general, we ask customers to migrate only from the latest version of 5X to the latest version of 6X, so this should not be an issue. We also run [migration scripts](https://github.com/greenplum-db/gpupgrade/tree/master/data-migration-scripts) as a way to avoid our customers being in a pg_upgrade check loop, where they must re-run pg_upgrade check(run in `gpugprade initialize`) after every check that fails. This was the least bad option we could come up with, as it did not seem reasonable to have pg_upgrade pick up from where it left off. So we replicate many of the pg_upgrade checks in the data_migration scripts. Those scripts pre-drop database objects that will cause pg_upgrade to fail, and then re-add them after a successful upgrade. So we'll want to add that to gpugrade for these views as well.

Hey @dkrieger-pvtl and @greenplum-db/cluster-management team, I have some updates:
1. We couldn't merge the pg_upgrade bits with this PR by the 6.14.1 release window. So we opened a follow-up PR for 6X: 
#11542
2. We opened a consolidated backport of this PR and the 6X upgrade follow-up PR for 5X_STABLE: #11558