Follow-up: pg_upgrade check to detect views with anyarray casts
greenplum-db/gpdb pull request #11542
Opened 2021-02-19 22:56 UTC by soumyadeep2007

This PR is a follow-up to https://github.com/greenplum-db/gpdb/pull/11506

This commit introduces a new Greenplum check to see if there are any
views with corrupted view definitions (having anyarray casts), which
could arise from the special GPDB specific ANYARRAY coercion logic added
in parse_coerce.c: coerce_type() circa 2008.

The check makes use of a new support UDF that invokes a walker to figure
out if there are any anyarray casts in the view's query tree.

Since, the pg_node_tree type (column type of pg_rewrite.ev_action), does
not allow input, it is hard to bust the catalog in order to perform an
automated test. So we performed a manual test by creating the following busted
views created with server binaries not having the fix.

```sql
         View "public.v_anyarray_in_cte"
 Column | Type | Modifiers | Storage  | Description
--------+------+-----------+----------+-------------
 foo    | text |           | extended |
View definition:
 WITH cte AS (
         SELECT 'foo'::text AS foo
           FROM pg_class
          WHERE '{1}'::anyarray = '{2}'::anyarray
        )
 SELECT cte.foo
   FROM cte;

         View "public.v_anyarray_in_func_expr"
  Column  |  Type   | Modifiers | Storage | Description
----------+---------+-----------+---------+-------------
 ?column? | boolean |           | plain   |
View definition:
 SELECT array_agg(pg_database.oid)::integer[] OPERATOR(pg_catalog.=) '{1}'::anyarray
   FROM pg_database;

         View "public.v_anyarray_in_subselect"
  Column  |  Type   | Modifiers | Storage | Description
----------+---------+-----------+---------+-------------
 ?column? | integer |           | plain   |
View definition:
 SELECT 1
   FROM ( SELECT '{1}'::anyarray = '{1}'::anyarray) sub;

           View "public.v_anyarray_in_tlist"
  Column  |  Type   | Modifiers | Storage | Description
----------+---------+-----------+---------+-------------
 ?column? | boolean |           | plain   |
View definition:
 SELECT '{1}'::anyarray = '{1}'::anyarray;

           View "public.v_anyarray_in_where"
  Column  |  Type   | Modifiers | Storage | Description
----------+---------+-----------+---------+-------------
 ?column? | integer |           | plain   |
View definition:
 SELECT 1
   FROM pg_class
  WHERE '{1}'::anyarray = '{1}'::anyarray;

```

False positive test case (should not be flagged as a bad view by
pg_upgrade):
```sql
       View "public.v_anyarray_in_text_expr"
 Column  | Type | Modifiers | Storage  | Description
---------+------+-----------+----------+-------------
 textcol | text |           | extended |
View definition:
 SELECT 'blah::anyarray'::text AS textcol;
```

Co-authored-by: Kevin Yeap <kyeap@vmware.com>

2021-02-22 23:15 UTC, d commented on contrib/pg_upgrade/greenplum/check_gp.c
> +static void check_views_with_corrupted_anyarray_casts(void);
wording: do you have an alternative for the name here? I won't call it "corrupt", after all, the view _does_ represent what the parser believed. It's only corrupt in a moral sense, not "data integrity" sense. But I think I understand what you want to express here.

Have you considered `check_views_with_fabricated_anyarray_casts`? It still carries the "morally corrupt" connotation without the ambiguity of "did you corrupt my data WTF?"

2021-02-23 00:09 UTC, soumyadeep2007 commented on contrib/pg_upgrade/greenplum/check_gp.c
> +static void check_views_with_corrupted_anyarray_casts(void);
Yes that is much better. Will make the change! Thanks!

2021-02-23 02:35 UTC, d requested changes

2021-02-23 02:35 UTC, d commented on contrib/pg_upgrade/greenplum/check_gp.c
> +									 "CREATE OR REPLACE FUNCTION "
hmm, I believe the convention is to install the support functions under schema `binary_upgrade` which will be dropped at the end of upgrade

2021-02-23 02:35 UTC, d commented on contrib/pg_upgrade_support/pg_upgrade_support.c
> +}
```suggestion
		return constant->consttype == ANYARRAYOID && !constant->constisnull;
	}
	return query_or_expression_tree_walker(query, check_node_anyarray_walker, context, 0);
}

```

2021-02-23 17:38 UTC, soumyadeep2007 commented on contrib/pg_upgrade/greenplum/check_gp.c
> +									 "CREATE OR REPLACE FUNCTION "
We tried that. However, it seems that the binary_upgrade schema was not accessible (even after tinkering with search_path) at the time of the check - it must be installed later on in the game.

2021-02-23 18:07 UTC, soumyadeep2007 commented on contrib/pg_upgrade_support/pg_upgrade_support.c
> +}
We had tried this too and I tried it again just now, but unfortunately we end up recursing infinitely, with the following stack trace. 

```
check_node_anyarray_walker()
query_or_expression_tree_walker()
check_node_anyarray_walker()
query_or_expression_tree_walker()
...
```

The functionality we want is:
```
else if (IsA(node, Query))
	{
		/* recurse into subselects and ctes */
		Query *query = (Query *) node;
		return query_tree_walker(query, check_node_anyarray_walker, context, 0);
	}

	return expression_tree_walker(node, check_node_anyarray_walker,
								  context);
```
With `query_or_expression_tree_walker`,  we end up getting:

```
if (node && IsA(node, Query))
		return query_tree_walker((Query *) node,
								 walker,
								 context,
								 flags);
	else
		return check_node_anyarray_walker(node, context);
```

This leads to the infinite recursion when a non-query node is passed to `query_or_expression_tree_walker()`

2021-02-24 23:42 UTC, d commented on contrib/pg_upgrade/greenplum/check_gp.c
> +									 "CREATE OR REPLACE FUNCTION "
aaaaah

2021-02-24 23:44 UTC, d commented on contrib/pg_upgrade_support/pg_upgrade_support.c
> +}
oops I'm an idiot

2021-02-25 00:27 UTC, soumyadeep2007 commented on contrib/pg_upgrade_support/pg_upgrade_support.c
> +}
No worries, `query_or_expression_tree_walker` can be very misleading

2021-02-25 00:57 UTC, jimmyyih requested changes

2021-02-25 00:57 UTC, jimmyyih commented on contrib/pg_upgrade/greenplum/check_gp.c
> +								"SELECT format('%%s.%%s', n.nspname, c.relname) AS badviewname "
The `format()` function does not exist in GPDB 5.  I suggest keeping it simple and just use `n.nspname || '.' || c.relname AS badviewname`.  If we care about FQN, then `quote_ident(n.nspname) || '.' || quote_ident(c.relname) AS badviewname` should work.

2021-02-25 01:57 UTC, soumyadeep2007 commented on contrib/pg_upgrade/greenplum/check_gp.c
> +								"SELECT format('%%s.%%s', n.nspname, c.relname) AS badviewname "
Wait, I thought that we were not going to backport the check into 5X and only backport the pg_upgrade_support UDF.

2021-02-25 06:17 UTC, jimmyyih commented on contrib/pg_upgrade/greenplum/check_gp.c
> +								"SELECT format('%%s.%%s', n.nspname, c.relname) AS badviewname "
Isn't that `CREATE FUNCTION` going to run against the source 5X cluster when running gpupgrade?

2021-02-25 17:41 UTC, soumyadeep2007 commented on contrib/pg_upgrade/greenplum/check_gp.c
> +								"SELECT format('%%s.%%s', n.nspname, c.relname) AS badviewname "
It is..my bad, for some stupid reason I was forgetting that the query with `format` is going to be run on a 5X cluster when during an upgrade to 6X.

Nice catch! I will make the change.

2021-02-25 20:19 UTC, jimmyyih approved these changes

2021-02-26 19:33 UTC, merged

2021-03-18 07:14 UTC, adam8157 commented
Does the Greenplum master branch need this?

2021-03-18 16:43 UTC, soumyadeep2007 commented
@adam8157 Yes master will need this check too, along with a fix so that such views are not generated. We have been discussing offline ways to fix this for master (see the commit message: https://github.com/greenplum-db/gpdb/pull/11506)
We haven't yet attempted the fix as we will have to fix gpsd/minirepro as well if the hack mentioned above, is to be ripped out.