Added reference to RHEL 6 not supported on both sections
greenplum-db/gpdb pull request #11591
Opened 2021-03-03 21:18 UTC by mperezfuster

Here are the links of the staging app for review:
https://mireia-deeplearning.sc2-04-pcf1-apps.oc.vmware.com/7-0/analytics/madlib.html
https://mireia-deeplearning.sc2-04-pcf1-apps.oc.vmware.com/7-0/install_guide/install_python_dsmod.html

Note I have used the GPDB branded book since Python Data Science Module Package is only available on the branded GPDB docs.

2021-03-10 23:31 UTC, dyozie requested changes

2021-03-10 23:31 UTC, dyozie commented on gpdb-doc/dita/analytics/madlib.xml
> +          scope="external">Keras API </xref>using the Tensorflow backend. Note that it is not
Need a closing period (.) here.

2021-03-11 16:36 UTC, mperezfuster commented on gpdb-doc/dita/analytics/madlib.xml
> +          scope="external">Keras API </xref>using the Tensorflow backend. Note that it is not
sorted

2021-03-12 16:27 UTC, dyozie approved these changes

2021-03-12 16:27 UTC, merged