Docs - adding dblink new function dblink_connect_no_auth
greenplum-db/gpdb pull request #11626
Opened 2021-03-10 23:10 UTC by mperezfuster

Documented the following PR: https://github.com/greenplum-db/gpdb/pull/11566
Added a Warning section to highlight this is a high risk functionality and also mentioned that pg_hba.conf needs to be correctly configured for dblink_connect_u to work.
You can preview the page by using the following link (needs VPN access):
https://mireia-dblink-branded.sc2-04-pcf1-apps.oc.vmware.com/7-0/ref_guide/modules/dblink.html

2021-03-10 23:21 UTC, lij55 approved these changes

2021-03-11 20:34 UTC, dyozie requested changes

2021-03-11 20:34 UTC, dyozie commented on gpdb-doc/dita/ref_guide/modules/dblink.xml
> +            connection.<codeblock>testdb=# <b>GRANT EXECUTE ON FUNCTION dblink_connect_no_auth(text) TO test_user;</b>
No need to bold these - just codeblock format is fine.

2021-03-11 21:28 UTC, lisakowen commented on gpdb-doc/dita/ref_guide/modules/dblink.xml
> +            <codeph>dblink_connect_no_auth</codeph> provides this functionality as it bypasses the
(general) most of the other function references include a () - i.e. dblink_connect_no_auth()

2021-03-11 21:28 UTC, lisakowen commented on gpdb-doc/dita/ref_guide/modules/dblink.xml
> +        <note type="warning">Using these functions introduces a security risk; ensure that you grant
i was a little confused because the intro mentions a single function, and the note here refers to functions.  then i realized after reading farther down that there are two signatures for the function.

2021-03-11 21:28 UTC, lisakowen commented on gpdb-doc/dita/ref_guide/modules/dblink.xml
> +testdb=# GRANT EXECUTE ON FUNCTION dblink_connect_no_auth(text, text) TO test_user;</codeblock></li>
we never identify the signatures with parameter names so the user knows what the text fields correspond to.  (from reading below, it looks like (name, connectionstring) for the 2 parameter function.  i am not sure what the single parameter signature text field is - connection string?)

2021-03-11 22:28 UTC, dyozie approved these changes

2021-03-11 22:29 UTC, dyozie commented
Thanks @lenapivotal - I'm going to merge this in now so that it's part of the general 6.15 review, but please go ahead and make changes to address @lisakowen 's comments in a follow-on PR.

2021-03-11 22:30 UTC, merged

2021-03-12 18:10 UTC, lenapivotal commented
> Thanks @lenapivotal - I'm going to merge this in now so that it's part of the general 6.15 review, but please go ahead and make changes to address @lisakowen 's comments in a follow-on PR.

@dyozie not sure you got the right person here, this was done by @mperezfuster