Docs: Modified Upgrade PXF when GPDB
greenplum-db/gpdb pull request #11710
Opened 2021-03-24 21:30 UTC by mperezfuster

Edited some of the steps when upgrading PXF as part of a GPDB upgrade.
Unfortunately I am unable to provide preview link.

2021-03-24 22:03 UTC, bradfordb-vmware approved these changes

2021-03-24 22:30 UTC, lisakowen requested changes
thanks, these changes should help reduce confusion.

2021-03-24 22:30 UTC, lisakowen commented on gpdb-doc/markdown/pxf/upgrade_pxf_6x.html.md.erb
> +2. If you installed the PXF `rpm` on your Greenplum 6 hosts, you will need to register it in order to continue using PXF:
you will need to register it in order to continue using pxf -> you must register it to continue using pxf

2021-03-24 22:30 UTC, lisakowen commented on gpdb-doc/markdown/pxf/upgrade_pxf_6x.html.md.erb
> +2. If you are using the PXF version included with Greenplum Database installation, initialize PXF on each segment host as described in [Initializing PXF](../../pxf/5-15/init_pxf.html). You may choose
what about "To continue using the PXF version included in the Greenplum ..."?  if they are on this page, they were using embedded pxf in their previous greenplum.

2021-03-24 22:30 UTC, lisakowen commented on gpdb-doc/markdown/pxf/upgrade_pxf_6x.html.md.erb
> +Note: if you are planning in upgrading PXF but not as part of a Greenplum Database upgrade, refer to the [PXF Documentation](../../../pxf/5-15/upgrade_pxf_rpm.html)
planning in -> planning on?  or maybe ... planning to upgrade PXF ...

also, i am noticing that the other links to the pxf docset include only two dir levels up (../../), not three.

2021-03-29 15:50 UTC, dyozie approved these changes

2021-03-29 15:50 UTC, dyozie commented on gpdb-doc/markdown/pxf/upgrade_pxf_6x.html.md.erb
> +Note: if you are planning to upgrade PXF but not as part of a Greenplum Database upgrade, refer to the [PXF Documentation](../../pxf/5-15/upgrade_pxf_rpm.html)
Bold the **Note:**

2021-03-29 15:50 UTC, dyozie commented on gpdb-doc/markdown/pxf/upgrade_pxf_6x.html.md.erb
> +2. To continue using the PXF version included with Greenplum Database installation, initialize PXF on each segment host as described in [Initializing PXF](../../pxf/5-15/init_pxf.html). You may choos
with Greenplum -> with the Greenplum

2021-03-29 20:58 UTC, ashuka24 approved these changes

2021-03-29 22:17 UTC, dyozie approved these changes

2021-03-29 22:17 UTC, merged