Docs: added reference to tablespace mapping file for gpexpand utility
greenplum-db/gpdb pull request #11726
Opened 2021-03-29 20:37 UTC by mperezfuster

Reference to tablespace mapping file being generated by gpexpand utility if the cluster is configured with tablespaces.

2021-03-29 21:52 UTC, jmcatamney approved these changes

2021-03-30 23:11 UTC, dyozie requested changes

2021-03-30 23:11 UTC, dyozie commented on gpdb-doc/dita/admin_guide/expand/expand-initialize.xml
> +                the Greenplum cluster is configured with tablespaces, the utility will automatically
will automatically generate -> automatically generates

2021-03-30 23:11 UTC, dyozie commented on gpdb-doc/dita/admin_guide/expand/expand-initialize.xml
> +                the Greenplum cluster is configured with tablespaces, the utility will automatically
This will will be later parsed -> This file is required for later parsing

2021-04-19 15:20 UTC, dyozie approved these changes

2021-04-19 15:20 UTC, merged