docs: Gpmt tool reference
greenplum-db/gpdb pull request #11733
Opened 2021-03-30 17:28 UTC by mperezfuster

This PR replaces the Support KB article: https://community.pivotal.io/s/article/Greenplum-Magic-Tool-GPMT?language=en_US and the 4 linked articles from that one (some of them internal).

2021-03-30 20:25 UTC, VMWareJennyBeth commented on gpdb-doc/dita/utility_guide/ref/gpmt.xml
> +          <pd>For VMware Support use only. Backup catalog prior to performing catalog repairs.</pd>
Backup is one word when a noun. When a verb, use two: back up

2021-03-30 20:30 UTC, VMWareJennyBeth commented on gpdb-doc/dita/utility_guide/ref/gpmt.xml
> +          <pd>For VMware Support use only. Check if primary and mirror AO and AOCO relfiles are the
Check whether

2021-03-30 20:30 UTC, VMWareJennyBeth commented on gpdb-doc/dita/utility_guide/ref/gpmt.xml
> +          <pd>Check if tool is replicated to all hosts.</pd>
Check whether

2021-03-30 20:35 UTC, VMWareJennyBeth requested changes
Looks really good, Mireia. I had just a handful of suggestions.

2021-04-01 02:14 UTC, lenapivotal commented on gpdb-doc/dita/utility_guide/ref/gpmt.xml
> +    <section>
Have we agreed to add a VMware Support tool to the Greenplum docs? I find that a bit confusing. Who supports it and who owns it?

2021-04-01 13:12 UTC, mperezfuster commented on gpdb-doc/dita/utility_guide/ref/gpmt.xml
> +    <section>
Yes GPMT will be included with GPDB 5.x and 6.x and the KB article will be made private that's why Engineering have requested to have this documented within the docs. I am not sure but I presume they will own it from now on.

2021-04-05 18:23 UTC, dyozie requested changes

2021-04-05 18:23 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpmt-gp_log_collector.xml
> +          <pd>Comma seperated list of content IDs to collect logs from.</pd>
Also global change:

to collect logs from -> from which logs are collected

2021-04-05 18:23 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpmt-gp_log_collector.xml
> +            option to skip Greenplum Master log collection when only Greenplum Segment logs are
Master -> master segment
Segment -> segment

2021-04-05 18:23 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpmt-gp_log_collector.xml
> +    <p>
Make this an action Note element, and nest it in the --hostfile plentry above

2021-04-05 18:23 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpmt-gp_log_collector.xml
> +                <li><codeph>$SEG_DIRE/postgresql.conf</codeph></li>
SEG_DIRE -> SEG_DIR

2021-04-05 18:23 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpmt-gp_log_collector.xml
> +    <p>Note: some commands might not be able to be run if user does not have enough permission.</p>
Make into Note element, and reword to:

Some commands may require additional permission to run.

Also relocate this note to the table cell that lists the various commands.

2021-04-05 18:23 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpmt-gpstatscheck.xml
> +    <p>This tool can be used to verify if all tables involved in a query have optimal statistics.
can be used to verify if all -> helps to verify that

2021-04-05 18:23 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpmt-packcore.xml
> +    <p>This tool collects all the necessary files and generates a script to run the
to run the \<codeph>gdb\</codeph> command that makes -> that runs the \<codeph>gdb\</codeph> command to create

2021-04-05 18:23 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpmt-packcore.xml
> +        <codeph>gdb</codeph> command that makes a core file readable by an external host. It is used
It is used -> Use this command

2021-04-05 18:23 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpmt-packcore.xml
> +      <codeblock><b>gpmt</b> <b>packcore</b> -cmd COMMAND -core COREFILE [<varname>-binary BINARY </varname>]
Not sure what COMMAND  is referring to here. There should be a -cmd description in the options that are described to indicate what commands are available & what they do. If only `collect` is what they'd be doing, just add that as part of the required syntax.

2021-04-05 18:23 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpmt-packcore.xml
> +          <pd>Do not delete temp directory.</pd>
temp -> the temporary

2021-04-09 18:05 UTC, dyozie approved these changes

2021-04-09 18:05 UTC, merged