Remove a merge fixme about GetNewOidForAuthId()
greenplum-db/gpdb pull request #11768
Opened 2021-04-02 08:09 UTC by adam8157

Greenplum requires a pre-assigned auth id to keep QD and QEs synchronized in
binary upgrade mode, error out if there is no pre-assigned id as the merge
fixme says.

2021-04-02 11:29 UTC, asimrp commented
PR pipeline is not happy, `pg_upgrade` has failed.  Please take a look, @adam8157

2021-04-04 05:17 UTC, adam8157 commented
> PR pipeline is not happy, `pg_upgrade` has failed. Please take a look, @adam8157

Thanks for reviewing, now it passed.

2021-04-05 03:46 UTC, asimrp requested changes

2021-04-05 03:46 UTC, asimrp commented on src/backend/catalog/oid_dispatch.c
> +			if (IS_QUERY_DISPATCHER())
That is confusing.  We are already inside `if (Gp_role == GP_ROLE_EXECUTE || IsBinaryUpgrade)` block.  And the corresponding else block is dedicated to the case `(Gp_role == GP_ROLE_DISPATCH)`.   So something is not right with the proposed code change.

2021-04-06 02:08 UTC, adam8157 commented on src/backend/catalog/oid_dispatch.c
> +			if (IS_QUERY_DISPATCHER())
It's `GP_ROLE_UTILITY` and `IsBinaryUpgrade` on the coordinator node here.

`pg_upgrade` establishes the connection as `GP_ROLE_UTILITY`, first on the coordinator node creates the schema, then on the segments retores with the pre-assigned OIDs.

2021-04-08 02:07 UTC, adam8157 commented on src/backend/catalog/oid_dispatch.c
> +			if (IS_QUERY_DISPATCHER())
I added redundant checks here, `(IS_QUERY_DISPATCHER() && IsBinaryUpgrade && Gp_role == GP_ROLE_UTILITY)`

2021-05-07 06:30 UTC, adam8157 commented
Have fixed the concern, will merge this the next day if no objection, thanks for the review.

2021-05-08 02:43 UTC, merged