gpconfig: aborting a config update with down host should exit properly
greenplum-db/gpdb pull request #11765
Opened 2021-04-02 00:38 UTC by divyeshddv

When a host is down, and a user runs gpconfig to update any config on an unreachable host: we warn them and ask for confirmation to continue with the config update. If the user chooses to abort the update, we currently do not exit out properly due to (non daemon) threads staying open when exiting.

This change fixes the abort/exit to close threads

We also remove use of GpHostCache as part of this change and instead use functions from GpArray

Tracker story: https://www.pivotaltracker.com/story/show/177336745

2021-04-09 21:48 UTC, kalensk approved these changes
LGTM.

(For next time, consider waiting until the master PR has been approved/merged and then simply cherry-pick the changes to 6X. This should make things easy.)

2021-04-26 10:26 UTC, gfphoenix78 requested changes

2021-04-26 10:26 UTC, gfphoenix78 commented on gpMgmt/bin/gpconfig
> +        msg = "normalized_host=%s host=%s dir=%s" % (hostname, directory)
The string format expects 3 arguments.

2021-04-26 21:16 UTC, divyeshddv commented on gpMgmt/bin/gpconfig
> +        msg = "normalized_host=%s host=%s dir=%s" % (hostname, directory)
Thanks for catching this. Fixed

2021-04-27 02:10 UTC, gfphoenix78 approved these changes

2021-04-27 20:00 UTC, merged