Docs: modified last gpexpand step and added steps for pxf
greenplum-db/gpdb pull request #11813
Opened 2021-04-14 16:25 UTC by mperezfuster

I have renamed the last step "Removing the Expansion Schema" to "Post Expansion Tasks" and added steps for initializing the new PXF hosts.
This should work as a placeholder for when we document post expansion steps for other components (GPSS, GPCC).
I am assuming that the PXF hosts can be initialized after the gpexpand process is fully completed but please correct me if this is not right.

Preview:
https://mireia-gpexpand-pxf.sc2-04-pcf1-apps.oc.vmware.com/7-0/admin_guide/expand/expand-post.html

2021-04-22 15:48 UTC, lisakowen requested changes
thanks, i just had a few minor comments.

(this is a great reorganization, it will be easy to add expansion-related sections for other components.)

2021-04-22 15:48 UTC, lisakowen commented on gpdb-doc/dita/admin_guide/expand/expand-post.xml
> +    <title>Initializing new PXF segments</title>
initialize is a general term, but it does have specific connotations for pxf 5 that are not required in pxf 6.  wondering if  something a little more generic likd "Setting Up PXF on the New Host" might work?

and i think both titles should be using caps, i.e. "Removing the Expansion Schema", whatever this one is.

2021-04-22 15:48 UTC, lisakowen commented on gpdb-doc/dita/admin_guide/expand/expand-post.xml
> +      <p>There are different steps to follow depending on your PXF version and type of
... version and *the* type of ...   or  and the source of

2021-04-22 15:48 UTC, lisakowen commented on gpdb-doc/dita/admin_guide/expand/expand-post.xml
> +plx cluster init</codeblock></li>
plx -> pxf (all occurrences)

2021-04-22 15:48 UTC, lisakowen commented on gpdb-doc/dita/admin_guide/expand/expand-post.xml
> +          <li>If you installed the PXF 5.x <codeph>rpm</codeph> on your Greenplum cluster, you must
i wonder if we should also explicitly state something to address those customers using the PXF distributed with greenplum ...  "if you are using the PXF installed/included with your greenplum distribution, no install action is required on your part."

2021-04-22 15:48 UTC, lisakowen commented on gpdb-doc/dita/admin_guide/expand/expand-post.xml
> +            the following commands:<codeblock>pxf cluster reset
in the pxf docs, we usually preface commands with something like the following to reinforce the user and host that the command should be run on:
```
gpadmin@gpmaster$
```
this isn't a convention in the greenplum docs, and commands in the section above aren't doing it, so maybe just added a $ in front of the command should suffice.

2021-04-22 15:48 UTC, lisakowen commented on gpdb-doc/dita/admin_guide/expand/expand-post.xml
> +          <li>If you installed the PXF 6.x <codeph>rpm</codeph> on your Greenplum cluster, you must
rpm -> rpm or deb

2021-04-22 21:38 UTC, lisakowen approved these changes
looks good, please remove the noted statement in the pxf  6 section.

2021-04-22 21:38 UTC, lisakowen commented on gpdb-doc/dita/admin_guide/expand/expand-post.xml
> +          <li>If you are using the PXF version included with your Greenplum Database distribution,
pxf 6 is not embedded in greenplum, so i think we can remove this bullet.

2021-05-06 18:08 UTC, bradfordb-vmware approved these changes

2021-05-06 18:29 UTC, ashuka24 approved these changes

2021-05-12 22:38 UTC, dyozie requested changes

2021-05-12 22:38 UTC, dyozie commented on gpdb-doc/dita/admin_guide/expand/expand-post.xml
> +  <shortdesc>Once the expansion is completed, you must perform different tasks depending on your
Once -> After

2021-05-12 22:38 UTC, dyozie commented on gpdb-doc/dita/admin_guide/expand/expand-post.xml
> +    <title>Removing the expansion schema</title>
Init caps:  Expansion Schema

2021-05-12 22:38 UTC, dyozie commented on gpdb-doc/dita/admin_guide/expand/expand-post.xml
> +        verified. To run another expansion operation on a Greenplum system, first remove the
Maybe reword to:  You _must_ remove the existing expansion schema before you can perform another expansion operation on the Greenplum system.

2021-05-12 22:38 UTC, dyozie commented on gpdb-doc/dita/admin_guide/expand/expand-post.xml
> +      <p>If you are using PXF in your Grenplum Database cluster, you must perform some configuration
typo: Grenplum

2021-05-25 23:38 UTC, dyozie approved these changes

2021-05-25 23:38 UTC, merged