Docs: modified gprecoverseg -p utility guide
greenplum-db/gpdb pull request #11814
Opened 2021-04-14 17:13 UTC by mperezfuster

I have modified the section for gprecoverseg -p as suggested by @kalensk. 
Let me know if anything needs to be amended. Thanks!
Preview (needs VPN access):
https://mireia-gprecoverseg-p.sc2-04-pcf1-apps.oc.vmware.com/7-0/utility_guide/ref/gprecoverseg.html

2021-04-14 21:35 UTC, niralis13 requested changes
We need to back port these changes to Greenplum 6 and Greenplum 5 documentation as well. I am not sure how docs changes are back ported.  

Also, Nothing needs to be added to release note for 6.16.0.

2021-04-14 21:35 UTC, niralis13 commented on gpdb-doc/dita/utility_guide/ref/gprecoverseg.xml
> +            installed, the host able to connect password-less with all segments including the
"the host" --> "the spare host"

2021-04-14 21:35 UTC, niralis13 commented on gpdb-doc/dita/utility_guide/ref/gprecoverseg.xml
> +            which to recover invalid segments. Note that the hostname of the new node needs to match
Can we highlight the "Note that the hostname of the new node needs to match the hostname being recovered" almost as a warning?

2021-04-14 21:35 UTC, niralis13 commented on gpdb-doc/dita/utility_guide/ref/gprecoverseg.xml
> +            and corresponding mirrors are offline.</pd>
Instead of this paragraph please add something similar to, 

" In the case of multiple failed segment hosts, you can specify a comma-separated list. However we strongly recommend to recover one host at a time. If you must recover more than one host at a time then it is critical to ensure a double fault scenario does not occur in which both the primaries and corresponding mirrors are offline. " 

I would suggest to highlight this section to catch attention on critical details.

2021-04-15 13:31 UTC, mperezfuster commented on gpdb-doc/dita/utility_guide/ref/gprecoverseg.xml
> +            and corresponding mirrors are offline.</pd>
Hi Nirali,
Thanks for your comments.
Can you check again here: 
https://mireia-gprecoverseg-p.sc2-04-pcf1-apps.oc.vmware.com/7-0/utility_guide/ref/gprecoverseg.html
Is this too much warning, would you prefer the red warning box instead?

2021-04-15 15:03 UTC, niralis13 commented on gpdb-doc/dita/utility_guide/ref/gprecoverseg.xml
> +            and corresponding mirrors are offline.</pd>
LGTM

2021-04-15 15:03 UTC, niralis13 approved these changes

2021-04-15 17:40 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gprecoverseg.xml
> +    <section id="section3"><title>Description</title>-<p>In a system with mirrors enabled, the
Not sure what changed here, but I notice there's a dash (-) in-between xml elements. This is probably going to cause a problem with xml validation at some point?

2021-04-15 17:42 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gprecoverseg.xml
> +            convention, and so on.). Specifically, the Greenplum Database binaries must be
.). should change to ).

(remove the first period)

2021-04-15 17:43 UTC, dyozie requested changes

2021-04-15 17:43 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gprecoverseg.xml
> +            installed, the spare host must able to connect password-less with all segments including
must able -> must be able

2021-04-15 19:36 UTC, dyozie approved these changes

2021-04-15 19:36 UTC, merged