docs: pxf upgrade landing page
greenplum-db/gpdb pull request #11845
Opened 2021-04-21 18:18 UTC by mperezfuster

Added a "PXF Upgrade and Migration" landing page for Greenplum upgrade documentation. 
When upgrading to Greenplum 6 (https://mireia-pxf-upgrade-landing.sc2-04-pcf1-apps.oc.vmware.com/7-0/install_guide/upgrade_intro.html), all PXF options are grouped into one into the landing page: 
https://mireia-pxf-upgrade-landing.sc2-04-pcf1-apps.oc.vmware.com/7-0/pxf/pxf_upgrade_migration.html
This provides a breakdown of different scenarios and directs user to the specific steps to follow in every case.

2021-04-21 18:43 UTC, bradfordb-vmware approved these changes
Looks good. I suggested a few wording changes but they are more of an opinion/preference.

2021-04-21 18:43 UTC, bradfordb-vmware commented on gpdb-doc/markdown/pxf/pxf_upgrade_migration.html.md.erb
> +1. Upgrading PXF after [upgrading Greenplum Database from a previous 6.x version](upgrade_pxf_6x.html). Note that different steps are outlined based on your PXF installation type: it can be a manuall
```suggestion
1. Upgrading PXF after [upgrading Greenplum Database from a previous 6.x version](upgrade_pxf_6x.html). Note that different steps are outlined based on your PXF installation type: it can be a manually installed via an `rpm` package or the version include with the Greenplum Database installer. 
```

2021-04-21 18:57 UTC, lisakowen requested changes
this page is going to be really helpful to those users that read it!

2021-04-21 18:57 UTC, lisakowen commented on gpdb-doc/markdown/pxf/pxf_upgrade_migration.html.md.erb
> +    - If you were previously using the `gphdfs` external table protocol to access data stored in Hadoop, you must [migrate](gphdfs-pxf-migrate.html) your `gphdfs` external tables to use PXF instead,
what if the link text is [migrate your gphdfs external tables] instead of just [migrate]?

2021-04-21 18:57 UTC, lisakowen commented on gpdb-doc/markdown/pxf/pxf_upgrade_migration.html.md.erb
> +1. Upgrading PXF after [upgrading Greenplum Database from a previous 6.x version](upgrade_pxf_6x.html). Note that different steps are outlined based on your PXF installation type: it can be a manuall
not sure about this, but what about installation source instead of installation type?  i.e. (combined with bradford's comment):

Note that different steps are outlined based on your PXF installation source:  a manually installed `rpm` or `deb` package, or the version included with the Greenplum Database installer.

2021-04-21 18:57 UTC, lisakowen commented on gpdb-doc/markdown/pxf/pxf_upgrade_migration.html.md.erb
> +1. If you are planning a PXF upgrade, but not as part of a Greenplum Database upgrade, you must refer to the [PXF Documentation](../../pxf/5-15/upgrade_pxf_rpm.html).
`If you are planning to upgrade a PXF `rpm` or `deb` installation outside of a Greenplum upgrade,` ...  might make it more explicit.

i notice that we are xrefing to pxf 5-15 docs here.  most of these topics xref to that version because pxf 5.15.1 is embedded in greenplum 6.x right now.  i am wondering if we should xref to latest, which would be 6.0?  or maybe even 5.16, which is the last pxf 5.x version?

2021-04-21 19:21 UTC, ashuka24 commented on gpdb-doc/markdown/pxf/pxf_upgrade_migration.html.md.erb
> +1. Upgrading PXF after [upgrading Greenplum Database from a previous 6.x version](upgrade_pxf_6x.html). Note that different steps are outlined based on your PXF installation type: it can be a manuall
maybe you could say here 
``` suggestion
1. Upgrading PXF after [upgrading Greenplum Database from a previous 6.x version](upgrade_pxf_6x.html). Note that different steps are outlined based on your PXF installation type: it can be a manually installed version obtained from an`rpm` or `deb` package downloaded from TanzuNet or the version included with the Greenplum Database installer
```

2021-04-21 19:21 UTC, ashuka24 commented on gpdb-doc/markdown/pxf/pxf_upgrade_migration.html.md.erb
> +    - If you were previously using the `gphdfs` external table protocol to access data stored in Hadoop, you must [migrate](gphdfs-pxf-migrate.html) your `gphdfs` external tables to use PXF instead,
Here we use a new line and a bullet point to add a note. Below, we just say "Note that different... " 

Should we make these consistent?

2021-04-21 19:21 UTC, ashuka24 commented on gpdb-doc/markdown/pxf/pxf_upgrade_migration.html.md.erb
> +
unnecessary new line

2021-04-21 19:50 UTC, mperezfuster commented on gpdb-doc/markdown/pxf/pxf_upgrade_migration.html.md.erb
> +    - If you were previously using the `gphdfs` external table protocol to access data stored in Hadoop, you must [migrate](gphdfs-pxf-migrate.html) your `gphdfs` external tables to use PXF instead,
the original idea instead of the bullet point was a sub list, as in, option 1, sub-option 1, which points to a different link. But because there was only one suboption I changed it to a bullet point. The second case is more of a warning within the same option if that makes sense? I am happy to change to bullet point if it doesn't seem clear!

2021-04-28 17:21 UTC, lisakowen approved these changes

2021-05-04 00:09 UTC, dyozie requested changes

2021-05-04 00:09 UTC, dyozie commented on gpdb-doc/markdown/pxf/pxf_upgrade_migration.html.md.erb
> +There are different possible scenarios:
different -> three

?

2021-05-04 00:09 UTC, dyozie commented on gpdb-doc/markdown/pxf/pxf_upgrade_migration.html.md.erb
> +    - If you were previously using the `gphdfs` external table protocol to access data stored in Hadoop, you must [migrate your gphdfs external tables](gphdfs-pxf-migrate.html) to use PXF instead, si
I don't think this should be a sub-bullet since it's just a follow-on paragraph.  Make this similar to the other list items that follow.

2021-05-04 00:09 UTC, dyozie commented on gpdb-doc/markdown/pxf/pxf_upgrade_migration.html.md.erb
> +1. Upgrading PXF after [upgrading Greenplum Database from a previous 6.x version](upgrade_pxf_6x.html). Note that different steps are outlined based on your PXF installation source: a manually instal
TanzuNet -> Tanzu Network

2021-05-04 00:09 UTC, dyozie commented on gpdb-doc/markdown/pxf/pxf_upgrade_migration.html.md.erb
> +1. If you are planning to upgrade a PXF `rpm` or `deb` installation outside of a Greenplum Database upgrade, you must refer to the [PXF Documentation](../../pxf/6-0/upgrade_pxf_rpm.html).
If you are planning to upgrade -> Upgrading
upgrade, you must refer -> upgrade. Refer

2021-05-04 10:12 UTC, mperezfuster commented on gpdb-doc/markdown/pxf/pxf_upgrade_migration.html.md.erb
> +    - If you were previously using the `gphdfs` external table protocol to access data stored in Hadoop, you must [migrate your gphdfs external tables](gphdfs-pxf-migrate.html) to use PXF instead, si
I wrote this as a sub bullet because it only applies when migrating from Greenplum 5.x. If I have it at the same level as the other ones it would look like if migrating from gphdfs is a standalone migration path and maybe user wouldn't follow the steps for migrating from 5.x?

2021-05-04 15:59 UTC, dyozie commented on gpdb-doc/markdown/pxf/pxf_upgrade_migration.html.md.erb
> +    - If you were previously using the `gphdfs` external table protocol to access data stored in Hadoop, you must [migrate your gphdfs external tables](gphdfs-pxf-migrate.html) to use PXF instead, si
I just meant make this a continuation of the previous sentence (keep the follow-on content with the numbered bullet)..

2021-05-04 16:29 UTC, mperezfuster commented on gpdb-doc/markdown/pxf/pxf_upgrade_migration.html.md.erb
> +    - If you were previously using the `gphdfs` external table protocol to access data stored in Hadoop, you must [migrate your gphdfs external tables](gphdfs-pxf-migrate.html) to use PXF instead, si
got it thanks!

2021-05-04 18:11 UTC, ashuka24 approved these changes

2021-05-04 23:17 UTC, dyozie approved these changes

2021-05-04 23:17 UTC, merged