Fix bug: query failed if exists subquery have group by clause
greenplum-db/gpdb pull request #11918
Opened 2021-05-06 05:29 UTC by weinan003

In upstream, the planner may rid of exists subquery targetlist after
several validations. But for gpdb, it forgets to check if the query
has Aggregation.

For instance,
```sql
create temp table group_by_subquery(col1 int);
insert into group_by_subquery select i from generate_series(1, 5) i;
explain (costs off)
select col1 from group_by_subquery where exists (select avg(col1) from group_by_subquery group by col1);
```

Roll back a piece of code to fix this issue.

https://github.com/greenplum-db/gpdb/issues/11849

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [x] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2021-05-06 08:16 UTC, asimrp commented
Hey @weinan003, thank you for the fix!  Do you mind updating the Orca specific answer file as well: `bfv_aggregate_optimizer.out`?

2021-05-06 09:04 UTC, pivotal-issuemaster commented
@weinan003 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=11918)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=11918) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2021-05-06 09:05 UTC, pivotal-issuemaster commented
@weinan003 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=11918)!

2021-05-06 09:07 UTC, weinan003 commented
Hi @asimrp, thanks for the notice. I've updated the orca answer file.

2021-05-06 09:08 UTC, asimrp commented
:+1: the code change looks good to me.  We can rely on PR pipeline to further validate the change.  Not sure why PR pipeline wasn't triggered.

2021-05-07 07:16 UTC, adam8157 commented
👍

2021-06-28 07:47 UTC, adam8157 requested changes

2021-06-28 07:47 UTC, adam8157 commented on src/backend/optimizer/plan/subselect.c
>  		query->hasAggs ||
Changing `query->hasAggs ||` to `(query->hasAggs && !query->havingQual) ||` would be better. It would best if we could also skip `SELECT Agg() .. FROM .. GROUP BY .. HAVING Agg() ..`

We only skip plain Aggs, the **Aggs** not in **HAVING**.

2021-06-28 07:47 UTC, adam8157 commented on src/backend/optimizer/plan/subselect.c
> -#endif
https://github.com/greenplum-db/gpdb-postgres-merge/commit/5ff3d00a2c47bf1839e1aaf04116b3fe34ba30f0

Because Greenplum wants to demote the HAVING, HAVING has Aggs.

2021-07-06 01:58 UTC, weinan003 commented on src/backend/optimizer/plan/subselect.c
> -#endif
Yes.Thanks for helping me dig the answer out. I've updated the patch.

2021-07-06 02:45 UTC, adam8157 submitted a review, later dismissed

2021-07-06 09:15 UTC, guofengrichard commented on src/test/regress/expected/qp_correlated_query.out
> +                                   ->  Seq Scan on c  (cost=0.00..1.03 rows=3 width=4)
The change introduces regression for this case.

2021-07-06 09:22 UTC, adam8157 commented on src/test/regress/expected/qp_correlated_query.out
> +                                   ->  Seq Scan on c  (cost=0.00..1.03 rows=3 width=4)
I suppose that's exactly what we want here.

	 * We don't try to simplify at all if the query uses set operations,
	 * aggregates, grouping sets, SRFs, modifying CTEs, HAVING, OFFSET, or FOR
	 * UPDATE/SHARE; none of these seem likely in normal usage and their
	 * possible effects are complex.

2021-07-06 09:28 UTC, adam8157 commented on src/test/regress/expected/qp_correlated_query.out
> +                                   ->  Seq Scan on c  (cost=0.00..1.03 rows=3 width=4)
My point is we probably should not simplify the query with aggs as the comment says, so I'm for it.

However, this seems not the root cause of that "target list missing" issue, I'm still working on that.

2021-07-06 09:30 UTC, guofengrichard commented on src/test/regress/expected/qp_correlated_query.out
> +                                   ->  Seq Scan on c  (cost=0.00..1.03 rows=3 width=4)
> I suppose that's exactly what we want here.
> 
> ```
>  * We don't try to simplify at all if the query uses set operations,
>  * aggregates, grouping sets, SRFs, modifying CTEs, HAVING, OFFSET, or FOR
>  * UPDATE/SHARE; none of these seem likely in normal usage and their
>  * possible effects are complex. 
> ```

This is what PostgreSQL wants. For GPDB, it's a different story.  Subplan is much more inefficient here in GPDB. So this is a big regression which we should avoid.

2021-07-08 02:17 UTC, adam8157 commented on src/test/regress/expected/qp_correlated_query.out
> +                                   ->  Seq Scan on c  (cost=0.00..1.03 rows=3 width=4)
👍

2021-07-13 09:17 UTC, adam8157 commented on src/test/regress/expected/qp_correlated_query.out
> +                                   ->  Seq Scan on c  (cost=0.00..1.03 rows=3 width=4)
@guofengrichard I got confused again.

1, I don't see how `simplify_EXISTS_query()` simplifies this query, it only has optimizations for limit and having, I guess it changed the output plan because the cheapest one failed (because some info are thrown away)
2, is it really a worse plan?

2021-07-14 02:30 UTC, adam8157 commented
6X has no such issue because 6X doesn't try to simplify sub-queries with limitCount at the very beginning.
```
                                       QUERY PLAN
-----------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice2; segments: 3)
   ->  Result
         One-Time Filter: $0
         InitPlan 1 (returns $0)  (slice3)
           ->  Limit
                 ->  Gather Motion 3:1  (slice1; segments: 3)
                       ->  Limit
                             ->  HashAggregate
                                   Group Key: group_by_subquery_1.col1
                                   ->  Seq Scan on group_by_subquery group_by_subquery_1
         ->  Seq Scan on group_by_subquery
 Optimizer: Postgres query optimizer
(12 rows)
```

And I don't see how `simplify_EXISTS_query()` simplifies plain aggregations, it only has optimizations for limit and having, does it?

2022-07-18 06:48 UTC, SmartKeyerror commented
@adam8157  After some investigations, I think I can give a rough conclusion.

First, **We should never try to pull up irrelevant EXISTS sublinks**, because they can be calculated once, and used everywhere, it's more efficient than any join (Hash Join/Nested Loop Join), just like:

```
postgres=# create table tmbk (c1 int, c2 varchar, c3 timestamp ) distributed by (c2);
CREATE TABLE
postgres=# explain select c3 from tmbk where exists (select avg(c1) from tmbk group by c1);
                                                          QUERY PLAN                                                           
---------------------------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice3; segments: 3)  (cost=798.03..1340.03 rows=44200 width=8)
   ->  Result  (cost=798.03..1340.03 rows=14734 width=8)
         One-Time Filter: $0
         InitPlan 1 (returns $0)  (slice4)
           ->  Limit  (cost=798.00..798.03 rows=1 width=36)
                 ->  Gather Motion 3:1  (slice2; segments: 3)  (cost=798.00..798.03 rows=1 width=36)
                       ->  Limit  (cost=798.00..798.01 rows=1 width=36)
                             ->  HashAggregate  (cost=798.00..810.50 rows=334 width=36)
                                   Group Key: tmbk_1.c1
                                   ->  Redistribute Motion 3:3  (slice1; segments: 3)  (cost=763.00..783.00 rows=334 width=36)
                                         Hash Key: tmbk_1.c1
                                         ->  HashAggregate  (cost=763.00..763.00 rows=334 width=36)
                                               Group Key: tmbk_1.c1
                                               ->  Seq Scan on tmbk tmbk_1  (cost=0.00..542.00 rows=14734 width=4)
         ->  Seq Scan on tmbk  (cost=0.00..542.00 rows=14734 width=8)
 Optimizer: Postgres query optimizer
(16 rows)
```

Greenplum 7.0-Alpha and 6X-STABLE do not pull up non-relevant EXISTS sublinks indeed, this action is correct.

But in 6X-STABLE, it will optimize non-relevant EXISTS sublinks, just add a `LIMIT 1` Node to `QueryTree`:

```
Node *
convert_EXISTS_sublink_to_join(PlannerInfo *root, SubLink *sublink,
							   bool under_not, Relids available_rels)
{
	/*
	 * On the other hand, the WHERE clause must contain some Vars of the
	 * parent query, else it's not gonna be a join.
	 */
	if (!contain_vars_of_level(whereClause, 1))
	{
		/*
		 * CDB: Add 'limit 1' in this case.
		 */
		((Query*)sublink->subselect)->limitCount =
			(Node *) makeConst(INT8OID, -1, InvalidOid, sizeof(int64),
								Int64GetDatum(1), false, true);
		return NULL;
	}
}
```

And in `simplify_EXISTS_query()`, it'll not try to simplify the query tree which has `limitCount` Node:

```
	if (query->commandType != CMD_SELECT ||
		query->setOperations ||
		query->hasModifyingCTE ||
		query->limitOffset ||
		query->limitCount ||
		query->rowMarks)
		return false;
```

But 7.0-Alpha doesn't do it. So in function `simplify_EXISTS_query()`, it will be simplified: remove `targetList` Node. 

It will crash when we have Agg but no target column.

After the below patch, this issue will be resolved and not lead to regression on some queries:

```
diff --git a/src/backend/optimizer/plan/subselect.c b/src/backend/optimizer/plan/subselect.c
index c6cde87e790..912c420c306 100644
--- a/src/backend/optimizer/plan/subselect.c
+++ b/src/backend/optimizer/plan/subselect.c
@@ -1748,6 +1748,10 @@ simplify_EXISTS_query(PlannerInfo *root, Query *query)
                query->rowMarks)
                return false;
 
+
+       if (!contain_vars_of_level(query->jointree->quals, 1))
+               return false;
+
        /*
         * LIMIT with a constant positive (or NULL) value doesn't affect the
         * semantics of EXISTS, so let's ignore such clauses.  This is worth doing
```

But this part of the code will still look messy, there will be a big difference between 6 and 7, which need more consideration.

2022-09-19 09:24 UTC, SmartKeyerror commented
The original issue has been fixed by #13838, so close this PR. 

Thanks for the contribution!

2022-09-19 09:24 UTC, closed without merging