docs: removed reference of openssl.conf
greenplum-db/gpdb pull request #11926
Opened 2021-05-06 15:47 UTC by mperezfuster

We do not ship a version of openssl with Greenplum 6 so there is no openssl.conf file under $GPHOME/etc.
It is now listed as a requirement https://greenplum.docs.pivotal.io/6-16/install_guide/platform-requirements.html
I removed the whole OpenSSL Configuration section since it only consisted of an explanation of that file. I can add it again with references to how to configure OpenSSL or references to OpenSSL documentation if that makes more sense?

2021-05-11 23:52 UTC, lisakowen requested changes

2021-05-11 23:52 UTC, lisakowen commented on gpdb-doc/dita/security-guide/topics/Authenticate.xml
> -      </section>
i think that, when set, OPENSSL_CONF points to the filesystem location of the ssl config file (typically named openssl.cnf).  from what i can tell, if $GPHOME/etc/openssl.cnf exists, we set OPENSSL_CONF to this value in greenplum_path.sh. in other cases, we are either using the system-provided openssl.cnf, or a custom OPENSSL_CONF specified in the gpadmin users environment.

so i think that we want to keep the section in the docs, but have it say something more like:

You can make changes to the OpenSSL configuration by updating the <codeph>openssl.cnf</codeph> file, or the file referenced by <codeph>OPENSSL_CONF</codeph>, and then restarting the Greenplum Database server.

(probably should request an engineering review, just to be safe.)

2021-05-13 09:57 UTC, mperezfuster commented on gpdb-doc/dita/security-guide/topics/Authenticate.xml
> -      </section>
Thank you, I modified it, let me know if it looks ok!

2021-05-25 15:57 UTC, lisakowen approved these changes
minor comment

2021-05-25 15:57 UTC, lisakowen commented on gpdb-doc/dita/security-guide/topics/Authenticate.xml
> +          referenced by <codeph>OPENSSL_CONF</codeph>, if present, and then restarting the Greenplum
... referenced by `$OPENSSL_CONF`.

2021-06-11 22:27 UTC, dyozie approved these changes

2021-06-11 22:27 UTC, merged