Alternate Text for Offensive Terminology
greenplum-db/gpdb pull request #11993
Opened 2021-05-17 10:12 UTC by mperezfuster

Modified the following terminology:
- abort
- rule of thumb
- kill
- suffer
- execute

Note some of them are context dependant and it is not possible to modify them (ie command syntax, "execution permissions", etc).

2021-05-17 14:30 UTC, VMWareJennyBeth approved these changes

2021-05-17 14:31 UTC, VMWareJennyBeth commented on gpdb-doc/dita/admin_guide/dml.xml
> +        which segments are runing the transactions. Sample output of the
@mperezfuster Ooops I missed this typo. Change to "running"

2021-05-17 14:32 UTC, VMWareJennyBeth commented on gpdb-doc/dita/admin_guide/external/g-devel-fdw.xml
> +              <entry colname="col2">Begin runing a foreign scan. Called during
@mperezfuster Same typo. Maybe global search for this.

2021-05-17 14:36 UTC, VMWareJennyBeth commented on gpdb-doc/dita/admin_guide/external/g-using-the-greenplum-parallel-file-server--gpfdist-.xml
> +         <p>Then stops the process, for example (where 3456 is the process ID in this example):</p>
@mperezfuster Since it's kill, should it be stop instead of stops?

2021-05-17 14:39 UTC, VMWareJennyBeth commented on gpdb-doc/dita/admin_guide/intro/about_mvcc.xml
> +        rows. Performance decreases due to the increased disk I/O required to run queries. This
@mperezfuster Performance degrades

2021-05-17 14:49 UTC, VMWareJennyBeth commented on gpdb-doc/dita/admin_guide/perf_issues.xml
> +        workloads compete for access to these resources, database performance decreases. Resource
@mperezfuster 
degrades

2021-05-17 14:49 UTC, VMWareJennyBeth commented on gpdb-doc/dita/admin_guide/perf_issues.xml
> +          Performance may decrease when these values are unusually large.</p>
@mperezfuster degrade

2021-05-17 14:57 UTC, VMWareJennyBeth commented on gpdb-doc/dita/ref_guide/sql_commands/CREATE_RESOURCE_QUEUE.xml
> +            runtime is limited by the physical memory of a segment host. The default is no
@mperezfuster I think this should be running time. "runtime" is a 1-word noun that has a different meaning in computer science.

2021-05-17 14:58 UTC, VMWareJennyBeth commented on gpdb-doc/dita/ref_guide/sql_commands/CREATE_RESOURCE_QUEUE.xml
> +        within a transaction.</p>Also, an SQL statement that is run during the runtime of an
@mperezfuster Again, this doesn't feel like the correct word. I suggest "during the running of"

2021-05-17 15:00 UTC, VMWareJennyBeth commented on gpdb-doc/dita/ref_guide/sql_commands/CREATE_TRIGGER.xml
> +is handled in a language-specific way.</li><li id="cg152852">Greenplum Database only allows running a user-defined function
@mperezfuster allows you to run

2021-05-17 15:01 UTC, VMWareJennyBeth commented on gpdb-doc/dita/ref_guide/sql_commands/DECLARE.xml
> +        the same session. (But if the creating transaction is ended prematurely, the cursor is
@mperezfuster "is ended prematurely" => "ends prematurely" (avoid passive voice if at all possible)

2021-05-17 18:27 UTC, fifthposition reviewed
I found one or two things to fix and had some other comments.

2021-05-17 18:27 UTC, fifthposition commented on gpdb-doc/dita/ref_guide/sql_commands/CREATE_RESOURCE_QUEUE.xml
> +        processes of a query can consume on a segment host during query running time. Greenplum
I think "runtime" is correct in this case. Alternatively (as we do later on) "execution time" could work.

2021-05-17 18:27 UTC, fifthposition commented on gpdb-doc/dita/ref_guide/sql_commands/CREATE_RESOURCE_QUEUE.xml
> +        execution time if the segment host memory limit specified in
I think we should be consistent here. We should either always say "runtime" or always say "execution time".

2021-05-17 18:27 UTC, fifthposition commented on gpdb-doc/dita/ref_guide/sql_commands/DECLARE.xml
> +        the same session. (But if the creating transaction is ends prematurely, the cursor is
This should be either "is ended", or "ends" (without "is")

2021-05-17 18:27 UTC, fifthposition commented on gpdb-doc/dita/utility_guide/ref/createdb.xml
> +via the <codeph>-O</codeph> option, if the running user has appropriate
"the running user" doesn't sound very clear to me here. I suppose, though, if we used to say "the executing user", then "the running user" works instead.

2021-05-17 18:27 UTC, fifthposition commented on gpdb-doc/dita/utility_guide/ref/createdb.xml
> +          to the user running this command. (This name
"the user running this command" is clearer to me than "the running user". FYI

2021-05-18 14:18 UTC, mperezfuster commented on gpdb-doc/dita/utility_guide/ref/createdb.xml
> +via the <codeph>-O</codeph> option, if the running user has appropriate
thanks, changing it back to executing

2021-05-26 03:43 UTC, fifthposition requested changes
In some cases, we need to use different replacement terms, or alternatively rephrase in order to make the replacement terms fit. I also had some other comments / suggestions.

2021-05-26 03:43 UTC, fifthposition commented on gpdb-doc/dita/ref_guide/sql_commands/VACUUM.xml
> +          <i>autovacuum daemon</i>, whose purpose is to automate the run of
This should be "automate the running of..."

2021-05-26 03:43 UTC, fifthposition commented on gpdb-doc/dita/ref_guide/sql_commands/SET.xml
> +        is later ended prematurely, the effects of the <codeph>SET</codeph> command disappear when
Maybe this could instead say "a transaction that is later cancelled".

2021-06-01 14:57 UTC, fifthposition approved these changes

2021-06-23 16:50 UTC, lenapivotal approved these changes
I completed 102/199
my suggestions do not have to be followed

2021-06-29 12:39 UTC, mperezfuster commented on gpdb-doc/dita/admin_guide/dml.xml
> +            <li id="ix154149">Sees updates run within the transaction.</li>
same here, past participle of run is run

2021-07-07 20:27 UTC, merged