Assorted documentation fixes
greenplum-db/gpdb pull request #11990
Opened 2021-05-14 19:41 UTC by fifthposition

2021-06-04 16:53 UTC, dyozie requested changes

2021-06-04 16:53 UTC, dyozie commented on gpdb-doc/dita/best_practices/encryption.xml
> +Vew29efdoqrCcJIRrZ9XExP9dFcB+VFeWPBIo/0O7LIVWCT88CqzUZf+aAU8RH88
I think we'd still want to redact part of this (and not provide an actual key as part of the example)?

2021-06-04 18:08 UTC, fifthposition commented on gpdb-doc/dita/best_practices/encryption.xml
> +Vew29efdoqrCcJIRrZ9XExP9dFcB+VFeWPBIo/0O7LIVWCT88CqzUZf+aAU8RH88
Good catch...

2021-06-08 15:31 UTC, dyozie approved these changes

2021-06-08 15:33 UTC, merged