Enable header for custom formatter in gpfdist protocol.
greenplum-db/gpdb pull request #12022
Opened 2021-05-20 09:13 UTC by zhaorui20005

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2021-05-20 13:18 UTC, linwen requested changes
I suggest add some brief description at the header of PR. BTW, I have seen the interface to customer is changed, do you have test case for this change? Thanks!

2021-05-20 13:18 UTC, linwen commented on src/backend/access/external/fileam.c
> +static List*
Suggest add some comments about what list this function returns.

2021-05-20 13:18 UTC, linwen commented on src/backend/access/external/fileam.c
> +				        header_elem_p = makeDefElem(pstrdup(key_modified.data),
Please fix the indent.

2021-05-21 01:27 UTC, zhaorui20005 commented on src/backend/access/external/fileam.c
> +				        header_elem_p = makeDefElem(pstrdup(key_modified.data),
> Please fix the indent.

Any docs to follow or any tools to use? I found the codes are using '\t' indent, but make it too long in more 3depth of 'if else'.

2021-05-21 01:45 UTC, zhaorui20005 commented on src/backend/access/external/fileam.c
> +static List*
> I suggest add some brief description at the header of PR. BTW, I have seen the interface to customer is changed, do you have test case for this change? Thanks!

Thanks for advise! 
This pr is to solve custom formatter of external table that does not support 'header' option for gpfdist protocol. As limited to the frame of the custom formatter of external table structure, the custom option cannot be parsed and stored in cstate->header_line:
The custom option and 'text' or 'csv' option are handled in two different ways. And options are stored in metadata at create external table stage, and during that stage custom options are not parsed but just stored. In the execute stage, it will not be parsed into cstate->header_line. Even in S3 protocol, only 'text' and 'csv' formats will parse that option in metadata. So in order to let custom formatter 'text_in' support header in different protocols, there are much to be mofidied.

This pr is just created to let others to see the changes, and if it is to be merged, I will add some test cases. After discussed with @pf-qiu , I found it may not work for other protocols like S3 and it may cause some regress case. So this pr has to be considered carefully.

2021-05-24 01:25 UTC, closed without merging