fsync related optimization for gpdb recovery
greenplum-db/gpdb pull request #12065
Opened 2021-05-27 09:04 UTC by paul-guo-

This is an alternative method for the issue discussed in https://github.com/greenplum-db/gpdb/pull/11896. The PR includes two commits.

```
commit 90219f3935e7bb8a9adb63823dca1926803b955e (HEAD -> sync_opt, origin/sync_opt)
Author: Paul Guo <guopa@vmware.com>
Date:   Wed Jan 20 16:05:34 2021 +0800

    Just fsync those affected files during pg_rewind.

    In gpdb we've ensured that the database is in sync state before rewinding, so
    we could just fsync those affected files after rewinding.

commit 8d3100bb7400d909a6c6093baafc6f0c5922700b
Author: Paul Guo <pguo@pivotal.io>
Date:   Thu May 27 14:18:41 2021 +0800

    Optimize the pgdata directory fsync during startup.

    Previously startup would fsync all files under the whole pgdata directory if
    the database is not cleanly shutdown. This step could be rather slow if pgdata
    directory includes millions of table files. Latest upstream provides syncfs()
    instead fsync() as an alternative but that is not enough for us since firstly
    stable syncfs() implementation needs 5.8+ Linux kernel support (or low-version
    kernel with related patches backported) but mainline linux stable releases do
    not seem to be qualified, second is that the current upstream code does not
    return error if syncfs() fails but we depend on this much if we skip fsync in
    pg_basebackup/pg_rewind, last is that syncfs() operates on one file system that
    could be shared my other applications or segments so it is not convenient for
    us to determine the default value.

    While this is a big pain for some users, we decide another gpdb specific
    solution: For the full/incremental recovery cases, we assume those files are
    synchronized already (the utilities ensure this) so we simply skip the fsync
    step, while for other cases (crash recovery), we do synchronize the wal files
    only if full page writes is on (should be on in production environments), else
    we still synchronize all the files in the pgdata directory. Note why wal files
    sync is needed? That's because during wal redo if partial flushing of buffer
    pages happens and if those related wal contents are missing during system
    crash, those pages would be broken forever.
```

The first patch was submitted to upstream. Our gp version is a bit different.
- The gp version is more correct - I found some small issues in the pg version (I'll update the pg version later).
- The gp version removes pre_sync_fname() calls since else we will add more conflicts with upstream code and also upstream pre_sync seems to be a bit buggy and may harm if we have millions of files.

I've done a lot of manual testing for the code change and it seems work well.

2021-05-27 18:04 UTC, ashwinstar requested changes

2021-05-27 18:04 UTC, ashwinstar commented on src/backend/access/transam/xlog.c
> +SyncAllXLogFiles(void)
why don't we implement this function exactly as `SyncDataDirectory()` is implemented, just for `pg_xlog` using `walkdir()` interface and such. As that will take care of "hint to the kernel that we're soon going to fs" piece, if pg_xlog is symbolic link part and also not emitting ERRORs etc...

2021-05-27 18:07 UTC, ashwinstar commented
I have not reviewed "Just fsync those affected files during pg_rewind." commit in this PR. Please open separate PR for it. Rational timeline for those 2 commits to be committed in code base is independent, hence lets take them separately.

2021-05-28 01:58 UTC, paul-guo- reviewed
The two patches are a bit dependent since the whole optimization logic for full/incremental recovery is either utility sync or startup sync. Now that in the PR, one patch optimizes pg_rewind to do partial sync and another PR skips fsync during startup for that scenario.

I've opened/closed too much times of related PRs and seems it could make users more confused if creating separate PRs again. Also the two patch changes are not interleaved and also easy to be reviewed independently. So it seems fine to keep them in the same PR.

2021-05-28 01:58 UTC, paul-guo- commented on src/backend/access/transam/xlog.c
> +SyncAllXLogFiles(void)
- This function can handle pg_wal dir symbolic link and there is no need of recursive walking for the wal directory right? 

- If fsync fails, fsync_fname() elog(ERROR) while SyncDataDirectory() only simply elog(LOG). fsync_fname() seems better also. Also I think upstream SyncDataDirectory() behavior is not that correct (I don't think startup->SyncDataDirectory() is the future in upstream per pg-hackers discussion).

- For xlog files, normally most wal contents have been flushed since xact commit or wal file extending would flush wal, so mostly "hint fsync" means nothing here. Also pre_sync_fname()->pg_flush_data()->posix_fadvise(POSIX_FADV_DONTNEED) does not seem correct I think, though on high version Linux kernel, sync_file_range() instead of posix_fadvise() is used.

2021-05-28 01:58 UTC, paul-guo- commented on src/backend/access/transam/xlog.c
> +	if (ControlFile->state != DB_SHUTDOWNED &&
Yes I thought about this yesterday (worry about it affects future PG merge) also. I even thought about just skipping the !full_page_writes case since if full_page_writes is off, even having the pgdata sync logic the table files are still fragile.

Or keeping the main code logic to the upstream location but adding the simple !full_page_writes logic here - This does not seems to affect future PG merge?
if (ControlFile->state != DB_SHUTDOWNED && ControlFile->state != DB_SHUTDOWNED_IN_RECOVERY && checkPoint.fullPageWrites)
SyncDataDirectory():

2021-06-01 22:49 UTC, ashwinstar commented on src/backend/access/transam/xlog.c
> +SyncAllXLogFiles(void)
This upstream commit added logic to not treat ERRORs in this code path, main reason being "failure to start is worse than any consequence of not fsync'ing is likely to be, therefore treat all errors in this code as nonfatal;"

```
commit d8179b001ae574da00c8f4549577095bf90f3337                                                       
Author: Tom Lane <tgl@sss.pgh.pa.us>                                                                  
Date:   Thu May 28 17:33:03 2015 -0400                                                                
                                                                                                      
    Fix fsync-at-startup code to not treat errors as fatal.                                           
```
I feel we need to follow the same.

In general, I feel not good to have different implementation for same functionality. It's confusing in long run, plus exposes the logical problem to exist in both implementation but fixed only for one of them.

2021-06-02 01:29 UTC, paul-guo- commented on src/bin/pg_rewind/pg_rewind.c
> +	/* fsync some files that are (possibly) written by pg_rewind. */
`recovery.conf` would be added for gp6 only. Actually in the PG version I created for upstream the code change is

```
+   if (access("recovery.conf", F_OK) == 0)
+       fsync_fname("recovery.conf", false);
+   if (access("postgresql.auto.conf", F_OK) == 0)
+       fsync_fname("postgresql.auto.conf", false);
```

I submitted the patch to upstream and if upstream thinks it is ok we won't need to worry about that. Also even we forget to fsync to several files it is not a big deal mostly since data loss just happens during system abnormal shutdown and also note that not long after write those files would be sync-ed soon by the kernel.

Also I have been wondering if we should add a long-time FIXME flag in comment for the scenarios that we should check during each PG merge iteration (though we should create them as fewer as possible) - this could be used in our scenario.

2021-06-02 01:34 UTC, paul-guo- commented on src/bin/pg_rewind/pg_rewind.c
> +				default:
default is more like a defensive branch here to prevent cascading errors due to unexpected entry->action (value not in the enum range). I understand you point/concern (if there is no code for some actions) so let me play with that to see if we have any solution.

2021-06-02 01:40 UTC, paul-guo- commented on src/backend/access/transam/xlog.c
> +	if (!enableFsync)
I did testing the code branch manually. Seems fine to add a simple test given this is gpdb specific code branch by enabling fsync on one node and triggering an unclean shutdown and then testing a simple write query. It should be not time-consuming.

2021-06-02 03:39 UTC, paul-guo- commented on src/bin/pg_rewind/pg_rewind.c
> +				default:
switch-enum in gcc could be used to check that.

https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html

I tried that quickly on the master branch. A lot of warnings come out when compling, e.g.

```
tablecmds.c:4134:3: warning: enumeration value ‘AT_ColumnDefault’ not handled in switch [-Wswitch-enum]
tablecmds.c:4134:3: warning: enumeration value ‘AT_DropNotNull’ not handled in switch [-Wswitch-enum]
tablecmds.c:4134:3: warning: enumeration value ‘AT_SetNotNull’ not handled in switch [-Wswitch-enum]
tablecmds.c:4134:3: warning: enumeration value ‘AT_CheckNotNull’ not handled in switch [-Wswitch-enum]
```

2021-06-02 07:25 UTC, paul-guo- commented on src/backend/access/transam/xlog.c
> +	if (!enableFsync)
isolation2 test `ao_same_trans_truncate_crash` covers the code path. I've added comment in the test and updated in this PR.

2021-06-02 17:37 UTC, ashwinstar commented on src/backend/access/transam/xlog.c
> +SyncAllXLogFiles(void)
I strongly disagree on ERRORs during recovery for this. I think irrespective of patch state in upstream this statement is relevant "failure to start is worse than any consequence of not fsync'ing is likely to be, therefore treat all errors in this code as nonfatal;". If get paged for this ERROR, naturally one will gdb and skip fsync to bring the cluster up.

Plus, you contradict yourself in this PR itself with statement "Also even we forget to fsync to several files it is not a big deal mostly since data loss just happens during system abnormal shutdown and also note that not long after write those files would be sync-ed soon by the kernel." :-)

2021-06-02 17:41 UTC, ashwinstar commented on src/bin/pg_rewind/pg_rewind.c
> +				default:
Yes, please track it a separate github issue and we can take it up.

2021-06-02 17:43 UTC, ashwinstar commented on src/backend/access/transam/xlog.c
> +	if (ControlFile->state != DB_SHUTDOWNED &&
I would strongly prefer this logic to be in original upstream location and not moved.

2021-06-03 00:59 UTC, paul-guo- commented on src/backend/access/transam/xlog.c
> +	if (ControlFile->state != DB_SHUTDOWNED &&
I agree that moving the main checking code to the upstream location but for the !full_page_writes, maybe two solutions:

one is: check `data_checksums` in the upstream location as an alternative for full_page_write, but do simly sanity check here.

if (data_checksum enabled && ! full_page_writes)
   elog(ERROR, "...");

Another is put the !full_page_writes code path here but others in the upstream location.

2021-06-03 01:26 UTC, paul-guo- commented on src/backend/access/transam/xlog.c
> +SyncAllXLogFiles(void)
`fsync` error is rare though exists in real. If we look at the code fsync code like`FileSync()` is called very frequently but I have never seen an user complaint/request relevant to fsync returning error and I don't think we would get paged for such case since users could recover using gprecoverseg and if gprecoverseg -F fails that usually means it is a non-gp issue.

Another reason is if use LOG level we need to add another function similar to fsync_fname() and the new function is just used to fsync maybe just 1 wal file (other files should sync-ed already). It seems that does not deserve adding such code conflict against upstream just for the small case. Using LOG or ERROR is not a big deal for me actually for the case.

"Also even we forget to fsync to several files it is not a big deal mostly since data loss just happens during system abnormal shutdown and also note that not long after write those files would be sync-ed soon by the kernel."

For whatever cases we should try to fsync all files that need to fsync but if we forget to fsync one file in code due to bug that might not be a big issue usually but we should try to prevent.

2021-06-03 01:27 UTC, ashwinstar commented on src/backend/access/transam/xlog.c
> +	if (ControlFile->state != DB_SHUTDOWNED &&
or how about just checking for `fullPageWrites` variable guc value (instead of checking its checkpoint value)? As we are checking it during recovery only and this GUC is `PGC_SIGHUP` means the value for sure needs to come via postgresql.conf file. Now what are the changes things could go wrong based on that check? (full pages were turned off, database was stopped, conf file was modified to mark it on and then crash recovery is performed). That seems super-super rare.

If you don't feel good about it I am okay with option 1 you mentioned. Though still would go with WARNING instead of ERROR even for that :-) as `full_page_writes` is not on means user is okay with missing data integrity.

2021-06-03 01:30 UTC, paul-guo- commented on src/bin/pg_rewind/pg_rewind.c
> +				default:
I remember there are a lot of hits. I believe many of them come from upstream. I can track this. Later we can spend a bit time to evaluate.

2021-06-03 01:41 UTC, paul-guo- commented on src/bin/pg_rewind/pg_rewind.c
> +				default:
New issue: https://github.com/greenplum-db/gpdb/issues/12092

2021-06-03 03:35 UTC, paul-guo- commented on src/backend/access/transam/xlog.c
> +	if (ControlFile->state != DB_SHUTDOWNED &&
How about adding the code below here and in the upstream location just do sync wal files for the crash recovery case regardless of the guc (checksum, full page write) setting?
+   /*
+    * gpdb specific: Do pgdata fsync for the case that is almost not possible
+    * on real production scenarios. See previous code that calls
+    * SyncAllXLogFiles() for details.
+    */
+   if (!haveBackupLabel && !wasShutdown && !checkPoint.fullPageWrites)
+       SyncDataDirectory();
+

2021-06-03 06:20 UTC, ashwinstar commented on src/backend/access/transam/xlog.c
> +	if (ControlFile->state != DB_SHUTDOWNED &&
That's good thought and cleaner, lets do it that way.

2021-06-03 06:35 UTC, ashwinstar commented on src/backend/access/transam/xlog.c
> +SyncAllXLogFiles(void)
> Another reason is if use LOG level we need to add another function similar to fsync_fname() and the new function is just used to fsync maybe just 1 wal file (other files should sync-ed already). It seems that does not deserve adding such code conflict against upstream just for the small case. Using LOG or ERROR is not a big deal for me actually for the case.

This was the reason I was suggesting to use `walkdir()` as `SyncDataDirectory()` does as it has argument to pass error level. I don't see downside of using `walkdir()` interface.

Plus, do we need to sync `pg_xlog` directory itself as well. `walkdir()` has this comment:
```c
    /*                                                                                                
     * It's important to fsync the destination directory itself as individual                         
     * file fsyncs don't guarantee that the directory entry for the file is                           
     * synced.                                                                                        
     */                                                                                               
```

2021-06-03 06:57 UTC, paul-guo- commented on src/backend/access/transam/xlog.c
> +SyncAllXLogFiles(void)
OK not a big deal. I can quickly create a version similar to SyncDataDirectory(). Yes need to fsync pg_wal itself since adding/removing/renaming xlog files would make the  pg_wal directory itself dirty. SyncDataDirectory()->walkdir() has already cared about the case.

2021-06-03 16:23 UTC, ashwinstar approved these changes
Thanks @paul-guo- for working through multiple iterations to finally reach a great solution to resolve this pain point for GPDB. Very thankful to patiently absorb review feedback and bake the solution :+1:

2021-06-03 16:23 UTC, ashwinstar commented on src/backend/storage/file/fd.c
> +
I think would be good to have LOG with start and end of this part, just to ease knowing the timings of it.

2021-06-03 16:23 UTC, ashwinstar commented on src/bin/pg_rewind/pg_rewind.c
> +	for (i = 0; i < filemap->narray; i++)
Do we have test for this code path in CI for pg_rewind?

2021-06-04 00:13 UTC, paul-guo- commented on src/bin/pg_rewind/pg_rewind.c
> +	for (i = 0; i < filemap->narray; i++)
gprecoverseg is run with fsync on currently (guc fsync just affects kernel) so the code path has been widely tested.

2021-06-04 00:35 UTC, paul-guo- commented on src/backend/storage/file/fd.c
> +
Probably existing "pg_log_info("syncing target data directory");" code is enough since if pg_rewind succeeds there is no log file and if pg_rewind fails mostly it should not fail at the fsync stage.

2021-06-04 01:18 UTC, ashwinstar commented on src/backend/storage/file/fd.c
> +
I am confused this has nothing to do with `pg_rewind`?

2021-06-04 01:31 UTC, paul-guo- commented on src/backend/storage/file/fd.c
> +
Ah I replied too fast: -) I agree with you, keeping the previous time logging code.

2021-06-04 06:40 UTC, merged