COPY ON SEGMENT for distributed replicated tables
greenplum-db/gpdb pull request #12137
Opened 2021-06-10 09:26 UTC by beeender

Reports an error when COPY FROM ON SEGMENT is executed on a distributed
replicated table. The data cannot be guaranteed to be the same on all
the segments if that is allowed.

## Here are some reminders before you submit the pull request
- [x] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [x] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2021-06-10 15:49 UTC, ashwinstar requested changes
Referring back to this discussion https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/lawvXUMujIc/m/epaeDLqRCgAJ how would backup and restore continue to work after this PR. There were ideas discussed to make `COPY FROM... ON SEGMENT` safer for replicated tables, any ideas what happened to those? Can those be implemented instead of plain erroring out?

2021-06-10 15:49 UTC, ashwinstar commented on src/test/regress/input/gpcopy.source
> +DROP TABLE IF EXISTS dist_rep_src;
don't need these drop statements, as they are not going to exist

2021-06-10 15:49 UTC, ashwinstar commented on src/test/regress/output/gpcopy.source
> +COPY dist_rep_src TO '/tmp/dist_rep_src_<SEGID>.txt' ON SEGMENT;
it's doable and no issues with it, just curious though to learn what's the use-case then for `COPY TO..ON SEGMENT` for replicated tables?

2021-06-11 01:59 UTC, beeender commented on src/test/regress/output/gpcopy.source
> +COPY dist_rep_src TO '/tmp/dist_rep_src_<SEGID>.txt' ON SEGMENT;
This problem was found through gpcopy. When the source and the destination don't have the same number of segments, gpcopy tries to iterate all source segments to make sure all data will be copied. Like:
src:   0, 1, 2, 3
dest: 0, 1, 2
The first round copy 0->0, 1->1, 2-2
The second round :  3->0
For the replicated tables, this ends with extra duplicated rows on the destination.

The discussion thread is quite interesting.
> 1) COPY TO ON SEGMENT will only let one segment dump its data for a replicated table so that there is only one copy of the data in backup file
> 2) COPY FROM ON SEGMENT will introduce a motion node and broadcast replicated table data to other nodes, or check and re-distributed a tuple to right segment for other cases

The suggestion could also fix some other limitation of `COPY FROM` redistribution. It will be a more reasonable fix.

2021-06-11 02:02 UTC, beeender commented on src/test/regress/output/gpcopy.source
> +COPY dist_rep_src TO '/tmp/dist_rep_src_<SEGID>.txt' ON SEGMENT;
BTW, a workaround on the gpcopy side has been committed by copying through the master node only for replicated distributed tables.

2021-06-11 08:24 UTC, adam8157 reviewed
Better do the check in `BeginCopy()` right after `ProcessCopyOptions()`, and no need to check `Gp_role` I suppose.

Please inform related teams, like gpbackup.

2021-06-11 23:53 UTC, ashwinstar commented
@jimmyyih @oakbarrett impact of this PR to gpbackup, seems it would break backups for replicated tables. Please can you take a look and comment.

2021-06-11 23:56 UTC, jimmyyih reviewed
Is this being backported to 6X?  If so, this is a pretty breaking change for the gpbackup/gprestore utility.

2021-06-11 23:56 UTC, jimmyyih commented on src/test/regress/input/gpcopy.source
> +COPY dist_rep_src TO '/tmp/dist_rep_src_<SEGID>.txt' ON SEGMENT;
Why should COPY TO ON SEGMENT work if the user won't be able to use COPY FROM ON SEGMENT?  It might be better to restrict replicated tables to just regular COPY only.

2021-06-15 02:32 UTC, beeender commented
> Is this being backported to 6X? If so, this is a pretty breaking change for the gpbackup/gprestore utility.

@jimmyyih what is the current behavior for gpbackup/gprestore on the replicated distributed tables?

2021-06-15 06:13 UTC, jimmyyih commented
> @jimmyyih what is the current behavior for gpbackup/gprestore on the replicated distributed tables?

It just runs COPY TO/FROM PROGRAM ON SEGMENT; nothing too special besides the PROGRAM call (compress, upload to S3, etc) with each dump file being uniquely marked with the segment's content id.  Duplicate data will be dumped for each segment for the replicated table and restored as such.  Should be fine since replicated tables shouldn't be that big and gpbackup/gprestore assumes same size cluster (for now anyways).

If this PR is backported to 6X, then users that upgrade to latest 6X would encounter gprestore failures if their backups contain replicated tables.  We would need a coordinated gpbackup/gprestore patch as well:
1.  Have gprestore redirect a primary segment (content id 0) replicated table dump to the coordinator segment using regular COPY FROM.  This wouldn't be too hard to do but adds somewhat confusing restore logic.
  --or--
2. Have gpbackup/gprestore call COPY TO/FROM without ON SEGMENT similar to what you did for gpcopy.  This is the most correct patch idea but would invalidate all previous backups.

I think this PR is okay for GPDB 7X (maybe restrict COPY TO ON SEGMENT as well like I mentioned) but is borderline questionable for a GPDB 6X backport since this isn't necessarily a bug fix but a change in current expected COPY logic.

2021-07-15 07:49 UTC, adam8157 commented on src/test/regress/input/gpcopy.source
> +COPY dist_rep_src TO '/tmp/dist_rep_src_<SEGID>.txt' ON SEGMENT;
Agree with Jimmy on this.

2021-07-15 07:52 UTC, adam8157 commented
What's the status of this PR?

How about making some code changes, merge it into master, and let PMs decide whether to apply to 6X or not?

2021-08-17 02:39 UTC, beeender commented
> How about making some code changes, merge it into master, and let PMs decide whether to apply to 6X or not?

I am not quite sure if this is the right approach. From the google-group discussion, the most sane suggestion is:

> 1) COPY TO ON SEGMENT will only let one segment dump its data for replicated table so that there is only one copy of the data in backup file
> 2) COPY FROM ON SEGMENT will introduce a motion node and broadcast replicated table data to other nodes, or check and re-distributed a tuple to right segment for other cases

`COPY TO` can be implemented easily I think. But adding a motion node to `COPY FROM` looks difficult since it doesn't even have a plan, right?

2021-08-17 03:32 UTC, adam8157 commented
My suggestion was to report an error for `COPY FROM distributed replicated tables ON SEGMENT`, maybe `COPY TO ON SEGMENT` too, on the master branch. But for 6X, since other utilities need to change their behaviors, let PMs decide.

Adding a motion node to `COPY FROM ON SEGMENT` is not a short-term thing, but we could fallback to `COPY FROM` on the coordinator node.

2021-09-23 15:13 UTC, beeender commented
created  #12627 to track this issue. Close this one since it is not the ideal solution.

2021-09-23 15:13 UTC, closed without merging