Docs: fixed typos
greenplum-db/gpdb pull request #12162
Opened 2021-06-15 11:36 UTC by mperezfuster

Fixed two typos on the docs.

2021-06-23 22:01 UTC, dyozie requested changes

2021-06-23 22:01 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpstart.xml
> +            <codeblock>gpstart -m
This line break (inside the codeblock) doesn't seem intentional.

2021-06-23 22:01 UTC, dyozie commented on gpdb-doc/dita/best_practices/summary.xml
> +            <codeph>gp_vmem</codeph> factor with this formulate to account for the
formulate -> formula

2021-06-24 08:50 UTC, mperezfuster commented on gpdb-doc/dita/utility_guide/ref/gpstart.xml
> +            <codeblock>gpstart -m
they are two separate commands, I separated them into two lines since it could be confusing and if you run them as one line you get an error

2021-06-24 17:40 UTC, dyozie approved these changes

2021-06-24 17:40 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpstart.xml
> +            <codeblock>gpstart -m
Sorry - I see it now!

2021-06-24 17:40 UTC, merged