Wrong snapshot for EOF corrupts data in AO/AOCO
greenplum-db/gpdb pull request #12197
Opened 2021-06-22 07:43 UTC by darthunix

In 5X a snapshot satisfies "now" was used when transaction extracted AO/AOCO segment file eof. In other words "now" allowed us to see all committed transactions. When this code was ported to 6X a catalog snapshot was chosen for this purpose. As a result we don't see committed transactions that started after the snapshot has been taken. As a result a transaction can change segment file eof between the moment a snapshot was taken and an exclusive file segment lock was hold. So AO/AOCO in 6X suffers from data corruption in concurrent DML queries.

This PR consists of two commits. The first one demonstrates the problem (all added tests should fail). The second one fixes the problem using snapshot self instead of catalog snapshot - it allows us to see all committed data as "now" in 5X did.

5X and 7X (thanks to a [big refactoring](https://github.com/greenplum-db/gpdb/commit/5778f31124d5737e18d76f8d06f07f96c31c8be7)) do not face this problem.

2021-06-22 09:32 UTC, darthunix commented
It is strange, but Concourse CI doesn't start (I have force pushed to re-run it, but it doesn't work).

2021-06-22 13:03 UTC, gfphoenix78 commented
@darthunix Don't worry, I'm running your PR in my private pipeline. Or, you may amend-and-push your commit and try it again.

2021-06-23 13:19 UTC, asimrp requested changes
`SnapshotSelf` ignores distributed snapshots altogether.  Using it to scan aoseg tables will lead to disastrous consequences.  For instance, a AO insert transaction that is prepared on seg0 and then aborted due to "abort prepared" message from distributed transaction manager on the coordinator.  In the small window where the transaction is prepared, the eof updated by it in aoseg table will be seen as committed by `SnapshotSelf`.

Unless, of course, I'm missing something obvious :-)

2021-06-23 13:23 UTC, asimrp commented
@darthunix do you see a problem in production with current 6X behaviour?  I am very interested in understanding the scenario if it doesn't involve changes directly to segments in utility mode stuff.

2021-06-24 00:34 UTC, darthunix commented on src/test/isolation2/input/uao/snapshot_eof.source
> +0U&:COPY insert_eof FROM PROGRAM 'printf "1\n2\n3\n4\n5\n6\n7\n8\n9\n10"';
I believe that AO/AOCO should not corrupt data under any conditions and utility mode is not an excuse for that. The idea was to make regression tests for all scenarios where we have a time window between taking MVCC snapshot and acquiring and exclusive segment file lock. The more tests we have, the more reliable GPDB is. And this test shows us data corruption, I believe it is a very serious problem and we should leave the test in place (or may be even extent the amount of tests). If one day the logic of choosing segment file number on coordinator would be changed, we can face the same problem for non-utility COPY.

2021-06-24 05:39 UTC, darthunix commented
@asimrp thank you for your review (I really need a feedback it this ticket as my expertise in snapshot visibility is very poor).

1. I have added a new [commit](https://github.com/greenplum-db/gpdb/pull/12197/commits/823de68cf60de0c0b2bc7c2e54ef9be6b8a203a4) demonstrating the same data corruption for non-utility queries. In fact it is the original case where I have detected data corruption in a cluster. All other tests were synthetic ones to close all possible cases I could imagine.
2. In 5X we successfully used [SnapshotNow](https://github.com/greenplum-db/gpdb/blob/72f983002135567b120ff2216a4326be6217dbe5/src/backend/utils/time/tqual.c#L401) that didn't take into account distributed snapshots, when backend took an exclusive segment file lock to move EOF. It was also mixed with MVCC snapshot used for different scans without problems. Was it incorrect too? Or I missed some changes in 6X?

2021-06-24 08:29 UTC, darthunix commented
@asimrp I have also added a new [test](https://github.com/greenplum-db/gpdb/pull/12197/commits/3e26f4b68e80d7da520e9d7c02d47f8aa0cdc50e) to demonstrate that we don't have anomalies with SnapshotSelf in a time window between prepared transaction and two phase commit. Can you look att it - may be I've missed something?

2021-06-28 09:09 UTC, darthunix commented
@asimrp @gfphoenix78 can you take a look at this PR once more? Greenplum 6X corrupts and silently looses committed data in AO tables - it seems to be a **serious** problem.

2021-06-28 11:02 UTC, asimrp commented
@darthunix please note that I'm not denying existence of the problem you have found and fixed.  Thanks for the contribution.  

If I cannot break your PR before my end of day today, I will withdraw my -1.  Thanks for your patience!

2021-06-28 11:55 UTC, asimrp commented on src/test/isolation2/input/uao/snapshot_eof.source
> +3:SELECT count(*) FROM truncate_eof;
Without the fix, this select statement fails on the latest 6X_STABLE with "read beyond eof" error.  The first copy is blocked the the suspended vacuum.  The vacuum holds access exclusive lock on the segment file with segno = 1.  The second copy (session 3) is assigned segno = 2 on QD and proceeds without being blocked.  It creates a new entry in pg_aoseg table with segno = 2 and extends the eof to a non-zero value.  However, this is a two-step process.  First, a frozen tuple is inserted into pg_aoseg table with segno=2 and eof=0.  The eof value is updated later at the end of copy.  Once the suspended vacuum resumes, it sees only the frozen entry for segno = 2 and does not see the updated entry as its snapshot is stale.  It then happily truncates the segfile with segno = 2 to 0 on disk.  And we get the error.

2021-06-28 12:49 UTC, asimrp commented on src/test/isolation2/input/uao/snapshot_eof.source
> +3:SELECT count(*) FROM truncate_eof;
Vacuum is the culprit here.  Without vacuum, the "read beyond eof" error is not possible.  Two or more concurrent DML operations are protected by the centralized segment file assignment logic in `appendonlywirter.c`.

2021-06-28 13:43 UTC, asimrp commented
Although `SnapshotSelf` makes uncommitted data (prepared but not committed) to be seen on QEs,  concurrent vacuum and DML happen to be protected by locks.  In particular, the ao segfile locks.  Allowing uncommitted data to be visible still sounds risky.  As an alternative to `SnapshotSelf`, does it make sense to retake catalog snapshot after waiting on a lock?  Such a change will be needed only in vacuum, because other DML operations are protected by appendonlywriter.c's segfile allocation logic.  Vacuum is the only one that tinkers with all entries in the aoseg table at once.

2021-06-28 13:53 UTC, asimrp commented on src/test/isolation2/input/uao/snapshot_eof.source
> +1:SELECT gp_inject_fault('after_commit_prepared', 'suspend', dbid)
This is not the right fault.  The intention is to suspend the transaction after prepare phase but *before* commit phase.  Consider using `end_prepare_two_phase` fault.

This test can be made more interesting by suspending the insert transaction at different points on different QEs.  E.g. one QE at `end_prepare_two_phase` and other QEs at `start_prepare`.

Vacuum when run concurrently, should see the effects of QE suspended at `end_prepare_two_phase` but `SnapshotSelf` will treat the QEs suspended at `start_prepare` as still in progress, their effects as invisible.

I tried that manually, but realized that vacuum simply skips the segment file being operated on by the insert transaction on all QEs because it is protected by the ao segment file lock.

2021-06-29 03:56 UTC, darthunix commented
> SnapshotSelf makes uncommitted data (prepared but not committed) to be seen on QEs

@asimrp it is the most confusing part that I can't understand. [Prepared transactions](https://github.com/greenplum-db/gpdb/blob/bcda274934047df3c3771c4743652917363fa666/src/backend/access/transam/xact.c#L2901) on QEs are detached and saved in `pg_twophase` directory without writing anything to CLOG (we do [it](https://github.com/greenplum-db/gpdb/blob/bcda274934047df3c3771c4743652917363fa666/src/backend/access/transam/xact.c#L1580) on transaction [commit](https://github.com/greenplum-db/gpdb/blob/bcda274934047df3c3771c4743652917363fa666/src/backend/access/transam/xact.c#L2732)). So prepared data on QEs is not committed. `SnapshotSelf` can see only [committed](https://github.com/greenplum-db/gpdb/blob/bcda274934047df3c3771c4743652917363fa666/src/backend/utils/time/tqual.c#L218) data and changes made by the current command. I thought that we can see uncommitted data only [since](https://github.com/greenplum-db/gpdb/blob/bcda274934047df3c3771c4743652917363fa666/src/backend/utils/time/tqual.c#L38) `HeapTupleSatisfiesDirty()`. If I have confused something please correct me.

That was the reason to use `SnapshotSelf` instead of taking and releasing MVCC snapshots for each segment file under exclusive lock during EOF operations.

2021-06-29 10:53 UTC, asimrp commented
@darthunix you are correct.  I was wrong again - prepared but not committed transactions continue to be seen as in-progress by SnapshotSelf.  The problem with SnapshotSelf is not as severe as I thought.

The problem with SnapshotSelf is it ignores distributed snapshots altogether.  It is equivalent to the visibility interpreted by a utility mode connection directly connected to a Greenplum segment.  If a distributed transaction is finished on seg0 but not yet on seg1, its changes are visible to SnapshotSelf on seg0 but not on seg1.

It is not entirely clear to me whether this problem can affect your patch.

2021-06-29 10:59 UTC, asimrp commented on src/test/isolation2/input/uao/snapshot_eof.source
> +1:SELECT gp_inject_fault('after_commit_prepared', 'suspend', dbid)
Based on my corrected understanding (thank you Denis), the above comment can be ignored.  It is not necessary to test prepared transactions, the test scenario can be removed altogether.

2021-06-29 11:18 UTC, asimrp approved these changes

2021-06-30 00:12 UTC, darthunix commented
> It is not entirely clear to me whether this problem can affect your patch.

I don't think that we need any knowledge about concurrent distributed transactions when move EOF under exclusive lock.
1. VACUUM (truncate and compaction) simply needs the latest committed EOF on a local segment. Any information about distributed transactions is redundant.
2. COPY can cause corruption only in utility mode as distributed COPY is protected by the centralized segment file assignment logic in `appendonlywirter.c`.

So I believe it is safe to use `SnapshotSelf`.

P.S. @asimrp thanks for your review (and for your patience).

2021-07-07 01:53 UTC, kainwen commented
I have manually built a dev pipeline to verify this fix green all the jobs.

Push it, thanks!

2021-07-07 01:56 UTC, merged