First pass at updating -B and adding -b for these 3 utilities
greenplum-db/gpdb pull request #12231
Opened 2021-06-28 22:28 UTC by VMWareJennyBeth

gpaddmirrors
gpmovemirrors
gprecoverseg

2021-06-29 16:33 UTC, niralis13 requested changes

2021-06-29 16:33 UTC, niralis13 commented on gpdb-doc/dita/utility_guide/ref/gprecoverseg.xml
> +          <pd>The maximum number of segments per host to operate on in parallel. Valid values are
Please add the default value here. Something like:  "If not specified, the utility will start recovering up to 64 segments in parallel on each host. "

2021-06-29 16:33 UTC, niralis13 commented on gpdb-doc/dita/utility_guide/ref/gprecoverseg.xml
>            <pt>-B <varname>parallel_processes</varname></pt>
-B parallel_processes --> -B batch_size

2021-06-29 16:33 UTC, niralis13 commented on gpdb-doc/dita/utility_guide/ref/gpmovemirrors.xml
>            <pt>-B <varname>parallel_processes</varname></pt>
-B parallel_processes --> -B batch_size

2021-06-29 16:33 UTC, niralis13 commented on gpdb-doc/dita/utility_guide/ref/gpmovemirrors.xml
> +          <pd>The maximum number of segments per host to operate on in parallel. Valid values are
Please add the default value here. Something like: "If not specified, the utility will start recovering up to 64 segments in parallel on each host. "

2021-06-29 16:33 UTC, niralis13 commented on gpdb-doc/dita/utility_guide/ref/gpmovemirrors.xml
>            [<b>-B</b> <varname>parallel_processes</varname>] [<b>-v</b>] [<b>--hba-hostnames</b> <varname>boolean</varname>]
-B parallel_processes --> -B batch_size

2021-06-29 16:33 UTC, niralis13 commented on gpdb-doc/dita/utility_guide/ref/gpaddmirrors.xml
>                      <pt>-B <varname>parallel_processes</varname></pt>
-B parallel_processes --> -B batch_size

2021-06-29 16:33 UTC, niralis13 commented on gpdb-doc/dita/utility_guide/ref/gpaddmirrors.xml
> +                    <pd>The maximum number of segments per host to operate on in parallel. Valid
Please add the default value here. Something like: "If not specified, the utility will start recovering up to 64 segments in parallel on each host. "

2021-06-29 16:33 UTC, niralis13 commented on gpdb-doc/dita/utility_guide/ref/gpaddmirrors.xml
> +   [<b>-b</b> <varname>segment_batch_size</varname>] [<b>-B</b> <varname>parallel_processes</varname>] [<b>-l</b> <varname>logfile_directory</varname>] [<b>-v</b>]
-B parallel_processes --> -B batch_size

2021-06-29 16:33 UTC, niralis13 commented on gpdb-doc/dita/utility_guide/ref/gprecoverseg.xml
> +             [<b>-b</b> <varname>segment_batch_size</varname>] [<b>-B</b> <varname>parallel_processes</varname>] [<b>-F</b> [<b>-s</b>]] [<b>-a</b>] [<b>-q</b>]
-B parallel_processes --> -B batch_size

2021-06-29 17:22 UTC, niralis13 approved these changes

2021-07-07 19:08 UTC, dyozie approved these changes

2021-07-07 19:08 UTC, merged