search ETag case insensitively
greenplum-db/gpdb pull request #12442
Opened 2021-08-11 10:01 UTC by reshke

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

Some cloud providers form ETAG in a different format, for example Yandex Cloud Object Storage sends it in format
`Etag: "......"`

according to the RFC (https://www.w3.org/Protocols/rfc2616/rfc2616.html)
ETag can be in any case. So we should parse header case insensitively.

also added NextMarker processing logic

2021-08-16 05:43 UTC, x4m requested changes
Hi!
This PR fixes obvious incompatibility with RFC.
Meanwhile, maybe, let's make nearby code a little better?

2021-08-16 05:43 UTC, x4m commented on gpcontrib/gpcloud/src/s3interface.cpp
> +        uint64_t etagStartPos = std::search(headers.begin(), headers.end(), toSearch.begin(), toSearch.end(), [](char ch1, char ch2){
Let's check -1 result of std::search()?

2021-08-16 05:43 UTC, x4m commented on gpcontrib/gpcloud/src/s3interface.cpp
> +        }) - headers.begin() + 6;
maybe sizeof(toSearch) would be slightly better than 6?

2021-08-20 10:28 UTC, x4m commented on gpcontrib/gpcloud/src/s3interface.cpp
> +    if (is_truncated && next_marker) marker = next_marker;
Is this formatting per project style? I could not find similar formatting of ```if-else``` statement in nearby code.

2021-08-20 10:28 UTC, x4m commented on gpcontrib/gpcloud/src/s3interface.cpp
> +            S3_DIE(S3RuntimeError, "responce does not contain etag in header");
responce -> response

2021-08-20 10:28 UTC, x4m commented on gpcontrib/gpcloud/src/s3url.cpp
> +}
This change is correct, but unrelated.

2021-09-17 08:25 UTC, zhaorui20005 commented on gpcontrib/gpcloud/src/s3interface.cpp
> +        });
Could "Etag  " string be in other format?

2021-11-09 10:43 UTC, reshke commented on gpcontrib/gpcloud/src/s3interface.cpp
> +            S3_DIE(S3RuntimeError, "responce does not contain etag in header");
thnx, fixed

2021-11-09 10:43 UTC, reshke commented on gpcontrib/gpcloud/src/s3interface.cpp
> +    if (is_truncated && next_marker) marker = next_marker;
thnx, fixed

2021-11-09 10:50 UTC, x4m approved these changes

2021-11-09 14:03 UTC, zhaorui20005 commented
After I merged this pr on master in my envs, I found it cannot get s3 files correctly.
Take an s3 example, assume we create s3 file like this: 

aws s3 ls us-east-1.s3test.pivotal.io/gpss/ --recursive
2021-09-17 14:55:57          7 gpss/test/photos/2020/photo0
2021-09-17 14:56:06          7 gpss/test/photos/2020/photo1
2021-09-17 14:56:16          7 gpss/test/photos/2020/photo2
2021-09-17 16:14:11          7 gpss/test/photos/2021/photo4
2021-09-17 14:54:08         11 gpss/test/sample.jpg
gpcheckcloud -d "s3://s3-us-east-1.amazonaws.com/us-east-1.s3test.pivotal.io/gpss/test config=/tmp/s3.conf"
photo0
photo1
photo2
photo4
sample.jpg

The above output are what we expect to get.
But after I merged this pr and recompile the gpcheckcloud, it cannot get the expect result, so this pr will make a regression for normal function.

2021-11-16 05:33 UTC, adam8157 commented
@zhaorui20005 what output do you see with this PR? Do you know the cause?

2021-11-16 07:18 UTC, zhaorui20005 commented
> @zhaorui20005 what output do you see with this PR? Do you know the cause?

The valuable codes are added between 490-500 in s3interface.cpp which enables the s3 to recognize the **case insensitive** "ETag"in the response, because some servers which support S3 APIs may return "etag" or "Etag" which cause the s3 failed to recognize the "etag" part and throw an exception.

2021-11-16 09:23 UTC, adam8157 commented
Quote:

    But after I merged this pr and recompile the gpcheckcloud, it cannot get the expect result, so this pr will make a regression for normal function.

You said it can not get the expected result, what output did it get?

2021-11-16 09:25 UTC, zhaorui20005 commented
> Quote:
> 
> ```
> But after I merged this pr and recompile the gpcheckcloud, it cannot get the expect result, so this pr will make a regression for normal function.
> ```
> 
> You said it can not get the expected result, what output did it get?

Empty result. But we expect it can get the file data.

2021-11-17 02:29 UTC, adam8157 reviewed
Will pair with @zhaorui20005 offline to fix these small issues.

2021-11-17 02:29 UTC, adam8157 commented on gpcontrib/gpcloud/src/s3interface.cpp
> +        querySs << "delimiter" << "=" << UriEncode("/");
I guess this is the cause that @zhaorui20005 got empty results.

Will confirm.

2021-11-17 07:35 UTC, adam8157 commented on gpcontrib/gpcloud/src/s3interface.cpp
> +        querySs << "delimiter" << "=" << UriEncode("/");
Confirmed, removed this logic.

2021-11-17 07:37 UTC, merged

2021-11-17 07:38 UTC, adam8157 commented
I removed the "delimiter" logic since it has a regression.

Thanks for the contribution.