writable_external_table_bufsize: correct units
greenplum-db/gpdb pull request #12453
Opened 2021-08-17 23:49 UTC by fifthposition

Based on greenplum-db/sre-test#230

2021-08-24 18:30 UTC, lenapivotal commented on gpdb-doc/dita/ref_guide/config_params/guc-list.xml
> +          <codeph>GB</codeph>, and <codeph>TB</codeph>. Greenplum Database stores data in the buffer
Ben, I think kB -> KB

2021-09-02 21:37 UTC, dyozie requested changes

2021-09-02 21:37 UTC, dyozie commented on gpdb-doc/dita/ref_guide/config_params/guc-list.xml
> +          <codeph>GB</codeph>, and <codeph>TB</codeph>. Greenplum Database stores data in the buffer
Agree - change kB -> KB twice here.

2021-09-07 15:57 UTC, fifthposition commented on gpdb-doc/dita/ref_guide/config_params/guc-list.xml
> +          <codeph>GB</codeph>, and <codeph>TB</codeph>. Greenplum Database stores data in the buffer
I wondered about that :)

2021-09-15 17:56 UTC, dyozie approved these changes

2021-09-15 17:56 UTC, merged