Docs: moved core dump instructions to install guide
greenplum-db/gpdb pull request #12598
Opened 2021-09-16 14:57 UTC by mperezfuster

Ref https://github.com/greenplum-db/gpdb/issues/12329
Core dump instructions should be part of the Install Guide rather than Best Practices.
Preview page:
https://mireia-core.sc2-04-pcf1-apps.oc.vmware.com/7-0/install_guide/prep_os.html#topic3__core_dump

2021-09-16 17:26 UTC, lenapivotal approved these changes
Small suggestions that can be ignored.

2021-09-16 17:26 UTC, lenapivotal commented on gpdb-doc/dita/install_guide/prep_os.xml
> +      <section id="xfs_mount">
I think there's an extra space between soft and core. 
Also, we're asking them to ensure that "soft core unlimited" exists but is it in the `limits.conf` file by default? OR do they add it? Is it a file that user can add various entries?

2021-09-16 17:26 UTC, lenapivotal commented on gpdb-doc/dita/install_guide/prep_os.xml
> +        kernel:<codeblock># sysctl -p</codeblock></p>
Maybe:
To enable the change to the live kernel, run the following command:

2021-09-16 17:36 UTC, VMWareJennyBeth commented on gpdb-doc/dita/install_guide/prep_os.xml
> +        <p>Enable core files output to a known location by adding the following line to
What is this sentence trying to say? Is it to specify where core files' output should go? Is it to just enable output from core files? Is it the output of the core files?

2021-09-17 11:15 UTC, mperezfuster commented on gpdb-doc/dita/install_guide/prep_os.xml
> +        <p>Enable core files output to a known location by adding the following line to
Output acts like a verb here. Since it is not too clear, I will rephrase it.

2021-09-17 11:24 UTC, mperezfuster commented on gpdb-doc/dita/install_guide/prep_os.xml
> +      <section id="xfs_mount">
Thanks, I will rephrase it to ask user to add the line.

2021-09-21 17:26 UTC, ashwinstar approved these changes

2021-10-05 00:47 UTC, dyozie requested changes

2021-10-05 00:47 UTC, dyozie commented on gpdb-doc/dita/install_guide/prep_os.xml
> +      </section>
This closing section tag seems out of place.  The paragraphs that follow still seem to apply to the core dump section.  Either that, or they're orphaned and not part of a section.

2021-10-06 00:37 UTC, dyozie approved these changes

2021-10-06 00:37 UTC, merged