Documentation added for utilities gpmemwatcher and gpmemreport
greenplum-db/gpdb pull request #12854
Opened 2021-11-23 10:26 UTC by mperezfuster

6.19 includes the utilities gpmemwatcher and gpmemreport for memory usage tracking.
Created pages under the utility guide for both utilities.
Preview pages:
https://mireia-gpmemwatcher.sc2-04-pcf1-apps.oc.vmware.com/7-0/utility_guide/ref/gpmemwatcher.html
https://mireia-gpmemwatcher.sc2-04-pcf1-apps.oc.vmware.com/7-0/utility_guide/ref/gpmemreport.html

2021-11-23 10:57 UTC, tbozzio commented
Look good.

2021-11-23 10:58 UTC, tbozzio approved these changes

2021-11-24 11:02 UTC, snithin748 approved these changes
Looks good. Thanks @mperezfuster.

2021-11-30 01:27 UTC, dyozie requested changes

2021-11-30 01:27 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpmemreport.xml
> +      <codeblock><b>gpmemreport</b> [<varname>GZIP_FILE</varname>] [[<b>-s</b> <varname>START</varname>] | [<b>--start=</b> <varname>START</varname>]] [[<b>-e</b> <varname>END</varname>] | [<b>--end=
Instead of all-caps for variable names, let's use lowercase along the lines of the other utilities.  Also, better to change:

START -> start_time
END -> end_time

2021-11-30 01:27 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpmemreport.xml
> +        by <codeph>gpmemwatcher</codeph>, it generates a series of files, where each one of them
one of them -> file

2021-11-30 01:27 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpmemreport.xml
> +        corresponds to a 60 second period of the data collected by <codeph>gpmemwatcher</codeph>
the data -> data

2021-11-30 01:27 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpmemreport.xml
> +      <p>Check under the current directory, all the generated files are
, all -> that all

2021-11-30 01:27 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpmemreport.xml
> +      <p>Check under the current directory, only the selected timestamp files are
, only -> that only

2021-11-30 01:27 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpmemwatcher.xml
> +      <codeblock><b>gpmemwatcher</b> [<b>-f</b> | <b>--host_file</b> <varname>HOSTFILE</varname>]
Same here - use lowercase for varnames.

2021-11-30 01:27 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpmemwatcher.xml
> +      <p>You may use this utility when Greenplum Database is reporting <codeph>Out of
when -> if

2021-11-30 01:27 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpmemwatcher.xml
> +          <pd>Indicates the <varname>hostfile</varname> input file that lists the hosts that the
that the utility will collect the memory usage information from ->
from which the utility will collect memory usage information

2021-11-30 01:27 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpmemwatcher.xml
> +            hostnames and a working directory that must exist in these hosts. For
must exist in these -> exists on each of the

2021-11-30 01:27 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpmemwatcher.xml
> +      <p><b>Example 1: Start the utility specifying the list of hosts to collect the information
to collect the information from -> from which to collect the information

2021-11-30 01:27 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpmemwatcher.xml
> +      <p>Make sure that the path <codeph>/home/gpadmin/gpmemwatcher_dir/working</codeph> exists in
in -> on

2021-11-30 01:27 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpmemwatcher.xml
> +      <p>The results <codeph>.gz</codeph> files will be dumped into the directory where you are
results -> resulting

2021-11-30 01:27 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpmemreport.xml
> +          Greenplum master:</b></p>
remove trailing colon (:) to be consistent with other example headings.

2021-12-03 18:19 UTC, dyozie approved these changes

2021-12-03 18:19 UTC, merged