Fix PANIC error in ALTER TABLE xxx EXPAND PARTITION PREPARE
greenplum-db/gpdb pull request #12935
Opened 2021-12-15 10:49 UTC by SmartKeyerror

The PANIC issue is bringed in by commit: [Expand partition table leaves in parallel.](https://github.com/greenplum-db/gpdb/commit/a45be43489294386c23c5fa068ce071ec068d0d8), here's the setp to reproduce it:

1. Build gpdb without cassert, such as

```
./configure --with-perl --with-python --with-libxml --with-gssapi --enable-debug --disable-cassert --prefix=/usr/local/gpdb
````

2. Run commands:

```
postgres=# create extension if not exists gp_debug_numsegments;
NOTICE:  extension "gp_debug_numsegments" already exists, skipping
CREATE EXTENSION
postgres=# select gp_debug_set_create_table_default_numsegments(1);
 gp_debug_set_create_table_default_numsegments 
-----------------------------------------------
 1
(1 row)

postgres=# begin;
BEGIN
postgres=# ALTER TABLE partition_test EXPAND PARTITION PREPARE;
ALTER TABLE
postgres=# select * from partition_test;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
```

If we exec `ALTER TABLE partition_test EXPAND PARTITION PREPARE` in a transaction and have an access to it next, sunch `select * from partition_test` or `select * from gp_distribution_policy`, QD or QE will PANIC cause wrong `relation->rd_cdbpolicy`.

The root cause is that we used GpPolicy data that may become invalid in function `ATExecExpandPartitionTablePrepare`:

```cpp
static void
ATExecExpandPartitionTablePrepare(Relation rel)
{
        // ......
	if (GpPolicyIsRandomPartitioned(rel_dist) || rel->rd_rel->relkind == RELKIND_PARTITIONED_TABLE)
	{
		GpPolicyReplace(relid, root_dist);
		rel->rd_cdbpolicy = root_dist;        // here
	}
}
```

In fact, the `ALTER TABLE` command will invoke `ATExecCmd()`, which will call `CommandCounterIncrement()` to increase command numbers and invalid relation cache entry by `CommandEndInvalidationMessages()`, which invoke `RelationClearRelation()` eventually. The function `RelationClearRelation()` will physically blow away a relation cache entry, or reset it and rebuild it from scratch, also include the GpPolicy of a relation.

And in the inner of `GpPolicyReplace()`, it'll invalid the relation cache entry by `CatalogTupleUpdate` by send a message using SI (Share Invalid), which will be processed by `ProcessInvalidationMessages` in `CommandCounterIncrement()`.

Since the relation in `ATExecExpandPartitionTablePrepare` is fetched by `relation_open()`, which could be a cache result in relation cache. If we update the `rd_cdbpolicy`, it could update the relation cache entry's `rd_cdbpolicy ` to the new one, which not we wanted. 

If the relation's GpPolicy is pointer to new policy, `RelationClearRelation()` **will not** swap the GpPolicy with a new relation entry, it still pointer to old memory address. And then, the release of memory will cause a null pointer exception.

2021-12-15 12:56 UTC, kainwen commented
LGTM.

1. Please create a GitHub issue to record the details
2. reword a bit the commit message and add comments in the code.

2021-12-15 23:01 UTC, ashwinstar requested changes

2021-12-15 23:12 UTC, ashwinstar commented
> Please create a GitHub issue to record the details

We can though not sure is necessary. We should try to capture most of context in commit message, change set and test associated with it. I understand many times github issue exists or mailing list discussion exist which has lot of context and referring it in code or commit message helps. In this case none exist and just to capture the context opening the issue while fixing seems overwork. Instead in this case can easily capture in commit context itself.

> I think it is a good chance for you to try to find out why with-cassert not (or not easy) to reproduce?

Interesting, yes need to think, I fell chances of failure with asserts enabled will be higher as  `CLOBBER_FREED_MEMORY` and `RELCACHE_FORCE_RELEASE` are defined with asserts enabled.

2021-12-16 02:19 UTC, SmartKeyerror commented on src/backend/commands/tablecmds.c
> -		rel->rd_cdbpolicy = root_dist;
The point is that we do not need to assign new policy to `rel` in this situation, so we can just use `GpPolicyReplace` to update catalog.
Thanks for the code of  correct switching memory context, it's pretty nice, I'll do some research on it.

2021-12-16 02:27 UTC, ashwinstar commented on src/backend/commands/tablecmds.c
> -		rel->rd_cdbpolicy = root_dist;
> The point is that we do not need to assign new policy to rel in this situation, so we can just use GpPolicyReplace to update catalog.

on-disk and memory should reflect same reality. Understand currently there might be no code referring to this relation's policy after we have updated the catalog within this command. But if in future some code is added which refers to the relations policy, it can be get inconsistent results (old policy or new policy) based on if the invalidation request gets processed in-between command (which is very well possible).

2021-12-16 03:13 UTC, SmartKeyerror commented on src/backend/commands/tablecmds.c
> -		rel->rd_cdbpolicy = root_dist;
That's right, I'll change it.

2021-12-21 00:03 UTC, ashwinstar commented on src/backend/commands/tablecmds.c
> +		rel->rd_cdbpolicy = GpPolicyCopy(new_policy);
Why we make the copy 2 times? Can't we just `MemoryContextSwitchTo(GetMemoryChunkContext(rel));` while making the new_policy first time and then just assign it here?

2021-12-21 00:03 UTC, ashwinstar commented on src/backend/commands/tablecmds.c
> +	GpPolicy *new_policy = NULL;
Seems the scope of this variable should be just inside the `if` block where its used.

2021-12-21 00:03 UTC, ashwinstar commented on src/backend/commands/tablecmds.c
> +			oldcontext = MemoryContextSwitchTo(GetMemoryChunkContext(rel));
even for this case should be able to switch the context before `createRandomPartitionedPolicy()`, and avoid this copy again, no?

2021-12-21 03:43 UTC, SmartKeyerror commented on src/backend/commands/tablecmds.c
> +		GpPolicy	 *new_policy;
I think this codes are much wordy, but if we extraction this logic to a function, it's a bit weird:

```cpp
/*
 * Change num segments of given relation, and make the policy between on-disk
 * catalog and on-memory relation cache consistently.
 */
void
GpPolicyReplaceNumSegments(Relation rel, const int new_numsegments)
{
	GpPolicy	 *new_policy;
	MemoryContext oldcontext;

	oldcontext = MemoryContextSwitchTo(GetMemoryChunkContext(rel));

	new_policy = GpPolicyCopy(rel->rd_cdbpolicy);
	new_policy->numsegments = new_numsegments;

	GpPolicyReplace(RelationGetRelid(rel), new_policy);

	/* We should make the policy between on-disk catalog and on-memory relation cache consistently */
	rel->rd_cdbpolicy = new_policy;
	MemoryContextSwitchTo(oldcontext);
}
```

It is not at the same level as `GpPolicyReplace`, just an encapsulation for it. So I think it's not appropriate to extraction the repeated code to a single function, which will be used rarely.

2021-12-22 00:11 UTC, ashwinstar approved these changes
Overall LGTM, just need to address that last comment

2021-12-22 00:11 UTC, ashwinstar commented on src/backend/commands/tablecmds.c
> +		MemoryContextSwitchTo(oldcontext);
we only wish to be in `GetMemoryChunkContext(rel)` for `GpPolicyCopy()`. Lets reset the context soon after that's done. Like any allocation done by `GpPolicyReplace()` we don't wish to do in this context.

2021-12-22 00:11 UTC, ashwinstar commented on src/backend/commands/tablecmds.c
> +		GpPolicy	 *new_policy;
Agree its okay to not extract the same in separate function

2021-12-22 18:43 UTC, ashwinstar approved these changes
:+1: Thanks for interactively incorporating the review comments

2021-12-23 14:06 UTC, kainwen approved these changes
LGTM.

When merging this, please reword the commit message a bit. Might consider adding why with-cassert not produce the issue?

Thanks for you contribution!

2021-12-24 02:25 UTC, SmartKeyerror commented
@kainwen Actually, the version build with `--enable-cassert` also can reproduce this problem, if we use the example I posted in this pr, but it not failed in pipeline.

2021-12-24 05:59 UTC, kainwen commented
> @kainwen Actually, the version build with `--enable-cassert` also can reproduce this problem, if we use the example I posted in this pr, but it not failed in pipeline.

Thanks for your explanation!

2021-12-24 06:13 UTC, merged