Make sendControlMessage to retry when interrupted
greenplum-db/gpdb pull request #12968
Opened 2022-01-04 08:15 UTC by Aegeaner

As #12961 mensioned, `sendControlMessage()` is sent without retry, that is because in normal case, UDPIFC's retransmit mechanism will handle the normal data packet loss issue, and will retransmit UDP packets with another ACK sent, so there is no need to retry in `sendControlMessage()`, as [the comments](https://github.com/greenplum-db/gpdb/blob/f4ffe428f06616cf50904f5eb5f129f19ce6ba98/src/backend/cdb/motion/ic_udpifc.c#L1774) pointed out. But for some special case, if the ACK is loss, it will not retransmit with UDP packets, e.g. in the EOS ACK message case.

In this PR, I move `sendto()` call with retry logic to a new method, so any relative call can reuse it enabling retries when interrupted.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [x] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2022-01-06 06:22 UTC, adam8157 requested changes
I see three `sprintf()` as of now, it's not safe, please use `snprintf()` if it has to do that.

Or better, can we refactor it to avoid `sprintf`/`snprintf`?

2022-01-06 07:44 UTC, Aegeaner commented
> I see three `sprintf()` as of now, it's not safe, please use `snprintf()` if it has to do that.
> 
> Or better, can we refactor it to avoid `sprintf`/`snprintf`?

I have removed all uses of `sprintf`, use `snprintf` instead.

2022-01-06 11:39 UTC, interma commented on src/backend/cdb/motion/ic_udpifc.c
>  			ereport(LOG,
there is a EAGAIN before:
```
		if (errno == EAGAIN)	/* no space ? not an error. */
			return;
```
I feel it also should do retry, don't why return here before.

2022-01-06 11:43 UTC, interma commented on src/backend/cdb/motion/ic_udpifc.c
> +		ereport(WARNING, (errcode(ERRCODE_GP_INTERCONNECTION_ERROR),
So, all send cannot cause error after this PR?
I think giving a return value for `sendtoWithRetry()` is better, then the caller can do notice/error/warning by its purpose. 
And I think cannot send package (after some tries) should trigger an error.

2022-01-06 12:39 UTC, Aegeaner commented on src/backend/cdb/motion/ic_udpifc.c
>  			ereport(LOG,
If space is not available at the sending socket to hold the message to be transmitted and the socket file descriptor does have O_NONBLOCK set (By `pg_set_noblock(fd)` to the socket), sendto() shall fail. In this case, it will wait for `Gp_interconnect_timer_checking_period` and retransmit.

2022-01-06 12:46 UTC, Aegeaner commented on src/backend/cdb/motion/ic_udpifc.c
> +		ereport(WARNING, (errcode(ERRCODE_GP_INTERCONNECTION_ERROR),
I will restore to ERROR level here.

2022-01-07 03:09 UTC, adam8157 approved these changes

2022-01-14 07:56 UTC, zhaorui20005 commented on src/backend/cdb/motion/ic_udpifc.c
> +		return;
Did not find good improvements of this retry. The old "sendOnce" can retry as many times as needed if interrupted. Why not just replace "sendto" with "sendOnce"?
I doubt if this pr really solves the https://github.com/greenplum-db/gpdb/issues/12961 issue?

2022-01-14 07:56 UTC, zhaorui20005 commented on src/backend/cdb/motion/ic_udpifc.c
> +	char errDetail[100];
Magic number 100 seems not good.

2022-01-29 02:27 UTC, Aegeaner commented on src/backend/cdb/motion/ic_udpifc.c
> +		return;
This pr refactored the code to make all send logic such as `sendControlMessage` and `SendDummyPacket` etc.,  to use the same logic with `sendOnce`. This is part of the refactor code, as this method will be called in `SendDummyPacket` with limit count times, I added a count param.

2022-01-29 09:31 UTC, zhaorui20005 commented on src/backend/cdb/motion/ic_udpifc.c
> +		return;
Maybe I do not fully understand this logic. But I have question with the logic that when we try to call "send" or "sendto " through a socket, and the return value is -1 and error number is "EINTR " then we should try to call it again on no conditions, why do we here set retry number instead try again on no conditions?
The old function "sendOnce" retry to call sendto on no conditions which is the right way to handle socket return value. 
So I doubt if we could simply substitute the function "sendto" with "sendOnce"?
The new function "sendtoWithRetry" only add some log messages and reduce the retry numbers in extreme situations. 
So back to the original issue, I doubt if the sending EOS failure may not be figured out by the return value of the sendto. Or the failure caused by interrupted by signals.
If I have wrong points, please point me out.

2022-01-29 13:57 UTC, Aegeaner commented on src/backend/cdb/motion/ic_udpifc.c
> +		return;
> Maybe I do not fully understand this logic. But I have question with the logic that when we try to call "send" or "sendto " through a socket, and the return value is -1 and error number is "EINTR " then we should try to call it again on no conditions, why do we here set retry number instead try again on no conditions? The old function "sendOnce" retry to call sendto on no conditions which is the right way to handle socket return value. So I doubt if we could simply substitute the function "sendto" with "sendOnce"? The new function "sendtoWithRetry" only add some log messages and reduce the retry numbers in extreme situations.

In short, `sendOnce` and `sendto(-*)` are functions at different level. 
`void sendOnce(ChunkTransportState *transportStates, ChunkTransportStateEntry *pEntry, ICBuffer *buf, MotionConn *conn)` is a high level function, we can get its purpose from the parameters which is to send an `ICBuffer` which is a fundamental unit of the data.


`ssize_t sendto(int socket, const void *message, size_t length, int flags, const struct sockaddr *dest_addr, socklen_t dest_len);` is a low level Posix API method called by `sendOnce()`.
I abstracted the retry logic and created a new encapsulated function `sendtoWithRetry`, which is a enhanced version of `sendto`, which is also a low-level method.


`inline void
sendControlMessage(icpkthdr *pkt, int fd, struct sockaddr *addr, socklen_t peerLen)` is another high level method which calls `sendto`, while the message sending is a control message (including EOS, ACK, etc.) by type `icpkthdr`, so we cannot directly use another high level method with diffrent purpose which is `sendOnce` inside it.

> And back to the original issue, I doubt if the sending EOS failure may not be figured out by the return value of the sendto. Or the failure caused by interrupted by signals. If I have wrong points, please point me out.

Possible EOS packet losses is reported  in #12961 and many other jiras. Though the scenario is hard to reproduce in lab, but it's reasonable to unify the low-level sending logic of both normal data and control message.

2022-02-01 02:15 UTC, zhaorui20005 commented on src/backend/cdb/motion/ic_udpifc.c
> +		return;
OK, Thanks for your explanation!
One last question: why would we need to control the retry numbers when interrupted by signal ? Why not just keep retrying calling "sendto" until success or failure with other errno?

2022-02-10 07:54 UTC, z-wenlin commented on src/backend/cdb/motion/ic_udpifc.c
> -				continue;
The Logic in SendDummyPacket before is when `errno == EINTR || errno == EAGAIN || errno == EWOULDBLOCK` it will retry the sendto.
But currently, SendDummyPacket is calling sendtoWithRetry, but sendtoWithRetry seems only retry when errno == EINTR.
Besides that, the before logic has some goto send_error label, not sure if the logic after refactors is the same.

2022-02-10 08:03 UTC, z-wenlin commented on src/backend/cdb/motion/ic_udpifc.c
>  		if (errno == EINTR)
As https://github.com/greenplum-db/gpdb/issues/12961 mentioned, the sender slice has sent EOS to receiver slice and the receiver slice will send ACK to the sender slice process, but if the network is bad, the sender might not receive ACK from the receiver,  based on my understanding, the PR is improving the `sendControlMessage`, add retry logic, so for 12961 scenarios, when the packet is lost, what's the errno would be?
Seems that `errno ENTER` is `A signal interrupted sendto() before any data was transmitted` and it will retry when `errno == ENTER`?

2022-03-29 06:56 UTC, merged