fix: before insert/update row trigger that modifies the distributed key
greenplum-db/gpdb pull request #13002
Opened 2022-01-14 12:59 UTC by seaboxsg

If the insert/update before row trigger modifies the distributed key,
that would destroy the distributed rule, we should not allow this happen.

The illustration case:

create table t(id int primary key, color text) distributed by(id);

create or replace function insert_before_row() returns trigger as
$$
begin
  new.id = new.id + 1;
  return new;
end;
$$ language plpgsql;

create trigger insert_before_trig before insert on t
  for each row execute procedure insert_before_row();

insert into t values(1, 'red');

select * from t;
 id | color
----+-------
  2 | red
(1 row)

-- no rows return beacuse the row stored in the segment that
-- hashed by value 1, not 2.
select * from t where id=2;
 id | color
----+-------
(0 rows)

-- no rows retrun beacuse the row is filtered out by condition of
-- "id=1".
select * from t where id=1;
 id | color
----+-------
(0 rows)

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2022-01-17 01:24 UTC, SmartKeyerror commented
By the way, 6X has this issue too.

2022-01-17 03:45 UTC, SmartKeyerror requested changes

2022-01-17 03:45 UTC, SmartKeyerror commented on src/backend/executor/nodeModifyTable.c
> +	GpPolicy   *policy = relation->rd_cdbpolicy;
we should never use local variable to store the pointer to `rel->rd_cdbpolicy`, instead should use the `rel->rd_cdbpolicy` directly wherever required. 

Refer to commit [0bfc725](https://github.com/greenplum-db/gpdb/commit/0bfc72517d7a28d5a4143ba026f57e5f35caf29e) for reasons for the same. Main thing is relcache invalidation can happen anytime and locally stored can easily become stale.

2022-01-17 03:45 UTC, SmartKeyerror commented on src/backend/executor/nodeModifyTable.c
> +		Datum		values[MaxPolicyAttributeNumber];
Why use `MaxPolicyAttributeNumber ` instead of `resultRelationDesc->rd_cdbpolicy->nattrs`?

2022-01-17 03:45 UTC, SmartKeyerror commented on src/backend/executor/nodeModifyTable.c
> +			 * , since trigger invocation can guarantee that the row structure(columns
"," should not be placed at the beginning of a line

2022-01-18 01:16 UTC, seaboxsg commented on src/backend/executor/nodeModifyTable.c
> +		Datum		values[MaxPolicyAttributeNumber];
Yes, this will cause some memory waste, i will use resultRelationDesc->rd_cdbpolicy->nattrs in next commit.

2022-01-18 01:18 UTC, seaboxsg commented on src/backend/executor/nodeModifyTable.c
> +			 * , since trigger invocation can guarantee that the row structure(columns
Thanks for reminding.

2022-01-18 01:24 UTC, seaboxsg commented
Should i create another pull request for that?
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Mon, Jan 17, 2022 09:24 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [greenplum-db/gpdb] fix: before insert/update row trigger that modifies the distributed key (PR #13002)

&nbsp;



 
By the way, 6X has this issue too.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2022-01-18 01:27 UTC, seaboxsg commented on src/backend/executor/nodeModifyTable.c
> +	GpPolicy   *policy = relation->rd_cdbpolicy;
Thanks for reminding.

2022-01-18 08:54 UTC, seaboxsg commented on src/backend/executor/nodeModifyTable.c
> +	GpPolicy   *policy = relation->rd_cdbpolicy;
Thanks for reminding.

2022-01-18 14:37 UTC, SmartKeyerror commented
> Should i create another pull request for that?

Thanks for your contribution! We greatly appreciate that you can open another pull request for 6X_STABLE after this pull request merged.

2022-01-19 01:24 UTC, seaboxsg commented on src/backend/executor/nodeModifyTable.c
> +	GpPolicy   *policy = relation->rd_cdbpolicy;
Thanks for reminding.

2022-01-19 01:33 UTC, seaboxsg commented
&nbsp;Should i do something else for commit merge, i see there left a "1 change requested", should i something for this, thanks!

&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Tue, Jan 18, 2022 10:39 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [greenplum-db/gpdb] fix: before insert/update row trigger that modifies the distributed key (PR #13002)

&nbsp;



  
Should i create another pull request for that?
  
Thanks for your contribution! We greatly appreciate that you can open another pull request for 6X_STABLE after this pull request merged.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2022-01-20 02:52 UTC, SmartKeyerror commented
Remind by my colleagues, I found that Triggers are not supported in gpdb:

> 6. Triggers are not supported since they typically rely on the use of VOLATILE functions.

We can find this in the document: [Summary of Greenplum Features](https://gpdb.docs.pivotal.io/6-19/ref_guide/feature_summary.html)

After discussion, we think there is no need to fix this anymore, we no longer need to spend more time on features that are not supported.

Thanks again for your contribution! Sorry for not being able to bring your contribution into the master branch this time, we will do better for the next time.

2022-01-21 08:55 UTC, seaboxsg commented
> 



> Remind by my colleagues, I found that Triggers are not supported in gpdb:
> 
> > 6. Triggers are not supported since they typically rely on the use of VOLATILE functions.
> 
> We can find this in the document: [Summary of Greenplum Features](https://gpdb.docs.pivotal.io/6-19/ref_guide/feature_summary.html)
> 
> After discussion, we think there is no need to fix this anymore, we no longer need to spend more time on features that are not supported.
> 
> Thanks again for your contribution! Sorry for not being able to bring your contribution into the master branch this time, we will do better for the next time.



> Remind by my colleagues, I found that Triggers are not supported in gpdb:
> 
> > 6. Triggers are not supported since they typically rely on the use of VOLATILE functions.
> 
> We can find this in the document: [Summary of Greenplum Features](https://gpdb.docs.pivotal.io/6-19/ref_guide/feature_summary.html)
> 
> After discussion, we think there is no need to fix this anymore, we no longer need to spend more time on features that are not supported.
> 
> Thanks again for your contribution! Sorry for not being able to bring your contribution into the master branch this time, we will do better for the next time.

Hi, thanks for your reply.
I still have some confuse: I executed trigger sqls in greeplum6.19, it could execute successfully. As follows:

```sql
[postgres@node1 greenplum-db]$ psql -p30200 postgres
psql (9.4.26)
Type "help" for help.

postgres=#
postgres=# select version();
                                                                                                      version

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------
 PostgreSQL 9.4.26 (Greenplum Database 6.19.0 build commit:c88801925e5d51e4be57f54ff2158ed74a264b8e Open Source) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on
Dec  8 2021 23:08:44
(1 row)

postgres=# create schema qp_misc_jiras;
CREATE SCHEMA
postgres=# CREATE TABLE qp_misc_jiras.test_trig(id int, aaa text) DISTRIBUTED BY (id);
CREATE TABLE
postgres=# INSERT INTO qp_misc_jiras.test_trig VALUES (1, 'before creating trigger');
INSERT 0 1
postgres=# SELECT gp_segment_id, * FROM qp_misc_jiras.test_trig;
 gp_segment_id | id |           aaa
---------------+----+-------------------------
             1 |  1 | before creating trigger
(1 row)
postgres=#
postgres=# CREATE OR REPLACE FUNCTION fn_trig() RETURNS TRIGGER LANGUAGE plpgsql AS $$
postgres$# BEGIN
postgres$#    NEW.aaa = NEW.aaa || '1';
postgres$#    NEW.id = NEW.id + 1;
postgres$#    RAISE NOTICE '%', NEW.id;
postgres$# RETURN NEW;
postgres$# END
postgres$# $$;
CREATE FUNCTION
postgres=#
postgres=#
postgres=# CREATE TRIGGER test_trig_1
postgres-# BEFORE INSERT OR UPDATE ON qp_misc_jiras.test_trig
postgres-# FOR EACH ROW
postgres-#     EXECUTE PROCEDURE fn_trig();
CREATE TRIGGER
postgres=#
postgres=#
postgres=#
postgres=# INSERT INTO qp_misc_jiras.test_trig VALUES (0, 'after creating trigger');
NOTICE:  1  (seg1 192.168.154.4:30301 pid=19985)
INSERT 0 1
postgres=#
postgres=# INSERT INTO qp_misc_jiras.test_trig VALUES (1, 'aaa');
NOTICE:  2  (seg1 192.168.154.4:30301 pid=19985)
INSERT 0 1
postgres=# SELECT gp_segment_id, * FROM qp_misc_jiras.test_trig;
 gp_segment_id | id |           aaa
---------------+----+-------------------------
             1 |  1 | before creating trigger
             1 |  1 | after creating trigger1
             1 |  2 | aaa1
(3 rows)
```

Before insert row trigger(test_trig_1) works when insert rows, and the select results also had the issues that i described in the commit message.

So i suppose the users could use triggers on tables to do some special things, and i do find the sentence " 6. Triggers are not supported since..." in  [Summary of Greenplum Features](https://gpdb.docs.pivotal.io/6-19/ref_guide/feature_summary.html), so i am confused that the trigger feature is actually supported or not in greenplum stable 6x or in master branch? 

Expect your reply, thanks!

2022-01-22 06:22 UTC, SmartKeyerror commented
Yes, we can use triggers in 6X_STABLE and master branch, even though the document says triggers are not supported in Greenplm Database, it just only disabled at the document level.

2022-06-21 01:42 UTC, closed without merging