gpstate -e : Display ongoing recovery progress
greenplum-db/gpdb pull request #13026
Opened 2022-01-21 11:02 UTC by pobbatihari

Added new section under gpstate -e, which displays progress of segments in recovery

-Edited buildMirrorSegments to create new file (recovery_progress.file) and updates
the current recovery progress, deletes the file after recoveries are completed.
-Added new section under gpstate -e to display progress of segments in recovery
-Added _parse_recovery_progress_data(), which will look for the recovery_progress.file
and populate the required fields
-Added behave and unit tests for above scenario

Sample output:
-----------------------------------------------------
Segments in recovery
Segment                     Port   Recovery type   Completed bytes (kB)   Total bytes (kB)   Percentage completed
hmaddileti-a01.vmware.com   7002   full            1164848                1371715            84%
hmaddileti-a01.vmware.com   7003   incremental     1171384                1371875            85%
hmaddileti-a01.vmware.com   7004   full            116488                 1371715            60%

Co-authored-by: Divyesh Vanjare <vanjared@vmware.com>

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2022-01-21 19:39 UTC, kaknikhil commented on gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
> +        coordinator_remove_cmd = base.Command("remove file", "rm -f %s" % coordinator_progress_file)
I haven't looked into the PR carefully yet, these are some of my initial thoughts

1.  What happens if gprecoverseg fails before this step ? We should also add a behave test where we make gprecoverseg fail and then assert that this file doesn't exist.
2. This also makes me think of the case when for some reason the `recovery_progress.file` doesn't get deleted (for e.g. . someone interrupts gprecoverseg). What should the next run of gprecoverseg do ? Should we overwrite the existing file ?

2022-01-24 10:50 UTC, divyeshddv commented on gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
> +        coordinator_remove_cmd = base.Command("remove file", "rm -f %s" % coordinator_progress_file)
Updated gpstate logic to additionally look for gprecoverseg.lock file. Since this file gets deleted if gprecoverseg fails/interupted), we can use this file to determine if gprecoverseg is actually running

> 1. What happens if gprecoverseg fails before this step ? We should also add a behave test where we make gprecoverseg fail and then assert that this file doesn't exist.

Even if the file exists, we will now also look for gprecoverseg.lock - to determine if recoverseg is in progress. This way, we will only show progress if recovery is actually running 

> 2. This also makes me think of the case when for some reason the `recovery_progress.file` doesn't get deleted (for e.g. . someone interrupts gprecoverseg). What should the next run of gprecoverseg do ? Should we overwrite the existing file ?

Every run will overwrite the file (whether or not it exists), to show progress of current recoveries

2022-01-24 10:57 UTC, divyeshddv commented on gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
> +        coordinator_progress_file = "{}/recovery_progress.file".format(gplog.get_logger_dir())
is gpAdminLogs directory a good place to keep this file? Should we instead keep it under coordinator_data_directory?

Considering user could delete files from adminLogs directory at any point if they want, and it should not affect utils behavior.

2022-03-01 23:10 UTC, jmcatamney commented on gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
> +                    fp.flush()
This `flush` should come after the `write` on the following line.

2022-03-01 23:12 UTC, jmcatamney commented
The updates in response to Nikhil's feedback look good, but I'm going to hold off on approving this for now as the upcoming merge of the gprecoverseg PR may necessitate changes to this one after the rebase.

2022-03-01 23:19 UTC, divyeshddv commented on gpMgmt/test/behave/mgmt_utils/gpstate.feature
> +    @wip
We currently have tests for checking if 
- gprecoverseg creates a progress file
- gpstate can read from a correctly formatted progress file

We might also need to add some tests for checking if the file that gprecoverseg is formatted correctly

Also we can remove the wip tags on behave

2022-03-02 06:40 UTC, pobbatihari commented on gpMgmt/test/behave/mgmt_utils/gpstate.feature
> +    @wip
@divyeshddv  removed wip tags.  I feel it will be tricky to add behave test for checking contents of progress file, since we do flush the content based on recovery progress and delete the file once the progress completes.

2022-03-05 00:00 UTC, divyeshddv commented
Rebased the PR over the gprecoverseg new workflow changes

2022-03-05 03:03 UTC, kaknikhil requested changes

2022-03-05 03:03 UTC, kaknikhil commented on gpMgmt/test/behave/mgmt_utils/gpstate.feature
> +        And a sample recovery_progress.file is created with completed recoveries in gpAdminLogs
what if we decide to change the name of the recovery progress file and don't update this test ? This test will still pass

2022-03-05 03:03 UTC, kaknikhil commented on gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
> +@then('recovery_progress.file should not exist')
We might already have a step for this, might be worth scanning the code base.

2022-03-07 05:47 UTC, pobbatihari commented on gpMgmt/bin/gppylib/programs/clsSystemState.py
> +            exitCode = 1
agree. Since we are printing the progress changing exitcode to 0

2022-03-07 07:16 UTC, pobbatihari commented on gpMgmt/test/behave/mgmt_utils/gpstate.feature
> +        And a sample recovery_progress.file is created with completed recoveries in gpAdminLogs
i think next step in this testcase might fail.

2022-03-07 22:11 UTC, divyeshddv commented on gpMgmt/bin/gppylib/programs/clsSystemState.py
> +            exitCode = 1
The exitCode here signifies that the cluster is running in perfect/preferred state. Since there are still some recoveries in progress/segments down.

When exitCode is 0, we print "All segments are running normally" which is not the case when some recoveries are in progress.

2022-03-07 22:11 UTC, divyeshddv commented on gpMgmt/bin/gppylib/programs/clsSystemState.py
> +            exitCode = 1
The exitCode here signifies that the cluster is running in perfect/preferred state. Since there are still some recoveries in progress/segments down.

When exitCode is 0, we print "All segments are running normally" which is not the case when some recoveries are in progress.

2022-03-11 22:50 UTC, divyeshddv approved these changes
Code LGTM. Added a comment about a small nit on field name

2022-03-11 22:50 UTC, divyeshddv commented on gpMgmt/bin/gppylib/programs/clsSystemState.py
> +VALUE_RECOVERY_COMPLETED_BYTES = FieldDefinition("Completed bytes (kB)", "recovery_completed_bytes", "int")
Nit: `Completed bytes (kB)`  - we say bytes but actually mean kB. I don't know if there is a better way to word this field.

2022-03-12 02:31 UTC, merged