Backport: Free disk space for dropped relations
greenplum-db/gpdb pull request #13091
Opened 2022-02-14 22:35 UTC by degaurab

backport commits:
- d9d15d3b7b77ff3df3e2451ceff00adafad71c26
- d3a4fa897aef820386b3cb6f2f14650aa0dcbe6c

Reference: https://github.com/greenplum-db/gpdb/pull/11988/commits

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [x] Communicate in the mailing list if needed
- [] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2022-02-16 02:47 UTC, haolinw commented on src/backend/storage/smgr/md.c
> +register_forget_request(RelFileNodeBackend rnode, ForkNumber forknum, BlockNumber segno)
The argument forknum is not used in this function. Should pass MAIN_FORKNUM directly in the caller ?

2022-02-16 02:58 UTC, haolinw commented on src/backend/storage/smgr/md.c
> +			register_forget_request(rnode, forkNum, 0 /* first seg */ );
There is a case that forkNum != MAIN_FORKNUM, but calling register_forget_request() to hard code the forknum to MAIN_FORKNUM internally, it seems a little confused. Can we re-arrange this piece of code to clarify the logic here ?

2022-02-16 03:00 UTC, haolinw commented on src/backend/storage/smgr/md.c
> +				register_forget_request(rnode, forkNum, segno);
If only supports MAIN_FORKNUM in register_forget_request(), pass it directly.

2022-02-16 03:26 UTC, haolinw commented on src/backend/storage/smgr/md.c
> +			register_forget_request(rnode, forkNum, 0 /* first seg */ );
Actually I have some concern on backporting the commit "[Free disk space for dropped relations on commit.](https://github.com/greenplum-db/gpdb/pull/11988/commits/ca26c0668b72e310c48101e474b54fdd39729f33)" due to lack of the FILETAG facilities on 6X. It may bring coding complexity and different implementations between 6X and master without backporting the whole FILETAG stuffs. So I'm wondering is it really a critical reproducible issue on 6X ?

2022-02-17 03:02 UTC, jimmyyih requested changes
@degaurab Let's close this PR and split the commits into their own: 1) The AO open file leak and 2) The HEAP not truncating held files on DROP.

For commit (1), it's fairly straight forward.  For commit (2), I'll help you get through the merge conflicts and provide a more detailed description to assist PR reviewers.

2022-02-17 08:22 UTC, haolinw commented on src/backend/storage/smgr/md.c
> +			register_forget_request(rnode, forkNum, 0 /* first seg */ );
Indeed. I reproduced it, too, leaving already deleted file occupying disk space for uncertain period is not a good behavior.

2022-02-18 01:05 UTC, degaurab commented
Closing the PR in favour of splitting into 2 separate PRs:
- [Free disk space for dropped relations on commit](https://github.com/greenplum-db/gpdb/pull/13107)
- [Close AO segment file](https://github.com/greenplum-db/gpdb/pull/13105)

2022-02-18 01:05 UTC, closed without merging