Fix incorrect use of waived vmem chunks when reserving vmem chunks
greenplum-db/gpdb pull request #13241
Opened 2022-03-14 02:59 UTC by dreamedcheng

When a QE process has used out the waived chunks, and didn't
release any chunks yet, at this very moment, another QE may
also need waived chunks to process error messages. However,
with previouse vmem reserving logic, the second QE will loop
in gp_malloc and gp_failed_to_alloc again and again, and finally
exit abnormally.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2022-03-14 03:01 UTC, dreamedcheng commented
Without the fix, we may get the following error stack:
![image](https://user-images.githubusercontent.com/7367189/158097458-3b7dde22-a62a-443f-aec0-c6a201dcb127.png)

2022-03-15 06:34 UTC, higuoxing commented on src/backend/utils/mmgr/vmem_tracker.c
> +
```suggestion
	SIMPLE_FAULT_INJECTOR("vmem_oom_startup");
```

`SIMPLE_FAULT_INJECTOR()` expands to nothing if `FAULT_INJECTOR ` isn't enabled, so we don't need to guard it with the macro.

2022-03-15 06:34 UTC, higuoxing commented on src/backend/tcop/postgres.c
> +						VmemTracker_SetTrackedBytes(VmemTracker_GetReservedVmemBytes()+(1<<VmemTracker_GetChunkSizeInBits())-20);
Could you please explain more about this formula?

Besides, you may want to use `CHUNKS_TO_BYTES()` ?
```suggestion
						VmemTracker_SetTrackedBytes(VmemTracker_GetReservedVmemBytes()+CHUNKS_TO_BYTES(1)-20);
```

2022-03-15 12:18 UTC, dreamedcheng commented on src/backend/utils/mmgr/vmem_tracker.c
> +
OK, I'll remove it later.

2022-03-15 12:18 UTC, dreamedcheng commented on src/backend/tcop/postgres.c
> +						VmemTracker_SetTrackedBytes(VmemTracker_GetReservedVmemBytes()+(1<<VmemTracker_GetChunkSizeInBits())-20);
Under the circumstance that session 1  has consumed all vmem chunks including waivedChunks, we set session 2's trackedBytes close to threshold that it needs to reserve a new chunk, so that it can easily trigger `gp_malloc` and find that no available chunks remained. Then session 2 will the handle OOM error messages, and call `gp_malloc` again.

2022-03-15 13:52 UTC, higuoxing commented on src/backend/tcop/postgres.c
> +						VmemTracker_SetTrackedBytes(VmemTracker_GetReservedVmemBytes()+(1<<VmemTracker_GetChunkSizeInBits())-20);
Thanks for your explanation. I'm curious that why we need to substract 20-byte from it? What does the 20-byte stand for?

2022-03-16 03:44 UTC, dreamedcheng commented on src/backend/tcop/postgres.c
> +						VmemTracker_SetTrackedBytes(VmemTracker_GetReservedVmemBytes()+(1<<VmemTracker_GetChunkSizeInBits())-20);
HAHA, 20 bytes is kind of a small number I chosen arbitrarily, so that it can easily trigger the logic of reserving new vmem chunks when `gp_malloc` is called. Of course, other small number is also OK, like 100, 200 and so on.

2022-03-16 07:25 UTC, dreamedcheng commented on src/backend/tcop/postgres.c
> +						VmemTracker_SetTrackedBytes(VmemTracker_GetReservedVmemBytes()+(1<<VmemTracker_GetChunkSizeInBits())-20);
> CHUNKS_TO_BYTES

Thanks for the comment, the reason that I didn't use `CHUNKS_TO_BYTES(1)` is that it's a macro defined in `vmem_tracker.c`, so we can't use it in `postgres.c`.

2022-03-16 07:55 UTC, dreamedcheng commented on src/backend/tcop/postgres.c
> +						VmemTracker_SetTrackedBytes(VmemTracker_GetReservedVmemBytes()+(1<<VmemTracker_GetChunkSizeInBits())-20);
> this fix ensures that every QE process has it own waived vmem chunks to handle error messages.



> Thanks for your explanation. I'm curious that why we need to substract 20-byte from it? What does the 20-byte stand for?

I go through the related code again, and found there is no need to subtract a small number given that the trackedBytes has been set to `VmemTracker_GetReservedVmemBytes()+(1<<VmemTracker_GetChunkSizeInBits())`. I modified it in the latest push.

2022-03-17 06:01 UTC, higuoxing commented on src/test/isolation2/sql/oom_elog_message.sql
> +-- This case tests OOM when writting elog messages into server log files.
After playing with this test case, I encountered some failure by running it multiple times. Anyway, this test looks good to me. I'm going to investigate it later.

```diff
diff -I HINT: -I CONTEXT: -I GP_IGNORE: -U3 /home/v/x/gh/gpdb-master/src/test/isolation2/expected/oom_elog_message.out /home/v/x/gh/gpdb-master/src/test/isolation2/results/oom_elog_message.out
--- /home/v/x/gh/gpdb-master/src/test/isolation2/expected/oom_elog_message.out	2022-03-17 00:12:38.291614242 +0800
+++ /home/v/x/gh/gpdb-master/src/test/isolation2/results/oom_elog_message.out	2022-03-17 00:12:38.291614242 +0800
@@ -94,8 +94,9 @@
  Success:                 
 (1 row)
 1: select temp_t3.c1, temp_t3.c2, temp_t3.c3, temp_t3.c4, temp_t3.c5, temp_t3.c6, temp_t3.c7, temp_t3.c8, temp_t3.c9, temp_t3.c10, temp_t3.c1+temp_t3.c2, temp_t3.c2+temp_t3.c3, temp_t3.c3+temp_t3.c4, temp_t3.c4+temp_t3.c5, temp_t3.c6+temp_t3.c7, temp_t3.c7+temp_t3.c8, + temp_t3.c9+temp_t3.c10 from (select temp_t2.c1, temp_t2.c2, temp_t2.c3, temp_t2.c4, temp_t2.c5, temp_t2.c6, temp_t2.c7, temp_t2.c8, temp_t2.c9, temp_t2.c10, temp_t2.c1+temp_t2.c2, temp_t2.c2+temp_t2.c3, temp_t2.c3+temp_t2.c4, temp_t2.c4+temp_t2.c5, temp_t2.c6+temp_t2.c7, temp_t2.c7+temp_t2.c8, + temp_t2.c9+temp_t2.c10  from (select temp_t1.c1, temp_t1.c2, temp_t1.c3, temp_t1.c4, temp_t1.c5, temp_t1.c6, temp_t1.c7, temp_t1.c8, temp_t1.c9, temp_t1.c10, temp_t1.c1+temp_t1.c2, temp_t1.c2+temp_t1.c3, temp_t1.c3+temp_t1.c4, temp_t1.c4+temp_t1.c5, temp_t1.c6+temp_t1.c7, temp_t1.c7+temp_t1.c8, + temp_t1.c9+temp_t1.c10 from (select c1, c2, c3, c4, c5, c6, c7, c8, c9, c10 from test_vmem_tbl limit 1000000000) temp_t1 limit 1000000000) temp_t2 limit 100000) temp_t3 limit 10000;
-DETAIL:  Vmem limit reached, failed to allocate XXX bytes from tracker, which has XXX MB available
-ERROR:  Out of memory
+DETAIL:  timeout expired
+ERROR:  failed to acquire resources on one or more segments
+(seg<ID> IP:PORT)
 2: select gp_inject_fault_infinite('vmem_oom_set_startup_chunks', 'reset', dbid) from gp_segment_configuration where content = 0 and role = 'p';
  gp_inject_fault_infinite 
 --------------------------
@@ -112,15 +113,17 @@
  Success:                 
 (1 row)
 3<:  <... completed>
-DETAIL:  FATAL:  Out of memory
-DETAIL:  Per-query memory limit reached: current limit is 20480 kB, , has 0 MB available for this query
+DETAIL:  timeout expired
 ERROR:  failed to acquire resources on one or more segments
 (seg<ID> IP:PORT)
 1q: ... <quitting>
 2q: ... <quitting>
 3q: ... <quitting>
 1: drop table test_vmem_tbl;
-DROP
+DETAIL:  FATAL:  Out of memory
+DETAIL:  Vmem limit reached, failed to allocate XXX bytes from tracker, which has XXX MB available
+ERROR:  failed to acquire resources on one or more segments
+(seg<ID> IP:PORT)
 GP_IGNORE:-- start_ignore
 GP_IGNORE:!\retcode gpconfig -c gp_log_format -v csv;
 GP_IGNORE:-- start_ignore
```

2022-03-17 07:54 UTC, dreamedcheng commented on src/backend/tcop/postgres.c
> +					 * Set the trackedBytes of the QE proces, so the function VmemTracker_ReserveVmemChunks
Good catch!

2022-03-17 07:58 UTC, dreamedcheng commented on src/backend/utils/mmgr/vmem_tracker.c
> +		else if (new_vmem > vmemLimitChunks + waivedChunks)
There is one case missed in the last push. Given `vmemLimitChunks = 60 , new_vmem = 61,  numChunksToReserve = 2, waivedChunks = 1, usedWaivedChunks = 0`, in the last push, it won' report OOM error, but the `usedWaivedChunks` is not updated correctly (actual value is 0 but the correct value should be 1). I correct it in the latest push, and based on that, I removed the second condition.

Speaking of `new_vmem > vmemLimitChunks + waivedChunks - usedWaivedChunks`, I don't think it is reasonable, since the `usedWaivedChunks` is already included in `new_vmem`.

2022-03-19 08:09 UTC, higuoxing commented on src/test/isolation2/sql/oom_elog_message.sql
> +-- This case tests OOM when writting elog messages into server log files.
I can't see the failure with the latest commit, so mark it as resolved.

2022-03-19 08:09 UTC, higuoxing commented on src/backend/utils/mmgr/vmem_tracker.c
> +		else if (new_vmem > vmemLimitChunks + waivedChunks)
Got it. Thanks for the information. Now I think this PR looks good.

2022-03-19 08:14 UTC, higuoxing approved these changes
LGTM. Since this PR is modifying the vmemtracker's memory accounting strategy, it might be good to have somebody else to take a look as well :-) @kainwen

2022-03-23 06:46 UTC, SmartKeyerror commented on src/backend/utils/mmgr/vmem_tracker.c
> +		if (waivedChunks > 0 && usedWaivedChunks + extraChunks <= waivedChunks)
Does this work if we enabled the resource group? It seems do not consider reserve memory from resource group.

2022-03-23 09:39 UTC, dreamedcheng commented on src/backend/utils/mmgr/vmem_tracker.c
> +		if (waivedChunks > 0 && usedWaivedChunks + extraChunks <= waivedChunks)
A quick look at the related code, resource group may also have the problem. Will fix it later in this PR.

2022-03-24 08:40 UTC, dreamedcheng commented
Hi all, I fix the same problem when reserving chunks from resgroup memory, and resolve some code format issues.

2022-03-25 06:56 UTC, SmartKeyerror reviewed
Thanks for your contribution and modification! And I think we should have more disscussion on this, especially in function `ResGroupReserveMemory()`.

2022-03-25 06:56 UTC, SmartKeyerror commented on src/backend/utils/resgroup/resgroup.c
> +		extraChunks = Min(deltaGlobalSharedMemUsage, globalOveruse);
Could you give more explanation on this? 

In my view, `groupIncMemUsage()` should always return the overused memory from global free memory. On your code, if we got a negative free chunks from `pResGroupControl->freeChunks`, for instance, -10, and we suppose the value of `deltaGlobalSharedMemUsage` is 20. Then `globalOveruse` will be 30,  `extraChunks` will be 20. 
It seems we lost 10 chunks on our account.

2022-03-25 06:56 UTC, SmartKeyerror commented on src/backend/utils/resgroup/resgroup.c
> + * Return the extra chunks need to reserve from waived chunks.
In my opinion, the function of `groupIncMemUsage` should never know the existence of waived chunks, they should not be coupled together. This function should calculate memory chunks with slot/share/global memory only.
What do you think?

2022-03-25 07:17 UTC, dreamedcheng commented on src/backend/utils/resgroup/resgroup.c
> +			*rgUsedWaivedChunks = overuseMem;
This is because usedWaivedChunks can't be modified here. Note that, when calculating if the requested vmem chunks will overflow `segmentVmemChunks`, we also need to see if waived chunks is required. So we can only update `usedWaivedChunks` until all the condition is satisfied, and update the `usedWaivedChunks` with the larger one in the end.

2022-03-25 07:31 UTC, dreamedcheng commented on src/backend/utils/resgroup/resgroup.c
> +		extraChunks = Min(deltaGlobalSharedMemUsage, globalOveruse);
The reason why resource group OOM will also trigger the abort problem is that resgroup will use `globalOveruse ` to compare with `waivedChunks`. But actually, `globalOveruse` is not represents current QE process' requested chunks that may need to reserve from `waivedChunks`. So here we use `Min(deltaGlobalSharedMemUsage, globalOveruse)` to represents that instead. 

In your case, when `pResGroupControl->freeChunks` is -10, it may mean that other QE process already overuse 10 chunks, but in current QE, we only needs `20` chunks, and this fix assure that every QE has its own waived chunks to
process error messages.

2022-03-25 07:42 UTC, dreamedcheng commented on src/backend/utils/resgroup/resgroup.c
> + * Return the extra chunks need to reserve from waived chunks.
In the original logic, function `groupIncMemUsage ` will return the global overused chunks, after the modifications, it just returns current QE's overused chunks. I think this would be fine, or perhaps, we need some extra work to calculate the overused chunks.

2022-03-28 02:00 UTC, SmartKeyerror reviewed
For the last push, I just have some minor comments on it, the core logic of calculate extra chunks need in function `groupIncMemUsage()` and the waived chunks in `VmemTracker_ReserveVmemChunks()` and `ResGroupReserveMemory()` are looks fine for me.

But there were to many angles in this area, we need more eyes on it.

2022-03-28 03:33 UTC, dreamedcheng commented on src/backend/utils/resgroup/resgroup.c
> +		extraChunks = Min(deltaGlobalSharedMemUsage, globalOveruse);
Thanks for the comments. I've added more detailed comments and changed "extraChunks" to  "extraChunksNeed".

2022-04-13 06:40 UTC, haolinw commented on src/test/isolation2/sql/resgroup/resgroup_oom_elog.sql
> +1: select temp_t3.c1, temp_t3.c2, temp_t3.c3, temp_t3.c4, temp_t3.c5, temp_t3.c6, temp_t3.c7, temp_t3.c8, temp_t3.c9,
Seems this is easily flaky, I happened to fail at the first time run. Is that based on something like predicting the memory size limit of the running host ?
```
cat regression.diffs 
diff -I HINT: -I CONTEXT: -I GP_IGNORE: -U3 /home/gpadmin/workspace/gpdb/src/test/isolation2/expected/resgroup/resgroup_oom_elog.out /home/gpadmin/workspace/gpdb/src/test/isolation2/results/resgroup/resgroup_oom_elog.out
--- /home/gpadmin/workspace/gpdb/src/test/isolation2/expected/resgroup/resgroup_oom_elog.out	2022-04-13 22:23:33.333816988 +0800
+++ /home/gpadmin/workspace/gpdb/src/test/isolation2/results/resgroup/resgroup_oom_elog.out	2022-04-13 22:23:33.334816988 +0800
@@ -69,8 +73,9 @@
  Success:                 
 (1 row)
 1: select temp_t3.c1, temp_t3.c2, temp_t3.c3, temp_t3.c4, temp_t3.c5, temp_t3.c6, temp_t3.c7, temp_t3.c8, temp_t3.c9, temp_t3.c10, temp_t3.c1+temp_t3.c2, temp_t3.c2+temp_t3.c3, temp_t3.c3+temp_t3.c4, temp_t3.c4+temp_t3.c5, temp_t3.c6+temp_t3.c7, temp_t3.c7+temp_t3.c8, temp_t3.c9+temp_t3.c10 from (select temp_t2.c1, temp_t2.c2, temp_t2.c3, temp_t2.c4, temp_t2.c5, temp_t2.c6, temp_t2.c7, temp_t2.c8, temp_t2.c9, temp_t2.c10, temp_t2.c1+temp_t2.c2, temp_t2.c2+temp_t2.c3, temp_t2.c3+temp_t2.c4, temp_t2.c4+temp_t2.c5, temp_t2.c6+temp_t2.c7, temp_t2.c7+temp_t2.c8, temp_t2.c9+temp_t2.c10 from (select temp_t1.c1, temp_t1.c2, temp_t1.c3, temp_t1.c4, temp_t1.c5, temp_t1.c6, temp_t1.c7, temp_t1.c8, temp_t1.c9, temp_t1.c10, temp_t1.c1+temp_t1.c2, temp_t1.c2+temp_t1.c3, temp_t1.c3+temp_t1.c4, temp_t1.c4+temp_t1.c5, temp_t1.c6+temp_t1.c7, temp_t1.c7+temp_t1.c8, temp_t1.c9+temp_t1.c10 from (select c1, c2, c3, c4, c5, c6, c7, c8, c9, c10 from test_vmem_tbl limit 1000000000) temp_t1 limit 1000000000) temp_t2 limit 100000) temp_t3 limit 10000;
-DETAIL:  Resource group memory limit reached
-ERROR:  Out of memory
+ c1 | c2 | c3 | c4 | c5 | c6 | c7 | c8 | c9 | c10 | ?column? | ?column? | ?column? | ?column? | ?column? | ?column? | ?column? 
+----+----+----+----+----+----+----+----+----+-----+----------+----------+----------+----------+----------+----------+----------
+(0 rows)
 1: select gp_inject_fault_infinite('vmem_oom_set_tracked_bytes', 'reset', dbid) from gp_segment_configuration where content = 0 and role = 'p';
  gp_inject_fault_infinite 
 --------------------------
```

2022-04-13 06:44 UTC, haolinw commented on src/test/isolation2/sql/oom_elog_message.sql
> +1: select temp_t3.c1, temp_t3.c2, temp_t3.c3, temp_t3.c4, temp_t3.c5, temp_t3.c6, temp_t3.c7, temp_t3.c8, temp_t3.c9,
Same as resgroup, seems to be flaky.

2022-04-13 06:51 UTC, dreamedcheng commented on src/test/isolation2/sql/resgroup/resgroup_oom_elog.sql
> +1: select temp_t3.c1, temp_t3.c2, temp_t3.c3, temp_t3.c4, temp_t3.c5, temp_t3.c6, temp_t3.c7, temp_t3.c8, temp_t3.c9,
Did you set `gp_resource_manager` to `group`? This case requires that the resgroup is enabled.

2022-04-13 07:04 UTC, haolinw commented on src/test/isolation2/sql/resgroup/resgroup_oom_elog.sql
> +1: select temp_t3.c1, temp_t3.c2, temp_t3.c3, temp_t3.c4, temp_t3.c5, temp_t3.c6, temp_t3.c7, temp_t3.c8, temp_t3.c9,
All right. After setting that, it succeeded. But shouldn't that be set automatically during the test like resgroup/restore_default_resgroup ?

2022-04-13 07:31 UTC, dreamedcheng commented on src/test/isolation2/sql/resgroup/resgroup_oom_elog.sql
> +1: select temp_t3.c1, temp_t3.c2, temp_t3.c3, temp_t3.c4, temp_t3.c5, temp_t3.c6, temp_t3.c7, temp_t3.c8, temp_t3.c9,
Before writing this case, I refer to many existing resgroup related cases. These cases din't set `gp_resource_manager` to `group` separately.  Instead, they are run in a group, and at the beginning of the group (e.g., `isolation2_resgroup_schedule`) there will be a case to modify the GUCs. 

I follow that philosophy. Because changing `gp_resource_manager` need to restart the cluster, avoid changing it in every single resgroup related case can save the total run time of the test.

2022-04-13 07:39 UTC, haolinw commented on src/test/isolation2/sql/resgroup/resgroup_oom_elog.sql
> +1: select temp_t3.c1, temp_t3.c2, temp_t3.c3, temp_t3.c4, temp_t3.c5, temp_t3.c6, temp_t3.c7, temp_t3.c8, temp_t3.c9,
> Because changing gp_resource_manager need to restart the cluster,

Your case does need to restart the cluster, right ? Maybe set it together with gp_log_format and restart. 
Anyway, I see  your point. Either way works for me. Just want to make sure it is not based on any prediction of resource limit for target running machine.

2022-04-13 07:50 UTC, kainwen commented on src/test/isolation2/sql/resgroup/resgroup_oom_elog.sql
> +1: select temp_t3.c1, temp_t3.c2, temp_t3.c3, temp_t3.c4, temp_t3.c5, temp_t3.c6, temp_t3.c7, temp_t3.c8, temp_t3.c9,
resgroup test suites will enable in the first test. These tests are dependent.

2022-04-13 07:53 UTC, haolinw commented on src/test/isolation2/sql/resgroup/resgroup_oom_elog.sql
> +1: select temp_t3.c1, temp_t3.c2, temp_t3.c3, temp_t3.c4, temp_t3.c5, temp_t3.c6, temp_t3.c7, temp_t3.c8, temp_t3.c9,
Got it.

2022-04-13 07:54 UTC, dreamedcheng commented on src/test/isolation2/sql/resgroup/resgroup_oom_elog.sql
> +1: select temp_t3.c1, temp_t3.c2, temp_t3.c3, temp_t3.c4, temp_t3.c5, temp_t3.c6, temp_t3.c7, temp_t3.c8, temp_t3.c9,
The case doesn't based on any prediction of resource limit for target running machine. It will inject fault `resgroup_set_mem_chunks` to set the value of  `slot->memUsage`, `group->memSharedUsage` and `pResGroupControl->freeChunks` to pretend as all related memory are used out. Besides, all of these target value are based on the properies of the resgroup not the machine.

2022-04-21 10:50 UTC, yaowangm commented
I do have some major concerns...

Firstly let me try to summarize the issue: say there is 100MB as vmem limit, and session can use 1MB as waived memory. Session 1# required memory, and found all the 100MB limit was occupied, then required 1MB more as waived memory. Note now the used memory (`segmentVmemChunks`) was 101MB, and session #1 kept the memory. At the meantime session 2# required memory, and tried to require 1MB more as waived memory. For now, `new_vmem` (`segmentVmemChunks + numChunksToReserve`) was 102MB, which was larger than 101MB (`vmemLimitChunks + waivedChunks`), and failed at the check:

```
        if (new_vmem > vmemLimitChunks + waivedChunks)
        {   
            /* Revert query memory reservation */
            pg_atomic_sub_fetch_u32((pg_atomic_uint32 *)&MySessionState->sessionVmem, numChunksToReserve);
            /* Revert vmem reservation */
            pg_atomic_sub_fetch_u32((pg_atomic_uint32 *)segmentVmemChunks, numChunksToReserve);
            /* Revert resgroup memory reservation */
            ResGroupReleaseMemory(numChunksToReserve);

            return MemoryFailure_VmemExhausted;
        }   
```

In other words, once the vmem limit is hit, and a session has required waived memory, other session is not able to require more waived memory. Furthermore, when session #2 failed to require memory, it was to elog the OOM error which required more memory and failed again due to the same check. So there was an infinite loop till abnormal abort.

The proposed fix inducted a new var `usedWaivedChunks` to record the actual used waived memory:

```
static int32 usedWaivedChunks = 0;
```

Instead of checking `new_vmem > vmemLimitChunks + waivedChunks`, **it just checks whether required waived memory is under the limit of waivedChunks**:

```
	if (!ResGroupReserveMemory(numChunksToReserve, waivedChunks - usedWaivedChunks, &requestWaivedChunks, &waiverUsed))
	{
		pg_atomic_sub_fetch_u32((pg_atomic_uint32 *)&MySessionState->sessionVmem, numChunksToReserve);
		return MemoryFailure_ResourceGroupMemoryExhausted;
	}
...
		/*
 		 * If current reserve exceeds vmem limit of the segment, see if the QE process
 		 * has sufficient waivedChunks remained, reserve the extra chunks from it.
		 */
		if (waivedChunks > 0 && usedWaivedChunks + extraChunksNeed <= waivedChunks)
		{
			/*
			 * If a resource group also reserved some chunks from available
			 * waivedChunks, we should update the requestWaivedChunks with the
			 * larger one needs to reserve.
			 */
			requestWaivedChunks = Max(extraChunksNeed, requestWaivedChunks);
		}
		else
		{
			/* Revert query memory reservation */
...
```
The result is, each QE can require waived memory under waivedChunks limit and ignore the check of total memory usage. Back to the case above: with the fix, session 2# would require enough memory when it under waivedChunks limit. Even if it failed due to some waived memory was required previously by the same QE and no quota left,  it still can require more waived memory to elog the OOM error in gp_failed_to_alloc():
```
308     /* Request 1 MB of waiver for processing error */
309     VmemTracker_RequestWaiver(1024 * 1024);
```

However, I don't think it's a correct direction. `vmemLimitChunks` is a global limit across all QEs. `waivedChunks` allows QE to require a little bit more memory over the limit to elog OOM error, so it should also be treated as a global limit. The actual limit is `vmemLimitChunks` + `waivedChunks`.

The fix actually exceeds the global limit. Since each QE has its own `waivedChunks`, the actual limit is `vmemLimitChunks` + `waivedChunks` * `QE count`. That means, there may be uncountable "over usage" of waived memory if QE count keeps increasing, and the global limit is ignored at all. Say there is 500 QEs and each QE required 1MB waived memory, we will get 500MB as memory over usage. It's possible that no more 500MB memory available at all. In addition, since `waivedChunks` can increase by `VmemTracker_RequestWaiver()`, there is actually no upper limit.

You may argue that 500 QEs is a corner case and there might be enough memory left even when `vmemLimitChunks` is hit. But we can never rely on "the error will rarely happen". Once the error happens, it would be very hard to track. We need a thorough, self-consistent solution.

I am still thinking about possible solutions, and will update later.

2022-04-21 12:06 UTC, dreamedcheng commented
Good analysis!

The maximum overused chunks is `max_connectinos * 1MB`, so the maximum chunks a segment might used is `gp_vmem_protect_limit + max_connectinos * 1MB` (still has a limit). If we still want `gp_vmem_protect_limit` to control the maximum chunks a segment can reserve, perhaps, we could set `vmemLimitChunks` to `gp_vmem_protect_limit - max_connectinos * 1MB`. 

Of course, better solutions are welcome, thanks.

2022-04-25 11:11 UTC, yaowangm commented
> The maximum overused chunks is `max_connectinos * 1MB`, so the maximum chunks a segment might used is `gp_vmem_protect_limit + max_connectinos * 1MB` (still has a limit). If we still want `gp_vmem_protect_limit` to control the maximum chunks a segment can reserve, perhaps, we could set `vmemLimitChunks` to `gp_vmem_protect_limit - max_connectinos * 1MB`.

Thanks for your idea. I am afraid it's infeasible. `vmemLimitChunks` is not simply decided by `gp_vmem_protect_limit`. In resource group, it's decided by `pResGroupControl->totalChunks`, which is a result of a series of complex setting and algorithms. Please see the code path:

```
VmemTracker_ReserveVmemChunks
--VmemTracker_GetVmemLimitChunks
----ResGroupGetVmemLimitChunks
```
So we cannot simply change `vmemLimitChunks`, at least when RG is enabled.

Some thoughts of possible solutions:

### Solution 1

**Use a global var `usedWaivedChunks`** instead of the per QE one. Also set `waivedChunks` (or `waivedLimitChunks` might be a better name) to a bigger value (e.g. 5~10MB). Once a QE required waived memory, add the usage to `usedWaivedChunks` till it hits `waivedLimitChunks`. By this, we have `vmemLimitChunks` + `waivedLimitChunks` as a total limit which will never be exceeded.

However, there still are side-effects:

1. We actually reserve some memory of size `waivedLimitChunks` which cannot be used by regular usage. Considering the size is just 5~10MB, it might be acceptable.
2. For an extreme case, hundreds of QEs requires waived memory and `waivedLimitChunks` is hit. After that, any QE requires waived memory will fail, and we will hit the same issue again. It might also acceptable because it's unnecessary to log for each QE when hundreds of QEs hit OOM, but seems ugly more or less.

### Solution 2

The essential problem is that we try to require more memory when OOM is hit. The requirement itself should be treated as improper. Since we are warned with "no more memory available",  how can we require more memory (even for logging)? The correct direction should to **avoid requiring more memory after OOM**.

Look back to the code in elog.c line 4241 according to the stack:

```
    else if (edata->internalpos > 0) 
        appendStringInfo(&buf, _(" at character %d"),
                         edata->internalpos);
```

The error happened when it required memory for string buffer of log. Why don't we **use a pre-allocated buffer with fixed size** for that? Since it's just for log string, 200 bytes or a little bit more might be enough. When QE starts, it always allocates the buffer for OOM and avoids requiring more memory after OOM. If it works, we might don't need waived memory at all since it's just for log OOM error.

After all, I didn't get much time to go through all the details. They are just ideas and I cannot guarantee they are feasible. @dreamedcheng If you have interest and time, could you please continue with them (or any other better idea you have)? Feel free to talk me if help is needed. Thanks!

2022-04-26 03:08 UTC, yaowangm requested changes
Please see my previous comments.

2022-04-27 03:27 UTC, dreamedcheng commented
Thanks for your feedbacks.

I think solution 1 may be better. Because `elog` might need to request a very large buffer according to query string length. 

By the way, with solution 1, when the pre-reserved waivedchunks is used out, we could use `write_stderr` to print error message, which will use pre-allocated space. What do you think of this solution.

2022-04-28 08:00 UTC, yaowangm reviewed
I'd to clarify:

> By the way, based on solution 1, when the pre-reserved waivedchunks is used out, we could use `write_stderr` to print error message, which will use pre-allocated space to avoid request new memory chunks.

Why do you think `write_stderr` uses pre-allocated memory? I took a basic look and it uses buffer like this:

```
    char        errbuf[2048];
```

It requires memory on stack instead of heap. Although it avoids explicit palloc, it requires memory dynamically but not pre-allocating. So we still can over the total limit (vmem track will be not aware of that because the memory size is not counted), right?

In reverse, if we can use pre-allocated memory (such as `static char...`) in `write_stderr`, we can always use `write_stderr` to log OOM and abandon `waivedChunks` at all.

2022-04-28 12:18 UTC, dreamedcheng commented
Sorry for the unclear description `pre-allocated memory`, let me describe my solution more clearly:

Firstly, the code trigger the problem is` elog(LOG, "Logging memory usage for reaching Vmem limit"); ` when no sufficient vmem chunks and waivedChunks.

Secondly, I want to use `write_stderr` to replace `elog(LOG, ....)` (just like the way when `MemoryFailure_SystemMemoryExhausted` error happens.).  Because write_stderr reserve memory from stack memory (yes, this isn't pre-allocated) space (`palloc` won't be called). So we can avoid the problem.  

Of course we can eliminate waivedChunks by replacing all `elog(LOG, ....)` with `write_stderr`, but we may lose some details such as the query trigger the problem, and all the other things we want to show in `elog`.  So we'd better use `write_stderr` in some extreme cases.

Thirdly, the subsequent `ereport(ERROR,` wouldn't stuck in the infinite loop. This is because, its log level is `ERROR`, which will throw the error in `errfinish`. Moreover, when `ereport(ERROR,` was called more than 2 times (controlled by `in_error_recursion_trouble`), the `debug_query_string` and `error_context_stack` will be cleared. So it's very likely that afterwards `ereport(ERROR,` won't OOM again, because `ErrorContext` has pre-allocated memory to process small error messages.

2022-04-29 02:25 UTC, yaowangm commented
Thanks for your explanation. Let me summarize the solution we are talking about:

1. ( solution 1 ) Use a global var `usedWaivedChunks` instead of the per QE one. Also set `waivedChunks` (or `waivedLimitChunks` might be a better name) to a bigger value (e.g. 5~10MB). Once a QE required waived memory, add the usage to `usedWaivedChunks` till it hits `waivedLimitChunks`.
2. Once `waivedLimitChunks` is hit, use `write_stderr` instead of `elog` to log OOM error to avoid requiring more memory on heap.

It's still not a thorough solution, but at least we can reduce the risk to minimum scope. As to solution 2, it might be too radical and will cause too big change. So I am fine with current solution.

Please go ahead with the solution and open a new PR when the code is ready. Feel free to let me know if you have any question. Thanks for your work in advance.

2022-04-29 02:57 UTC, dreamedcheng commented
OK, I'll go on the work in a new PR.

2022-04-30 12:46 UTC, yaowangm commented
> > Use a global var usedWaivedChunks instead of the per QE one.
> 
> @yaowangm what do you mean by global variable? Global Variable is private to each process.

When I mentioned "a global var" I actually meant "a variable shared by all processes".

2022-05-04 01:52 UTC, dreamedcheng commented
Speaking of the global shared variable. There are two ways to give it an initial value (available waived chunks in total):

1. By adding a GUC.
2. Use a hard code value.

which way do you think is better?

2022-05-05 07:29 UTC, SmartKeyerror commented
> Speaking of the global shared variable. There are two ways to give it an initial value (available waived chunks in total):
> 
> 1. By adding a GUC.
> 2. Use a hard code value.
> 
> which way do you think is better?

In my own opinion, using a GUC to initial the available waived chunks is a better choice, it's more flexible.

2022-05-06 01:52 UTC, dreamedcheng commented
> In my own opinion, using a GUC to initial the available waived chunks is a better choice, it's more flexible.

Thanks. I'll use a GUC.

2022-05-07 02:30 UTC, dreamedcheng commented
Hi all,

I opened a new PR https://github.com/greenplum-db/gpdb/pull/13443/files to fix this issues. Could help to take a look? Thanks!

The new PR maintains the logic of the old in the aspects of request waived chunks and reserve vmem chunks. The main difference lies in that: 
  1. not every QE will have 1MB waived vmem, but all QE will share a fixed amount of global waived chunks (controlled by a GUC `gp_vmem_waiver_limit`, default 5MB).
  2. if there is no avaiable waived vmem in the segment, afterwards requests for waived chunks won't get any waived vmem, so the QE will use `write_stderr` to print OMM messages instead of `elog` (this could prevent the QE from being stuck in infinite loop and abort in the end).
  3. since we used a global shared variable `freeWaivedVmemChunks` to record global available waived chunks, plus the modifications we made above, unit test of `vmem_tracker_test.c` is modified accordingly.

2022-05-07 02:33 UTC, dreamedcheng commented
Hi all,

I opened a new PR https://github.com/greenplum-db/gpdb/pull/13443/files to fix this issues. Could help to take a look? Thanks!

The new PR maintains the logic of the old in the aspects of request waived chunks and reserve vmem chunks. The main difference lies in that: 
  1. not every QE will have 1MB waived vmem, but all QE will share a fixed amount of global waived chunks (controlled by a GUC `gp_vmem_waiver_limit`, default 5MB).
  2. if there is no avaiable waived vmem in the segment, afterwards requests for waived chunks won't get any waived vmem, so the QE will use `write_stderr` to print OMM messages instead of `elog` (this could prevent the QE from being stuck in infinite loop and abort in the end).
  3. since we used a global shared variable `freeWaivedVmemChunks` to record global available waived chunks, plus the modifications we made above, unit test of `vmem_tracker_test.c` is modified accordingly.

2022-05-13 01:50 UTC, closed without merging

2022-05-13 01:50 UTC, dreamedcheng commented
The PR is closed. 

The issue will be fixed in PR https://github.com/greenplum-db/gpdb/pull/13443.