[WIP] Prevent gp_tablespace_segment_location() from executing on entrydb QE
greenplum-db/gpdb pull request #13287
Opened 2022-03-21 12:08 UTC by interma

This PR fix https://github.com/greenplum-db/gpdb/pull/13075 in 6x.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2022-03-23 01:12 UTC, interma commented on src/backend/optimizer/util/pathnode.c
> +	if (!strcmp(proname, "gp_tablespace_segment_location"))
compare the function name one by one is not effective here, but I think it's acceptable: 
* there are not many such functions
* only `exec_location == PROEXECLOCATION_ALL_SEGMENTS` and run on entrydb does this check

2022-03-23 02:39 UTC, kainwen requested changes
I think the banned list logic might be added in `init_fcache`. Please spike it.

2022-03-23 02:39 UTC, kainwen commented on src/backend/optimizer/util/pathnode.c
> +	// check by oid (if it has a fixed oid)
`/* */` style comments.

2022-03-23 02:39 UTC, kainwen commented on src/backend/optimizer/util/pathnode.c
> +	if (!strcmp(proname, "gp_tablespace_segment_location"))
We cannot compare via text name. In theory, user can define a UDF has the same name but in different schema.

So please use funcid, this is the identifier.

2022-03-23 02:39 UTC, kainwen commented on src/backend/optimizer/util/pathnode.c
> +		// Gp_role == GP_ROLE_EXECUTE
Comment style and extra blank line.

2022-03-23 02:39 UTC, kainwen commented on src/backend/optimizer/util/pathnode.c
> +				if (GpIdentity.segindex == MASTER_CONTENT_ID &&
`create_function_scan` is called during planning stage. Most of the case, `GpIdentity.segindex == MASTER_CONTENT_ID` will be true. Here we are creating plan not running a function. Thsi is not correct place to add the logic.

2022-03-23 03:13 UTC, interma commented
thanks Zhenghua, I will fix them later.

2022-03-29 12:00 UTC, kainwen approved these changes

2022-03-30 01:04 UTC, interma commented
thanks zhenghua for review!

2022-03-30 02:26 UTC, interma commented
refactor the code: integrated Junfeng's https://github.com/greenplum-db/gpdb/pull/11178 logic in my PR.

2022-04-12 11:01 UTC, kainwen commented on src/backend/executor/execQual.c
> +	char exec_location = func_exec_location(foid);
These two lines `1487 & 1488` seem redundant to me.

2022-04-12 11:02 UTC, kainwen commented on src/backend/optimizer/util/pathnode.c
> +	{
This seems not related to the issue, it is better not to change.

2022-04-12 11:02 UTC, kainwen commented on src/backend/executor/execQual.c
> +static bool
Maybe one word on why some are checked via OID and some are by text.

2022-04-12 11:03 UTC, kainwen reviewed
@interma 
I have added some more minor comments. Please address them before merging. Thanks.

2022-04-12 11:12 UTC, interma commented
got it, will fix them later, thanks zhenghua!

2022-04-13 01:08 UTC, interma commented on src/backend/optimizer/util/pathnode.c
> +	{
done

2022-04-13 01:08 UTC, interma commented on src/backend/executor/execQual.c
> +static bool
done

2022-04-13 01:21 UTC, interma commented on src/backend/executor/execQual.c
> +	char exec_location = func_exec_location(foid);
My thoughts:
so far, these functions (need to check by name) are not too much, and all of them are`PROEXECLOCATION_ALL_SEGMENTS`, using the if condition first can boost a little performance (avoid every function to go to strcmp later).

2022-04-14 01:01 UTC, kainwen commented on src/backend/executor/execQual.c
> +	char exec_location = func_exec_location(foid);
> My thoughts: so far, these functions (need to check by name) are not too many, and all of them are`PROEXECLOCATION_ALL_SEGMENTS`, using the if condition first can boost a little performance (avoid every function to go to strcmp later).
> 
> I will add some comments in code.

But the logic is a bit confusing.  We want to disallow a function's call by name, but here we'd try to fetch another field to filter out first.

Also `func_exec_location` will search the syscache and I do not think the perf is changed.

2022-04-14 07:50 UTC, merged

2022-04-14 07:51 UTC, interma commented
merged, thanks zhenghua for review it!