gprecoverseg to continue recovery in case failed host cannot be reached
greenplum-db/gpdb pull request #13323
Opened 2022-03-28 18:00 UTC by piyushc01

When gprecoverseg -I ran to recover segments to a new target and failed host cannot be reached previously we used to abort the recovery. With this current change, recovery will continue even if failed host is un-reachable but live peer can be reached and failover host is also in reach. 
Also added behave tests to cover the scenario of failed host, and partial recovery. 

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2022-03-30 02:03 UTC, kaknikhil commented on gpMgmt/bin/gppylib/programs/clsRecoverSegment_triples.py
> +        return self._convert_requests_to_triplets(requests, self.paralleldegree)
Instead of passing around the paralleldegree variable, we can instead set `self.paralleldegree = paralleldegree` in the `RecoveryTriplets` class and then reference it directly  as `self.paralleldegree` in the `_convert_requests_to_triplets` function

2022-04-04 17:48 UTC, piyushc01 commented on gpMgmt/bin/gppylib/programs/clsRecoverSegment_triples.py
> +    def _convert_requests_to_triplets(self, requests: List[RecoveryTripletRequest], paralleldegree) -> List[RecoveryTriplet]:
As per updated changes, unit test is not applicable anymore.
Let me know if you think otherwise.

2022-04-05 01:55 UTC, kaknikhil commented on gpMgmt/bin/gppylib/programs/clsRecoverSegment_triples.py
> +    def _convert_requests_to_triplets(self, requests: List[RecoveryTripletRequest], paralleldegree) -> List[RecoveryTriplet]:
Even after the update, there are changes to the `_convert_requests_to_triplets`  function which would need to tested through unit tests, right ?

2022-04-08 02:31 UTC, kaknikhil requested changes

2022-04-08 02:31 UTC, kaknikhil commented on gpMgmt/bin/gppylib/programs/clsRecoverSegment_triples.py
> +                failover.unreachable = False if (failover.getSegmentHostName() not in unreachable_hosts) else failover.unreachable
Consider the case where a failover host in unreachable but failed host is reachable. This code will set failover.unreachable to False which is incorrect. This is a good example of how unit tests can be helpful in finding these sneaky bugs.

I think we don't even need to worry about checking for failover.unreachable. We had to do that before because we weren't checking if the failover host was reachable or not. So we kind of copied over the failed segment's unreachable property(since failover is a clone of the failed seg)

Can't we just do `failover.unreachable = failover.getSegmentHostName() in unreachable_hosts`

We should add a unit test for this as well as a behave tests where the failed host is reachable but the failover host is unreachable and then assert that the recovery doesn't go through and the correct error message is printed

2022-04-19 18:30 UTC, piyushc01 commented on gpMgmt/bin/gppylib/programs/clsRecoverSegment_triples.py
> +                failover.unreachable = False if (failover.getSegmentHostName() not in unreachable_hosts) else failover.unreachable
Updated the code based on your suggestions.

2022-04-29 23:09 UTC, divyeshddv approved these changes
PR changes and tests LGTM!
Make sure pipeline is green and we squash the commits into fewer commits before merging

2022-05-06 19:24 UTC, kaknikhil reviewed
Left a couple of comments. Also can you look at this comment as well

https://github.com/greenplum-db/gpdb/pull/13323#discussion_r838049142

2022-05-06 19:24 UTC, kaknikhil commented on gpMgmt/bin/gppylib/programs/clsRecoverSegment_triples.py
> +        unreachable_hosts = self._get_unreachable_failover_hosts(requests, self.paralleldegree)
I would suggest changing all references of `unreachable_hosts` to `unreachable_failover_hosts`, even in the `_get_unreachable_failover_hosts` function

2022-05-06 19:24 UTC, kaknikhil commented on gpMgmt/test/behave/mgmt_utils/gprecoverseg_newhost.feature
> +    Scenario: "gprecoverseg -p newhost" failure correctly for start failures
Can you check if we have any tests where the failover host in unreachable ? If not, we might have to add those tests as well since we changed that code as well in this PR

2022-05-18 12:29 UTC, piyushc01 commented on gpMgmt/bin/gppylib/programs/clsRecoverSegment_triples.py
> +        return self._convert_requests_to_triplets(requests, self.paralleldegree)
Already taken case :)

2022-05-18 20:35 UTC, kaknikhil commented on gpMgmt/bin/gppylib/programs/clsRecoverSegment_triples.py
> +        return self._convert_requests_to_triplets(requests, self.paralleldegree)
@piyushc01 I think this one is still pending since we don't really need to keep passing the paralleldegree variable around. We can set `self.parallel_degree = parallel_degree `in the RecoveryTriplets class and then reference it directly as `self.parallel_degree` in the _convert_requests_to_triplets function

2022-05-23 18:56 UTC, piyushc01 commented on gpMgmt/bin/gppylib/programs/clsRecoverSegment_triples.py
> +        return self._convert_requests_to_triplets(requests, self.paralleldegree)
Updated the code with latest changes.

2022-06-16 10:18 UTC, piyushc01 commented on gpMgmt/bin/gppylib/programs/clsRecoverSegment_triples.py
> +    def _get_unreachable_failover_hosts(requests, paralleldegree) -> List[str]:
I have updated the code. Initially the  method was static hence was calling function without any object instance. 
Now changed this method to be regular method and hence can access parallel degree from the parent class directly. 
Marking it as resolved.

2022-06-22 10:40 UTC, kaknikhil approved these changes
LGTM. Left a comment about adding a behave test

2022-06-22 10:40 UTC, kaknikhil commented on gpMgmt/bin/gppylib/programs/clsRecoverSegment_triples.py
> +                    # skip the recovery
I think it would be good to add a behave test for the case when the user has requested an in place recovery but the failed host is unreachable.  We should assert that the expected messages are printed and gprecoverseg returns a 0 return code.

2022-06-23 18:51 UTC, merged

2023-08-22 07:41 UTC, Annu149 commented on gpMgmt/bin/gppylib/programs/clsRecoverSegment_triples.py
> +                failover.unreachable = failover.getSegmentHostName() in unreachable_failover_hosts
If failover is unreachable then also we should skip the recovery right? Can't see that part here. Will that be covered in another PR ?