utility guide markdown corrections
greenplum-db/gpdb pull request #13401
Opened 2022-04-18 22:50 UTC by beelia

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2022-04-18 23:04 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/analyzedb.xml
> +       -x &lt;col1>[,&lt;col2>, ...] ] } |
Missing closing > after col2 in these lines.

2022-04-18 23:06 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/analyzedb.xml
> +          <pt><varname>--skip_orca_root_stats</varname></pt>
This shouldn't be formatted as varname.  Make it codeph instead.

2022-04-18 23:15 UTC, beelia commented on gpdb-doc/dita/utility_guide/ref/analyzedb.xml
> +          <pt><varname>--skip_orca_root_stats</varname></pt>
There are many varnames throughout the guide. Replace them all with codeph?

2022-04-18 23:31 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/dropdb.xml
> +<topic id="topic1"><title id="pc137116">dropdb</title><body><p id="client_util_desc">Removes a database.</p><section id="section2"><title>Synopsis</title><codeblock id="client_util_synopsis">dropdb [
connection-option is missing the closing >

2022-04-18 23:47 UTC, beelia commented on gpdb-doc/dita/utility_guide/ref/analyzedb.xml
> +          <pt><varname>--skip_orca_root_stats</varname></pt>
Fixed as advised (a mistake, not a global change).

2022-04-18 23:51 UTC, beelia commented on gpdb-doc/dita/utility_guide/ref/analyzedb.xml
> +       -x &lt;col1>[,&lt;col2>, ...] ] } |
Added missing > to line 15 after col2

2022-04-19 23:41 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/dropuser.xml
> +<topic id="topic1"><title id="pe137116">dropuser</title><body><p id="client_util_desc">Removes a database role.</p><section id="section2"><title>Synopsis</title><codeblock id="client_util_synopsis">d
role_name also needs a closing >

2022-04-19 23:41 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/dropuser.xml
> +<topic id="topic1"><title id="pe137116">dropuser</title><body><p id="client_util_desc">Removes a database role.</p><section id="section2"><title>Synopsis</title><codeblock id="client_util_synopsis">d
role_name also needs a closing >

2022-04-20 00:16 UTC, dyozie requested changes

2022-04-20 00:16 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpmapreduce-yaml.xml
> +<xref href="#topic1/DATABASE" format="dita">DATABASE</xref>: dbname
We'll need to decide an approach for this section - the xrefs will need to be removed from the codeblock. Or maybe we just use the HTML output instead of trying to represent this in DITA.

2022-04-20 00:16 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpmapreduce-yaml.xml
> +<xref href="#topic1/DATABASE" format="dita">DATABASE</xref>: dbname
We'll need to decide an approach for this section - the xrefs will need to be removed from the codeblock. Or maybe we just use the HTML output instead of trying to represent this in DITA.

2022-04-20 00:16 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/reindexdb.xml
> +<topic id="topic1"><title id="pg137116">reindexdb</title><body><p id="client_util_desc">Rebuilds indexes in a database.</p><section id="section2"><title>Synopsis</title><codeblock id="client_util_syn
table is missing a closing >

2022-04-20 00:16 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/reindexdb.xml
> +<topic id="topic1"><title id="pg137116">reindexdb</title><body><p id="client_util_desc">Rebuilds indexes in a database.</p><section id="section2"><title>Synopsis</title><codeblock id="client_util_syn
table is missing a closing >

2022-04-20 00:16 UTC, dyozie commented on gpdb-doc/dita/utility_guide/utility-programs.xml
> +                    <?oxy_custom_start type="oxy_content_highlight" color="140,255,140"?><codeph>$GPHOME/bin</codeph><?oxy_custom_end?>.
Something went wrong here with oxygen - I've never seen this particular element used.

2022-04-20 00:16 UTC, dyozie commented on gpdb-doc/dita/utility_guide/utility-programs.xml
> +                    <?oxy_custom_start type="oxy_content_highlight" color="140,255,140"?><codeph>$GPHOME/bin</codeph><?oxy_custom_end?>.
Something went wrong here with oxygen - I've never seen this particular element used.

2022-04-21 19:00 UTC, beelia commented on gpdb-doc/dita/utility_guide/ref/dropuser.xml
> +<topic id="topic1"><title id="pe137116">dropuser</title><body><p id="client_util_desc">Removes a database role.</p><section id="section2"><title>Synopsis</title><codeblock id="client_util_synopsis">d
closing > added

2022-04-21 19:23 UTC, beelia commented on gpdb-doc/dita/utility_guide/ref/dropdb.xml
> +<topic id="topic1"><title id="pc137116">dropdb</title><body><p id="client_util_desc">Removes a database.</p><section id="section2"><title>Synopsis</title><codeblock id="client_util_synopsis">dropdb [
added closing >

2022-04-21 19:27 UTC, beelia commented on gpdb-doc/dita/utility_guide/ref/dropuser.xml
> +<topic id="topic1"><title id="pe137116">dropuser</title><body><p id="client_util_desc">Removes a database role.</p><section id="section2"><title>Synopsis</title><codeblock id="client_util_synopsis">d
duplicate?

2022-04-21 19:29 UTC, beelia commented on gpdb-doc/dita/utility_guide/ref/gpbackup_manager.xml
> +      <codeblock>delete-backup &lt;timestamp [--plugin-config &lt;config-file>]
added closing >

2022-04-21 19:32 UTC, beelia commented on gpdb-doc/dita/utility_guide/ref/gpcheckcat.xml
> +     -s &lt;test_name | 'test_name1, test_name2 [, ...]'>
Please take a second look at the end of the line. If I add > after test_name, there will be two >'s on this line.

2022-04-21 19:34 UTC, beelia commented on gpdb-doc/dita/utility_guide/ref/gpcheckcat.xml
> +     -s &lt;test_name | 'test_name1, test_name2 [, ...]'>
Same extra ">"? Duplicate?

2022-04-21 19:36 UTC, beelia commented on gpdb-doc/dita/utility_guide/ref/gpcheckcat.xml
> +      displays a summary list of tables with missing attributes in the format <codeph>&lt;database>.
Unclear - <database> has a closing tag ...?

2022-04-21 19:36 UTC, beelia commented on gpdb-doc/dita/utility_guide/ref/gpcheckcat.xml
> +      displays a summary list of tables with missing attributes in the format <codeph>&lt;database>.
duplicate?

2022-04-21 19:38 UTC, beelia commented on gpdb-doc/dita/utility_guide/ref/gpcheckperf.xml
> +                        <codeblock>[&lt;username@>]&lt;hostname>[:&lt;ssh_port>]</codeblock>
Done.

2022-04-21 19:41 UTC, beelia commented on gpdb-doc/dita/utility_guide/ref/gpinitsystem.xml
> +                        information:<codeblock>&lt;hostname>~&lt;address>~&lt;port>~&lt;data_directory>/&lt;seg_prefix&lt;segment_id>>~&lt;dbid>~&lt;content_id></codeblock>or
redundant > removed.

2022-04-21 19:42 UTC, beelia commented on gpdb-doc/dita/utility_guide/ref/gpmapreduce-yaml.xml
> +<xref href="#topic1/DATABASE" format="dita">DATABASE</xref>: dbname
Removing the xref is a content decision I am not qualified to make. Your decision?

2022-04-21 19:45 UTC, beelia commented on gpdb-doc/dita/utility_guide/ref/gpmapreduce-yaml.xml
> +<xref href="#topic1/DATABASE" format="dita">DATABASE</xref>: dbname
I put this one on my list because I realized I didn't know how to deal with it. 
Take the xrefs out? Again, a content decision.

2022-04-21 19:47 UTC, beelia commented on gpdb-doc/dita/utility_guide/ref/reindexdb.xml
> +<topic id="topic1"><title id="pg137116">reindexdb</title><body><p id="client_util_desc">Rebuilds indexes in a database.</p><section id="section2"><title>Synopsis</title><codeblock id="client_util_syn
missing > added

2022-04-21 20:14 UTC, beelia commented on gpdb-doc/dita/utility_guide/utility-programs.xml
> +                    <?oxy_custom_start type="oxy_content_highlight" color="140,255,140"?><codeph>$GPHOME/bin</codeph><?oxy_custom_end?>.
This is not in the Oxygen interface --
![Oxygen_utility_programs](https://user-images.githubusercontent.com/6751718/164544466-65739612-3bd1-4212-82f7-b2dc866724d0.png)

but it is visible in the VSCode file -- 
![VSCode_utility_programs](https://user-images.githubusercontent.com/6751718/164544517-3858a226-56c1-4eb4-9a26-fb79777f38bc.png)

Screenshots made with Share, provided by Oasis. Saved to my desktop, but I'm not sure you can see them.

The odd content clearly has nothing to do with the file, so I just deleted the following and saved the file in VSCode: 
<?oxy_custom_start type="oxy_content_highlight" color="140,255,140"?>

2022-04-21 21:02 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpcheckcat.xml
> +      displays a summary list of tables with missing attributes in the format <codeph>&lt;database>.
You can ignore this - I thought the codeph wasn't closed, but see now that it is closed later on the next line.

2022-04-21 21:02 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpmapreduce-yaml.xml
> +<xref href="#topic1/DATABASE" format="dita">DATABASE</xref>: dbname
Let's leave them in for now, and I can try to address this after markdown is generated.

2022-04-21 21:02 UTC, dyozie commented on gpdb-doc/dita/utility_guide/ref/gpmapreduce.xml
> +     [-k &lt;name=value> | --key &lt;name=valu>e]
closing > is misplaced here.  Should be value> instead of valu>e

2022-04-21 21:09 UTC, beelia commented on gpdb-doc/dita/utility_guide/ref/dropuser.xml
> +<topic id="topic1"><title id="pe137116">dropuser</title><body><p id="client_util_desc">Removes a database role.</p><section id="section2"><title>Synopsis</title><codeblock id="client_util_synopsis">d
Resolved, it is a duplicate

2022-04-21 21:19 UTC, beelia commented on gpdb-doc/dita/utility_guide/ref/gpcheckperf.xml
> +                        <codeblock>[&lt;username@>]&lt;hostname>[:&lt;ssh_port>]</codeblock>
Resolved.

2022-04-21 21:20 UTC, beelia commented on gpdb-doc/dita/utility_guide/ref/gpcheckperf.xml
> +                        <codeblock>[&lt;username@>]&lt;hostname>[:&lt;ssh_port>]</codeblock>
This is an oddity only because the "Resolve conversation" button isn't working. The issue IS resolved.

2022-04-21 21:21 UTC, beelia commented on gpdb-doc/dita/utility_guide/ref/gpmapreduce-yaml.xml
> +<xref href="#topic1/DATABASE" format="dita">DATABASE</xref>: dbname
Decision is to use HTML output.

2022-04-21 21:23 UTC, beelia commented on gpdb-doc/dita/utility_guide/ref/gpmapreduce.xml
> +     [-k &lt;name=value> | --key &lt;name=valu>e]
Fixed.

2022-04-21 21:24 UTC, beelia commented on gpdb-doc/dita/utility_guide/ref/gpbackup_manager.xml
> +      <codeblock>delete-backup &lt;timestamp [--plugin-config &lt;config-file>]
Fixed.

2022-04-21 21:24 UTC, beelia commented on gpdb-doc/dita/utility_guide/utility-programs.xml
> +                    <?oxy_custom_start type="oxy_content_highlight" color="140,255,140"?><codeph>$GPHOME/bin</codeph><?oxy_custom_end?>.
Fixed.

2022-04-21 21:26 UTC, beelia commented on gpdb-doc/dita/utility_guide/ref/gpcheckcat.xml
> +      displays a summary list of tables with missing attributes in the format <codeph>&lt;database>.
Yes, duplicate.

2022-04-25 17:50 UTC, dyozie approved these changes

2022-04-25 17:50 UTC, merged