Fix epoll() fd leak in waiteventset related PR
greenplum-db/gpdb pull request #13513
Opened 2022-05-18 00:56 UTC by interma

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2022-05-18 02:06 UTC, interma commented on src/backend/cdb/dispatcher/cdbdisp_async.c
> +	PG_TRY();
For reviewer:
The diff format is not read-friendly, it looks changed too much code.
But it is not complex, most of what I did is: add `PG_TRY()` to make sure free waiteventset, it follows the pattern:
```
waitset = CreateWaitEventSet();
PG_TRY();
{
    // original logic
}
PG_CATCH();
{
    FreeWaitEventSet(waitset);
    PG_RE_THROW();
}
PG_END_TRY();
```

2022-05-18 03:01 UTC, interma commented on src/backend/cdb/dispatcher/cdbgang_async.c
> +			{
Leaked many fd here before: it breaks the loop when all gang is done, so leaks one fd in each query...

My stupid mistake.

2022-05-18 07:38 UTC, interma commented on src/backend/cdb/dispatcher/cdbdisp_async.c
> +			PG_END_TRY();
A nested pg_try in another pg_try, may have some risks?

2022-05-20 00:48 UTC, soumyadeep2007 reviewed
Please open separate commits for each function for enhanced reviewability. I have included formats that will simplify the implementation and fix the leaks. Look for my comments at the top of each function.

2022-05-20 00:48 UTC, soumyadeep2007 commented on src/backend/cdb/dispatcher/cdbdisp_async.c
>  	WaitEvent 		*revents = palloc(sizeof(WaitEvent) * dispatchCount);
Please follow the following format (pseudocode with comments, please remove
comments after incorporating):
```
waitset = CreateWaitEventSet(..);
char *errormsg;
for (i = 0; i < dispatchCount; i++)
{
     ret = pqFlushNonBlocking(conn)
     if (ret < 0)
     {
          // copy message from PQerrorMessage in errormsg var
          break;
      }
}
pfree(revents);
pfree(added);
FreeWaitEventSet(waitset);
if (errormsg && errormsg[0] != '\0')
   elog(ERROR, "cdbdisp_waitDispatchFinish_async failed with: %s", errormsg);
```

Note: 
```
if (pollRet < 0)
			elog(ERROR, "Poll failed during dispatch");
```
is unnecessary as `WaitEventSetWait` can't return a negative value.

Slightly unrelated:
Also please check if SOCK_ERRNO == EINTR || SOCK_ERRNO == EAGAIN is necessary in
a WaitEvent API context.

2022-05-20 00:48 UTC, soumyadeep2007 commented on src/backend/cdb/dispatcher/cdbgang_async.c
Please follow the following format (pseudocode with comments, please remove
comments after incorporating):

```
// Declare in outside scope to allow for easy cleanup
WaitEventSet *gang_waitset = NULL;

PG_TRY();
{
     ...
     for (;;)
     {
          gang_waitset = CreateWaitEventSet(CurrentMemoryContext, size);

          ...

          for (i = 0; i < size; i++)
          {
               ...
          }

          ...

          if (allStatusDone)
          {
               FreeWaitEventSet(gang_waitset);
               break;
          }

          ...

          int nready = WaitEventSetWait(gang_waitset, poll_timeout, revents, size, WAIT_EVENT_GANG_ASSIGN);
          Assert(nready >= 0);
          FreeWaitEventSet(gang_waitset);
          gang_waitset = NULL; // necessary in case we ERROR out in the getPollTimeout block at the top
     }
}
PG_CATCH();
{
     if (gang_waitset)
          FreeWaitEventSet(gang_waitset);

     PG_RE_THROW();

}
PG_END_TRY();

pfree(pollingStatus);
pfree(connStatusDone);
pfree(revents);

...

2022-05-20 00:48 UTC, soumyadeep2007 commented on src/backend/cdb/motion/ic_udpifc.c
>  	/* init WaitEventSet */
Please follow the following format (pseudocode with comments, please remove
comments after incorporating):

```
WaitEventSet        *waitset = NULL;
...
waitset = CreateWaitEventSet(CurrentMemoryContext, nevent);
rEvents = palloc(nevent * sizeof(WaitEvent)); /* returned events */
AddWaitEventToSet(waitset, WL_LATCH_SET, PGINVALID_SOCKET, &ic_control_info.latch, NULL);
AddWaitEventToSet(waitset, WL_POSTMASTER_DEATH, PGINVALID_SOCKET, NULL, NULL);

for (int i = 0; i < nFds; i++)
{
     AddWaitEventToSet(waitset, WL_SOCKET_READABLE, waitFds[i], NULL, NULL);
}

...

PG_TRY()
{
     // will contain entirety of for(;;)
     // responsibility to clear the waitset, revents, waitFds etc 
     // will entirely be on the caller of the function
     receiveChunksUDPIFCLoop(..., waitset, revents, ); // or a better name? The *Loop convention is used extensively in PG.
}
PG_CATCH()
{
     FreeWaitEventSet(waitset);
     // no need to check if revents is NULL as we palloced it above.
     pfree(rEvents);
     if (waitFds != NULL)
          pfree(waitFds);

     PG_RE_THROW();
}
PG_END_TRY();

...

FreeWaitEventSet(waitset);
// no need to check if revents is NULL as we palloced it above.
pfree(rEvents);
if (waitFds != NULL)
     pfree(waitFds);
```

2022-05-20 03:28 UTC, interma commented
Thanks Deep!
Very detailed review advice, I am going to modify code and verify it in dev pipeline.

2022-05-20 08:21 UTC, interma commented on src/backend/cdb/dispatcher/cdbdisp_async.c
>  	WaitEvent 		*revents = palloc(sizeof(WaitEvent) * dispatchCount);
Looks no `PG_TRY` in this function, but I think should use `PG_TRY` here: 
There are some `elog(ERROR,...)` in AddWaitEventToSet(). Even if not, other committer may add a throwing-exception function in future, but doesn't notice using `PG_TRY` to wrap it.

About "SOCK_ERRNO == EINTR || SOCK_ERRNO == EAGAIN":
they are handled in `WaitEventSetWait`, so I removed them from the condition.

2022-05-20 08:58 UTC, interma commented on src/backend/cdb/motion/ic_udpifc.c
>  	/* init WaitEventSet */
Same as [cdbdisp_async.c]: 
`AddWaitEventToSet()` may ERROR, so I keep it in the `PG_TRY`.

Did other change as you recommend.

2022-05-20 11:25 UTC, interma commented
@soumyadeep2007
Fixed your comment and pipeline is passed.
Please review again when you have time.
Thanks.

2022-05-20 11:27 UTC, interma commented on src/backend/cdb/dispatcher/cdbdisp_async.c
> +			PG_END_TRY();
looks have to call `FlushErrorState()` in `PG_CATCH`.

2022-05-20 22:56 UTC, soumyadeep2007 reviewed
Thank you for addressing the feedback, the implementation is looking much better. I have more feedback to improve it further. Please read my comment on cdbdisp_waitDispatchFinish_async first. It will help you address the rest.

Also. to reiterate my request, please see if you can separate the changes into 4 commits, one for each function. It will greatly improve reviewability and help posterity.

2022-05-20 22:56 UTC, soumyadeep2007 commented on src/backend/cdb/motion/ic_udpifc.c
> +					int16 motNodeID, int16 *srcRoute, MotionConn *conn,
* `motNodeID` is a dead argument - it is not used in this function. Please remove.

2022-05-20 22:56 UTC, soumyadeep2007 commented on src/backend/cdb/dispatcher/cdbdisp_async.c
> +			PG_END_TRY();
@adam8157 since you might be familiar with this code block, why do we wrap `CHECK_FOR_INTERRUPTS` in a `PG_TRY/PG_CATCH` here? Also what is the real purpose of `cancelRequested`> I didn't find similar code anywhere else. Are we trying to detect if a query cancellation is pending? Why not use `QueryCancelPending` instead?

2022-05-20 22:56 UTC, soumyadeep2007 commented on src/backend/cdb/dispatcher/cdbdisp_async.c
>  	WaitEvent 		*revents = palloc(sizeof(WaitEvent) * db_count);
I completely missed this function during my previous review.

Pattern to follow here to reduce diff and keep things clean:

```c
WaitEventSet *waitset = CreateWaitEventSet(CurrentMemoryContext, db_count);

PG_TRY()
{
     // this will contain the while_true, with revents and added allocation and freeing
     checkDispatchResultLoop(.., waitset);
}
PG_CATCH()
{
     FreeWaitEventSet(waitset);
}
```

2022-05-21 08:17 UTC, interma commented on src/backend/cdb/dispatcher/cdbdisp_async.c
>  	WaitEvent 		*revents = palloc(sizeof(WaitEvent) * dispatchCount);
Thank you very much, Deep.
They are very detailed and helpful, I am going to fix them.

2022-05-23 03:19 UTC, interma commented on src/backend/cdb/dispatcher/cdbdisp_async.c
> +			PG_END_TRY();
I tested it manual by gdb here: elog an ERROR after `CHECK_FOR_INTERRUPTS()`, looks no fatal/other unexpected error happened.

2022-05-23 03:26 UTC, interma commented
@soumyadeep2007 Fixed your comment and pipeline is passed, pls take a look again.

Btw: I don't find a way to separate changes in each file's commit, except open a new PR.. So I still put them all in one commit. I will follow the advice in my future PRs. :-)

Thanks!

2022-05-23 09:01 UTC, adam8157 commented on src/backend/cdb/dispatcher/cdbdisp_async.c
> +			PG_END_TRY();
For reference https://github.com/greenplum-db/gpdb/issues/13048 and https://github.com/greenplum-db/gpdb/commit/ee255b55398818c6e6401668b540d2f45ff4c719

@interma Please check, and add some comments for it

2022-05-23 10:22 UTC, interma commented on src/backend/cdb/dispatcher/cdbdisp_async.c
> +			PG_END_TRY();
thanks Adam, looks they are reasonable and no need to change.

2022-05-23 12:59 UTC, kainwen commented on src/backend/cdb/dispatcher/cdbdisp_async.c
> +			*cancelRequested = true;
CATCH clause neither rethrow nor clear errstack. This is an obvious bug that might lead to errstack overflow.

2022-05-23 13:01 UTC, kainwen commented on src/backend/cdb/dispatcher/cdbdisp_async.c
> +		*/
Why change the format here?

2022-05-23 13:05 UTC, kainwen commented on src/backend/cdb/dispatcher/cdbgang_async.c
> +		if (gang_waitset != NULL)
`gang_waitset` is not defined as `volatile` so it might be pushed into register and when entering CATCH clause, only stack is roll-ed back, register content cannot be guarantted.

2022-05-24 01:16 UTC, interma commented on src/backend/cdb/dispatcher/cdbdisp_async.c
> +			*cancelRequested = true;
I supposed to call `FlushErrorState()` here. But it caused cannot re-throw in:
https://github.com/greenplum-db/gpdb/blob/47823ae056630329b40273b94b988ded2e02d61c/src/backend/cdb/dispatcher/cdbdisp_async.c#L663-L665

About "errstack overflow", I test it manually and no overflow happened, can we consider it's safe?
https://github.com/greenplum-db/gpdb/pull/13513#discussion_r878994841

2022-05-24 01:35 UTC, kainwen commented on src/backend/cdb/dispatcher/cdbdisp_async.c
> +			*cancelRequested = true;
NO. When this code path is reached for more than 10 times ti will hit the overflow FATAL.

2022-05-24 01:56 UTC, interma commented on src/backend/cdb/dispatcher/cdbdisp_async.c
> +			*cancelRequested = true;
got it, thanks Zhenghua. I am going to check code and find a nice way to handle it.

2022-05-25 01:27 UTC, adam8157 commented on src/backend/cdb/dispatcher/cdbdisp_async.c
> +			PG_END_TRY();
@Aegeaner

2022-05-25 01:39 UTC, interma commented on src/backend/cdb/dispatcher/cdbdisp_async.c
> +			PG_END_TRY();
I give a new pattern to handle it:
```c
		MemoryContext oldcontext = CurrentMemoryContext;
		PG_TRY();
		{
			CHECK_FOR_INTERRUPTS();
		}
		PG_CATCH();
		{
			/* storage error in edata for caller to check it */
			MemoryContextSwitchTo(oldcontext);
			*edata = CopyErrorData();  // <= handle edata later
			FlushErrorState();
		}
		PG_END_TRY();
```

pls see the latest code of this PR.

2022-05-25 03:47 UTC, Aegeaner requested changes
Noticed an `ereport(FATAL)` will not be caught by `PG_CATCH();`, control will exit straight through `proc_exit()`, these fds may still got leak.  I suppose to encapsulate the `WaitEventSet` and `fds` cleanup logic into a function, then call it with the `PG_ENSURE_ERROR_CLEANUP()` macro instead, to ensure that this works not only for `ereport(ERROR)`, but even for `elog(FATAL)` scenarios, and by this way we will not mess up with the error stack.

https://github.com/greenplum-db/gpdb/blob/19cd1cf4b68faff2e29bc2fa884c480e4644cdb4/src/include/storage/ipc.h#L47

To add: During the `proc_exit()`, all file descriptors will got closed according POSIX standard, so it will not cause a leak.

2022-05-25 08:40 UTC, Aegeaner commented on src/backend/cdb/dispatcher/cdbdisp_async.c
> +			PG_END_TRY();
@adam8157 @interma The code block here is for fixing issue #13048, we should not call `PG_THROW()` here immediately, neither to call `FlushErrorState();` here. The only right way is to call`PG_RE_THROW()` at the end of this function to handle the `cancelRequested` flag.

2022-05-27 01:04 UTC, soumyadeep2007 reviewed
Looking much better, great work! I still have a few cleanup asks though, please take a look. Oh and there is still a lot of whitespace diff in the PR - please remove. 

Unfortunately, we have to solve the CFI TRY-CATCH business in checkDispatchResult before we can merge the PR.

2022-05-27 01:04 UTC, soumyadeep2007 commented on src/backend/cdb/motion/ic_udpifc.c
> +	rEvents = palloc(nevent * sizeof(WaitEvent)); /* returned events */
Use the waitset's size (`waitset->nevents`) to construct the revents array everywhere, will be more canonical and simple to understand.
This will eliminate the need to pass in `nevent`

2022-05-27 01:05 UTC, soumyadeep2007 commented on src/backend/cdb/motion/ic_udpifc.c
> +receiveChunksUDPIFCLoop(ChunkTransportState *pTransportStates, ChunkTransportStateEntry *pEntry,
The prototype should be declared at the top of the file with the other prototypes.

2022-05-27 02:51 UTC, Aegeaner commented on src/backend/cdb/dispatcher/cdbdisp_async.c
>  		}
I agree with Plan b). We could solve issue #13048 in another PR to propagate the cancel request to all QEs other than the current way: setting `pParms->waitMode = DISPATCH_WAIT_CANCEL;`.

2022-05-27 03:22 UTC, Aegeaner commented on src/backend/cdb/dispatcher/cdbdisp_async.c
>  		}
After a look at `cdbdisp_cleanupDispatcherHandle` mentioned above , I think `cleanup_dispatcher_handle` will be called during either `AtAbort_DispatcherState` or `AtSubAbort_DispatcherState`, so the tricky specialized handling for the `cancelRequested` before may not be necessary.

https://github.com/greenplum-db/gpdb/blob/683d5a4c724f4eee1dc98fded1e0b1e7b37371ef/src/backend/cdb/dispatcher/cdbdisp.c#L530

2022-05-27 03:35 UTC, Aegeaner commented on src/backend/cdb/dispatcher/cdbdisp_async.c
>  		}
There is also a `CdbDispatchHandleError()` call in `mppExecutorCleanup()`, which is inside the `PG_CATCH` inside `PortalRun()`.

https://github.com/greenplum-db/gpdb/blob/b9d3ce9a9f0c5bcf209d3eb44d017e155306b58d/src/backend/executor/execUtils.c#L1736

2022-05-27 10:32 UTC, interma commented on src/backend/cdb/dispatcher/cdbdisp_async.c
>  		}
Thanks @soumyadeep2007 
We discussed today, will **apply the option b**: open another PR to remove PG_TRY and do fix + verify (parallel cursor issue). @Aegeaner 
After the new PR has been merged, I will rebase and merge this PR. 

I am going to fix your other comments first.

2022-05-27 10:34 UTC, interma commented
paste the latest news here for notice
> Thanks @soumyadeep2007 We discussed today, will **apply the option b**: open another PR to remove PG_TRY and do fix + verify (parallel cursor issue). @Aegeaner After the new PR has been merged, I will rebase and merge this PR.
> 
> I am going to fix your other comments first.

https://github.com/greenplum-db/gpdb/pull/13513#discussion_r883190234

2022-05-30 02:34 UTC, interma commented on src/backend/cdb/motion/ic_udpifc.c
> +	rEvents = palloc(nevent * sizeof(WaitEvent)); /* returned events */
Thanks Deep, but the waitset's implement is hidden in c file, only get the structure type in h file:
https://github.com/greenplum-db/gpdb/blob/f64280c7e5001668def798e6d746840d74f70a9b/src/include/storage/latch.h#L152-L154 

So cannot using its `nevents` field.

2022-05-30 11:21 UTC, interma commented
@soumyadeep2007 
Guojian's master is merged: https://github.com/greenplum-db/gpdb/commit/93955a93da8131bd903b1042aeed80e37dbf4a76

I have been fixed and rebased my PR, please take a look when you have time, thanks!

2022-05-31 04:12 UTC, soumyadeep2007 reviewed
LGTM! There are still a few whitespace diffs, a typo and a stray declaration not following coding guidelines, please remove before merging.

Suggestion for the commit message (please fill in the relevant 7X commit SHAs):

```
Commit message title: Fix various WaitEventSet fd leaks

Commits <>, <> introduced WaitEventSets in place of poll() in various
GPDB specific mechanisms.

WaitEventSets need to be freed with FreeWaitEventSet(), which is
necessary to close() the associated fd. This commit hardens the
following functions to ensure the waitsets are cleaned up, even in the
face of an ERROR:

* cdbdisp_waitDispatchFinish_async()
* checkDispatchResult()
* receiveChunksUDPIFC()
* cdbgang_createGang_async()

To do so, we have relied on PG_TRY/CATCH. This is unlike upstream code,
where in many cases, the waitset involved is tied to the lifecycle of
the backend, rendering explicit cleanup unnecessary (fds would be closed
during process exit anyway). One such example is FeBeWaitSet. Our 
waitsets aren't, so we have to walk the extra mile.
```

2022-05-31 09:17 UTC, interma commented
Yes, thanks Deep for your detailed comment.
I am going to fix them and use 'squash+merge' to give a good comment message.

2022-06-01 01:17 UTC, merged

2022-06-01 01:18 UTC, interma commented
Merged, thanks Deep for taking a long time to help me to improve it!