gpstate -e to check gprecoverseg process before displaying recovery progress
greenplum-db/gpdb pull request #13606
Opened 2022-06-03 16:59 UTC by ravoorsh

When gprecoverseg is running, gpstate -e command displays status of the recovered segments. if the user kills the gprecoverseg process then gpstate -e continues to report the status of the old gprecoverseg.

As a code fix, previously we added a check to see if ~/workspace/gpdb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1/gprecoverseg.lock exists before reporting the gprecoverseg progress.
This fix has a limitation as in the user needs to manually delete the lock file, otherwise gpstate -e will continue to report the progress of gprecoverseg.
To avoid this, now we are also checking if gprecoverseg process is running and gpstate -e reports the progress only if this check succeeds.

Some of the behave test cases had to be removed/modified to accomadate this code change.
Previosuly some of the gpstate -e test cases used to create a sample recovery_progress_file and check the format of the gpstate -e output. This test case worked before as the gprecoverseg process was not running.
Now since there is a gprecoverseg process running which updates the recovery_progress file, this test cases will always fail.
Hence 1 test case is removed and 2 are modified.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2022-06-03 16:59 UTC, ravoorsh commented
Pipeline is mostly green 
https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-ravoos_checkrecoverseg_process

Only one job is failing and looks like network, timing issue. I have restarted the job again and will update progress.

2022-06-06 05:44 UTC, pobbatihari commented on gpMgmt/test/behave/mgmt_utils/gpstate.feature
> +        Then the user reset the walsender on the primary on content 0
Looks we are going to miss the format check of gpstate -e output, Could it possible to check the format for the content which is suspended?

2022-06-06 10:51 UTC, ravoorsh commented on gpMgmt/test/behave/mgmt_utils/gpstate.feature
> +        Then the user reset the walsender on the primary on content 0
I thought about this..but should we check only the format? The previous test case we were adding sample recovery file and comparing full/incremental recovery and port data..Not sure we will add value by just checking the headers..As discussed I will check the the recovery_progress_file output for suspended db and see if we can add a case for this

2022-06-08 22:06 UTC, ashwinstar commented on gpMgmt/bin/gppylib/programs/clsSystemState.py
> +        is_running = subprocess.call(["pgrep", "-f", process], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
just checking for process is running, we also need to make sure its `gprecoverseg` process or not. As same process id can be assigned to some other process and that's fine.

2022-06-13 04:54 UTC, shrakesh commented on gpMgmt/test/behave/mgmt_utils/steps/gpstate_utils.py
> +        fp.write("incremental:6: 1/1371875 kB (1%)")
add new line at the end of file.

2022-06-13 05:44 UTC, shrakesh approved these changes
approving with comment to add new line in file gpstate_utils.py.

2022-06-15 00:14 UTC, ashwinstar commented on gpMgmt/bin/gppylib/utils.py
> +    is_running = subprocess.call(["pgrep", "-f", process], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
Current code is yield very incorrect behavior. For example I just had one process `emacs gprecoverseg` and then did `pgrep -f gprecoverseg` with no real gprecoverseg running.

```
$ pgrep -f gprecoverseg
642931


$ ps -ef | grep 642931
ashwin    642931   10288  0 16:29 pts/0    00:00:00 emacs gprecoverseg
```

so if customer has any process with gprecoverseg string in it will convey process is running which is not right. I think we have the PID of the process in the lock file we should use that as first filter followed by checking if that process is `gprecoverseg` process or not.

Plus, the usage of "-f" seems incorrect as we only wish to match against program name and not full command line?

2022-06-27 17:13 UTC, ashwinstar requested changes

2022-06-27 17:13 UTC, ashwinstar commented on gpMgmt/bin/gppylib/programs/clsSystemState.py
> +        if process != 'gprecoverseg':
what's the point of passing the parameter if only `gprecoverseg` string is the expected input?

2022-06-27 17:13 UTC, ashwinstar commented on gpMgmt/bin/gppylib/programs/clsSystemState.py
> +        cmd = Command(name='pgrep -f for %s' % process,
this can return multiple lines of output based on how the pattern is matched with the existing processes like if I do on my system for firefox

```
pgrep -f firefox
9771
9844
9901
9966
38753
45587
45683
45736
45739
45793
45832
47373
49220
51670
51737
51760
51803
52846
64544
64579
64652
64694
64765
78114
78157
78204
78245
78299
151644
151687
151770
```
I get these many process IDs. So, this way checking will need to have loop to go though all the output lines to check for the PID.

I think reversing the logic is much simpler. Read the PID from the lock file and then check if its running process or not and `gprecoverseg` command or not.

2022-06-30 18:35 UTC, ashwinstar commented on gpMgmt/bin/gppylib/programs/clsSystemState.py
> +        # return true if ps -p succeeds.
can't just blindly return true if the process with that process id is running. Please check if the process is running and is `gprecoverseg` process. Same process ID can be used for some other process in that case don't wish to return true.

2022-07-19 21:41 UTC, ashwinstar commented on gpMgmt/bin/gppylib/programs/clsSystemState.py
> +                      cmdStr="ps -p %d | tail -1 | awk '{print $5}' | awk -F/ '{print $6}'" % int(pid))
possibly can use `ps -p 2108667 -o args=` instead of `ps -p %d | tail -1` for getting the command line with args

2022-08-04 00:48 UTC, ashwinstar commented on gpMgmt/bin/gppylib/programs/clsSystemState.py
> +                      cmdStr="ps aux | awk '$2 == %d  { print $0 }' | awk '{print $12}' | awk -F/ '{print $6}'" % int(pid))
Please provide an example in a comment and explain what $12 and $6 map to.

2022-08-04 11:13 UTC, kaknikhil commented on gpMgmt/bin/gppylib/test/unit/test_unit_gpstate.py
> +    def test_isGprecoversegRunning_pid_file_does_not_exist(self, mock1):
We should add some exception handling unit tests

2022-11-04 18:58 UTC, ashwinstar commented
@ravoorsh seems pending to address comments from Nikhil on this PR for a long time. Please can we can take care of those and bring this long-standing PR to closure?

2022-12-08 17:52 UTC, ravoorsh commented
@ashwinstar Took a look at the review comments, need to revamp the code and add additional behave/unit test cases.
I am closing this PR as I don't have the bandwidth to work on this right now.
I will get this reassigned in the next sprints.

2022-12-08 17:52 UTC, closed without merging