docs - for ip4r contrib module
greenplum-db/gpdb pull request #13623
Opened 2022-06-06 19:44 UTC by lisakowen

docs for https://github.com/greenplum-db/gpdb/pull/13588 (master) and https://github.com/greenplum-db/gpdb/pull/13600 (6X_STABLE)

in this PR:  add topic for new ip4r module.
question:  did i appropriately state the attribution?

will be backported to 6X_STABLE.

doc review site link (behind vpn):  https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/lisa-ip4r/greenplum-database/GUID-ref_guide-modules-ip4r.html

2022-08-03 03:46 UTC, liuxueyang approved these changes

2022-08-23 16:47 UTC, dyozie requested changes

2022-08-23 16:47 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/modules/ip4r.html.md
> +The `ip4r` module was developed by `RhodiumToad`.  Refer the [RhodiumToad/ip4r](https://github.com/RhodiumToad/ip4r) documentation on `github` for detailed information about using the module.
Refer -> Refer to

2022-09-07 01:55 UTC, higuoxing approved these changes
Looks good! Thanks for the doc!

2022-09-07 16:29 UTC, radarwave approved these changes

2022-09-07 16:54 UTC, merged