docs - add disk i/o sched policy recommends for diff storage types
greenplum-db/gpdb pull request #13755
Opened 2022-06-30 21:35 UTC by lisakowen

clarify the disk schedule docs.  in this PR:
- add a storagetype/os/scheduler table
- remove some specifics about setting the scheduler and replace with links to rhel and ubuntu documentation

QUESTION:  i pulled the ubuntu settings from the referenced link.  can someone please confirm/verify these settings?

attached is a screen cap of the html.
![disksched2](https://user-images.githubusercontent.com/19785845/176781970-d9f4d50d-4956-4864-bf74-717a222cdcfe.png)

2022-06-30 23:04 UTC, kmacoskey commented
Absolutely. We just did some research on IO schedulers. @xinzweb can you help review?

2022-07-12 22:28 UTC, xinzweb requested changes
Great information for the schedulers of all different OS platforms.
Just some simplification and minor issues. Thanks.

w/ @mnemesh-pivotal

2022-07-12 22:28 UTC, xinzweb commented on gpdb-doc/markdown/install_guide/prep_os.html.md
> +
Maybe these two lines should be after the line 490, and right before the 491, since it's talking about the `grubby`, and not related to the `ssh`?

2022-07-12 22:28 UTC, xinzweb commented on gpdb-doc/markdown/install_guide/prep_os.html.md
> +    (If you used the `grubby` command to configure the disk scheduler on a RHEL or CentOS 7.x system and it does not update the kernels, see the [Note](#grubby_note) at the end of the section.)
Not sure why do we remove the entire section of configure the grubby? 

The example was very useful in the past to help people understand how to change the scheduler.

Maybe it's ok to remove the RHEL6 instruction (line 391 to 399).

However, the content in 389 and 400 to 414 are still pretty good example on RHEL7. Maybe keep it?

2022-07-12 22:28 UTC, xinzweb commented on gpdb-doc/markdown/install_guide/prep_os.html.md
> +    |       | Ubuntu | `mq-deadline` or `bfq` |
Since we are talking about setting up GP server, then I will not use `bfq` in the mix for the other type is disks (e.g. HDD)

2022-07-12 22:28 UTC, xinzweb commented on gpdb-doc/markdown/install_guide/prep_os.html.md
> +    |       | Ubuntu | `mq-deadline` or `bfq` |
```suggestion
    |       | RHEL 8</br>Ubuntu| `mq-deadline` |
```

2022-07-13 14:39 UTC, lisakowen commented on gpdb-doc/markdown/install_guide/prep_os.html.md
> +
i will move the note.  i initially created this PR when we were publishing to docs.pivotal.io which didn't do a great job of aligning the content with the link, so i located it earlier in the text.  works better now.

2022-07-13 15:05 UTC, lisakowen commented
thank you for reviewing, @xinzweb .  i reinstated the grub info.  attached is a screencap of the new content.
![disksched3](https://user-images.githubusercontent.com/19785845/178766963-016216c7-1244-411b-80f0-5a29faeea0f7.png)

2022-07-14 18:08 UTC, xinzweb approved these changes
Wonderful!

Just one nitpicking thing on the table for the ioschedulers. I am not sure if that's possible to merge the cells vertically for the `Storage Device Type`, e.g. row 2/3 for `SSD` together, and row 4/5 for `other` together.

2022-07-14 20:09 UTC, lisakowen commented
@xinzweb , i converted the table to html which allows me to merge cells vertically.
![disksched4](https://user-images.githubusercontent.com/19785845/179074096-73d7825f-05ef-4818-be4e-f5b068486f81.png)

thanks again for the review.

2022-07-21 22:20 UTC, dyozie approved these changes

2022-07-21 22:20 UTC, merged