DOCS: Document new extension and view to support PITR
greenplum-db/gpdb pull request #13947
Opened 2022-08-16 23:55 UTC by VMWareJennyBeth

2022-08-17 20:59 UTC, jimmyyih approved these changes

2022-08-17 20:59 UTC, jimmyyih commented on gpdb-doc/markdown/ref_guide/system_catalogs/gp_stat_archiver.html.md
> +```
On second thought, would it be weird to link back to the gp_pitr documentation page instead of duplicating the `CREATE EXTENSION gp_pitr;` command?  It would create a circular reference but that should be a good thing I suppose?  Otherwise, this looks good to me.

2022-08-17 21:03 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/ref_guide/system_catalogs/gp_stat_archiver.html.md
> +```
I think ok to reproduce her, as it's just one, tiny line of code. Our docs are sometimes subject to over cross-referencing, making the reader leap around excessively.

2022-08-23 15:54 UTC, dyozie requested changes

2022-08-23 15:54 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/modules/gp_pitr.html.md
> +The `gp_pitr` module supports implementing Point-in-Time Recovery for Greenplum Database 6X. In service of this it creates a new view -- `gp_stat_archiver` -- as well as two user-defined functions th
6X -> 6

2022-08-23 15:54 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/modules/intro.html.md
> +-   [gp_pitr](gp_pitr.html.md) - Supports implementing Point-in-Time Recovery for Greenplum Database 6X.
6X -> 6

2022-08-25 18:05 UTC, merged