docs - update sql ref pages for ABORT/BEGIN/END/COMMIT/ROLLBACK/...
greenplum-db/gpdb pull request #14157
Opened 2022-09-22 20:07 UTC by lisakowen

SET TRANSACTION and START TRANSACTION commands

this PR updates the listed sql command reference pages to the postgres v12 content.  in some cases i changed a parameter option name to align with pg.  in cases where there was greenplum-specific info in the original reference page, (like greenplum doesn't support SERIALIZABLE transaction isolation level), i retained the info.

tbd if greenplum supports AND CHAIN.

doc review site link for ABORT (behind vpn), can navigate to others from there:  https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/lisa-sqlref-abort/greenplum-database/GUID-ref_guide-sql_commands-ABORT.html

2022-12-09 17:30 UTC, divyeshddv approved these changes
LGTM!

2022-12-12 22:13 UTC, lisakowen commented
thank you for reviewing, @divyeshddv !

2023-01-24 23:45 UTC, dyozie requested changes

2023-01-24 23:45 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/feature_summary.html.md
> +<p class="p"><code class="ph codeph">SET TRANSACTION SNAPSHOT</code>YES</p>
I think the intention here is to remove the entire line here (the entire HTML <p>).  Otherwise the "YES" here doesn't seem correct - the paragraphs are listing limitations.

2023-01-24 23:55 UTC, lisakowen commented on gpdb-doc/markdown/ref_guide/feature_summary.html.md
> +<p class="p"><code class="ph codeph">SET TRANSACTION SNAPSHOT</code>YES</p>
yes, thanks for catching that!

2023-01-25 18:56 UTC, dyozie approved these changes

2023-01-25 18:57 UTC, merged