Docs/event trigger support
greenplum-db/gpdb pull request #14244
Opened 2022-10-10 20:42 UTC by dyozie

Clarify support for PostgreSQL Event Triggers.

2022-10-11 18:20 UTC, lisakowen requested changes

2022-10-11 18:20 UTC, lisakowen commented on gpdb-doc/markdown/ref_guide/feature_summary.html.md
> +6.  Triggers are not generally supported because they typically rely on the use of `VOLATILE` functions. PostgreSQL [Event Triggers](https://www.postgresql.org/docs/9.4/event-triggers.html) are suppo
i think we support event triggers because they are capable of capturing DDL events.

2022-10-11 18:20 UTC, lisakowen commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TRIGGER.html.md
> +> Event Triggers, which capture only DML events, _are_ supported in Greenplum Database. See the PostgreSQL documentation for [Event Triggers](https://www.postgresql.org/docs/9.4/event-triggers.html)
DML -> DDL

2022-10-11 18:46 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TRIGGER.html.md
> +> Event Triggers, which capture only DML events, _are_ supported in Greenplum Database. See the PostgreSQL documentation for [Event Triggers](https://www.postgresql.org/docs/9.4/event-triggers.html)
Oh boy - what a typo and thank you for calling it out!

2022-10-11 18:56 UTC, lenapivotal approved these changes
LGTM

2022-10-12 02:59 UTC, adam8157 approved these changes

2022-10-12 17:13 UTC, merged