Loading environment variable from etc/environment.d
greenplum-db/gpdb pull request #14327
Opened 2022-10-24 12:15 UTC by Sasasu

Load an external environment variable from '$GPHOME/etc/environment.d/'. The name of the configuration must be '\d\d-\w*\.conf'. Adding two numeric prefixes in front of the file name simplifies the ordering.

For example:

```
etc/environment.d/
   - 00-overload-openssl.conf
   - 10-add-python-path-gpdb.conf
   - 90-add-rlib.conf
   - 90-load-pfx-path.conf
   - some_bad_file
```

The order of loading will be an ascending numerical order, in this case it will be 00, 10 and then 90, the order between two 90's is undefined. files without .conf suffix will not be loaded.

The format and file path are from systemd, which is already widely used in most Linux systems.
https://www.freedesktop.org/software/systemd/man/environment.d.html

Use case:

Some extensions need an additional environment variable to boot up, with environment.d, the extension can add the environment variable without modifying greenplum_path.sh.
example: https://github.com/greenplum-db/pljava/blob/9a14421cfad80be06d8245a64a5766481e89c6df/gpdb/packaging/gppkg_spec.yml.in#L11-L19

Load pxf environment file automatically. pxf and gptext need an additional PATH directory to store the executable files. with this environment file, the component can add them self to greenplum_path.sh without modifying this file.

2022-10-24 13:38 UTC, beeender commented
Can we have an example of how does the conf file look like? something like:

```
# 00-default-greenplum.conf

PATH=/usr/local/greenplum-db/bin
LD_LIBRARY=/usr/local/greenplum-db/lib:/usr/local/greenplum-db/ext/python/lib
```

Will the existing ENV be appended? like if the `00-default-greenplum.conf` exists, the actual `PATH` will be exported as `PATH=$PATH:$PATH_IN_00_DEFAULT_GREENPLUM.CONF`?

2022-10-25 01:54 UTC, Sasasu commented
> Can we have an example of how does the conf file look like? something like:

example in systemd man page
```
/etc/environment.d/60-foo.conf:

        FOO_DEBUG=force-software-gl,log-verbose
        PATH=/opt/foo/bin:$PATH
        LD_LIBRARY_PATH=/opt/foo/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
        XDG_DATA_DIRS=/opt/foo/share:${XDG_DATA_DIRS:-/usr/local/share/:/usr/share/}
```

The configuration files contain a list of "KEY=VALUE" environment variable assignments, separated by newlines. The right hand side of these assignments may reference previously defined environment variables, using the "${OTHER_KEY}" and "$OTHER_KEY" format. It is also possible to use "${FOO:-DEFAULT_VALUE}" to expand in the same way as "${FOO}" unless the expansion would be empty, in which case it expands to DEFAULT_VALUE, and use "${FOO:+ALTERNATE_VALUE}" to expand to ALTERNATE_VALUE as long as "${FOO}" would have expanded to a non-empty value. No other elements of shell syntax are supported.

2022-10-28 09:13 UTC, piyushc01 commented
Can we try with a sample test environment file and check in one of the test case for specific variables in greenplum-path.sh file and environment ?
Also make sure that pipeline is not affected with this change.

2022-10-28 09:13 UTC, piyushc01 requested changes

2022-10-28 09:13 UTC, piyushc01 commented on gpMgmt/bin/generate-greenplum-path.sh
> +		source "${env}"
Can we log what all conf files are being referred in a log so that we know the source?

2022-10-31 02:35 UTC, Sasasu commented
> Also make sure that pipeline is not affected with this change.

our CI will source this file every time. so this change has a test.

2022-11-01 02:47 UTC, higuoxing commented on gpMgmt/bin/generate-greenplum-path.sh
> +	for env in $(find "${GPHOME}/etc/environment.d" -name '*.conf' -type f | sort -n); do
It would be great to check that configuration files' name are obeying the naming conventions. Otherwise, looks good to me.

2022-11-02 01:04 UTC, higuoxing approved these changes
Looks good!

2022-11-02 02:06 UTC, merged