Fixme: basebackup slot creation
greenplum-db/gpdb pull request #14346
Opened 2022-10-27 03:13 UTC by shrakesh

Issue: If the cluster never has mirrors, PgBasebackUp call will fail with create-slot option False, so to add the mirror as part of fall back we were making the PgBasebackUp call with create-slot option true. 

Fix: we are dropping the existing slot if slot is present and creating new one in the scenario where we are adding mirror or doing move mirror similar operation with full recovery.  

Updated unit and feature test cases for the following reason
    1. in feature test case if the full recovery fails we were trying to run the pgrewind, as with the new changes we are removing the replication slot and because of that while doing pgrewind it is giving error. the scenario could be fail even without the code changes if in between of full recovery the slot gets deleted or move or renamed. the possible future solution could be having name which indicates mapping of primary and mirror slot and based on that we can use the slot in pg rewind. but that's the little complex to work on now. for now in this situation customer would try to fix the issue and rerun full recovery instead of incremental.

    2.  as we have removed 1 call to pgbasebackup i have updated and removed some test cases accordingly.
            
## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2022-10-27 03:14 UTC, shrakesh commented
Pipeline link: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-gprecoverseg-create-slot?group=CLI

2022-10-31 09:56 UTC, piyushc01 requested changes

2022-10-31 09:56 UTC, piyushc01 commented on gpMgmt/bin/gppylib/commands/test/unit/test_unit_pg_base_backup.py
>              replication_slot_name='some-replication-slot-name',
Can we add following unit tests: 
1. When `drop_replication_slot_if_exist` return false
2. Unit test for `drop_replication_slot_if_exist`

2022-11-01 10:46 UTC, kaknikhil commented on gpMgmt/bin/gppylib/commands/pg.py
> +        if create_slot and drop_replication_slot_if_exist(source_host, source_port, replication_slot_name):
>  if the slot is not present we will treat it as success
>  if the slot is active and not able to drop. we will consider that as an error and will not create slot.

These two make for good behave test cases. We should make sure that we have behave tests for these scenarios

2022-11-01 10:46 UTC, kaknikhil commented on gpMgmt/bin/gppylib/commands/pg.py
> +        if "does not exist" in str(ex):
Rather than depending on the exception string, isn't there a better way to know if a replication slot exists ? Can't we query pg_replication_slots ?
If it is indeed possible, then we can create two functions, one to query if the slot exists and another one to drop the slot. Then the caller can first call the query function and then the drop function.

2022-11-01 10:46 UTC, kaknikhil commented on gpMgmt/bin/gppylib/commands/pg.py
> +        logger.exception("Failed to drop replication slot " + str(ex))
I would suggest using `.format` instead of `+`

2022-11-02 07:26 UTC, shrakesh commented on gpMgmt/bin/gppylib/commands/pg.py
> +        if "does not exist" in str(ex):
we can get existance status of the slot from pg_replication_slots table. just only thing is there will be two database call instead of one (this is in line with performance optimization but that's one time op) . 

Side Note: i struggled a bit while writing unit test cases for the  DatabaseError exception scenario as currently unit test case is supports mocking of only 2 exception type(Exception and BaseException).  if 2 function is made and we can replace DatabaseError to generic Exception and it will ease out to write unit test case for all code path. 
 
CC: @ashwinstar

2022-11-02 07:28 UTC, shrakesh commented on gpMgmt/bin/gppylib/commands/test/unit/test_unit_pg_base_backup.py
>              replication_slot_name='some-replication-slot-name',
for 2nd point i struggled while writing unit test cases for the DatabaseError exception scenario as currently unit test case is supports mocking of only 2 exception type(Exception and BaseException). i can try ti strengthen this in feature test case.

2022-11-02 07:32 UTC, shrakesh commented on gpMgmt/bin/gppylib/commands/pg.py
> +        logger.exception("Failed to drop replication slot " + str(ex))
sure I will try to make it the log messages more comprehensive. 
regarding entry and exit debug message, i haven't seen any example where we follow debug note on entry and exit for a function. IMHO this will make debug logs more clumsy as some of the functions are getting called in loop and there will be lot of log messages which are not intended.

2022-11-09 12:23 UTC, kaknikhil commented on gpMgmt/bin/gppylib/commands/pg.py
> +    except DatabaseError as e:
We should also add a test case for this exception type

2022-11-09 12:23 UTC, kaknikhil commented on gpMgmt/bin/gppylib/test/unit/test_unit_gpsegrecovery.py
> +    def test_is_slot_exist_conn_exception(self, mock1, mock2):
These unit tests do not belong in test_unit_gpsegrecovery.py since the `is_slot_exist` and `drop_replication_slot` functions are defined in pg.py and not test_unit_gpsegrecovery.py

2022-11-09 12:23 UTC, kaknikhil commented on gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
> +        And gprecoverseg should print "Checking if slot internal_wal_replication_slot exist" to stdout
We could also query the pg_replication_slots table and assert that the slot exists before and after running gprecoverseg

2022-11-09 12:23 UTC, kaknikhil commented on gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
> +    Scenario: gprecoverseg should drop existing slot on full recovery
We should also add similar tests for gpmovemirrors and gpaddmirrors

2022-11-11 18:55 UTC, shrakesh commented on gpMgmt/bin/gppylib/commands/pg.py
>              cmd_tokens.append('--create-slot')
@kaknikhil can you please check below restructured code, let me know if any change is needed.  i am also looking for some suggestion for the variable **ok_to_create**. 
```
        if create_slot:
            ok_to_create = True
            if slot_exists(source_host, source_port, replication_slot_name):
                ok_to_create = drop_replication_slot(source_host, source_port, replication_slot_name)

            if ok_to_create:
                cmd_tokens.append('--create-slot')
```

2022-11-16 19:11 UTC, shrakesh commented on gpMgmt/bin/gppylib/test/unit/test_unit_gpsegrecovery.py
> +    def test_is_slot_exist_conn_exception(self, mock1, mock2):
move these tests to pg_base_backup.py as the pg.py file is under commands directory this looks better fit place.

2022-11-16 19:12 UTC, shrakesh commented on gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
> +    When the user runs "gprecoverseg -aF"
i have added the details in one of the commits, i will clean up and create a specific commit with this change only.

2022-11-25 09:58 UTC, shrakesh commented on gpMgmt/bin/gppylib/commands/pg.py
> +            with closing(dbconn.connect(dburl, utility=True, encoding='UTF8')) as conn:
yes that's correct, on coordinator we won't get info, gp_dist_random gives combined info.

2022-11-28 14:28 UTC, shrakesh commented on gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
> +        And gprecoverseg should print "pg_basebackup: base backup completed" to stdout
Added "the user waits until mirror on content 0,1,2 is up" and similar to confirm that

2022-11-28 14:29 UTC, shrakesh commented on gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
> +                                        allowSystemTableMods=True, unsetSearchPath=False)) as conn:
yeah not actually, removed.

2022-11-29 05:50 UTC, shrakesh commented on gpMgmt/bin/gppylib/commands/pg.py
> +        sql = "select count(*) from pg_replication_slots where slot_name = '{}'". format(self.name)
yeah good to have it, added schema pg_catalog .

2022-11-29 06:31 UTC, kaknikhil approved these changes

2022-11-29 06:31 UTC, kaknikhil commented on gpMgmt/bin/gppylib/commands/test/unit/test_unit_pg_base_backup.py
> +    # @patch('gppylib.db.dbconn.DbURL', return_value=Mock())
We can delete this line

2022-11-29 06:54 UTC, piyushc01 approved these changes

2022-11-29 12:45 UTC, merged