docs - some system catalog updates for new partitioning ...
greenplum-db/gpdb pull request #14477
Opened 2022-11-15 19:24 UTC by lisakowen

add/update/remove some system catalogs related to partitioning, bring them up to postgres v12 content.  in this PR:
- add pg_partitioned_table system catalog ref page
- update pg_attribute, pg_class, pg_constraint, pg_depend pg_inherits, pg_opclass system catalog reference docs
- remove pg_partition_xxxx and pg_stat_partition_operation catalog ref docs
- NOTE:  this PR does NOT remove pg_partition or pg_partitions - too many references and no one-for-one replacement

question:  the pg_class and pg_inherits topics include XXX-tagged statements that are not in the postgres docs.  are these applicable to greenplum 7?

doc review site link for pg_partitioned_table (behind vpn) - you can navigate to the others from there:  https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/pcat/greenplum-database/GUID-ref_guide-system_catalogs-pg_partitioned_table.html

2022-11-16 18:33 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/ref_guide/system_catalogs/pg_attribute.html.md
> +In a dropped column's `pg_attribute` entry, `atttypid` is reset to zero, but `attlen` and the other fields copied from `pg_type` are still valid. This arrangement is needed to cope with the situation
to cope with the situation  ==> to address the situation

2022-11-16 18:37 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/ref_guide/system_catalogs/pg_inherits.html.md
> +XXX In Greenplum Database, inheritance relationships are created by both the `INHERITS` clause \(standalone inheritance\) and the `PARTITION BY` clause \(partitioned child table inheritance\) of `CRE
What is the "XXX"?

2022-11-16 18:38 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/ref_guide/system_catalogs/pg_depend.html.md
> +Other dependency flavors might be needed in future.
I don't know what a "dependency flavor" is. This feels slang-y.

2022-11-16 18:39 UTC, lisakowen commented on gpdb-doc/markdown/ref_guide/system_catalogs/pg_inherits.html.md
> +XXX In Greenplum Database, inheritance relationships are created by both the `INHERITS` clause \(standalone inheritance\) and the `PARTITION BY` clause \(partitioned child table inheritance\) of `CRE
related to a question in the PR description - i've been tagging (greenplum-specific?) content that is not on the postgres ref pages with XXX.  this is typically info that i want to verify is still relevant in greenplum 7.

2022-11-16 18:39 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/ref_guide/system_catalogs/pg_depend.html.md
> +-   **DEPENDENCY\_AUTO\_EXTENSION (x)** - The dependent object is not a member of the extension that is the referenced object \(and so it should not be ignored by pg_dump\), but it cannot function wi
Functionally, this  ==> Functionally, this

2022-11-16 18:41 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/ref_guide/system_catalogs/pg_depend.html.md
> +-   **DEPENDENCY\_INTERNAL \(i\)** — The dependent object was created as part of creation of the referenced object, and is really just a part of its internal implementation. A direct `DROP` of the de
So, just generally, this prose feels more conversational than I would expect in a technical writing guide (e.g., "we'll tell the user"). 

I realize that Postgres open source folks likely wrote this and perhaps aren't formally trained technical writers. And perhaps it's not the time or place to correct this.

2023-01-31 20:04 UTC, l-wang commented
I'm looking at this today.

2023-02-01 20:21 UTC, l-wang approved these changes
LGTM. I left some examples for reference.

Remaining (partitioning related) catalog tables/views need to be removed:
```
pg_partition
pg_partitions
pg_stat_partition_operations
```
Additional catalog tables/functions need to be added:
```
gp_partition_template -- GPDB7 specific
pg_partition_tree() -- upstream
pg_partition_ancestors() -- upstream
pg_partition_root() -- upstream
```

Most content `pg_partitions` view in 6X provides can be retrieve in 7X by the combination of `pg_class.relpartbound`, `pg_partitioned_table` and `pg_partition_tree()`. For example, in 7X to get similar content as 6X `pg_partitions` view, one can use the following query:
```sql
select
n.nspname,
c.relname,
pg_partition_root(c.oid) as rootname,
inh.inhparent::regclass::text as parentname,
pt.partstrat,
pt.partnatts,
pt.partattrs as partkeycol,
pg_get_expr(pt.partexprs, pt.partrelid) as partkeyexpr,
(select level from pg_partition_tree(c.oid)) as level,
pg_get_expr(c.relpartbound, c.oid) as partbound
from pg_class c
 LEFT JOIN pg_namespace n ON n.oid = c.relnamespace
 LEFT JOIN pg_inherits inh ON inh.inhrelid = c.oid
 LEFT JOIN pg_partitioned_table pt ON inh.inhparent = pt.partrelid
where c.relispartition = 't'; 
```
Output:
```
 nspname |   relname   | rootname | parentname | partstrat | partnatts | partkeycol | partkeyexpr | level |         partbound          
---------+-------------+----------+------------+-----------+-----------+------------+-------------+-------+----------------------------
 public  | bar_1_prt_2 | bar      | bar        | r         |         1 | 2          |             |     0 | FOR VALUES FROM (2) TO (3)
 public  | bar_1_prt_1 | bar      | bar        | r         |         1 | 2          |             |     0 | FOR VALUES FROM (1) TO (2)
(2 rows)
```
However, I would not command new users to just use the above query or something even more complicated to create a `pg_partitions` view in 7X and call it a day. I would recommend users to play with the following catalog tables and functions to figure out what they really need.
```sql
SELECT * FROM pg_partitioned_table;

SELECT
c.relname,
c.relkind,
c.relispartition,
pg_get_expr(c.relpartbound, c.oid) as partbound
FROM pg_class c
WHERE c.relkind = 'p' OR c.relispartition;

SELECT * FROM pg_partition_tree('sales');
SELECT * FROM pg_partition_ancestors('sales_1_prt_1');
SELECT pg_partition_root('sales_1_prt_1');
```

2023-02-01 20:26 UTC, l-wang commented on gpdb-doc/markdown/ref_guide/system_catalogs/pg_constraint.html.md
> +The `pg_constraint` system catalog table stores check, primary key, unique, foreign key, and exclusion constraints on tables. \(Column constraints are not treated specially. Every column constraint i
Greenplum specific: 
- Similar to Unique constraint, exclusion constraints are allowed only for replicated tables of if the distribution key columns are part of the constraint.
- Exclusion constraints are not supported by partitioned tables.

For reference:
```
commit cdb61585658e3685654c7e6cf9bed2f7a1b51f66
Author: Heikki Linnakangas <hlinnakangas@pivotal.io>
Date:   Mon Dec 23 14:47:15 2019 +0200

    Allow exclusion constraints.
    
    Exclusion constraints can be enforced if the table is replicated, or if
    the distribution key columns are part of the constraint, with the same =
    operator as in the distribution key's hash opclass. This is analogous to
    the similar restrictions on unique indexes.
    
    Exclusion constraints on partitioned tables would have similar
    restrictions, but because of the way creation of partitioned tables
    currently works, checking for those restrictions would be tricky. A
    partitioned table is only marked as partitioned after the indexes have
    been created, so we cannot check for compatibility with partitioning keys
    during index creation, like we can with distribution keys. Refactoring
    creation of partitioned tables is more than I can chew right now, so for
    now, continue to disallow exclusion constraints on partitioned tables.
    
    Reviewed-by: Zhenghua Lyu <zlv@pivotal.io>
    Reviewed-by: Kalen Krempely <kkrempely@pivotal.io>
```

2023-02-02 18:49 UTC, lisakowen commented
thank you for the thorough review, @l-wang .  i will work through your comments.  a few things first:
- i believe that this PR does remove pg_stat_partition_operations and references.
- will deal with pg_partition and pg_partitions separately - there are alot of references to those catalogs in the "using" docs, which will need a re-haul (which we have not started).
- i will add a ref page for gp_partition_template in this PR.
- will cover the pg_partition_tree(), pg_partition_ancestors(), and pg_partition_root() function definitions and use in the forthcoming "using" docs.

this is PR will be one of many related to partitioning.  i will be sure to note your comments/examples for addition in the "using" content docs.

2023-02-03 21:11 UTC, l-wang commented
> * i believe that this PR does remove pg_stat_partition_operations and references.

You are absolutely correct! Sorry I missed that one!

2023-02-07 19:05 UTC, lisakowen commented
@l-wang , could you please review the recent commit that adds docs for the gp_partition_template system catalog?

2023-02-08 18:48 UTC, l-wang approved these changes
Descriptions of the table attributes of `gp_partition_template` are correct, I added some minor comments. I only looked at the code change, I'm assuming we haven't redeployed the latest code so this table does not show up in this link https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/pcat/greenplum-database/GUID-ref_guide-system_catalogs-pg_partitioned_table.html

Question: Are we keeping docs that has examples of how to use subpartition template as before? This doc page for 6X has examples: https://docs.vmware.com/en/VMware-Tanzu-Greenplum/6/greenplum-database/GUID-admin_guide-ddl-ddl-partition.html . These examples are still valid, but in 7X we need to tell users the templates may not work as they expected if new syntax were used to create new child partitions.

Since this PR is just for catalog stuff we don't need to worry about adding examples,  in subsequent doc changes we can refer https://github.com/greenplum-db/gpdb/blob/main/src/test/regress/sql/gp_partition_template.sql to explain subpartition template usage and its limitations.

2023-02-08 18:48 UTC, l-wang commented on gpdb-doc/markdown/ref_guide/system_catalogs/gp_partition_template.html.md
> +Each subpartition template has a dependency on the existence of a template at the next lowest level of the hierarchy.
s/lowest/lower

2023-02-08 18:48 UTC, l-wang commented on gpdb-doc/markdown/ref_guide/system_catalogs/gp_partition_template.html.md
> +|`relid`| oid | [pg_class](pg_class.html).oid| The object identifier of the partitioned table. |
s/`partitioned table`/`root partitioned table` to be more explicit.

2023-02-08 18:48 UTC, l-wang commented on gpdb-doc/markdown/ref_guide/system_catalogs/gp_partition_template.html.md
> +|`level`|smallint| | The level of the partition in the hierarchy. |
Can we also explain how do we number the levels? For example: level 0 is the root partitioned table itself. Level 1 has the direct child/children of the root partitioned table, etc. The leaf partitions have the highest level numbers.

2023-02-08 18:55 UTC, l-wang requested changes

2023-02-08 18:55 UTC, l-wang commented on gpdb-doc/markdown/admin_guide/ddl/ddl-table.html.md
> +);
We can't just copy this example from upstream because this doesn't work for Greenplum:
```
CREATE TABLE circles (
    c circle,
    EXCLUDE USING gist (c WITH &&)
);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause, and no column type is suitable for a distribution key. Creating a NULL policy entry.
ERROR:  exclusion constraint and DISTRIBUTED RANDOMLY are incompatible
```
I will also have to poke a little to understand what is supported and what not in GP7 regarding exclusion constraint.

2023-02-08 19:08 UTC, l-wang commented on gpdb-doc/markdown/admin_guide/ddl/ddl-table.html.md
> +);
Ah I did poked already. Here are the current limitations of exclusion constraint in GP7: https://github.com/greenplum-db/gpdb/pull/14477#discussion_r1093696165

So we can modify the above example to use `distributed replicated`
```
postgres=# CREATE TABLE circles (
    c circle,
    EXCLUDE USING gist (c WITH &&)
) distributed replicated;
```

2023-03-08 23:36 UTC, lisakowen commented
hi @l-wang .  sorry it took me so long to get back to this.  i've made your requested edits and republished the review site.  here is a link to the new gp_partition_template system catalog page:  https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/pcat/greenplum-database/GUID-ref_guide-system_catalogs-gp_partition_template.html

per your question above, yes we plan to keep the examples on https://docs.vmware.com/en/VMware-Tanzu-Greenplum/6/greenplum-database/GUID-admin_guide-ddl-ddl-partition.html (and add new examples), thanks for pointing out that we will need to make a note about subpartition templates created with the new syntax.

2023-03-24 00:35 UTC, l-wang commented on gpdb-doc/markdown/ref_guide/system_catalogs/gp_partition_template.html.md
> +Each subpartition template has a dependency on the existence of a template at the next lower level of the hierarchy.
My bad I didn't catch this before. "lower" reads intuitive to me, but I wonder the way we number levels may confuse users. Given leaf partitions have the highest level number, should we say "next higher level" instead? Or just "next level"?

2023-03-24 00:38 UTC, l-wang approved these changes

2023-03-29 23:28 UTC, dyozie approved these changes

2023-03-29 23:38 UTC, merged