Fix aocsseg inconsistency when rollback add column
greenplum-db/gpdb pull request #14527
Opened 2022-11-23 21:10 UTC by divyeshddv

Before current commit we initailized pg_aocsseg entries with frozen tuples to make these entries implicitly visible even after rollback. It is a working approach for AO tables, but AOC tables store additional "vpinfo" structure with serialized information about every column EOF. This can cause inconsistency between "vpinfo" structure in pg_aocsseg entries and the actual number of columns in a table when we modify the amount of columns under explicit transaction and rollback it later. As a result we fail on asserts in "GetAllAOCSFileSegInfo_pg_aocsseg_rel()" or (in a case of a build without asserts) in some unpredictable places in the code when retrieve metadata from pg_aocsseg.

As a fix this commit inserts simple tuples to pg_aocsseg but still insert frozen tuples to gp_fastsequence (as it generates row numbers for segment files and should never be rollbacked to avoid inconsistency in index pointers of the AO/AOC tables).

Cherry-picked from commit a5e28ec with minor changes

This is forward ported from PR https://github.com/greenplum-db/gpdb/pull/11371
And solves github issue https://github.com/greenplum-db/gpdb/issues/14518

Co-authored-by: Vasiliy Ivanov <ivi@arenadata.io>
Co-authored-by: Denis Smirnov <sd@picodata.io>

2022-11-24 04:52 UTC, divyeshddv commented
Some tests are failing on the pipeline. Please hold off on the review for now.

2022-12-14 03:14 UTC, interma commented
Thanks @divyeshddv.
I have been a little busy recently, will review it in a couple of days (if no other guys review it).

2023-01-05 04:05 UTC, interma reviewed
some thoughts.

2023-01-05 04:05 UTC, interma commented on src/backend/access/appendonly/appendonlywriter.c
> +	 * Obtain a SNAPSHOT_DIRTY, to see all tuples in concurrent transactions.
I think we have to use `SNAPSHOT_DIRTY` carefully to avoid corner cases, I will think deeper.

2023-01-07 09:23 UTC, interma requested changes
I have read the related logic, I think the idea of this PR may not work, reasons:
* In previous code, each segfile has one and only one frozen tuple associated with it, so we  rely on `heap_lock_tuple()` to prevent concurrent access.
* In this PR, using normal tuple instead of frozen tuple and using SNAPSHOT_DIRTY to scan them later. I think it breaks the segno choose algorithm (in `choose_segno_internal()`): **now there are many row versions associated with one segfile**, it may choose an on-using row version tuple, then concurrent access a physical segfile and cause error.

2023-01-07 09:23 UTC, interma commented on src/backend/access/appendonly/appendonlywriter.c
> +	 * Obtain a SNAPSHOT_DIRTY, to see all tuples in concurrent transactions.
please see my comment: https://github.com/greenplum-db/gpdb/pull/14527#pullrequestreview-1239645307

2023-01-18 15:12 UTC, divyeshddv commented
> I have read the related logic, I think the idea of this PR may not work, reasons:
> 
> * In previous code, each segfile has one and only one frozen tuple associated with it, so our segno-choose algorithm (in `choose_segno_internal()`) relies on `heap_lock_tuple()` to prevent concurrent access.
> * In this PR, using normal tuple instead of frozen tuple and using SNAPSHOT_DIRTY to scan them later. I think it breaks the segno-choose algorithm: **now there are multi row versions associated with one segfile**, lock on one of them doesn't block others, so it may choose an on-using row version tuple, then concurrent access a physical segfile and cause error.
> 
> @divyeshddv please take a look, thanks.

Thanks a lot for the review!
I agree, using SNAPSHOT_DIRTY won't work for this case. 
Using dirty snapshot also breaks the segfile choosing logic for repeatable read isolation level where we need to specifically ignore segfiles edited after a repeatable read transaction begins.
Closing this PR

2023-01-18 15:12 UTC, closed without merging