docs - add content for new gp_max_parallel_cursors guc
greenplum-db/gpdb pull request #14548
Opened 2022-11-29 00:43 UTC by lisakowen

docs for https://github.com/greenplum-db/gpdb/pull/14051.

not sure if i got the set classifications correct.

(will backport to 6X_STABLE in a separate PR, as the parallel retrieve cursor functionality is a module in 6X.)

2022-11-30 17:54 UTC, dyozie approved these changes

2022-11-30 17:54 UTC, dyozie commented on gpdb-doc/markdown/admin_guide/parallel_retrieve_cursor.html.md
> +By default, Greenplum Database allows an unlimited number of parallel retrieve cursors to be active in the cluster. Should you wish to limit the number of open cursors, the Greenplum Database superus
Maybe edit second sentence to:  The Greenplum Database superuser can set the gp_max_parallel_cursors server configuration parameter to limit the  number of open cursors.

2022-11-30 19:12 UTC, lisakowen commented on gpdb-doc/markdown/admin_guide/parallel_retrieve_cursor.html.md
> +By default, Greenplum Database allows an unlimited number of parallel retrieve cursors to be active in the cluster. Should you wish to limit the number of open cursors, the Greenplum Database superus
thanks for reviewing, @dyozie

2022-12-01 08:33 UTC, adam8157 requested changes
Others look fine.

And we described this GUC in the guc_gp.c, `SHOW ALL` could display it, I remember the "source" or "dest" confused you, it would be great that update it too.

2022-12-01 08:33 UTC, adam8157 commented on gpdb-doc/markdown/admin_guide/parallel_retrieve_cursor.html.md
> +By default, Greenplum Database allows an unlimited number of parallel retrieve cursors to be active in the cluster. The Greenplum Database superuser can set the [gp\_max\_parallel\_cursors](../ref_gu
We could not have an unlimited number of parallel retrieve cursors, currently the number of endpoints has a limit (1024, just for now), and every parallel retrieve cursor has at least 1 endpoint, so ...

2022-12-01 15:27 UTC, lisakowen commented on gpdb-doc/markdown/admin_guide/parallel_retrieve_cursor.html.md
> +By default, Greenplum Database allows an unlimited number of parallel retrieve cursors to be active in the cluster. The Greenplum Database superuser can set the [gp\_max\_parallel\_cursors](../ref_gu
thank you for reviewing, @adam8157 .  i updated the guc description in guc_gp.c.  also updated the text on this page and the ref page to call out the maximum value of 1024.

2022-12-02 04:07 UTC, Aegeaner commented on gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
> +
before it is `CLOSE`d normally or `FAILED` because of error aborting.

2022-12-05 08:34 UTC, Aegeaner approved these changes

2022-12-05 15:37 UTC, lisakowen commented on src/backend/utils/misc/guc_gp.c
> +			gettext_noop("Parallel cursor concurrency control from the local cluster side, -1 means no limit, which is the default"),
ok, @adam8157 , i removed the clause.  

just to confirm... do you mention the gp2gp scenario because greenplum_fdw reads this guc value in the local cluster and somehow sets the value of this guc in the remote cluster (where the parallel cursors are defined)?  i didn't think so, but want to verify because i didn't document this as such.  (note that when i submit the PR for 6X_STABLE, i will also mention this guc for the remote in the greenplum_fdw docs.)

2022-12-06 23:24 UTC, lisakowen commented
hi @adam8157 , can you address my question above and then approve if all looks good to you?

2022-12-12 07:36 UTC, adam8157 commented on src/backend/utils/misc/guc_gp.c
> +			gettext_noop("Parallel cursor concurrency control from the local cluster side, -1 means no limit, which is the default"),
no, just because gp2gp uses parallel cursors.

2022-12-12 07:37 UTC, adam8157 approved these changes

2022-12-14 17:56 UTC, lisakowen commented
merging, will submit a new PR for 6X_STABLE.

2022-12-14 17:56 UTC, merged