[7x] Test fix failure by adding timeout
greenplum-db/gpdb pull request #14589
Opened 2022-12-02 04:00 UTC by piyushc01

Some of the gpmovemirror and gprecoverseg tests seen failing when waiting for segment to come online or waiting for progress file (recovery_progress.file)  to get created sometime which is taking longer. Enhancing timeout for such cases.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2022-12-02 04:28 UTC, ashwinstar requested changes
Should be increasing number of retries and not sleep time between retries. As current approach increases test type unnecessarily vs bumping number of retries doesn't affect success test times.

2022-12-02 04:30 UTC, ashwinstar commented
Also, commit title seems not correct - as this PR is not adding timeout. Timeout mechanism exists its just bumping the retry time.

2022-12-02 04:42 UTC, piyushc01 commented
> Should be increasing number of retries and not sleep time between retries. As current approach increases test type unnecessarily vs bumping number of retries doesn't affect success test times.

Here adding number of retries can result in CPU hogging. 
So extended sleep time by few milliseconds so that we are not hogging CPU and actual processes can run during the time.

2022-12-02 20:34 UTC, ashwinstar commented
> > Should be increasing number of retries and not sleep time between retries. As current approach increases test type unnecessarily vs bumping number of retries doesn't affect success test times.
> 
> Here adding number of retries can result in CPU hogging. So extended sleep time by few milliseconds so that we are not hogging CPU and actual processes can run during the time.

How many cores do we have for the job on the box this is running? How many actually processes are we running during this time? Are we really contending for CPU?

2022-12-05 11:52 UTC, piyushc01 commented
> > > Should be increasing number of retries and not sleep time between retries. As current approach increases test type unnecessarily vs bumping number of retries doesn't affect success test times.
> > 
> > 
> > Here adding number of retries can result in CPU hogging. So extended sleep time by few milliseconds so that we are not hogging CPU and actual processes can run during the time.
> 
> How many cores do we have for the job on the box this is running? How many actually processes are we running during this time? Are we really contending for CPU?

Current test env, we are having 2 single core CPU.
And in our test we are loading `100000000` number of rows which might also leading to slow response.
In test run even with this increased time, I can see that still this recovery progress file did not appear. 
Need to check why it is taking longer to generate progress file.

2022-12-05 23:55 UTC, ashwinstar commented
> Current test env, we are having 2 single core CPU. And in our test we are loading `100000000` number of rows which might also leading to slow response. In test run even with this increased time, I can see that still this recovery progress file did not appear. Need to check why it is taking longer to generate progress file.

Seriously, why do we need that much data for this test? Really just 2 cores, sounds super tiny :-)

2022-12-16 22:45 UTC, khuddlefish commented
> > Current test env, we are having 2 single core CPU. And in our test we are loading `100000000` number of rows which might also leading to slow response. In test run even with this increased time, I can see that still this recovery progress file did not appear. Need to check why it is taking longer to generate progress file.
> 
> Seriously, why do we need that much data for this test? Really just 2 cores, sounds super tiny :-)

I agree that sounds like more data than we should be using for this test. Why so much?

On the issue of increasing sleep time, I actually think it's appropriate in this case. The overall timeout is staying the same, we're just checking less frequently. I would almost say we could go to 600 retries at 1 second sleep. 1 second won't make much difference when this test runs for over an hour.

2023-01-05 23:56 UTC, ashwinstar approved these changes
If these are the changes in alignment with the changes committed to 6X (and pipeline is green after multiple runs) then seems fine to merge. Thanks for the effort.

2023-01-10 04:30 UTC, merged