docs - updates for diskquota version 2.1.0
greenplum-db/gpdb pull request #14660
Opened 2022-12-15 22:41 UTC by lisakowen

diskquota 2.1 includes some new gucs, among other features and changes.

questions:
1.  the new content i added references max_worker_processes server configuration parameter, but this guc is not documented.  should it be?
2. upgrade - not sure if i got the procedures correct.  are the 2.0.x diskquota libraries available with 2.1.0?
3. hard limit limitation - not sure what "that each table file doesn’t need to extend" means.

doc review site link (behind vpn):  https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/dq210/greenplum-database/GUID-ref_guide-modules-diskquota.html

2022-12-16 01:01 UTC, dyozie requested changes

2022-12-16 16:25 UTC, lisakowen commented on gpdb-doc/markdown/ref_guide/modules/diskquota.html.md
> +-   When `diskquota` is enforcing a *hard limit* for disk usage and data is inserted into a partition table, `diskquota` can not block the query even when `nspsize_in_bytes`, `rolsize_in_bytes`, and
i think only the first partition should be partitioned.

re: the sentence that needs an edit... that is what i am referring to in question 3 in the PR description.  the text is from the engineering team.

2022-12-21 00:13 UTC, lisakowen commented
please review @radarwave

2022-12-21 02:53 UTC, radarwave commented on gpdb-doc/markdown/ref_guide/modules/diskquota.html.md
> +**Note:** Setting `diskquota.max_workers` to a value that is larger than `max_worker_processes` has no effect; `diskquota` workers are taken from the pool of worker processes established by that Gree
GPDB document has a mention of 'max-worker-processes' instead of 'max_worker_processes', I feel no need to describe this again as we do not expect the user to change it, just let the user understand the relationship between the two GUCs.

2022-12-21 03:36 UTC, radarwave commented on gpdb-doc/markdown/ref_guide/modules/diskquota.html.md
> +3.  Re-initialize `diskquota` table size data:
This step is not needed after Diskquota upgrade.

2022-12-21 03:37 UTC, radarwave approved these changes
Comments added.

Others look good to me.

2022-12-21 15:23 UTC, lisakowen commented on gpdb-doc/markdown/ref_guide/modules/diskquota.html.md
> +**Note:** Setting `diskquota.max_workers` to a value that is larger than `max_worker_processes` has no effect; `diskquota` workers are taken from the pool of worker processes established by that Gree
ok.  i changed the other reference to `max_worker_processes`.

2022-12-21 15:24 UTC, lisakowen commented on gpdb-doc/markdown/ref_guide/modules/diskquota.html.md
> +-   When `diskquota` is enforcing a *hard limit* for disk usage and data is inserted into a partition table, `diskquota` can not block the query even when `nspsize_in_bytes`, `rolsize_in_bytes`, and
removed that known issue.

2022-12-21 15:26 UTC, lisakowen commented on gpdb-doc/markdown/ref_guide/modules/diskquota.html.md
> +3.  Re-initialize `diskquota` table size data:
i removed this step in the 2.0->2.1 upgrade section.  i retained this step in the 1.0 -> 2.0 upgrade section.  let me know if you want me to remove it there also.

2022-12-21 18:08 UTC, merged