Gpdocs 94
greenplum-db/gpdb pull request #14722
Opened 2023-01-05 12:07 UTC by mperezfuster

Updated LOAD and LOCK SQL reference pages to match Postgres v12.
Please can you review if I made a mistake by modifying some of the `LOAD` description contents. I will revert if needed.
Same for `LOCK` but mainly formatting changes for this one only. 

Also can you confirm if the option `MASTER_ONLY` would be renamed to `COORDINATOR_ONLY`?

Test link:
https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/mireia/greenplum-database/GUID-ref_guide-sql_commands-LOAD.html
https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/mireia/greenplum-database/GUID-ref_guide-sql_commands-LOCK.html

2023-01-06 20:40 UTC, dyozie requested changes

2023-01-06 20:40 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/sql_commands/LOAD.html.md
> +Non-superusers can only apply `LOAD` to library files located in `$libdir/plugins/` — the specified `filename` must begin with exactly that string. You must to ensure that only “safe” libraries are i
must to ensure -> must ensure

2023-01-06 20:40 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/sql_commands/LOCK.html.md
> +When acquiring locks automatically for commands that reference tables, Greenplum Database always uses the least restrictive lock mode possible. `LOCK TABLE` provides for cases when you might need mor
`LOCK TABLE <b>name</b>` will render as literal characters in markdown.  Probably better to make this `LOCK TABLE <name>` anyhow, since `<name>` seems to be a variable.

2023-04-12 07:40 UTC, yaowangm commented on gpdb-doc/markdown/ref_guide/sql_commands/LOCK.html.md
> -LOCK [TABLE] [ONLY] name [ * ] [, ...] [IN <lockmode> MODE] [NOWAIT] [MASTER ONLY]
Yes, MASTER ONLY was changed to COORDINATOR ONLY. See the relevant PR: https://github.com/greenplum-db/gpdb/pull/8703

I suggest to add the line:

_For backward compatibility, "ON MASTER" is still accepted but is thin
alias for "ON COORDINATOR"._

I verified both work:
```
testdb=# lock table t1 IN ACCESS SHARE MODE COORDINATOR ONLY;
LOCK TABLE
testdb=# lock table t1 IN ACCESS SHARE MODE MASTER ONLY;
LOCK TABLE
```

2023-04-12 19:14 UTC, dyozie approved these changes

2023-04-12 19:15 UTC, merged