docs - sql ref page updates for DEALLOCATE/EXECUTE/PREPARE
greenplum-db/gpdb pull request #14766
Opened 2023-01-11 23:50 UTC by lisakowen

this PR updates the listed sql command reference pages to align with the postgres v12 ref page content. there didn't appear to be any greenplum-specific content.

i also added the pg_prepared_statements system view to the ref guide.

doc review site (behind vpn):
- DEALLOCATE (can get to the others from there):  https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/sqlref-dealexprep/greenplum-database/GUID-ref_guide-sql_commands-DEALLOCATE.html
- pg_prepared_statements:  https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/sqlref-dealexprep/greenplum-database/GUID-ref_guide-system_catalogs-pg_prepared_statements.html

2023-02-02 01:54 UTC, Tao-T approved these changes

2023-02-02 02:40 UTC, dyozie requested changes

2023-02-02 02:40 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/system_catalogs/pg_prepared_statements.html.md
> +|----|----|----------|-----------|
Not sure if it caused any problems, but this defines an extra column (4 columns)

2023-02-02 16:49 UTC, lisakowen commented
thank you for reviewing, @Tao-T and @dyozie .

2023-02-03 18:49 UTC, dyozie approved these changes

2023-02-03 18:49 UTC, merged