add permission check for option execute_on in gp_exttable_fdw validator
greenplum-db/gpdb pull request #14797
Opened 2023-01-17 06:11 UTC by jingwen-yang-yjw

This pr is to fix issue https://github.com/greenplum-db/gpdb/issues/14528.

Now we usually use `create external table` syntax to create an external table in gpdb, which provides more permission check.

If we want to use `create foreign table` syntax to create an external table in gpdb, we must specify `execute_on` option.

Issue https://github.com/greenplum-db/gpdb/issues/14528 is caused by missing a permission check for `execute_on` option when using `create foreign table` syntax to create an external table in gpdb.

This pr adds a permission check for `execute_on` option in gp_exttable_fdw validator.

2023-01-17 08:12 UTC, huiliang-liu commented
need add a test case for it.

2023-01-18 03:28 UTC, jingwen-yang-yjw commented
> need add a test case for it.

OK. I will add a test case later.

2023-01-18 06:18 UTC, adam8157 commented on gpcontrib/gp_exttable_fdw/gp_exttable_fdw.c
> +				 errmsg("must specify option: execute_on")));
I thought only WEB EXTERNAL TABLES need the execute on option.

Please have several external table cases which create and alter not only WEB ones via the FOREIGN TABLE syntax.

2023-01-18 07:38 UTC, jingwen-yang-yjw commented on gpcontrib/gp_exttable_fdw/gp_exttable_fdw.c
> +				 errmsg("must specify option: execute_on")));
When using `CREATE FOREIGN TABLE` syntax, all types of external tables need to specify `execute_on` option.


The reason is that 
no matter which type of external tables are accessed, gpdb needs to get `ExtTableEntry.execlocations` from `execute_on` option in system table `pg_catalog.pg_exttable`.

If no `execute_on` option, it will cause gpdb crashing(segment fault).
```
// In src/backend/cdb/cdbcat.c:316 GpPolicyFetch(Oid)
if (rel_is_external_table(tbloid))
{
    ExtTableEntry *e = GetExtTableEntryIfExists(tbloid);
    if (e)
	{
	    // If no `execute_on` option, gpdb will crash here.
		char	   *on_clause = (char *) strVal(linitial(e->execlocations));
		...
	}
	...
}
```


By the way, using `CREATE EXTERNAL TABLE` syntax can guarantee that all external tables have `execute_on` option in system table `pg_catalog.pg_exttable`.

2023-01-18 07:45 UTC, jingwen-yang-yjw commented on gpcontrib/gp_exttable_fdw/gp_exttable_fdw.c
> +				 errmsg("must specify option: execute_on")));
This case can cause gpdb crashing.
```
CREATE FOREIGN TABLE foo (a int, b int) SERVER gp_exttable_server
OPTIONS (format 'csv', delimiter ',', "null" '', escape '"', quote '"', format_type 'c', location_uris 'file://localhost.localdomain/home/gpadmin/test_external_fdw.csv', log_errors 'f', encoding '6', is_writable 'false');

select * from foo;
```

2023-01-30 02:34 UTC, adam8157 commented on gpcontrib/gp_exttable_fdw/gp_exttable_fdw.c
> +				 errmsg("must specify option: execute_on")));
The current fixing looks not right to me, can we avoid the crash of not-web external tables without the execute_on clause?

2023-01-30 02:35 UTC, adam8157 requested changes
The `execute_on` option should not be a must for the non-web external tables.

2023-01-30 03:23 UTC, zhaorui20005 commented on gpcontrib/gp_exttable_fdw/gp_exttable_fdw.c
> +				 errmsg("must specify option: execute_on")));
> The current fixing looks not right to me, can we avoid the crash of not-web external tables without the execute_on clause?

I think this related to the question of "Is it reasonable to get rid of the external table syntax". Currently we should use external table through external syntax. If we use the external table with FDW syntax, there are a lot of similar cases to be fixed. Because there are a lot of parameters inside an external table that need to be set or have default values. But by using FDW syntax, all of the parameters have to be inside the option list. If some of the parameters are not filled correctly, in the normal code path of Foreign table, there is not an elegant way setting the default value for them.
This PR provides an easy way to make it correct I think.

2023-01-30 07:04 UTC, adam8157 commented on gpcontrib/gp_exttable_fdw/gp_exttable_fdw.c
> +				 errmsg("must specify option: execute_on")));
My bad, s3 and custom protocols could use the `execute_on` option too, I thought only WEB external tables are using it.

2023-01-30 09:07 UTC, zhaorui20005 commented on gpcontrib/gp_exttable_fdw/gp_exttable_fdw.c
> +				 errmsg("must specify option: execute_on")));
But this commit ba33de85288cf5d6df24ec1c7e2327694c8127b1 may cause another problem that the creation of `gp_exttable_server` or `gp_exttable_fdw` would also report an error that no "must specify option: execute_on". So it is not a good idea to add this restriction in function `gp_exttable_permission_check()`. Maybe we could add a default value in `GetExtTableEntryIfExists()`.

2023-01-30 09:50 UTC, jingwen-yang-yjw commented
Function `gp_exttable_permission_check` is gp_exttable_fdw's validator.
If we acquire `execute_on` option in function `gp_exttable_permission_check`, `CREATE FOREIGN SERVER gp_exttable_server` and `CREATE USER USER MAPPING FOR ... SERVER gp_exttable_server` must also specify `execute_on` option.
So current change is unreasonable.

I'll push a new commit with a different method handling issue https://github.com/greenplum-db/gpdb/issues/14528.
This new commit will fill a default value when `execute_on` option doesn't exist while accessing external table.

Please review this pr again. Thank you!

2023-01-30 10:16 UTC, zhaorui20005 approved these changes
LGTM

2023-02-06 09:09 UTC, huiliang-liu approved these changes

2023-02-09 02:35 UTC, adam8157 approved these changes
Be careful with the commit subject and message you are going to check in, it's a different fix.

2023-02-09 03:00 UTC, merged