docs - new sql ref pages for CREATE/DROP ACCESS METHOD
greenplum-db/gpdb pull request #14805
Opened 2023-01-18 16:46 UTC by lisakowen

add sql reference pages for CREATE ACCESS METHOD and DROP ACCESS METHOD.  i pulled the postgres 12 content.

question:  is there any greenplum-specific info that should be added to these pages?

doc review site link (behind vpn):  https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/sqlref-cam/greenplum-database/GUID-ref_guide-sql_commands-CREATE_ACCESS_METHOD.html

2023-01-18 23:38 UTC, dyozie requested changes

2023-01-18 23:38 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_ACCESS_METHOD.html.md
> +TYPE access\_method\_type
Remove "TYPE" here? (to conform with the postgres docs and the "Parameters" topic type?

2023-01-18 23:38 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_ACCESS_METHOD.html.md
> +HANDLER handler\_function
Same here - remove "HANDLER".

2023-01-18 23:38 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_ACCESS_METHOD.html.md
> +:   handler\_function is the name \(possibly schema-qualified\) of a previously registered function that represents the access method. The handler function must be declared to take a single argument
handler\_function -> `handler_function`

2023-01-18 23:38 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_ACCESS_METHOD.html.md
> +:   handler\_function is the name \(possibly schema-qualified\) of a previously registered function that represents the access method. The handler function must be declared to take a single argument
Also - no need to escape the parens in the paragraph body.

2023-01-18 23:38 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/sql_commands/DROP_ACCESS_METHOD.html.md
> +:   Automatically drop objects that depend on the the access method \(such as operator classes, operator families, and indexes\), and in turn all objects that depend on those objects.
repeated word:  the the

2023-01-18 23:38 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/sql_commands/DROP_ACCESS_METHOD.html.md
> +Drop the access method heptree;
heptree -> `heptree`

2023-01-18 23:49 UTC, lisakowen commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_ACCESS_METHOD.html.md
> +:   handler\_function is the name \(possibly schema-qualified\) of a previously registered function that represents the access method. The handler function must be declared to take a single argument
thanks for reviewing.  a few formatting-related questions:
- i am not sure why we would code-font handler_function in paragraph text but not in the definition list?  most of the sql reference pages do not code font (or highlight in any other manner) the parameters that were previously `<xxx>` or italicized in the synopsis.  (i think this originated with the dita to markdown conversion.)
- why do we not need to escape the parens in the paragraph body?  when do we need to escape parens?

2023-01-31 16:18 UTC, AJR-VMware reviewed
# Review done
* create access method AJR type table handler heap_tableam_handler;
    * worked
* create access method AJR2 type index handler bthandler;
    * worked
* create access method AJR3 type index handler heap_tableam_handler;
    * failed as expected
* create access method AJR3 type table handler brinhandler;
    * failed as expected
* create access method AJR3 type DNE handler heap_tableam_handler;
    * failed as expected
* drop access method ajr;
    * worked
* drop access method ajr2;
    * worked
* drop access method ajr3;
    * failed as expected
* many tests exist in src/test for both create and drop AM
    * regress/sql/create_am.sql
    * modules/test_pg_dump/sql/test_pg_dump.sql
    * regress/sql/drop_if_exists.sql
    * regress/sql/psql.sql

# Findings
* Compatibility section -- CREATE ACCESS METHOD is a Greenplum Database extension.
    * This is present verbatim in current upstream.  Do we have separate language to indicate that?

2023-02-02 17:55 UTC, AJR-VMware commented
@lisakowen I think you're right, there's no changes needed here.  I see the pattern we're using, upstream calls it out as an extension in the same way.

Thanks for responding, looks good to me.

2023-02-03 18:37 UTC, dyozie approved these changes

2023-02-03 18:37 UTC, merged