Introducing new diff recovery option for gprecoverseg
greenplum-db/gpdb pull request #14804
Opened 2023-01-18 12:32 UTC by Annu149

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2023-01-28 05:33 UTC, kaknikhil requested changes
Left a few comments. I'm assuming that there are on behave tests in this PR since it's still in draft mode

Some things to keep in mind
1. We should make sure that we extensively test the new flag and that it doesn't introduce any regressions
2. Test it's interactions with other flags like `-i` , `-p` etc
3. Run different types of recovery one after another. For e.g. Full, then differential, then incremental etc. etc.. I would highly recommend thinking through all the interesting test scenarios

2023-01-28 05:33 UTC, kaknikhil commented on gpMgmt/bin/gppylib/commands/pg.py
> +        rsync_cmd = rsync_cmd + " > {} 2>&1".format(pipes.quote(progress_file))
```suggestion
        exclude_str = ["--exclude={}".format(pattern) for pattern in RSYNC_EXCLUDE_LIST]
        
        rsync_cmd = "{} {} > {} 2>&1".format(rsync_cmd, " ".join(exclude_str), pipes.quote(progress_file))
```

2023-01-28 05:33 UTC, kaknikhil commented on gpMgmt/bin/gppylib/commands/pg.py
> +        rsync_cmd = rsync_cmd + " > {} 2>&1".format(pipes.quote(progress_file))
I think this refactor is slightly easier to read. What do you think ?

2023-01-28 05:33 UTC, kaknikhil commented on gpMgmt/bin/gppylib/recoveryinfo.py
> +    SYNC_ERROR = 'diff'
Unlike the other error types, I think it's not evident why SYNC_ERROR has the value 'diff'. Why not call the variable RSYNC_ERROR ?

2023-01-28 05:33 UTC, kaknikhil commented on gpMgmt/sbin/gpsegrecovery.py
> +        """start backup with pg_start_backup()"""
I think this comment is redundant

2023-01-28 05:33 UTC, kaknikhil commented on gpMgmt/sbin/gpsegrecovery.py
> +    def pgStartBackup(self):
This file follows the underscore convention for variables and methods. We should follow the same convention

2023-01-28 05:33 UTC, kaknikhil commented on gpMgmt/sbin/gpsegrecovery.py
> +    def pgStopBackup(self):
The only diff between `pgStartBackup` and `pgStopBackup` is the actual query that gets run. Everything else is the same. I think we have this same pattern elsewhere in the code where we just want to run a query on a specific segment.
We should refactor the boiler plate code and just send the query to run. So something like

```
run_this_query(hostname, port, "select run_some_function('foo')")
```
```

2023-01-28 05:33 UTC, kaknikhil commented on gpMgmt/sbin/gpsegsetuprecovery.py
> +        # is actively using that pid, pg_rewind will fail when it
why does DiffRecovery care about pg_rewind ?

2023-01-28 05:33 UTC, kaknikhil commented on gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
> +        addTo.add_option('--diff', None, default=False, action='store_true',
I'm wondering if it's better to use `--differential` instead of `--diff`. I know other tools like `pgbackrest` use `--diff` but I think `--differential` is more explicit and not that hard to spell out. Thoughts ?

2023-02-02 06:29 UTC, Annu149 commented
@kaknikhil Thanks for reviewing the code, I will address those. This PR is still work in progress, lot of local changes are not pushed here yet. @shrakesh and I are still working on code changes and feedbacks which we received, once completed we will let you know.

2023-02-02 17:46 UTC, Annu149 commented on gpMgmt/bin/gppylib/commands/pg.py
> +            "/pg_log",
This list is prepared based on excludeDirContents and excludeFiles const from postgres source file src/backend/backup/basebackup.c

2023-03-06 17:43 UTC, Annu149 commented
Created new PR https://github.com/greenplum-db/gpdb/pull/15146 with more detailed commits and PR description so closing this one.

2023-03-06 17:43 UTC, closed without merging