Gpdocs 108
greenplum-db/gpdb pull request #14826
Opened 2023-01-24 12:34 UTC by mperezfuster

Initial draft to include JIT compilation content for GPDB 7.
Big part of the text has been ported from Postgres docs: https://www.postgresql.org/docs/12/jit-reason.html and the Postgres readme file https://github.com/postgres/postgres/blob/master/src/backend/jit/README

Test site:
https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/mireia/greenplum-database/GUID-admin_guide-query-topics-just-in-time.html
New GUCs:
https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/mireia/greenplum-database/GUID-ref_guide-config_params-guc_category-list.html (new section for JIT GUCs)

Need advise on:
- Location of JIT pages? Currently under admin_guide/query/topics
- Content, structure, etc
- GUC category for JIT?
- Should we include the Extensibility section? https://www.postgresql.org/docs/12/jit-extensibility.html

2023-01-24 14:51 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +This topic provides an explanation of what Just-in-Time compilation is and how it can be configured in Greenplum Database.
how it can be configured => how to configure it

2023-01-24 14:54 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +Just-in-Time (JIT) compilation is the process of turning some form of interpreted program evaluation into a native program, and doing so at run time. For example, instead of using general-purpose cod
What is an "interpreted program evaluation"?

yielding speedup => resulting in faster execution

2023-01-24 14:56 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +Greenplum Database has builtin support to perform JIT compilation using LLVM when Greenplum Database is built with `--with-llvm`. If you installed Greenplum Database using the `rpm` installation file
builtin=>built-in

I think maybe call out the not necessary if rpm install in a Note?

2023-01-24 14:59 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +It is possible to use JIT with both Postgres Optimizer and GPORCA. Since GPORCA and Postgres Optimizer use different models and the relation of their costs varies, you must tune the JIT thresholds ac
What kind of models?

What does "relation of their costs" mean? 

your practical usage => your usage

2023-01-24 15:02 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +Currently Greenplum Database's JIT implementation has support for accelerating expression evaluation and tuple deforming. Several other operations could be accelerated in the future.
Remove sentence beginning with "Several" 
This is because we never predict the future or make promises in technical manuals; that is Marketing's purview.

2023-01-24 15:05 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +Greenplum Database is very extensible and allows new data types, functions, operators and other database objects to be defined. In fact, the built-in objects are implemented using nearly the same mec
inline is not a verb

2023-01-24 15:08 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +To determine whether JIT compilation should be used, the total estimated cost of a query is used. The estimated cost of the query is compared with the setting of `jit_above_cost`. If the cost is high
Can we make this active voice rather than passive voice: "the total estimated cost of the query is used"

2023-01-24 15:10 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +The configuration parameter [jit](../../../ref_guide/config_params/guc-list.html#jit) determines whether JIT compilation is enabled or disabled. If it is enabled, the decision whether to use or not J
the GUCs => the following server configuration parameters

2023-01-24 15:11 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +Note that setting the JIT cost parameters to ‘0’ will force all queries to be JIT-compiled and as a result slowing down all your queries.
as a result slowing down all your queries => and, as a result, slow down queries

2023-01-24 15:13 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
> +Sets the query cost above which JIT compilation attempts to inline functions and operators. Inlining adds planning time, but can improve execution speed. It is not meaningful to set this to less than
Again, "inline" is not a verb. It's a noun.

2023-01-24 17:33 UTC, dyozie requested changes

2023-01-24 17:33 UTC, dyozie commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +Greenplum Database has builtin support to perform JIT compilation using LLVM when Greenplum Database is built with `--with-llvm`. If you installed Greenplum Database using the `rpm` installation file
For the second sentence, I don't think `--with-llvm` is even an install option (just a compile option).  Probably better to flip this all around and say something like:

"JIT compilation support is enabled with all RPM distributions of Greenplum Database. If you build Greenplum Database from source, you must include the `--with-llvm` build option to include JIT compilation support."

2023-01-24 17:33 UTC, dyozie commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +It is possible to use JIT with both Postgres Optimizer and GPORCA. Since GPORCA and Postgres Optimizer use different models and the relation of their costs varies, you must tune the JIT thresholds ac
Postgres Optimizer -> the Postgres Planner

2023-01-24 17:33 UTC, dyozie commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +Currently Greenplum Database's JIT implementation has support for accelerating expression evaluation and tuple deforming. Several other operations could be accelerated in the future.
has support for -> supports

2023-01-24 17:33 UTC, dyozie commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +With Postgres Optimizer:
Optimizer -> Planner

2023-01-24 17:33 UTC, dyozie commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +Greenplum Database is very extensible and allows new data types, functions, operators and other database objects to be defined. In fact, the built-in objects are implemented using nearly the same mec
"inline" is used as a verb in in the implementation/output messages. But maybe we can clarify this in the actual documentation as "In-line Compilation".

2023-01-24 17:33 UTC, dyozie commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +- [jit_above_cost](../../../ref_guide/config_params/guc-list.html#jit_above_cost): All queries with a higher total cost get JITed, *without* optimization (expensive part), corresponding to -O0. This
Edit to remove use of "JITed" here (x2).  

Also, it's not clear what `-o0` means (this is the only reference to this option).

2023-01-24 17:33 UTC, dyozie commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +- [jit_inline_above_cost](../../../ref_guide/config_params/guc-list.html#jit_inline_above_cost): inlining is tried if query has higher cost.
if query -> if the query

2023-01-24 17:33 UTC, dyozie commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +Whenever the total cost of a query is above these limits, JIT is performed.
JIT -> JIT compilation

(?)

2023-01-24 17:33 UTC, dyozie commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +You should tune these configuration parameters when you enable or disable GPORCA, as the meaning of cost is different for GPORCA and Postgres Optimizer.
Optimizer -> Planner

2023-01-24 17:33 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
> +Sets the query cost above which JIT compilation is activated, if enabled. Performing JIT costs planning time but can accelerate query execution. Setting this to -1 disables JIT compilation.
Replace "if enabled" with "when `jit` is enabled"

2023-01-24 17:33 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
> +Sets the query cost above which JIT compilation is activated, if enabled. Performing JIT costs planning time but can accelerate query execution. Setting this to -1 disables JIT compilation.
JIT costs -> JIT compilation costs

2023-01-25 11:17 UTC, mperezfuster commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +Greenplum Database has builtin support to perform JIT compilation using LLVM when Greenplum Database is built with `--with-llvm`. If you installed Greenplum Database using the `rpm` installation file
Good idea, do you mean a **Note** or actually a note box?

2023-01-25 11:20 UTC, mperezfuster commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +Greenplum Database is very extensible and allows new data types, functions, operators and other database objects to be defined. In fact, the built-in objects are implemented using nearly the same mec
This was ported from Postgres documentation, I am afraid renaming Inlining to something else might affect the actual terminology? If you see the example of the explain analize output, it actually refers to `Inlining false`. I can rephrase it within the description but I think title should remain the same for consistency purposes.

2023-01-25 11:46 UTC, mperezfuster commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +Greenplum Database is very extensible and allows new data types, functions, operators and other database objects to be defined. In fact, the built-in objects are implemented using nearly the same mec
How about changing the title to "In-line Compilation (inlining)" ?

2023-01-25 14:16 UTC, mperezfuster commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +It is possible to use JIT with both Postgres Optimizer and GPORCA. Since GPORCA and Postgres Optimizer use different models and the relation of their costs varies, you must tune the JIT thresholds ac
ok thanks rephrasing this.

2023-01-25 15:50 UTC, lisakowen commented
i think the extensibility section could be useful for extension developers - i.e. someone creating their own fdw for example.  but not sure that the content would belong in the querying section, so may be best to leave it out for now.

2023-01-25 18:51 UTC, dyozie approved these changes

2023-02-09 01:01 UTC, Tao-T commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +The configuration parameter [jit](../../../ref_guide/config_params/guc-list.html#jit) determines whether JIT compilation is enabled or disabled. If it is enabled, the decision whether to use or not J
Maybe we should replace "the decision whether to use or not JIT is cost-based is controlled by the configuration parameters" with

"the decision whether or not to use JIT is cost-based and controlled by the configuration parameters:

2023-02-09 02:11 UTC, Tao-T commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +JIT compilation makes these cost-based decisions at plan time, not execution time. This means that when it is using prepared statements, and a generic plan (see [PREPARE](../../../ref_guide/sql_comma
Not exactly. The usage of JIT GUCs is a bit complex when PREPARE/EXECUTE considered:

GUCs take part in both planning and execution:
- `jit`:
   +  at plan time - as a mask (i.e. take *AND* logic) of other JIT GUCs
   +  at execution time - DO NOT initialize JIT environment if it is not enabled.

GUCs only applied at plan time:
- `jit_above_cost`
- `jit_inline_above_cost`
- `jit_optimize_above_cost`
- `jit_tuple_deforming`
- `jit_expressions`

GUCs read and applied at execution time:
- `jit_provider` : when initializing JIT environment for us
- `jit_dump_bitcode`: when compiling the during ExecutionRun
- `jit_profiling_support`: when creating JIT context
- `jit_debugging_support`: when creating JIT context

I think we can make a list about this for PREPARE/EXECUTION .

2023-02-09 02:39 UTC, Tao-T commented on gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
> +Sets the query cost above which JIT compilation is activated when JIT is enabled. Performing JIT compilation costs planning time but can accelerate query execution. Setting this to -1 disables JIT co
not sure if we should replace  "Setting this to -1 " to "Setting this to negative value (e.g. -1)" here

and for `jit_inline_above_cost`, `jit_optimize_above_cost`

2023-02-09 03:00 UTC, Tao-T commented on gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
> +
The minor GUCs for JIT may also be mentioned:
- `jit_provider` :  the provider (library of JIT driver)to load. (default llvm, other value are not officially supported)
- `jit_tuple_deforming` : Allow JIT compilation of tuple deforming. (default on)
- `jit_expressions` : Allow JIT compilation of expressions. (default on)
- __(the above GUCs are rarely used, better to keep the default values)__
- `jit_dump_bitcode` : Write out LLVM bitcode to facilitate JIT debugging
- `jit_debugging_support` : Register JIT compiled function with debugger
- `jit_profiling_support` : Register JIT compiled function with perf profiler
- __(the above GUCs for developers)__

2023-02-09 11:31 UTC, mperezfuster commented on gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
> +
Thanks Tao, can you please provide the set classification values (master/local, session/system, reload/restart/reinit) for the above GUCs and confirmed the other values are correct:

jit_provider: string, llvmjit, ???
jit_tuple_deforming: boolean, on, ???
jit_expressions: boolean, on, ???
jit_dump_bitcode: boolean, off, ???
jit_debugging_support: boolean, off, ???
jit_profiling_support: boolean, off, ???

2023-02-09 14:57 UTC, Tao-T commented on gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
> +
`jit_provider` : local, session, reload
`jit_tuple_deforming`: master, session, reload
`jit_expressions`: master, session, reload
`jit_dump_bitcode`: master, session, reload
`jit_debugging_support`: master, session, reload
`jit_profiling_support`: master, session, reload

2023-02-09 15:02 UTC, Tao-T commented on gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
> +
And a fix: the default value of `jit_provider` should be llvmjit

2023-02-16 15:49 UTC, lisakowen reviewed
looks good, just some minor comments.

2023-02-16 15:49 UTC, lisakowen commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +JIT compilation support is enabled with all RPM distributions of Greenplum Database. If you build Greenplum Database from source, you must include the `--with-llvm` build option to include JIT compil
not sure about "RPM" here, that is specific to centos i think.  an ubuntu distribution would be a .deb.  do we mean commercial?

2023-02-16 15:49 UTC, lisakowen commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +LLVM has support for optimizing generated code. Some of the optimizations are cheap enough to be performed whenever JIT is used, while others are only beneficial for longer-running queries. See the [
this is the first real mention of LLVM.  do we want to say something like "greenplum database uses LLVM for JIT compilation" or something like that as an intro?

2023-02-16 15:49 UTC, lisakowen commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +    You should tune these configuration parameters when you enable or disable GPORCA, as the meaning of cost is different for GPORCA and Postgres Planner. Note that setting the JIT cost parameters to
slow -> slows ?

2023-02-16 15:49 UTC, lisakowen commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +    - [jit_dump_bitcode](../../../ref_guide/config_params/guc-list.html#jit_dump_bitcode): Writes the generated LLVM IR out to the file system, inside `data_directory`.
what is data_directory?  maybe we should add the link to https://www.postgresql.org/docs/12/runtime-config-file-locations.html#GUC-DATA-DIRECTORY like in the postgres docs.

2023-02-16 15:49 UTC, lisakowen commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +    - [jit_debugging_support](../../../ref_guide/config_params/guc-list.html#jit_debugging_support): If LLVM has the required functionality, registers generated functions with `GDB`.
i think GDB is a term for the debugger, and `gdb` is the actual command name.  so no need for code font for GDB .

2023-02-16 15:49 UTC, lisakowen commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +In the above examples, the configuration parameter `jit_above_cost` was modified so it would trigger JIT compilation. The use of JIT affects the cost of the plan, which can or cannot be bigger than t
i don't think there were any examples above this statement.

2023-02-16 15:49 UTC, lisakowen commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +Note that the output from `EXPLAIN` provides information on JIT such as the slice average timing spent in JIT, what segment the maximum vector comes from, or how many JIT functions are created and to
a timing problems -> a timing problem ?

2023-02-16 15:49 UTC, lisakowen commented on gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
> +If LLVM has the required functionality, register generated functions with `GDB`. This makes debugging easier. The default setting is off. This parameter can only be set at server start.
no need to code font GDB here.  also should we code-font `off` (here and below)?

question:  if this parameter (and a few of the ones below) can be set only at server start, should the set classification include reload?

2023-02-16 15:49 UTC, lisakowen commented on gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
> +Sets the query cost above which JIT compilation is activated when JIT is enabled. Performing JIT compilation costs planning time but can accelerate query execution. Note that setting the JIT cost par
slow -> slows ?

2023-02-17 01:59 UTC, adam8157 commented
Is the "JIST" in the subject a typo?

2023-02-17 09:23 UTC, mperezfuster commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +JIT compilation support is enabled with all RPM distributions of Greenplum Database. If you build Greenplum Database from source, you must include the `--with-llvm` build option to include JIT compil
I actually had the same question but Tao said that the primary targeted OSs for gp7 are Rocky8/RHEL8/Oracle 8 (and not debian/ubuntu etc) and all of them are managed by RPM so we should specify it this way, would you agree?

2023-02-17 09:24 UTC, mperezfuster commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +LLVM has support for optimizing generated code. Some of the optimizations are cheap enough to be performed whenever JIT is used, while others are only beneficial for longer-running queries. See the [
thanks for pointing this out, I actually had something and removed it when I started referring only to the rpm packages

2023-02-17 09:32 UTC, mperezfuster commented on gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
> +If LLVM has the required functionality, register generated functions with `GDB`. This makes debugging easier. The default setting is off. This parameter can only be set at server start.
@Tao-T can you answer Lisa's question regarding set classification parameter as reload when these parameters are set at server start?

2023-02-17 09:33 UTC, mperezfuster commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +In the above examples, the configuration parameter `jit_above_cost` was modified so it would trigger JIT compilation. The use of JIT affects the cost of the plan, which can or cannot be bigger than t
sorry I moved the sentence from the bottom of the example to the top, my bad!

2023-02-17 16:30 UTC, dyozie commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +JIT compilation support is enabled with all RPM distributions of Greenplum Database. If you build Greenplum Database from source, you must include the `--with-llvm` build option to include JIT compil
RPM is specific to all RHEL-like builds, and those are the only ones currently planned for Greenplum 7. I guess saying "RPM" here is maybe a bit redundant, I guess, but it does imply that if you have a Greenplum RPM (either commercial or open source) then it's already compiled with JIT support built-in, so probably fine as-is.

2023-02-17 17:42 UTC, Tao-T commented on gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
> +If LLVM has the required functionality, emit the data needed to allow `perf` command to profile functions generated by JIT. This writes out files to `~/.debug/jit/`; you are responsible for performin
It's a `SU_BACKEND` guc.  so not "This parameter can only be set at server start." but
"This parameter can only be set at server start or when a client connection start (e.g. via PGOPTIONS)
And only by the superuser of gp.

2023-02-17 17:48 UTC, Tao-T commented on gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
> +Indicates the name of the JIT provider (library of JIT driver) to load. The default is `llvmjit`, any other value is not officially supported. This parameter can only be set at server start.
Also only by superuser of gp.

2023-02-17 17:54 UTC, Tao-T commented on gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
> +If LLVM has the required functionality, register generated functions with `GDB`. This makes debugging easier. The default setting is off. This parameter can only be set at server start.
only by superuser, and "This parameter can only be set at server start" or when a client connection start (e.g. via PGOPTIONS)

2023-02-17 19:19 UTC, Tao-T commented on gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
> +If LLVM has the required functionality, register generated functions with `GDB`. This makes debugging easier. The default setting is off. This parameter can only be set at server start.
Just checked again the meaning of categories here (https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/mireia/greenplum-database/GUID-ref_guide-config_params-guc_config.html):

1) `master` should be replaced to `coordinator` for
  - `gp_explain_jit`
  
2) `superuser` should be added to some JIT gucs:
  - `jit_debugging_support`
  - `jit_profiling_support`
  - `jit_provider`

3) the definition of `session` and `system` seems to be hard to cover our usage:
  - maybe we should add new items for the field?

4) `restart` should be used for `jit_provider`, for others can alternatively be tuned when start a client-backend connection, `reload` still fit the case.

2023-02-17 20:21 UTC, Tao-T commented on gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
> +If LLVM has the required functionality, emit the data needed to allow `perf` command to profile functions generated by JIT. This writes out files to `~/.debug/jit/`; you are responsible for performin
The location of files can be refered to the implementation of LLVM:

if we have an environment variable `JITDUMPDIR` set and load by gp, the output files will be written to sub directory `.debug/jit/` under directory `JITDUMPDIR`. Otherwise in sub directory `.debug/jit/` under `home directory`

2023-02-17 20:35 UTC, Tao-T commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +    - [gp_explain_jit](../../../ref_guide/config_params/guc-list.html#gp_explain_jit): Enables the display of summarized JIT information from all query executions when running the `EXPLAIN` command.
`gp_explain_jit`?  Not considered in this step.

2023-02-17 21:03 UTC, Tao-T commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +    - The estimated cost of the query is higher than the value of the configuration parameter [jit_above_cost](../../../ref_guide/config_params/guc-list.html#jit_above_cost).
Only `jit` and `jit_above_cost` take part in the 1st round of decision.
The rest mentioned in `Planner Stage` Part are used in the 2nd round. And the internal order is not important.

Only when all 3 stages are treated as a whole, `jit_expressions` is a key factor of JIT performing.

2023-02-20 10:22 UTC, mperezfuster commented on gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
> +    - [gp_explain_jit](../../../ref_guide/config_params/guc-list.html#gp_explain_jit): Enables the display of summarized JIT information from all query executions when running the `EXPLAIN` command.
@Tao-T should I include it somewhere else on this page?

2023-02-21 15:05 UTC, Tao-T approved these changes

2023-02-21 18:04 UTC, merged