Vacuum enhancements
greenplum-db/gpdb pull request #14842
Opened 2023-01-26 14:38 UTC by mperezfuster

Added references to the following VACUUM enhancements:

1. Avoid scanning pages unnecessarily. New VACUUM option `DISABLE_PAGE_SKIPPING`.
- This change adds a VACUUM option `DISABLE_PAGE_SKIPPING`.
-  The option `--disable-page-skipping` has also been added to the vacuumdb command.

2. Add the ability to skip VACUUM and ANALYZE operations on tables that cannot be locked immediately. New option `SKIP_LOCKED` for VACUUM and ANALYZE commands.
- This change adds a VACUUM and ANALYZE option `SKIP_LOCKED`
-  The option `--skip-locked` has also been added to the vacuumdb and analyzedb commands.

3. Allow VACUUM to skip index cleanup with VACUUM option `INDEX_CLEANUP`
	- This change adds a VACUUM command option `INDEX_CLEANUP` .
	- It also adds a Rel option `vacuum_index_cleanup` for pg_class. 

4. Avoid useless heap-truncation attempts during VACUUM
	There is no new content for this change, only Release Note content.

5. Allow VACUUM to avoid unnecessary index scans 
	- New GUC: vacuum_cleanup_index_scale_factor

Questions for writers/R&D:

- Any other pages that need update you think?

For change number 3:
 -  I cannot find anywhere to reference the addition of the reloption `vacuum_index_cleanup`. I presume we don't document these?
- I was not able to find any reference to the new option `INDEX_CLEANUP` for the wraparound command `vacuumdb`. Has this been included?

For change number 5:
- What are the set classification values for the GUC `vacuum_cleanup_index_scale_factor`? Ie master/local, session/system, reload/restart/reinit.

Review sites:
https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/mireia-vacuum/greenplum-database/GUID-ref_guide-sql_commands-VACUUM.html
https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/mireia-vacuum/greenplum-database/GUID-ref_guide-sql_commands-ANALYZE.html
https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/mireia-vacuum/greenplum-database/GUID-utility_guide-ref-vacuumdb.html
https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/mireia-vacuum/greenplum-database/GUID-utility_guide-ref-analyzedb.html
https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/mireia-vacuum/greenplum-database/GUID-ref_guide-config_params-guc-list.html

2023-01-26 17:59 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/ref_guide/sql_commands/VACUUM.html.md
> +:   Specifies that `VACUUM` should attempt to remove index entries pointing to dead tuples. This is normally the desired behavior and is the default unless you override it by setting `vacuum_index_cl
However, you do not perform => However, if you do not perform

2023-01-26 18:00 UTC, VMWareJennyBeth requested changes
Just one correction, otherwise perfect!

2023-01-26 18:57 UTC, dyozie requested changes

2023-01-26 18:57 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/sql_commands/VACUUM.html.md
> +:   Specifies that `VACUUM` should attempt to remove index entries pointing to dead tuples. This is normally the desired behavior and is the default unless you override it by setting `vacuum_index_cl
If you use if the `FULL` option -> If you use the `FULL` option

2023-01-30 16:41 UTC, dyozie approved these changes

2023-02-01 23:42 UTC, lisakowen approved these changes
looks good, a few minor comments.

2023-02-01 23:42 UTC, lisakowen commented on gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
> +## <a id="vacuum_cleanup_index_scale_factor"></a>vacuum_cleanup_index_scale_factor
do we want to include the other info about this guc on the https://www.postgresql.org/docs/12/runtime-config-client.html page?  or is it not applicable?

2023-02-01 23:42 UTC, lisakowen commented on gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
> +- [vacuum_cleanup_index_scale_factor](guc-list.html#vacuum_cleanup_index_scale_factor)
prob move this above vacuum_freeze_min_age if we are listing alphabetically.

2023-02-02 09:20 UTC, zxuejing approved these changes

2023-02-03 18:50 UTC, merged