Docs cgroup version
greenplum-db/gpdb pull request #14863
Opened 2023-01-30 14:18 UTC by mperezfuster

Modified documentation to specify that Greenplum 6.x only supports cgroup v1.
This PR only is intended to merge to 6X_STABLE as GPDB 7 will support v2.

Review site:

https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/mireia-cgroup/greenplum-database/GUID-admin_guide-workload_mgmt_resgroups.html#topic71717999

2023-01-30 14:23 UTC, ashwinstar commented
LGTM. @kainwen reads fine?

2023-01-30 16:22 UTC, mperezfuster commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +> **Note** There are two versions of cgroups in Linux: cgroup v1 and cgroup v2. Greenplum Database only supports cgroup v1. Follow the steps below to make sure that your system is mounting the `cgrou
It's a filesystem called cgroups according to the Red Hat documentation: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/managing_monitoring_and_updating_the_kernel/assembly_using-cgroupfs-to-manually-manage-cgroups_managing-monitoring-and-updating-the-kernel#proc_mounting-cgroups-v1_assembly_using-cgroupfs-to-manually-manage-cgroups

2023-01-30 16:35 UTC, lisakowen commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +> **Note** There are two versions of cgroups in Linux: cgroup v1 and cgroup v2. Greenplum Database only supports cgroup v1. Follow the steps below to make sure that your system is mounting the `cgrou
ok.  (those are redhat 9 docs.)  in any case, i was confused as to why it is a literal (code font) because it is not something that the user enters, nor does it appear to be part of the actual filesystem path per the examples you added later on the page.

2023-01-30 17:11 UTC, mperezfuster commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +> **Note** There are two versions of cgroups in Linux: cgroup v1 and cgroup v2. Greenplum Database only supports cgroup v1. Follow the steps below to make sure that your system is mounting the `cgrou
Thanks, this makes me think that there might be no scenario in RHEL 6/7 where cgroups v2 could be enabled?
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/8.0_release_notes/index
https://www.redhat.com/en/blog/world-domination-cgroups-rhel-8-welcome-cgroups-v2

So maybe just the Note box should be enough. At least for Red Hat, I am planning on adding the Ubuntu instructions for cgroups next.

2023-01-30 17:36 UTC, mperezfuster commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +> **Note** There are two versions of cgroups in Linux: cgroup v1 and cgroup v2. Greenplum Database only supports cgroup v1. Follow the steps below to make sure that your system is mounting the `cgrou
Sorry, here it is for version 8:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_monitoring_and_updating_the_kernel/using-cgroups-v2-to-control-distribution-of-cpu-time-for-applications_managing-monitoring-and-updating-the-kernel#doc-wrapper
"During the boot process, RHEL 8 mounts the `cgroup-v1` virtual filesystem by default."
I used the same naming for the filesystem, but if it makes more sense I won't use the code font. Thank you!

2023-01-30 22:05 UTC, dyozie requested changes

2023-01-30 22:05 UTC, dyozie commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +> **Note** There are two versions of cgroups in Linux: cgroup v1 and cgroup v2. Greenplum Database only supports cgroup v1. Follow the steps below to make sure that your system is mounting the `cgrou
It looks like you have an extra space in the name:  `cgroup- v1` instead of `cgroup-v1`

2023-01-30 22:05 UTC, dyozie commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +> **Note** There are two versions of cgroups in Linux: cgroup v1 and cgroup v2. Greenplum Database only supports cgroup v1. Follow the steps below to make sure that your system is mounting the `cgrou
This note should only call out RHEL8, as that's the only version that has the option of v2.

2023-01-30 22:05 UTC, dyozie commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +1. Make sure that you configured the system to mount the `cgroups-v1` filesystem by default during system boot by running the following command:
Make sure -> If you are using RHEL8, make sure

2023-02-01 11:54 UTC, mperezfuster commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +1. Make sure that you configured the system to mount the `cgroups-v1` filesystem by default during system boot by running the following command:
should I also include reference to CentOS 8.x?

2023-02-02 00:43 UTC, dyozie commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +1. Make sure that you configured the system to mount the `cgroups-v1` filesystem by default during system boot by running the following command:
Sorry - just noticed this.  Don't include CentOS (Or Oracle or Rocky) in the 8.x mentions yet.  Only Red Hat is currently validated.

2023-02-06 00:55 UTC, SmartKeyerror approved these changes
LGTM.

2023-02-13 21:28 UTC, dyozie approved these changes

2023-02-13 21:28 UTC, merged