gpcheckperf: Fix memory calculation function
greenplum-db/gpdb pull request #14865
Opened 2023-01-30 18:52 UTC by jnihal

The `getMemory()` function in gpcheckperf returns `0` value when it is not supposed to. This is because the `run()` method returns a return code of `0` when it runs successfully, and in the `getMemory()` function we check this return code as `if not ok` which results in `True` instead of `False` and causes the `getMemory()` function to return `0` because it assumes the `run()` method failed even though it ran successfully. This commit fixes this by changing the check from `if not ok` to `if ok != 0`.

Also added unit test cases to test the `getMemory()` function and added a main section to the gpcheckperf code.

2023-01-31 14:34 UTC, shrakesh commented
Please elaborate more on the PR description and provide an example to better understand the function output(type) before and after the changes made in the code.

2023-02-01 08:43 UTC, ravoorsh commented
> Please elaborate more on the PR description and provide an example to better understand the function output(type) before and after the changes made in the code.

+1

2023-02-08 17:47 UTC, shrakesh requested changes

2023-02-08 17:47 UTC, shrakesh commented on gpMgmt/bin/gpcheckperf
> +        else:
duplicate code(line 145-146 and line 156-157) can be avoided and we can have a default return at the end of the function.

2023-02-08 17:47 UTC, shrakesh commented on gpMgmt/bin/gpcheckperf
>      if getPlatform() == 'linux':
can we store output from getPlatform() and use that it will avoid calling twice the same function?

2023-02-08 17:47 UTC, shrakesh commented on gpMgmt/bin/gpcheckperf
> +    elif getPlatform() == 'darwin':
any specific reason to replace if with elif ?

2023-02-08 17:47 UTC, shrakesh commented on gpMgmt/bin/gpcheckperf
> +            return -1
IMO it would be good to return None instead of -1.

2023-02-08 17:47 UTC, shrakesh commented on gpMgmt/bin/gpcheckperf
> +        if system_mem_size == -1:
In some hypothetical corner case, lets say getMemory() returns 0.  as we are checking for -1, and in the else part, it will become the scene of the original issue. I think checking Not None would benefit here.

2023-02-08 17:47 UTC, shrakesh commented on gpMgmt/bin/gppylib/test/unit/test_unit_gpcheckperf.py
> +        actual_result = self.subject.getMemory()
we can also add a corner case of MemTotal returning 0kB on successful command execution.

2023-02-08 17:47 UTC, shrakesh commented on gpMgmt/bin/gpcheckperf
> +            sys.exit('[Error] Unable to get system memory size. Instead, you can use the -S option to provide the file size value.')
can we cover these newly added workflows to behave test case? we should add some for gpcheckperf -S option as well.

2023-02-13 07:13 UTC, jnihal commented on gpMgmt/bin/gpcheckperf
> +        else:
Added a default return value at the end.

2023-02-13 07:14 UTC, jnihal commented on gpMgmt/bin/gpcheckperf
> +    elif getPlatform() == 'darwin':
I added an else part at the end, so made the change. But now since we are returning a default value there is no need for it. Will revert it back.

2023-02-13 07:14 UTC, jnihal commented on gpMgmt/bin/gpcheckperf
> +            return -1
Agreed, returning a `None` would be better.

2023-02-13 07:17 UTC, jnihal commented on gpMgmt/bin/gpcheckperf
> +        if system_mem_size == -1:
Made a change in the getMemory() function so that it never returns a 0 value which will make sure the issue is avoided

2023-02-13 07:17 UTC, jnihal commented on gpMgmt/bin/gppylib/test/unit/test_unit_gpcheckperf.py
> +        actual_result = self.subject.getMemory()
Added the test

2023-02-13 14:11 UTC, shrakesh commented on gpMgmt/bin/gpcheckperf
> +        if ok != 0:
can we change ok to rc as this indicates the return code from the command?

2023-02-13 14:36 UTC, shrakesh commented on gpMgmt/bin/gpcheckperf
> +        if system_mem_size != None:
more preferred way 
if system_mem_size is not None:

2023-02-13 14:43 UTC, shrakesh approved these changes
Approving with some minor suggestions.

2023-02-13 14:55 UTC, Annu149 commented on gpMgmt/bin/gpcheckperf
> +            sys.exit('[Error] Unable to get system memory size. Instead, you can use the -S option to provide the file size value.')
Shouldn't we assert this error message in behave testcase and unit testcase?

2023-02-13 15:21 UTC, Annu149 commented on gpMgmt/test/behave/mgmt_utils/gpcheckperf.feature
> +  Scenario: gpcheckperf runs with -S option and prints a warning message
What if we provide an invalid value with -S? I guess parseMemorySize() function will throw an exception. We should add that scenario as well

2023-02-13 15:43 UTC, Annu149 commented on gpMgmt/test/behave/mgmt_utils/gpcheckperf.feature
> +    When  the user runs "gpcheckperf -h localhost -rd -d /tmp -S 1GB"
we should give space between -r and d for better understanding "gpcheckperf -h localhost -r d -d /tmp -S 1GB"

2023-02-13 16:24 UTC, ravoorsh requested changes

2023-02-13 16:24 UTC, ravoorsh commented on gpMgmt/bin/gpcheckperf
> +            sys.exit('[Error] Unable to get system memory size. Instead, you can use the -S option to provide the file size value.')
Please follow the Postgres guidelines for error messages 

Primary error messages: Do not capitalize the first letter. Do not end a message with a period. Do not even think about ending a message with an exclamation point.

Consider using "could not" instead of Unable

2023-02-15 04:13 UTC, jnihal commented on gpMgmt/test/behave/mgmt_utils/gpcheckperf.feature
> +  Scenario: gpcheckperf runs with -S option and prints a warning message
Added the scenario

2023-02-15 04:15 UTC, jnihal commented on gpMgmt/bin/gpcheckperf
> +            sys.exit('[Error] Unable to get system memory size. Instead, you can use the -S option to provide the file size value.')
> Shouldn't we assert this error message in behave testcase and unit testcase?

It is not possible to write a behave test case, because this error occurs only when the system memory size would be equal to 0.

2023-02-17 06:17 UTC, Annu149 approved these changes
Looks good to me

2023-02-20 06:48 UTC, ravoorsh approved these changes

2023-03-02 16:41 UTC, jmcatamney approved these changes

2023-03-06 06:01 UTC, merged

2023-03-06 06:01 UTC, shrakesh commented
merged on behalf of nihal.