DOCS: Feature/fix merge confusion plus improvements to storage params doc
greenplum-db/gpdb pull request #14904
Opened 2023-02-03 23:17 UTC by VMWareJennyBeth

2023-02-07 18:18 UTC, dyozie requested changes

2023-02-07 18:18 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/sql_commands/ALTER_TABLE.html.md
> +Add a column and change the table's access method, simultaneously:
Seems like we can remove "simultaneously" here.

2023-02-07 18:18 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/sql_commands/ALTER_TABLE.html.md
> +Add a column and change table storage parameters simultaneously:
Same here.

2023-02-07 18:18 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLE.html.md
> +and storage\_parameter for a table or partition is:
storage\_parameter -> `<storage_parameter>`

2023-02-07 18:18 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLE.html.md
> +[ WITH ( <storage_parameter>=<value> [, ... ] ) ]
spacing around = and [

2023-02-07 18:18 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLE.html.md
>       [ EVERY ([<datatype>] [<number | >INTERVAL] '<interval_value>') ]
<number | >INTERVAL -> <number> | INTERVAL

(I realize this has nothing to do with your changes, but I can't unsee the error here :)

2023-02-07 18:18 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLE.html.md
> +[ WITH ( <storage_parameter>=<value> [, ... ] ) ]
spacing around = and [

2023-02-07 18:18 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLE.html.md
> +The `WITH` clause can specify storage parameters for tables, and for indexes associated with a `UNIQUE` or `PRIMARY` constraint. Storage parameters for indexes are documented on the [CREATE INDEX](CR
on a particular partition -> for a partitcular partition

2023-02-07 18:18 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLE.html.md
> +:   **appendoptimized** — Set to `TRUE` to create the table as an append-optimized table. If `FALSE` or not declared, the table will be created as a regular heap-storage table.
This should be formatted as a regular deflist.  Each item should look roughly like:

appendoptimized
:    Set to `TRUE` to ...

2023-02-07 18:18 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLE.html.md
> +:   **compresstype** — Set to `ZLIB` \(the default\), `ZSTD`, `RLE_TYPE`, or `QUICKLZ`1 to specify the type of compression used. The value `NONE` deactivates compression. Zstd provides for both speed
1 -> <sup>1</sup>

2023-02-07 18:18 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLE.html.md
> +    > **Note** 1QuickLZ compression is available only in the commercial release of VMware Greenplum.
sup>1</sup>

2023-02-07 18:18 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLE.html.md
> +:   **compresstype** — Set to `ZLIB` \(the default\), `ZSTD`, `RLE_TYPE`, or `QUICKLZ`1 to specify the type of compression used. The value `NONE` deactivates compression. Zstd provides for both speed
or a good -> and a good

2023-02-07 18:18 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLE.html.md
> +    The value `RLE_TYPE`, which is supported only if `orientation`=`column` is specified, enables the run-length encoding \(RLE\) compression algorithm. RLE compresses data better than the Zstd, zlib
These follow-on deflist paragraphs should start with:

:   

(A colon and 4 spaces).

2023-02-08 00:48 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLE.html.md
>       [ EVERY ([<datatype>] [<number | >INTERVAL] '<interval_value>') ]
This occurs in multiple places. Are you sure it's incorrect?

2023-02-08 00:59 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLE.html.md
> +    > **Note** 1QuickLZ compression is available only in the commercial release of VMware Greenplum.
I recognize this as related to footnotes in Markdown but I don't know exactly where you intend this to go.

2023-02-08 01:00 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLE.html.md
> +    The value `RLE_TYPE`, which is supported only if `orientation`=`column` is specified, enables the run-length encoding \(RLE\) compression algorithm. RLE compresses data better than the Zstd, zlib
I need you to explain this comment. You've just requested above to do a colon followed by a single space. Now you're talking about four spaces. Which is it?

2023-02-13 21:26 UTC, dyozie approved these changes

2023-02-13 21:26 UTC, merged