DOCS: Add topic on migrating from OSS GPDB to commercial GPDB
greenplum-db/gpdb pull request #15043
Opened 2023-02-23 19:10 UTC by VMWareJennyBeth

2023-02-24 21:17 UTC, dyozie requested changes

2023-02-24 21:17 UTC, dyozie commented on gpdb-doc/markdown/install_guide/migrate-oss-to-vmware.html.md
> +- Review the Greenplum Database [Platform Requirements topic](platform-requirements-overview.html) to verify that you have all software you need in place to successfully migrate to VMware Greenplum.
all software -> all the software

2023-02-24 21:17 UTC, dyozie commented on gpdb-doc/markdown/install_guide/migrate-oss-to-vmware.html.md
> +## <a id="steps"></a>Steps to Migrate
Steps to Migrate -> Procedure

2023-02-24 21:17 UTC, dyozie commented on gpdb-doc/markdown/install_guide/migrate-oss-to-vmware.html.md
> +Migrating from an open source Greenplum Database to commercial VMware Greenplum involves stopping the open source Greenplum Database, replacing the Greenplum Database software, and restarting the dat
an open source -> Open Source
If your open source Greenplum Database includes -> If your Open Source Greenplum Database installation includes

"there are additional requirements, as summarized in the [Prerequisites](#prerequisites) section." Again, we can't leave those in the prerequisites section.  Just add them as a final step in the procedure.

2023-02-24 21:17 UTC, dyozie commented on gpdb-doc/markdown/install_guide/migrate-oss-to-vmware.html.md
> +Here are the detailed migration steps:
there are additional requirements, as summarized in the [Prerequisites](#prerequisites) section. -> Follow these steps to migrate Open Source Greenplum Database to VMware Greenplum:

2023-02-24 21:17 UTC, dyozie commented on gpdb-doc/markdown/install_guide/migrate-oss-to-vmware.html.md
> +1. Log into your Greenplum Database coordinator host as the Greenplum administrative user:
maybe add "Open Source" here for clarity?

2023-02-24 21:17 UTC, dyozie commented on gpdb-doc/markdown/install_guide/migrate-oss-to-vmware.html.md
> +```
These follow-on commands should be nested by 4 spaces to stay part of the steps.

2023-02-24 21:17 UTC, dyozie commented on gpdb-doc/markdown/install_guide/migrate-oss-to-vmware.html.md
> +3. Download the commercial VMware Greenplum package from [VMware Tanzu Network](https://network.pivotal.io/), and then copy the package to the `gpadmin` user's home directory on each coordinator, sta
can probably remove "commercial" from here on out, since the product name is qualified with VMware.

2023-02-24 21:17 UTC, dyozie commented on gpdb-doc/markdown/install_guide/migrate-oss-to-vmware.html.md
> +# apt install ./greenplum-db-<version>-<platform>.deb
This should also include `sudo`

2023-02-24 21:17 UTC, dyozie commented on gpdb-doc/markdown/install_guide/migrate-oss-to-vmware.html.md
> +3. Download the commercial VMware Greenplum package from [VMware Tanzu Network](https://network.pivotal.io/), and then copy the package to the `gpadmin` user's home directory on each coordinator, sta
, and then copy the package -> and copy it

2023-02-24 21:17 UTC, dyozie commented on gpdb-doc/markdown/install_guide/migrate-oss-to-vmware.html.md
> +5. If you used `rpm` to install Greenplum Database to a non-default location on RHEL/CentOS systems, run `rpm` on each host to replace the software and specify the same custom installation directory
to install Greenplum Database -> to install Open Source Greenplum Database

2023-02-24 21:17 UTC, dyozie commented on gpdb-doc/markdown/install_guide/migrate-oss-to-vmware.html.md
> +9. Once all segment hosts have been updated, log into the Greenplum databse coordinator as the `gpadmin` user and restart your Greenplum Database system:
databse -> Database

2023-02-24 21:17 UTC, dyozie commented on gpdb-doc/markdown/install_guide/migrate-oss-to-vmware.html.md
> +The output version string should no longer include "open source".
11. Re-install any Greenplum Database extensions that you used with the earlier Open Source Greenplum Database installation.

2023-02-24 23:18 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/install_guide/migrate-oss-to-vmware.html.md
> +# apt install ./greenplum-db-<version>-<platform>.deb
Good catch!

2023-02-27 21:31 UTC, dyozie approved these changes

2023-02-27 21:31 UTC, merged