DOCS: Add datatypes info for timestamp9 extension and add topic for isn extension
greenplum-db/gpdb pull request #15086
Opened 2023-02-28 23:11 UTC by VMWareJennyBeth

2023-03-01 02:35 UTC, higuoxing reviewed
LGTM for the timestamp9 part with some undetermined values. I will help correct the documentation once they are determined.

2023-03-01 02:35 UTC, higuoxing commented on gpdb-doc/markdown/ref_guide/modules/timestamp9.html.md
> +Refer to the [timestamp9 github documentation](https://github.com/fvannee/timestamp9) for detailed information about using the module.
Documentation in https://github.com/fvannee/timestamp9 doesn't contain these two types: `timestamp9_ltz` and `timestamp9_ntz`. We have to add documentation for these two types later.

2023-03-01 02:35 UTC, higuoxing commented on gpdb-doc/markdown/ref_guide/modules/timestamp9.html.md
> +|`TIMESTAMP9_NTZ`|8 bytes|Timestamp without time zone. |2262-04-11 00:00:00.000000000 +0000 |1970-01-01 00:00:00.000000000 +0000 | 1 nanosecond|
The `Max Value` and `Min Value` are not very clear in the documentation in https://github.com/fvannee/timestamp9. I'm not 100% for sure the value is correct. I'm working on a patch to that repo to help address this issue. I can help correct the value in our documentation once the issue is addressed.

2023-03-01 02:35 UTC, higuoxing commented on gpdb-doc/markdown/ref_guide/modules/timestamp9.html.md
> +The Greenplum Database `timestamp9` module is based on version 1.2.0 of the `timestamp9` module used with PostgreSQL.
The version of timestamp9 is bumped to 1.3.0 recently. I'm not sure if we're going to release 1.2.0 or 1.3.0 for Greenplum 6.24 release. I will help correct the version number once it's determined.

2023-03-01 03:42 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/ref_guide/modules/timestamp9.html.md
> +Refer to the [timestamp9 github documentation](https://github.com/fvannee/timestamp9) for detailed information about using the module.
Sounds good.

2023-03-01 03:43 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/ref_guide/modules/timestamp9.html.md
> +|`TIMESTAMP9_NTZ`|8 bytes|Timestamp without time zone. |2262-04-11 00:00:00.000000000 +0000 |1970-01-01 00:00:00.000000000 +0000 | 1 nanosecond|
Okay, thank you.

2023-03-01 03:43 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/ref_guide/modules/timestamp9.html.md
> +The Greenplum Database `timestamp9` module is based on version 1.2.0 of the `timestamp9` module used with PostgreSQL.
We're doing 1.2.0 for 6.24.

2023-03-01 09:46 UTC, zhrt123 commented on gpdb-doc/markdown/ref_guide/modules/isn.html.md
> +The Greenplum Database `isn` module is equivalent to version XXX of the `isn` module used with PostgreSQL. There are no Greenplum Database or MPP-specific considerations for the module.
For GPDB7: the isn module is in PostgreSQL 12, whose doc is https://www.postgresql.org/docs/12/isn.html. The version of isn is 1.2
For GPDB6: the isn module is in PostGreSQL 9.4, whose doc is https://www.postgresql.org/docs/9.4/isn.html. The version of isn is 1.0

2023-03-15 01:56 UTC, higuoxing commented on gpdb-doc/markdown/ref_guide/modules/timestamp9.html.md
> +|`TIMESTAMP9_NTZ`|8 bytes|Timestamp without time zone. |2262-04-11 00:00:00.000000000 +0000 |1970-01-01 00:00:00.000000000 +0000 | 1 nanosecond|
Hi, in our released extension, the value range for the timestamp is as follows.

```suggestion
|`TIMESTAMP9`|8 bytes|Like TIMESTAMP9_LTZ. Timestamp with local time zone. |2261-12-31 23:59:59.999999999 +0000 |1700-01-01 00:00:00.000000000 +0000 | 1 nanosecond |
|`TIMESTAMP9_LTZ`|8 bytes|Timestamp with local time zone. |2261-12-31 23:59:59.999999999 +0000 |1700-01-01 00:00:00.000000000 +0000 | 1 nanosecond |
|`TIMESTAMP9_NTZ`|8 bytes|Timestamp without time zone. |2261-12-31 23:59:59.999999999 |1700-01-01 00:00:00.000000000 | 1 nanosecond|
```

2023-03-15 16:04 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/ref_guide/modules/timestamp9.html.md
> +|`TIMESTAMP9_NTZ`|8 bytes|Timestamp without time zone. |2262-04-11 00:00:00.000000000 +0000 |1970-01-01 00:00:00.000000000 +0000 | 1 nanosecond|
Thanks, @higuoxing I will apply this update.

2023-03-16 01:38 UTC, zhrt123 commented on gpdb-doc/markdown/ref_guide/modules/isn.html.md
> +The Greenplum Database `isn` module is equivalent to version XXX of the `isn` module used with PostgreSQL. There are no Greenplum Database or MPP-specific considerations for the module.
Should we change `xxx` to `1.2`?

2023-03-16 18:24 UTC, dyozie requested changes

2023-03-16 18:24 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/modules/isn.html.md
> +The Greenplum Database `isn` module is equivalent to version XXX of the `isn` module used with PostgreSQL. There are no Greenplum Database or MPP-specific considerations for the module.
@VMWareJennyBeth still need to commit the above change.

2023-03-16 22:41 UTC, dyozie approved these changes

2023-03-16 22:41 UTC, merged