Adding README.macOS.arm.bash for arm based macOS for 7x
greenplum-db/gpdb pull request #15125
Opened 2023-03-03 11:43 UTC by Shakarada

[GPR-1231]

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2023-03-06 04:30 UTC, shrakesh commented
@Shakarada can you please add the pr description

2023-03-06 07:25 UTC, ravoorsh commented
@Shakarada @mounikagunnam 

The PR description needs to be more elaborate. 
Remove the confluence page, as its internal.
Explain clearly what was the problem, RCA and solution.
Remove the diff file added.
Mention the issues seen and fixed. 

You can remove for 7x from the title.

2023-03-07 04:27 UTC, shrakesh commented on README.macOS.arm.bash
> +	echo "INFO: xerces is not installed, Installing...."
do we require both the installation of xerces-c. here is what I can see we are installing Greenplum patched xerces-c and again we are installing the generic latest one via brew.

2023-03-07 12:30 UTC, jnihal commented on README.macOS.arm.bash
> +ln -s /opt/homebrew/Cellar/python@3.9/$python_version/bin/pip3.9 /opt/homebrew/bin/pip3
I think we can use the `brew link --force python@3.9` command here to link the python version.

2023-03-07 12:30 UTC, jnihal commented on README.macOS.arm.bash
> +pip3 install --user -r python-dependencies.txt
Do we need this message given we are already running this above? https://github.com/greenplum-db/gpdb/blob/1d5c31437f5486909a52d0384ab1348740f409da/README.macOS.arm.bash#L57

2023-03-07 18:54 UTC, ravoorsh requested changes

2023-03-15 17:32 UTC, Shakarada commented on README.macOS.arm.bash
> +ln -s /opt/homebrew/Cellar/python@3.9/$python_version/bin/pip3.9 /opt/homebrew/bin/pip3
This soft link we are using to default point to brew installed python instead of /usr/local/python for python3 (i.e which python)

The below command doesn't help in the scenario to link python3 to brew installed python . 
brew link --force python@3.9
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################## 100.0%
Warning: Already linked: /opt/homebrew/Cellar/python@3.9/3.9.16
To relink, run:
  brew unlink python@3.9 && brew link python@3.9
  
[~/Downloads:  none]$ which python3
/usr/local/bin/python3
[~/Downloads:  none]$ ls -lrt /usr/local/bin/python3
lrwxr-xr-x  1 root  wheel  53 Oct 28 13:31 /usr/local/bin/python3 -> /Users/shakarada/.pyenv/versions/3.9.14/bin/python3.9

with this its pointing to /usr/local/bin/

2023-03-15 17:39 UTC, Shakarada commented on README.macOS.arm.bash
> +pip3 install --user -r python-dependencies.txt
Yes because this is a note or heads-up  to the installer
1. we are executing source greenplum_path.sh after the configure step till then we wont be having the file in /usr/local/gpdb/
2. pip dependencies are in python-dependencies.txt  sometime not installed completely so we make sure we install these before the create cluster

2023-03-16 06:07 UTC, mounikagunnam commented on README.macOS.arm.bash
> +	echo "INFO: xerces is not installed, Installing...."
Removing brew install xerces-c

2023-03-30 12:02 UTC, jnihal approved these changes

2023-04-03 08:56 UTC, ravoorsh approved these changes

2023-04-14 08:25 UTC, shrakesh commented on README.macOS.arm.bash
> +export COORDINATOR_DATA_DIRECTORY=/Users/`whoami`/workspace/gpdb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1
IMO the COORDINATOR_DATA_DIRECTORY setting should not be here. it will be done while running gpinitsystem to create a cluster; here, this is always set  data_dir to demo data-dir. IMO we can remove this from here.

2023-04-14 08:28 UTC, shrakesh commented on README.macOS.arm.bash
> +brew install python@3.9
any specific reason to assign the 3.9 version instead of picking the latest? in the existing macOS readme script, the version is not tagged.

2023-04-16 03:07 UTC, Shakarada commented on README.macOS.arm.bash
> +#brew install xerces-c #gporca
Commented for future reference

2023-04-16 03:09 UTC, Shakarada commented on README.macOS.arm.bash
> +export COORDINATOR_DATA_DIRECTORY=/Users/`whoami`/workspace/gpdb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1
We added all necessary global variable needed for greenplum compilation in the bashrc so that user no need to explicitly set it manually.

2023-04-16 03:11 UTC, Shakarada commented on README.macOS.arm.bash
> +brew install python@3.9
with Python 3.9 the greenplum works the best there were some issues faced on latest version so we have integrated with recommended version and we are using the 3.9 version even for CI.

2023-04-16 05:35 UTC, shrakesh commented on README.macOS.arm.bash
> +export COORDINATOR_DATA_DIRECTORY=/Users/`whoami`/workspace/gpdb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1
> We added all necessary global variable needed for greenplum compilation in the bashrc so that user no need to explicitly set it manually.
> 
> @ravoorsh @shrakesh should we keep it or remove it ?

for greenplum compilation, COORDINATOR_DATA_DIRCTORY is not required. when you create a cluster using gpinitsystem then at the end of successful cluster creation it gives information about the env variable which should be set by the user.  for example. 

```
20230410:11:09:32:007445 gpinitsystem:cdw:gpadmin-[INFO]:-Greenplum Database instance successfully created
20230410:11:09:32:007445 gpinitsystem:cdw:gpadmin-[INFO]:-------------------------------------------------------
20230410:11:09:32:007445 gpinitsystem:cdw:gpadmin-[INFO]:-To complete the environment configuration, please 
20230410:11:09:32:007445 gpinitsystem:cdw:gpadmin-[INFO]:-update gpadmin .bashrc file with the following
20230410:11:09:32:007445 gpinitsystem:cdw:gpadmin-[INFO]:-1. Ensure that the greenplum_path.sh file is sourced
20230410:11:09:32:007445 gpinitsystem:cdw:gpadmin-[INFO]:-2. Add "export COORDINATOR_DATA_DIRECTORY=/data/gpdata/coordinator/gpseg-1"
20230410:11:09:32:007445 gpinitsystem:cdw:gpadmin-[INFO]:-   to access the Greenplum scripts for this instance:
20230410:11:09:32:007445 gpinitsystem:cdw:gpadmin-[INFO]:-   or, use -d /data/gpdata/coordinator/gpseg-1 option for the Greenplum scripts
20230410:11:09:32:007445 gpinitsystem:cdw:gpadmin-[INFO]:-   Example gpstate -d /data/gpdata/coordinator/gpseg-1
```

so the added path in the readme script will not be always the same.  I believe we should not export COORDINATOR_DATA_DIRECTORY default to demo path at the compilation or initial setup step. 

IMO we can remove it.

2023-04-17 11:42 UTC, shrakesh approved these changes
LGTM +1

2023-04-17 11:53 UTC, merged