Add max_slot_wal_keep_size GUC to GP7 docs
greenplum-db/gpdb pull request #15200
Opened 2023-03-15 22:03 UTC by VMWareJennyBeth

2023-03-17 22:25 UTC, l-wang approved these changes

2023-03-21 20:58 UTC, dyozie requested changes

2023-03-21 20:58 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
> +**WARNING**: If `max_slot_wal_keep_size` is set to a non-default value for acting primaries, full and incremental recovery of their mirrors may not be possible. Depending on the workload on the prima
**WARNING**: -> >> **CAUTION**

2023-03-21 20:58 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
> +**WARNING**: If `max_slot_wal_keep_size` is set to a non-default value for acting primaries, full and incremental recovery of their mirrors may not be possible. Depending on the workload on the prima
complaint -> error

2023-03-22 18:14 UTC, dyozie approved these changes

2023-03-22 18:14 UTC, merged