gpcheckperf: Added support for rsync
greenplum-db/gpdb pull request #15292
Opened 2023-03-30 14:47 UTC by kpraveen457

Check if scp has execute permission, if not then gpcheckperf should use rsync tool to copy files.

Used rsync options:
-a: archive mode
-c : copy files based on checksum
-e: to specify ssh options
-q : quiet mode

Added unit and behave test

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2023-04-03 17:24 UTC, ravoorsh requested changes

2023-04-03 17:24 UTC, ravoorsh commented on gpMgmt/bin/gpcheckperf
> +def getHostList(includemaster=False):
Add code comments, a function header explaining what this function is doing.

2023-04-03 17:24 UTC, ravoorsh commented on gpMgmt/bin/gppylib/commands/unix.py
> +            print 'Unable to get the executable file : {0}' .format(str(e))
Should be "could not get executable file"

2023-04-03 17:24 UTC, ravoorsh commented on gpMgmt/test/behave/mgmt_utils/gpcheckperf.feature
> +  @demo_cluster
More test cases can be added to see if scp does not exist, if scp exists etc..

2023-04-03 17:24 UTC, ravoorsh commented on gpMgmt/bin/gpcheckperf
> +        sys.exit('[ERROR] ' + str(e))
Use .format instead of +

2023-04-03 17:24 UTC, ravoorsh commented on gpMgmt/bin/gppylib/test/unit/test_unit_gpcheckperf.py
> +    @patch('gppylib.commands.unix.isScpEnabled', return_value=False)
More unit test cases can be added to assert log messages, check for exceptions.

2023-04-04 06:40 UTC, ravoorsh commented on gpMgmt/bin/gpcheckperf
> +    witherror = False
witherror variable logic is very confusing... See if the code can be made simpler and cleaner and add code comments here as well.

2023-04-04 06:45 UTC, ravoorsh commented on gpMgmt/bin/gpcheckperf
> +    hostlist = getHostList()
Do you need to call getHostList twice?

2023-04-04 16:46 UTC, shrakesh commented on gpMgmt/bin/gpcheckperf
> +        cmd = rsync_cmd + " " + src + " " + unix.canonicalize(peer) + ":" + dst
can we use format instead of +, this is a bit confusing and unclear.

2023-04-04 16:56 UTC, shrakesh commented on gpMgmt/bin/gpcheckperf
> +_SCP_ENABLED = True
can we check if we can avoid this global variable by passing down the variable as argument?

2023-04-04 17:11 UTC, shrakesh commented on gpMgmt/bin/gpcheckperf
> +    errorExists = False
IMO we can do more optimization on this part, we can discuss on this. 
what is the intention to return the second argument always as None? is it really required to have?

2023-04-04 17:17 UTC, shrakesh commented on gpMgmt/bin/gppylib/commands/unix.py
> +            print 'could not get executable file : {0}' .format(str(e))
use parenthesis with a print statement.

2023-04-04 17:18 UTC, shrakesh commented on gpMgmt/bin/gpcheckperf
> +            print '[Abort] Keyboard Interrupt ...'
use parentheses with a print statements.

2023-04-05 12:01 UTC, jnihal commented on gpMgmt/bin/gpcheckperf
> +_SCP_ENABLED = True
+1 to this. Perhaps we do not need a variable. We only call `isScpEnabled` once. We can call this directly in the if ...else condition here https://github.com/greenplum-db/gpdb/blob/fbb98ffece8f9de3ebc4e36838d7276e85234a6b/gpMgmt/bin/gpcheckperf#L421-L428

2023-04-05 12:10 UTC, jnihal commented on gpMgmt/bin/gpcheckperf
> +        if GV.opt['-v']: print('[INFO]', cmd)
Please use the .format here. Right now the message is printed in an unformatted way.
```
[Info] copy local /Users/jnihal/workspace/gpdb6/gpMgmt/bin/lib/multidd to remote /tmp/gpcheckperf_$USER/multidd
('[INFO]', 'rsync -q -a -c -e "ssh -o BatchMode=yes -o StrictHostKeyChecking=no" /Users/jnihal/workspace/gpdb6/gpMgmt/bin/lib/multidd localhost:/tmp/gpcheckperf_$USER/multidd')
[Info] /usr/local/gpdb6/bin/gpssh -h localhost 'chmod a+rx /tmp/gpcheckperf_$USER/multidd'
```
Also would suggest changing it from  `INFO` to `Info` like in other places in the code to make it consistent.

2023-04-05 12:26 UTC, kpraveen457 commented on gpMgmt/bin/gpcheckperf
> +_SCP_ENABLED = True
@jnihal this if else condition is written in `copyExecOver` function and this function gets called at multiple places, so if we call `isScpEnabled` in `copyExecOver` directly in the if ...else condition then `isScpEnabled` will also be called multiple times. So thats why we call `isScpEnabled` just once in the main function and allocate the return value to the global variable

2023-04-05 12:45 UTC, jnihal commented on gpMgmt/bin/gpcheckperf
> +            print('[OUT %s] %s' % ("".join(p.args), line))
We are running rsync in quiet mode using -q option. Will we get any output in the stdout? If not, then it does not make sense to add this message since nothing would be printed.

2023-04-05 12:45 UTC, jnihal commented on gpMgmt/bin/gpcheckperf
> +            print('[ERROR %s] exit %d, cmd - %s' % (p.stderr.read(), status, "".join(p.args)))
`args` attribute is not present in `Popen` objects in Python2.7. It was introduced in 3.3. Refer [here](https://docs.python.org/3/library/subprocess.html).

2023-04-05 12:45 UTC, jnihal commented on gpMgmt/bin/gpcheckperf
> +        (errorExists, out) = gpscp(path, '=:{0}' .format(target))
Would suggest changing `errorExists` to `rc` to make it consistent with the other places in the code.

2023-04-05 13:02 UTC, jnihal commented on gpMgmt/bin/gpcheckperf
> +_SCP_ENABLED = True
In that case, we can explore Rakesh's suggestion. Thanks for the clarification.

2023-04-06 09:47 UTC, kpraveen457 commented on gpMgmt/bin/gpcheckperf
> +    errorExists = False
optimised this part(gpsync) , please review it.

2023-04-06 09:53 UTC, kpraveen457 commented on gpMgmt/bin/gpcheckperf
> +            print('[ERROR %s] exit %d, cmd - %s' % (p.stderr.read(), status, "".join(p.args)))
@jnihal made the changes and added the unit test for the same, please review it.

2023-04-06 09:54 UTC, kpraveen457 commented on gpMgmt/bin/gpcheckperf
> +        (errorExists, out) = gpscp(path, '=:{0}' .format(target))
handling the error in gpscp and gpsync function itself.

2023-04-06 10:22 UTC, kpraveen457 commented on gpMgmt/bin/gpcheckperf
> +_SCP_ENABLED = True
Already discussed with Rakesh and we have agreed on global variable use .If we decide to pass it as argument, we will have to pass it to many functions as it's required by them all.

2023-04-10 06:14 UTC, shrakesh requested changes
old review comments address, few suggestions:
1. add more behave test cases. 
2. as per the python standard add 2 blank lines between the function definition. 
3. add comments to newly added functions.

2023-04-10 06:14 UTC, shrakesh commented on gpMgmt/bin/gppylib/test/unit/test_unit_gpcheckperf.py
> +        self.assertIn('[Error] command failed for host:invalid_host', e.exception.code)
add test to check the behavior in multiple hosts.

2023-04-10 06:14 UTC, shrakesh commented on gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
> +@given('remove scp executable permission')
instead of adding new steps check the following can be used in this scenario. 
to add the permission: '"{path}" has its permissions set to "{perm}"'
to restore/clean the permission: rely on environment.py to restore path permissions.

2023-04-10 06:14 UTC, shrakesh commented on gpMgmt/test/behave/mgmt_utils/gpcheckperf.feature
> +    Given the database is running
it looks like this test is only for the single-node clusters. I would suggest adding a similar for a multimode concourse cluster. more scenarios can be captured for multiple hosts/ different warnings/successes.

2023-04-10 06:19 UTC, shrakesh commented on gpMgmt/bin/gpcheckperf
> +_SCP_ENABLED = True
if there are two many changes I am ok with a global variable, we can add the purpose of the variable in the description.

2023-04-13 05:04 UTC, nimish350 commented on gpMgmt/bin/gppylib/commands/unix.py
> +            print('[Warning] could not get executable file : {0}' .format(str(e)))
Can we modify it to "[Warning] could not execute scp on host xxxx". This makes it more precise. Also @shrakesh should we notify that it is now going to try rsync if scp is not available?

2023-04-13 05:46 UTC, kpraveen457 commented on gpMgmt/bin/gppylib/commands/unix.py
> +            print('[Warning] could not get executable file : {0}' .format(str(e)))
"`[Warning] Either scp is not available or does not have execute permission on host:xxxx`" is the new warning message i have updated when scp is not availabe.

2023-04-13 06:51 UTC, nimish350 commented on gpMgmt/bin/gppylib/commands/unix.py
> +            print('[Warning] could not get executable file : {0}' .format(str(e)))
Ok thanks LGTM

2023-04-13 17:57 UTC, shrakesh commented on gpMgmt/test/behave/mgmt_utils/gpcheckperf.feature
> +    When  the user runs "gpcheckperf -h cdw -h sdw1 -r ds -d /data/gpdata/ -S 10MB"
we discussed to remove cdw to test if the code changes related to making list with cdw is working as expected.

2023-04-13 17:59 UTC, shrakesh commented on gpMgmt/test/behave/mgmt_utils/gpcheckperf.feature
> +    When  the user runs "gpcheckperf -h localhost -r ds -d /tmp -S 10MB"
this is the concourse test so instead of localhost we can check using cdw which is our coordinator host.

2023-04-14 03:28 UTC, jnihal reviewed
Overall looks good to me. Left a couple of minor comments. Also please make sure you update the commit message and the PR description to reflect the new -P flag which is used.

2023-04-14 03:28 UTC, jnihal commented on gpMgmt/bin/gpcheckperf
> +            print('[Info] {0}' .format(cmd))
We can assert this log message in the behave test cases.

2023-04-14 03:28 UTC, jnihal commented on gpMgmt/bin/gpcheckperf
> +            print('[Out {0}] {1}' .format(p.x_peer, line))
We can assert this log message in the behave test cases.

2023-04-14 03:28 UTC, jnihal commented on gpMgmt/bin/gpcheckperf
> +        sys.exit('[ERROR] {0}' .format(str(e)))
nit: Change it from `ERROR` --> `Error`

2023-04-14 07:12 UTC, kpraveen457 commented on gpMgmt/bin/gpcheckperf
> +            print('[Out {0}] {1}' .format(p.x_peer, line))
we can not assert this log message in the behave test because this differ with the rsync version, for 2.6.9 it will print `[Out hostname] building file list` and for 3.1.3 it will print `[Out hostname] sending incremental file list `

2023-04-14 07:18 UTC, jnihal commented on gpMgmt/bin/gpcheckperf
> +            print('[Out {0}] {1}' .format(p.x_peer, line))
okay, thanks for checking on this.

2023-04-17 17:08 UTC, ravoorsh approved these changes
LGTM

2023-04-18 06:10 UTC, shrakesh approved these changes
LGTM +1

2023-06-28 03:00 UTC, merged