DOCS: Update docs to reflect that QuickLZ is not supported in 7X and to document related new GUC
greenplum-db/gpdb pull request #15457
Opened 2023-05-02 20:18 UTC by VMWareJennyBeth

2023-05-02 20:34 UTC, AJR-VMware approved these changes
LGTM.  Minor phrasing nit.

2023-05-03 15:30 UTC, dyozie requested changes

2023-05-03 15:30 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
> +When a user starts a session with Greenplum Database and issues a query, the system creates groups or 'gangs' of worker processes on each segment to do the work. `gp_print_create_gang_time` controls
Looks like a copy/paste error from another guc here.

2023-05-03 18:25 UTC, bmdoil approved these changes

2023-05-03 21:48 UTC, dyozie approved these changes

2023-05-03 21:48 UTC, merged