Warn of upcoming deprecation in next major release of support for QuickLZ compression
greenplum-db/gpdb pull request #15465
Opened 2023-05-03 19:33 UTC by VMWareJennyBeth

2023-05-03 19:52 UTC, lisakowen approved these changes

2023-05-04 23:13 UTC, dyozie requested changes

2023-05-04 23:13 UTC, dyozie commented on gpdb-doc/markdown/admin_guide/ddl/ddl-storage.html.md
> +>**Note**:
Remove colon character after note.

2023-05-04 23:13 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLE_AS.html.md
> +    >**Note**
Here, and in the remaining notes for the PR, it would be better to have a single note callout for both items, like:

> **Note** <sup>1</sup>QuickLZ compression is available only in the commercial release of VMware Greenplum.
> Support for the QuickLZ compression algorithm is deprecated and will be removed in the next major release of VMware Greenplum.

2023-05-05 16:28 UTC, dyozie approved these changes

2023-05-05 16:28 UTC, merged