DOCS: Update all reference topics to reflect changes to memory and resource groups in 7X
greenplum-db/gpdb pull request #15543
Opened 2023-05-15 00:42 UTC by VMWareJennyBeth

EARLY STAGE, NOT READY FOR REVIEW. DO NOT REVIEW YET.

2023-05-26 17:58 UTC, soumyadeep2007 reviewed
Mainly reviewed the memory stuff. I will try to take a look at the other aspects such as CPU etc, when I get a few more cycles.

2023-05-26 17:58 UTC, soumyadeep2007 commented on gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
> +|0 < integer < INT_MAX| 0 |local, system, superuser, reload|
superuser->user (since this is meant for regular users to override the memory limit settings)
reload is not necessary.

This should be: `coordinator, session, user`

2023-05-26 17:58 UTC, soumyadeep2007 commented on gpdb-doc/markdown/ref_guide/gp_toolkit.html.md
> +|`memory_usage`|The real-time memory usage of the resource group on each Greenplum Database segment's host.|
Hmmm I think these were overhauled:

Right now the only fields I can see are:

```
postgres=# select * from gp_toolkit.gp_resgroup_status_per_host;
    rsgname    | groupid | hostname | cpu_usage | memory_usage
---------------+---------+----------+-----------+--------------
admin_group   |    6438 | zero     |      0.09 |         5.55
default_group |    6437 | zero     |      0.00 |         0.00
system_group  |    6441 | zero     |      0.01 |        40.55
(3 rows)
```

2023-05-26 17:58 UTC, soumyadeep2007 commented on gpdb-doc/markdown/ref_guide/gp_toolkit.html.md
> +"1":{"used":11, "limit_granted":15}
None of these formats are in json anymore. I think these are remnants from old docs?

2023-05-26 17:58 UTC, soumyadeep2007 commented on gpdb-doc/markdown/ref_guide/sql_commands/ALTER_RESOURCE_GROUP.html.md
> +:   You must set `CONCURRENCY` to `0` for resource groups that you create for external components.
What is meant by "external components"?

2023-05-26 17:58 UTC, soumyadeep2007 commented on gpdb-doc/markdown/ref_guide/sql_commands/ALTER_RESOURCE_GROUP.html.md
> +:   When you specify a `MEMORY_LIMIT` of `0` or `-1`, `MEMORY LIMIT` takes the value of the `statement_mem` server configuration parameter.
Don't think we need to call out the `0` case.

Setting it to `0` will fall into the general case where we will fallback to `statement_mem` because of queryMem **being too low** as `queryMem = memory_limit *1024L *1024L / concurrency = 0; // since memory_limit = 0`
and we allocate:
`Max(queryMem, stateMem);`

2023-05-26 17:58 UTC, soumyadeep2007 commented on gpdb-doc/markdown/ref_guide/sql_commands/ALTER_RESOURCE_GROUP.html.md
> +This means that low-cost queries will execute more quickly, as they are not subject to concurrency constraints.
not subject to concurrency constraints -> not subject to resource constraints
(its not just concurrency restrictions we are avoiding, but avoiding all the restrictions in the group)

2023-05-26 20:18 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/ref_guide/gp_toolkit.html.md
> +|`memory_usage`|The real-time memory usage of the resource group on each Greenplum Database segment's host.|
@kainwen Did, as Deep has remarked here, the contents of that table dramatically change since we last documented it? Thank you.

2023-05-26 20:18 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/ref_guide/gp_toolkit.html.md
> +"1":{"used":11, "limit_granted":15}
@kainwen Same question as above.

2023-05-26 20:20 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/ref_guide/sql_commands/ALTER_RESOURCE_GROUP.html.md
> +:   You must set `CONCURRENCY` to `0` for resource groups that you create for external components.
PL/Container, as an example:
@soumyadeep2007 
"apply to all running instances of the component. For example, if you create a resource group for a PL/Container external component, the memory limit that you define for the group specifies the maximum memory usage for all running instances of each PL/Container runtime to which you assign the group."

2023-05-29 02:39 UTC, SmartKeyerror commented on gpdb-doc/markdown/ref_guide/gp_toolkit.html.md
> +|`memory_usage`|The real-time memory usage of the resource group on each Greenplum Database segment's host.|
That's right

2023-05-29 02:39 UTC, SmartKeyerror commented on gpdb-doc/markdown/ref_guide/gp_toolkit.html.md
> +The `memory_usage` field is a JSON-formatted, key:value string. The string contents differ depending upon the type of resource group. For each resource group that you assign to a role \(default memor
For now, the `memory_usage` field is **NOT** a JSON-formatted, the value is float format and means the actual memory usage (not relevant to the `mtracker`) of a group in the host. Besides, we can not get the memory usage of a segment.

2023-05-29 02:39 UTC, SmartKeyerror commented on gpdb-doc/markdown/ref_guide/gp_toolkit.html.md
> +"1":{"used":11, "limit_granted":15}
Yes, these formats are not in JSON anymore.

2023-05-29 02:39 UTC, SmartKeyerror commented on gpdb-doc/markdown/ref_guide/sql_commands/ALTER_RESOURCE_GROUP.html.md
> +The sum of the `CPU_HARD_QUOTA_LIMIT` values specified for all resource groups defined in the Greenplum Database cluster must be less than or equal to 100.
> The sum of the `CPU_HARD_QUOTA_LIMIT` values specified for all resource groups defined in the Greenplum Database cluster must be less than or equal to 100.

Currently, we removed this restriction, the sum of  the `CPU_HARD_QUOTA_LIMIT` values specified for all resource groups  could be more than 100. For example:

```
postgres=# select * from gp_toolkit.gp_resgroup_config ;
 groupid |   groupname   | concurrency | cpu_hard_quota_limit | cpu_soft_priority | cpuset | memory_limit 
---------+---------------+-------------+----------------------+-------------------+--------+--------------
    6437 | default_group | 20          | 20                   | 100               | -1     | -1
    6438 | admin_group   | 10          | 10                   | 100               | -1     | -1
    6441 | system_group  | 0           | 10                   | 100               | -1     | -1
   24576 | rg            | 50          | 90                   | 100               | -1     | -1
(4 rows)
```

2023-05-29 02:39 UTC, SmartKeyerror commented on gpdb-doc/markdown/ref_guide/sql_commands/ALTER_RESOURCE_GROUP.html.md
> +:   The minimum memory percentage you can specify for a resource group is `0`. The maximum is `100`. The default value is `-1`.
The meaning of `MEMORY_LIMIT` is not a percentage, and the maximum is not 100 either.

2023-05-29 02:39 UTC, SmartKeyerror commented on gpdb-doc/markdown/ref_guide/sql_commands/ALTER_RESOURCE_GROUP.html.md
> +:   The sum of the `MEMORY_LIMIT` values specified for all resource groups defined in the Greenplum Database cluster must be less than or equal to 100.
> The sum of the `MEMORY_LIMIT` values specified for all resource groups defined in the Greenplum Database cluster must be less than or equal to 100.

We can remove this now.

2023-05-29 02:39 UTC, SmartKeyerror commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_RESOURCE_GROUP.html.md
> +The sum of the `CPU_HARD_QUOTA_LIMIT` values specified for all resource groups defined in the Greenplum Database cluster must be less than or equal to 100.
Ditto.

2023-05-29 02:39 UTC, SmartKeyerror commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_RESOURCE_GROUP.html.md
> +:   The minimum memory percentage you can specify for a resource group is `0`. The maximum is `100`. The default value is `-1`.
Ditto.

2023-05-29 02:39 UTC, SmartKeyerror commented on gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-views.html.md
> +The `memory_usage` field is a JSON-formatted, key:value string. The string contents differ depending upon the type of resource group. For each resource group that you assign to a role \(default memor
Ditto.

2023-05-29 02:39 UTC, SmartKeyerror commented on gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-views.html.md
> +|`cpu_usage`|json| |A set of key-value pairs. For each segment instance \(the key\), the value is the real-time, per-segment instance CPU core usage by a resource group. The value is the sum of the p
`cpu_usage` and `memory_usage` is not JSON-format now, it's the single float value.

2023-05-29 02:39 UTC, SmartKeyerror commented on gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-views.html.md
> +The `cpu_usage` field is a JSON-formatted, key:value string that identifies, for each resource group, the per-segment instance CPU core usage. The key is the segment id. The value is the sum of the p
Ditto.

2023-05-31 15:31 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/ref_guide/gp_toolkit.html.md
> +The `memory_usage` field is a JSON-formatted, key:value string. The string contents differ depending upon the type of resource group. For each resource group that you assign to a role \(default memor
@SmartKeyerror Hi, Zhenglong. 

Now that memory usage is reported at the host level, rather than at the segment level, I need to update both the description and the examples given in the documentation. 

I changed this:

"The memory_usage field is also a JSON-formatted, key:value string. The string contents differ depending upon the type of resource group. For each resource group that you assign to a role (default memory auditor vmtracker), this string identifies the used and available fixed and shared memory quota allocations on each segment. The key is segment id. The values are memory values displayed in MB units. "

To this: "The memory_usage field is in float format and reports the actual memory usage of a resource group on the host machine. Values are memory values displayed in MB units." 

QUESTION 1: Are you okay with that rewrite?

QUESTION 2: The docs go on to provide this example:

The following example shows memory_usage column output for a single segment for a resource group that you assign to a role:

```
"0":{"used":0, "available":76, "quota_used":-1, "quota_available":60, "shared_used":0, "shared_available":16}
```

CAN YOU GIVE ME A CODE EXAMPLE that illustrates this memory_usage concept at the host level instead of the segment level? 

QUESTION 3: Same request for these 3 other examples, all of which also illustrate segment-level functionality instead of the new host-level functionality. Can you provide examples that are updated to reflect host-level?

For each resource group that you assign to an external component, the `memory_usage` JSON-formatted string identifies the memory used and the memory limit on each segment. The following example shows `memory_usage` column output for an external component resource group for a single segment:

```
"1":{"used":11, "limit_granted":15}
```

The `memory_usage` field is a JSON-formatted, key:value string. The string contents differ depending upon the type of resource group. For each resource group that you assign to a role \(default memory auditor `vmtracker`\), this string identifies the used and available fixed and shared memory quota allocations on each segment. The key is segment id. The values are memory values displayed in MB units. The following example shows `memory_usage` column output for a single segment for a resource group that you assign to a role:

```

"0":{"used":0, "available":76, "quota_used":-1, "quota_available":60, "shared_used":0, "shared_available":16}
```

For each resource group that you assign to an external component, the `memory_usage` JSON-formatted string identifies the memory used and the memory limit on each segment. The following example shows `memory_usage` column output for an external component resource group for a single segment:

```
"1":{"used":11, "limit_granted":15}
```

Thank you.

2023-05-31 15:40 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-views.html.md
> +The `memory_usage` field is a JSON-formatted, key:value string. The string contents differ depending upon the type of resource group. For each resource group that you assign to a role \(default memor
@SmartKeyerror Also, I need a different example for this cpu illustration, as it's using key-value pairs rather than float:

Example `cpu_usage` column output:

```

{"-1":0.01, "0":0.31, "1":0.31}
```

2023-05-31 15:55 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/ref_guide/gp_toolkit.html.md
> +|`memory_usage`|The real-time memory usage of the resource group on each Greenplum Database segment's host.|
@SmartKeyerror So there are only those 3 rows now?

2023-06-02 00:21 UTC, SmartKeyerror commented on gpdb-doc/markdown/ref_guide/gp_toolkit.html.md
> +|`memory_usage`|The real-time memory usage of the resource group on each Greenplum Database segment's host.|
The unit is "MB", we should add it.

2023-06-02 00:21 UTC, SmartKeyerror commented on gpdb-doc/markdown/ref_guide/sql_commands/ALTER_RESOURCE_GROUP.html.md
> +The sum of the `CPU_HARD_QUOTA_LIMIT` values specified for all resource groups defined in the Greenplum Database cluster must be less than or equal to 100.
The sum of the `CPU_HARD_QUOTA_LIMIT` values specified for all resource groups defined in the Greenplum Database cluster could **NOT** be less than or equal to 100, it can be more than 100, as I commented before.

2023-06-02 00:21 UTC, SmartKeyerror commented on gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-views.html.md
> +|`memory_usage`|The real-time memory usage of the resource group on each Greenplum Database segment's host.|
The unit is "MB", we should add it.

2023-06-02 19:54 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/ref_guide/sql_commands/ALTER_RESOURCE_GROUP.html.md
> +The sum of the `CPU_HARD_QUOTA_LIMIT` values specified for all resource groups defined in the Greenplum Database cluster must be less than or equal to 100.
@SmartKeyerror Sorry for forgetting to remove that restriction, fixed now.

2023-06-05 02:12 UTC, SmartKeyerror approved these changes
Look good for me.

2023-06-06 15:44 UTC, dyozie requested changes
Thanks, Jenny!  Just a few edits and one question attached.

2023-06-06 15:44 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
> +Specifies a fixed amount of memory -- in MB -- reserved for all queries in a resource group **for the scope of a session**. When this parameter is set to `0` -- the default -- the `MEMORY_LIMIT` reso
Replace dashes -- with commas here.

2023-06-07 23:11 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-views.html.md
> +|Column|Description|
Good catch, David. Thank you! No, losing them for those two views was an unhappy accident.

2023-06-08 09:40 UTC, mperezfuster commented on gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
>  - [gp_vmem_protect_limit](guc-list.html#gp_vmem_protect_limit) \(resource queue-based resource management\)
Hi Jenny, I think this guc needs to be revisited, as it is also used by resource groups now (see the provided document for more details). I think it takes over from rg_perseg_mem as this has been removed now.

2023-06-08 12:07 UTC, mperezfuster commented on gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
Also here, we might need to review this. I know you removed the section on how to calculate statement_mem if using resource groups because the other parameters are removed, however we don't provide any guidelines on how to set statement_mem if using resource groups. I think it could be useful but I don't think we have any guidelines, I will need to ask Dev.

2023-06-09 20:26 UTC, dyozie approved these changes

2023-06-09 20:26 UTC, merged