fix a error about aoco table of tsquery type greenplum-db#15556
greenplum-db/gpdb pull request #15562
Opened 2023-05-17 02:39 UTC by HelloYJohn

## Here are some reminders before you submit the pull request
- [*] Add tests for the change
- [*] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2023-05-17 03:10 UTC, kainwen commented
Thanks for your contribution. Would you please help  write details in commit message (and copy in PR message) so others can learn and review?

2023-05-17 04:02 UTC, HelloYJohn commented
I find that aoco table of tsquery type is false and  aoco table of tsvector type is ok, so I compared the two types of select processes and found that geting the value the two types of select processes and found that geting the values are different(I also compared inserting process and found them are different(I also compared inserting process and found them are similar). I think it's just an oversight.

2023-05-17 04:53 UTC, adam8157 commented on src/test/regress/output/uao_ddl/create_ao_tables.source
> + 'a' 'and' 'ate' 'cat' 'fat' 'mat' 'on' 'rat' 'sat' | 'fat' & 'rat' |  1
I get the same result without this PR, did I miss something?

```
gpadmin=# BEGIN;
CREATE TABLE test_ao_tsquery(
          c1 TSVECTOR,
          c2 TSQUERY,
          c3 INT
          ) DISTRIBUTED BY (c3);
INSERT INTO test_ao_tsquery(c1, c2, c3) VALUES('a fat cat sat on a mat and ate a fat rat'::TSVECTOR, 'fat & rat'::TSQUERY, 1);
ANALYZE test_ao_tsquery;
SELECT * FROM test_ao_tsquery;
BEGIN
CREATE TABLE
INSERT 0 1
ANALYZE
                         c1                         |      c2       | c3
----------------------------------------------------+---------------+----
 'a' 'and' 'ate' 'cat' 'fat' 'mat' 'on' 'rat' 'sat' | 'fat' & 'rat' |  1
(1 row)

```

2023-05-17 05:05 UTC, HelloYJohn commented on src/test/regress/output/uao_ddl/create_ao_tables.source
> + 'a' 'and' 'ate' 'cat' 'fat' 'mat' 'on' 'rat' 'sat' | 'fat' & 'rat' |  1
using aoco table，please

2023-05-17 05:08 UTC, HelloYJohn commented on src/test/regress/output/uao_ddl/create_ao_tables.source
> + 'a' 'and' 'ate' 'cat' 'fat' 'mat' 'on' 'rat' 'sat' | 'fat' & 'rat' |  1
create table test_ts3(c2 tsquery, c3 int)WITH (appendonly=true, compresstype=zlib, compresslevel=5,orientation=column) distributed by (c3);
insert into test_ts3(c2 ,c3) select 'fat & rat'::tsquery, 1 ;
select * from test_ts3;

2023-05-17 05:13 UTC, HelloYJohn commented on src/test/regress/output/uao_ddl/create_ao_tables.source
> + 'a' 'and' 'ate' 'cat' 'fat' 'mat' 'on' 'rat' 'sat' | 'fat' & 'rat' |  1
SET default_table_access_method=ao_column;
BEGIN; 
CREATE TABLE test_ao_tsquery( c1 TSVECTOR, c2 TSQUERY, c3 INT ) DISTRIBUTED BY (c3); INSERT INTO test_ao_tsquery(c1, c2, c3) VALUES('a fat cat sat on a mat and ate a fat rat'::TSVECTOR, 'fat & rat'::TSQUERY, 1); 
ANALYZE test_ao_tsquery; 
SELECT * FROM test_ao_tsquery;
COMMIT;

2023-05-17 06:16 UTC, adam8157 requested changes
Why it's related to the table storage, could you please help me understand? Thanks.

2023-05-17 06:16 UTC, adam8157 commented on src/include/tsearch/ts_type.h
> +#define DatumGetTSQuery(X)			((TSQuery) PG_DETOAST_DATUM(X))
I don't get this line, `tsquery` is a plain type, why do you de-toast it?

2023-05-17 06:16 UTC, adam8157 commented on src/test/regress/input/uao_ddl/create_ao_tables.source
> +          ) DISTRIBUTED BY (c3);
Change it to an AOCO table, if the issue only reproduces with that.

2023-05-17 07:00 UTC, HelloYJohn commented on src/include/tsearch/ts_type.h
> +#define DatumGetTSQuery(X)			((TSQuery) PG_DETOAST_DATUM(X))
I gdb sql1 "insert into test_ao_tsquery(c2) values ('fat & rat'::TSQUERY)", sql2"select c2 from test_ao_tsquery", sql3 "insert into test_ao_tsquery(c1) values ('a fat cat sat on a mat and ate a fat rat'::TSVECTOR)" and sql4 "select c1 from test_ao_tsquery". I find inserting and selecting of TSVECTOR and TSQUERY is similar.

aocsam.c:aocs_insert_values(AOCSInsertDesc idesc, Datum *d, bool *null, AOTupleId *aoTupleId)
d is processed as toast type， so I stay consistent with TSVECTOR.


#define DatumGetTSVector(X) ((TSVector) PG_DETOAST_DATUM(X))
so I think TSQuery is similar.

2023-05-17 07:05 UTC, HelloYJohn commented on src/test/regress/input/uao_ddl/create_ao_tables.source
> +          ) DISTRIBUTED BY (c3);
SET default_table_access_method=@amname@; has been set at the begin of file create_ao_tables.source, so test_ao_tsquery is ao/aoco table

2023-05-17 07:20 UTC, adam8157 commented on src/include/tsearch/ts_type.h
> +#define DatumGetTSQuery(X)			((TSQuery) PG_DETOAST_DATUM(X))
It doesn't look strong at first glance, please allow me some time to follow.

2023-05-17 07:20 UTC, HelloYJohn commented
<img width="1421" alt="image" src="https://github.com/greenplum-db/gpdb/assets/16135175/899e963e-a550-4948-9d72-890ee2ddedba">

compile_and_test_gpdb_without_assert/status failed but compile_and_test_gpdb/status success, it becauses analyze_progress is not unstable? 

Can you help me to retry it ? @adam8157

2023-05-18 05:45 UTC, adam8157 commented
`varattrib_untoast_ptr_len()` looks like a function to de-toast, but it just analyzes and sets `*tofree` to null if the datum is a “varlena” type.

2023-05-18 05:46 UTC, adam8157 commented
FYI
```
gpadmin=# select typname from pg_type where typlen = -1 and typstorage = 'p';
  typname
------------
 int2vector
 oidvector
 gtsvector
 tsquery
(4 rows)
```

2023-05-18 11:46 UTC, adam8157 commented
I believe I got a bit better solution, please help reviewing https://github.com/greenplum-db/gpdb/pull/15575

2023-05-24 02:30 UTC, closed without merging