docs - new topic, updated ref pages for progress reporting views and some utilities
greenplum-db/gpdb pull request #15577
Opened 2023-05-18 18:08 UTC by lisakowen

docs for various progress reporting-related PRs, including but not limited to: https://github.com/greenplum-db/gpdb/pull/14994, https://github.com/greenplum-db/gpdb/pull/15042, https://github.com/greenplum-db/gpdb/pull/15121, https://github.com/greenplum-db/gpdb/pull/15327

in this PR:
- add reference info for `gp_stat_progress_<command>` and `gp_stat_progress_<command>_summary` views, where `<command>` is analyze, create_index, copy, cluster, basebackup, vacuum.
- add new "monitoring long-running operations" topic based on https://www.postgresql.org/docs/15/progress-reporting.html.  includes the info about the progress phases, and calls out any AO/CO table differences.
- add new utility reference page for pg_checksums
- opportunisticly update utility reference pages for clusterdb and reindexdb to bring them up to postgres v12.

NOTE:  i am not sure if i am aware of, or covered, all of the differences between heap AO/CO tables. 

PLEASE:  search for XXX in the modified files - please help fill in this content, or, where it prefaces content, let me know if the text still applicable in greenplum 7.

QUESTIONS:
1.  are there any limitations or known issues to call out?
2.  ok to keep the term term "heap" in phase descriptions that apply to both heap and AO/CO tables?
3.  do we support progress on both partitioned and non-partitioned tables?  and do we support progress in the same way for both?
4.  would a user invoke pg_checksums directly, or indirectly via a utility command (like gprecover seg and basebackup)?

doc review site links (behind vpn):
- progress reporting system views:  https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/prog-rpt/greenplum-database/GUID-ref_guide-system_catalogs-catalog_ref-views.html#progress-reporting-views
- new "monitoring long-running operations" topic:  https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/prog-rpt/greenplum-database/GUID-admin_guide-managing-progress_reporting.html
- new pg_checksums utility ref page:  https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/prog-rpt/greenplum-database/GUID-utility_guide-ref-pg_checksums.html

2023-05-23 16:19 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/admin_guide/managing/progress_reporting.html.md
> +Greenplum reports the command progress via ephemeral system views. That is, the views return data only while the operations are running. Two sets of progress reporting views are provided:
Greenplum reports the command progress via ephemeral system views. That is, the views return data only while the operations are running.  ==>

Greenplum reports the command progress via ephemeral system views, which return data only while the operations are running.

2023-06-06 15:15 UTC, Chibin commented on gpdb-doc/markdown/admin_guide/managing/progress_reporting.html.md
> +Greenplum Database can report the progress of `ANALYZE`, `CLUSTER`, `COPY`, `CREATE INDEX`, `REINDEX`, and `VACUUM` commands during command execution, with some caveats. Greeplum can also report the
s/Greeplum/Greenplum

2023-06-06 15:43 UTC, Chibin commented on gpdb-doc/markdown/admin_guide/managing/progress_reporting.html.md
> +For each active analyze operation, the `gp_stat_progress_analyze_summary` view aggregates across the Greenplum Database cluster the metrics reported by `gp_stat_progress_analyze`, and shares the same
Just for my curiosity, I noticed that we use Greenplum and sometimes Greenplum Database, is there a difference? and when do we decide to use one or the other?

2023-06-06 17:12 UTC, Chibin commented on gpdb-doc/markdown/admin_guide/managing/progress_reporting.html.md
> +You can also use these views to monitor the data movement progress of utilities that use `COPY` under the hood, such as XXX.
gpbackup or gprestore  could work for the XXX.

2023-06-06 17:21 UTC, l-wang commented on gpdb-doc/markdown/utility_guide/ref/clusterdb.html.md
> +XXX To cluster a table means to physically reorder a table on disk according to an index so that index scan operations can access data on disk in a somewhat sequential order, thereby improving index
The description is correct. The wording: "somewhat sequential order" is true but sounds vague. Maybe we can refer to upstream's description: 
> Clustering is a one-time operation: when the table is subsequently updated, the changes are not clustered. That is, no attempt is made to store new or updated rows according to their index order. 

https://www.postgresql.org/docs/12/sql-cluster.html

2023-06-06 17:26 UTC, l-wang commented on gpdb-doc/markdown/utility_guide/ref/clusterdb.html.md
> +XXX If you do need to order a table in this way to improve your query performance, use a `CREATE TABLE AS` statement to reorder the table on disk rather than using `CLUSTER`. If you do 'cluster' a ta
I don't see the purpose of this paragraph. Specifically, 
> If you do need to order a table in this way

What way is this way? It seems missing contaxt. "CREATE TABLE AS" simply creates a new table with same schema and insert same data as old table. It wouldn't reorder the old table. I think this paragraph is confusing and I'm fine with removing it.

2023-06-06 19:33 UTC, l-wang reviewed
I'm half way.

2023-06-06 19:33 UTC, l-wang commented on gpdb-doc/markdown/admin_guide/managing/progress_reporting.html.md
> +For each active copy operation, the `gp_stat_progress_copy_summary` aggregates across the Greenplum Database cluster the metrics reported by `gp_stat_progress_copy`, and shares the same schema as thi
gp_stat_progress_copy_summary view shares same schema as the upstream pg_stat_progress_copy view.
gp_stat_progress_copy view has an additional gp_segment_id column which tells the content id of the particular segment.

2023-06-06 19:33 UTC, l-wang commented on gpdb-doc/markdown/admin_guide/managing/progress_reporting.html.md
> +Greenplum uses `sum()` for `COPY TO` with replicated tables, as the actual copy originates from only a single segment.
As someone who always have hard time explaining all these caveats with the COPY summary view, I really like your explanations!

2023-06-06 19:33 UTC, l-wang commented on gpdb-doc/markdown/admin_guide/managing/progress_reporting.html.md
> +For each active index operation, the `gp_stat_progress_create_index_summary` view aggregates across the Greenplum Database cluster the metrics reported by `gp_stat_progress_create_index`, and shares
gp_stat_progress_create_index_summary view shares same schema as the upstream pg_stat_progress_create_indexview.
gp_stat_progress_create_index view has an additional gp_segment_id column which tells the content id of the particular segment.

2023-06-06 19:33 UTC, l-wang commented on gpdb-doc/markdown/admin_guide/managing/progress_reporting.html.md
> +The [gp_stat_progress_vacuum](../../ref_guide/system_catalogs/catalog_ref-views.html#gp_stat_progress_vacuum) system view reports the progress of running `VACUUM` and `vacuumdb` operations. The view
as well as VACUUM FULL for AO/CO tables.

2023-06-06 19:33 UTC, l-wang commented on gpdb-doc/markdown/admin_guide/managing/progress_reporting.html.md
> +(Regular `VACUUM` modifies the table in place. `VACUUM FULL` rewrites the table as does a `CLUSTER` operation. For information about progress reporting for `VACUUM FULL`, see [CLUSTER and VACUUM FULL
This is only true for heap tables. See my previous comment.

2023-06-06 19:33 UTC, l-wang commented on gpdb-doc/markdown/admin_guide/managing/progress_reporting.html.md
> +In Greenplum Database, an AO/CO table vacuum behaves differently than a heap table vacuum. Because Greenplum stores the logical EOF for each segment file, it does not need to scan physical blocks aft
In addition, AO/CO always rewrite data into new segment files to get rid of dead tuples, so VACUUM FULL and VACUUM for AO/CO tables perform the same way and there is no "lazy" vacuum for AO/AOCO tables.

2023-06-06 19:33 UTC, l-wang commented on gpdb-doc/markdown/admin_guide/managing/progress_reporting.html.md
> +For each active vacuum operation, the `gp_stat_progress_vacuum_summary` view aggregates across the Greenplum Database cluster the metrics reported by `gp_stat_progress_vacuum`, and shares the same sc
gp_stat_progress_vacuum_summary view shares same schema as the upstream pg_stat_progress_vacuum view.
gp_stat_progress_vacuum view has an additional gp_segment_id column which tells the content id of the particular segment.

2023-06-06 19:33 UTC, l-wang commented on gpdb-doc/markdown/admin_guide/managing/progress_reporting.html.md
> +| `append-optimized pre-cleanup` | XXX |
Something like:
`VACUUM` is currently performing pre-cleanup of the AO/CO table, which includes recycling AWAITING_DROP segments that are no longer visible to anyone from previous VACUUM, and truncating all live segment files to their logcial EOFs.

2023-06-06 21:02 UTC, l-wang requested changes
Thank you @lisakowen for puting these together! I've finished my first round of review.

2023-06-06 21:22 UTC, l-wang commented
> NOTE: i am not sure if i am aware of, or covered, all of the differences between heap AO/CO tables.
You did great job! Minor things see my individual comments. 

> 1. are there any limitations or known issues to call out?
I need to think about this too and will come back to you.

> 2. ok to keep the term term "heap" in phase descriptions that apply to both heap and AO/CO tables?
Right. I believe those terms are mostly "heap_tuples_*" and "heap_blks_*". We did not rename those for AO/CO tables because we want to keep the same schema as the upstream "pg_stat_progre_<command>" tables. Under the AO/CO context. "heap_tuples_*" means just tuples or live tuples. "heap_blks_*" means equivalent number of heap blocks of given size in bytes.

> 3. do we support progress on both partitioned and non-partitioned tables?  and do we support progress in the same way for both?
Yes we do support partitioned and non-partitioned tables in same way. Specifically, right now the views show only stats of individual partitions, the parent table don't aggregate progress of its children.

> 4. would a user invoke pg_checksums directly, or indirectly via a utility command (like gprecover seg and basebackup)?
`pg_checksums` I believe is a standalone utility. We currently don't invoke it via other utility command, or vice versa. I don't know if we have any plan to integrate it though. @greenplum-db/cluster-management may have more context on that front.

2023-06-06 22:11 UTC, lisakowen commented on gpdb-doc/markdown/admin_guide/managing/progress_reporting.html.md
> +Greenplum Database can report the progress of `ANALYZE`, `CLUSTER`, `COPY`, `CREATE INDEX`, `REINDEX`, and `VACUUM` commands during command execution, with some caveats. Greeplum can also report the
remove pg_checksums section and "with some caveats".

2023-06-06 22:12 UTC, lisakowen commented on gpdb-doc/markdown/utility_guide/ref/clusterdb.html.md
> +XXX To cluster a table means to physically reorder a table on disk according to an index so that index scan operations can access data on disk in a somewhat sequential order, thereby improving index
added the requested text to that paragraph.

2023-06-06 22:13 UTC, lisakowen commented on gpdb-doc/markdown/admin_guide/managing/progress_reporting.html.md
> +The [gp_stat_progress_cluster](../../ref_guide/system_catalogs/catalog_ref-views.html#gp_stat_progress_cluster) system view reports the progress of running `CLUSTER`, `clusterdb`, and `VACUUM FULL` o
i qualified VACUUM FULL for heap tables only.

2023-06-06 22:13 UTC, lisakowen commented on gpdb-doc/markdown/admin_guide/managing/progress_reporting.html.md
> +Greenplum uses `sum()` for `COPY TO` with replicated tables, as the actual copy originates from only a single segment.
thanks!

2023-06-06 22:14 UTC, lisakowen commented on gpdb-doc/markdown/admin_guide/managing/progress_reporting.html.md
> +| `append-optimized pre-cleanup` | XXX |
thank you for filling in the XXX, @l-wang !

2023-06-06 22:19 UTC, lisakowen commented on gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-views.html.md
> +The `gp_stat_progress_analyze_summary` view aggregates across the Greenplum Database cluster the metrics reported by `gp_stat_progress_analyze`, and shares the same schema as this view.
ok, i removed the ", and shares the same schema as this view." statements from the progress reporting views.  the description of the gp_segment_id in all of the progress views states "Unique identifier of a segment \(or coordinator\) instance. (This column is not present in the `gp_stat_progress_XXX_summary` view.)".  is this sufficient to address your comments in this area @l-wang ?

2023-06-06 22:33 UTC, lisakowen commented
thank you for reviewing @Chibin and @l-wang !  i made most of your requested edits and re-pushed the review site - you may need to refresh.  only one outstanding question on my end, sent previously.

2023-06-06 23:39 UTC, l-wang commented on gpdb-doc/markdown/utility_guide/ref/clusterdb.html.md
> +To cluster a table means to physically reorder a table on disk according to an index. Clustering is a one-time operation: when the table is subsequently updated, the changes are not clustered. That i
Can we still mention that CLUSTER helps improving index seek performance for queries that use that index?

2023-06-06 23:39 UTC, l-wang commented on gpdb-doc/markdown/admin_guide/managing/progress_reporting.html.md
> +(Regular `VACUUM` modifies the table in place. `VACUUM FULL` on a heap table rewrites the table as does a `CLUSTER` operation. For information about progress reporting for `VACUUM FULL` on a heap tab
"Regular `VACUUM` modifies the table in place" : this is also for heap table only.

2023-06-06 23:39 UTC, l-wang commented on gpdb-doc/markdown/admin_guide/managing/progress_reporting.html.md
> +In Greenplum Database, an AO/CO table vacuum behaves differently than a heap table vacuum. Because Greenplum stores the logical EOF for each segment file, it does not need to scan physical blocks aft
s/`and so`/`and`/ ?

2023-06-06 23:39 UTC, l-wang commented on gpdb-doc/markdown/admin_guide/managing/progress_reporting.html.md
> +The [gp_stat_progress_basebackup](../../ref_guide/system_catalogs/catalog_ref-views.html#gp_stat_progress_basebackup) system view reports the progress of running base backup operations, as is perform
s/`gprecoverseg`/`gprecoverseg -F`/ where `-F` stands for full recovery.

2023-06-07 17:03 UTC, l-wang commented on gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-views.html.md
> +| `heap_tuples_scanned` | bigint | Number of live tuples scanned. This counter only advances when the phase is `seq scanning append-optimized` or `seq scanning heap`, `index scanning heap`, or `writi
For heap table, `heap_tuples_scanned` records the number of tuples scanned, including both live and dead tuples.
For AO table, `heap_tuples_scanned` records the number of live tuples scanned, excluding the dead tuples.

2023-06-07 18:36 UTC, lisakowen commented
@Chibin - re: your question about "greenplum database" vs just "greenplum" ...  the docs use these terms interchangeably.  i think we typically initially refer to Greenplum Database on a page, and use one or the other for later references.

2023-06-07 20:24 UTC, l-wang commented
> QUESTIONS:
> 
> are there any limitations or known issues to call out?

1. Would it be worth mentionning progress phases and interpretations of attributes are slightly different for AO/AOCO tables from the heap tables for some commands? The commands are CREATE INDEX/REINDEX, VACUUM, CLUSTER. Maybe ask users refer to individual commands for details? I don't think this is limitation or "issue" though.
2. The progress views for ANALYZE a partitioned table shows progress of each individual leaf partitions, and no holistic progress of all partitions is available at the moment. This behavior is same as upstream Postgres.
3. CLUSTER a partitioned table is not supported. This is on par with Postgres 12. Postgres 15 does support it. (I just realized this is a regression from 6X. Let's document this for now and I will confirm if we want to re-enable it)

2023-06-07 21:13 UTC, lisakowen commented
@l-wang , thank you for the quick turnaround reviewing my commits.

question:  the docs use AO/CO in many places for this feature.  should these be replaced with AO/AOCO?

2023-06-07 22:22 UTC, l-wang commented
> @l-wang , thank you for the quick turnaround reviewing my commits.

No problem! 

> question: the docs use AO/CO in many places for this feature. should these be replaced with AO/AOCO?

I actually have the same question when initially looking at the PR. I don't know if we've established a convention, if we haven't, it's better to decided on one and use the same name consistently across all 7X documentations, not just the doc pages for this PR. 

Personally I perfer "append-optimized" tables over "AO/AOCO" or "AO/CO" because I like full names over acronyms. Although sometimes it becomes mouthful. I also prefer "ao_row" and "ao_column" if need to refer to exact access methods since those are the actual access method names we store in the catalog. Historically we also have names like append-only, AO, CO, AOCO, AOCS, and I'm sure people have different preferences. I'm cool with whatever name we decided to use as long as we keep consistency. @ashwinstar @soumyadeep2007 @dpandhi-git @shivzone  ideas?

2023-06-07 22:27 UTC, l-wang approved these changes
Content look good to me! Thanks Lisa!

I have reviewed all the git diffs. Due to VPN problem I was not able to check the format through the internal web page, so it would be nice if someone else can also check the web page before publishing.

2023-06-07 22:27 UTC, l-wang commented on gpdb-doc/markdown/admin_guide/managing/progress_reporting.html.md
> +- Greenplum does not support the `CLUSTER` operation on a partitioned table.
Thanks for adding this. I just created a story in backlog to enable the same. Hopefully we can remove this one soon.

2023-06-07 22:36 UTC, lisakowen commented
thank you, @l-wang !  i've created a new story for "use consistent terminology for append-optimized tables", will follow further discussion here.

2023-06-08 01:17 UTC, VMWareJennyBeth approved these changes

2023-06-08 01:17 UTC, VMWareJennyBeth approved these changes

2023-06-08 01:17 UTC, VMWareJennyBeth approved these changes

2023-06-08 01:17 UTC, VMWareJennyBeth approved these changes

2023-06-09 20:27 UTC, merged