Make it PANIC when the interconnect peer binding failed due to port used
greenplum-db/gpdb pull request #15609
Opened 2023-05-24 08:49 UTC by Aegeaner

For the occupied interconnect proxy address port:

- occupy a port which is intend to use:

`$ nc -l 6004`

-  configure the ic proxy addresses:

 

```
$ gpconfig --skipvalidation -c gp_interconnect_proxy_addresses -v "'1:-1:localhost.localdomain:6000,2:0:localhost.localdomain:6002,3:1:localhost.localdomain:6003,4:2:localhost.localdomain:6004'"
$ gpstop -u
```

 

-  got tons of warnings in segment log:

```
dbfast3/demoDataDir2/log/gpdb-2023-05-24_035320.csv:113:2023-05-24 04:18:28.795859 EDT,,,p98191,th-498856384,,,,0,,,seg2,,,,,"WARNING","01000","ic-proxy: tcp: fail to listen: address already in use",,,,,,,0,,"ic_proxy_main.c",206,
dbfast3/demoDataDir2/log/gpdb-2023-05-24_035320.csv:114:2023-05-24 04:18:29.796951 EDT,,,p98191,th-498856384,,,,0,,,seg2,,,,,"WARNING","01000","ic-proxy: tcp: fail to listen: address already in use",,,,,,,0,,"ic_proxy_main.c",206,
dbfast3/demoDataDir2/log/gpdb-2023-05-24_035320.csv:115:2023-05-24 04:18:30.798078 EDT,,,p98191,th-498856384,,,,0,,,seg2,,,,,"WARNING","01000","ic-proxy: tcp: fail to listen: address already in use",,,,,,,0,,"ic_proxy_main.c",206,
dbfast3/demoDataDir2/log/gpdb-2023-05-24_035320.csv:116:2023-05-24 04:18:31.799162 EDT,,,p98191,th-498856384,,,,0,,,seg2,,,,,"WARNING","01000","ic-proxy: tcp: fail to listen: address already in use",,,,,,,0,,"ic_proxy_main.c",206,
dbfast3/demoDataDir2/log/gpdb-2023-05-24_035320.csv:117:2023-05-24 04:18:32.800258 EDT,,,p98191,th-498856384,,,,0,,,seg2,,,,,"WARNING","01000","ic-proxy: tcp: fail to listen: address already in use",,,,,,,0,,"ic_proxy_main.c",206,
dbfast3/demoDataDir2/log/gpdb-2023-05-24_035320.csv:118:2023-05-24 04:18:33.801348 EDT,,,p98191,th-498856384,,,,0,,,seg2,,,,,"WARNING","01000","ic-proxy: tcp: fail to listen: address already in use",,,,,,,0,,"ic_proxy_main.c",206,

```
 

- But it doesn't effect normal query, except that corresponding segment keeps trying to startup but got failed again and again.

 

- Conclusion：we must make the segment error out in case of address port used.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2023-05-25 01:36 UTC, interma requested changes

2023-05-25 01:36 UTC, interma commented on src/backend/cdb/motion/ic_proxy_main.c
> +		elog(PANIC, "ic-proxy: tcp: fail to bind: %s",
We should not use `PANIC` here: 
It continuously restarts the icproxy process (because `ic_proxy_server_peer_listener_init()` is in the timer handler `ic_proxy_server_on_timer()`), and notifies the postmaster to do other dangerous works (e.g. recovery).

We need another safe and quick way to let users know their icproxy process doesn't work.

2023-05-25 01:38 UTC, interma commented
> But it doesn't effect normal query, except that corresponding segment keeps trying to startup but got failed again and again.

I don't think so, it should block all queries (the network communication is paused since icproxy doesn't work), you may check again.

2023-05-25 02:04 UTC, Aegeaner commented on src/backend/cdb/motion/ic_proxy_main.c
> +		elog(PANIC, "ic-proxy: tcp: fail to bind: %s",
`PANIC` is quick enough to inform the master the segment failed.

2023-05-25 02:21 UTC, Aegeaner commented on src/backend/cdb/motion/ic_proxy_main.c
> +		elog(PANIC, "ic-proxy: tcp: fail to bind: %s",
To fail more quickly, we can make ic proxy process's `bgw_restart_time` to `BGW_NEVER_RESTART`.

2023-05-25 08:07 UTC, Aegeaner commented
> > But it doesn't effect normal query, except that corresponding segment keeps trying to startup but got failed again and again.
> 
> I don't think so, it should block all queries (the network communication is paused since icproxy doesn't work), you may check again.

@interma By interconnect's current design, it will not block any queries from execution, because the motion layer was initialized successfully, the ic proxy layer is established based on the motion layer, but will **NOT** ERROR out if any one of the proxy peer failed to initialize, this is the issue we must solve.

2023-05-26 05:58 UTC, Aegeaner commented
> > > > But it doesn't effect normal query, except that corresponding segment keeps trying to startup but got failed again and again.
> > > 
> > > 
> > > I don't think so, it should block all queries (the network communication is paused since icproxy doesn't work), you may check again.
> > 
> > 
> > @interma By interconnect's current design, it will not block any queries from execution, because the motion layer was initialized successfully. The ic proxy layer is established based on the motion layer, but will **NOT** ERROR out if any one of the proxy peer failed to initialize, this is the issue we must solve.
> 
> I just tested it, it blocked queries. I think you may miss some steps to setup icproxy, refer here: https://github.com/greenplum-db/gpdb/blob/main/src/backend/cdb/motion/README.ic-proxy.md Please verify it again.

I forgot to set interconnect type at cluster level. As you said, `TerminateMppBackends()` got called and the query was blocked.

2023-05-26 05:58 UTC, closed without merging

2023-05-30 09:24 UTC, Aegeaner commented on src/backend/cdb/motion/ic_proxy_main.c
> +		elog(PANIC, "ic-proxy: tcp: fail to bind: %s",
> We need another safe and quick way to let users know their icproxy process doesn't work.

_In addition_:


Finding a proper way to alarm the client about segment failures seems tough, since libuv's asynchronous execution and no global state machine built for the proxy client. What I can think of includes:


- Ensure the the domain socket path exists. Each client will build server sock path in unix domain as "/tmp/.s.PGSQL.ic_proxy.%d.%d".
- Make sure the expected port is up, but this does not means the segment is must running successfully.
- Both of above are necessary but insufficient conditions .

2023-06-06 06:45 UTC, Aegeaner commented
> Why hung? The detail hung status and performance?

In interconnect proxy mode, the connections are established asynchronously in `SetupTCPInterconnect()` :

https://github.com/greenplum-db/gpdb/blob/4bb0004764e0aecf60cff145355d35cc67b57cdf/src/backend/cdb/motion/ic_tcp.c#L1406


```
 /*
 * Before ic_proxy_backend_run_loop, we have already gone though all the
 * incoming and outgoing connections and append them into the connect queue.
 * ic_proxy_backend_run_loop will trigger the uv_loop and begin to handle
 * the connect event in parallel and asynchronous way.
 *
 * Note that the domain socket fds are binded to libuv pipe handle, but we
 * still depends on ic_tcp code to send/recv interconnect data based on
 * these fds and close these fds in teardown function. As a result, we
 * should not touch the libuv pipe handles until ic_tcp close all the fds in
 * teardown function. In future, we should retire the ic_tcp code in ic_proxy
 * backend and use libuv to handle connection setup, data transfer and
 * teardown in a unified way.
 */
 ic_proxy_backend_run_loop(interconnect_context->proxyContext);
```


And if the port is occupied, the epoll would be blocked because of failed connection:

```
$ pstack 60564
#0  0x00007ff6c054ea7a in epoll_wait () from /lib64/libc.so.6
#1  0x00007ff6c0e212d9 in uv__io_poll (loop=loop@entry=0x29afe70, timeout=<optimized out>) at src/unix/epoll.c:236
#2  0x00007ff6c0e0e904 in uv_run (loop=0x29afe70, mode=UV_RUN_DEFAULT) at src/unix/core.c:389
#3  0x0000000000e2e987 in ic_proxy_backend_run_loop (context=0x29afe70) at ic_proxy_backend.c:567
#4  0x0000000000e0cbbc in SetupTCPInterconnect (estate=0x29ad540) at ic_tcp.c:1406
#5  0x0000000000e0ad14 in SetupInterconnect (estate=0x29ad540) at ic_common.c:543
#6  0x00000000008586f2 in standard_ExecutorStart (queryDesc=0x29031a0, eflags=16) at execMain.c:488
#7  0x0000000000857d30 in ExecutorStart (queryDesc=0x29031a0, eflags=0) at execMain.c:223
#8  0x0000000000b6933d in PortalStart (portal=0x2994ea0, params=0x0, eflags=0, snapshot=0x0, ddesc=0x2910918) at pquery.c:729
#9  0x0000000000b641c7 in exec_mpp_query (query_string=0x28e130e "SELECT *\n  FROM J1_TBL CROSS JOIN J2_TBL;", serializedPlantree=0x28e1338 "(\265/\375`T\a\245\016", serializedPlantreelen=478, serializedQueryDispatchDesc=0x28e1516 "(\265/\375`\253", serializedQueryDispatchDesclen=172) at postgres.c:1414
#10 0x0000000000b61e52 in PostgresMain (argc=1, argv=0x2919848, dbname=0x290c6d8 "postgres", username=0x290c6b8 "gpadmin") at postgres.c:5547
#11 0x0000000000a7c306 in BackendRun (port=0x2905e10) at postmaster.c:5012
#12 0x0000000000a7b686 in BackendStartup (port=0x2905e10) at postmaster.c:4689
#13 0x0000000000a7a321 in ServerLoop () at postmaster.c:2005
#14 0x0000000000a779ea in PostmasterMain (argc=5, argv=0x28daf90) at postmaster.c:1631
#15 0x0000000000914404 in main (argc=5, argv=0x28daf90) at main.c:240
```

2023-06-08 07:15 UTC, Aegeaner commented
The query hung can be reproduced stably when ic_proxy configured at cluster level. Previously it cannot be reproduced because ic-proxy peers establish connections following a rule: only peer with greater content id would connect to the other peer with smaller content id, but the peer whose address port used is with the greatest content id, so it will only connect to others, instead of being connected from others, and in the end the TCP connection established successsfully.

This is the issued QE's log:
```
2023-06-08 02:56:16.461888 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: server setting up",,,,,,,0,,"ic_proxy_main.c",532,
2023-06-08 02:56:16.461999 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: seg-1,dbid1: parsed addr: localhost.localdomain:6000",,,,,,,0,,"ic_proxy_addr.c",318,
2023-06-08 02:56:16.462161 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: seg0,dbid2: parsed addr: localhost.localdomain:6002",,,,,,,0,,"ic_proxy_addr.c",318,
2023-06-08 02:56:16.462176 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: seg1,dbid3: parsed addr: localhost.localdomain:6003",,,,,,,0,,"ic_proxy_addr.c",318,
2023-06-08 02:56:16.462186 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: seg2,dbid4: parsed addr: localhost.localdomain:6004",,,,,,,0,,"ic_proxy_addr.c",318,
2023-06-08 02:56:16.462478 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: server running",,,,,,,0,,"ic_proxy_main.c",573,
2023-06-08 02:56:16.462953 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: seg-1,dbid1: resolved address localhost.localdomain:6000 -> ::1:6000 family=10",,,,,,,0,,"ic_proxy_addr.c",203,
2023-06-08 02:56:16.462974 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: seg0,dbid2: resolved address localhost.localdomain:6002 -> ::1:6002 family=10",,,,,,,0,,"ic_proxy_addr.c",203,
2023-06-08 02:56:16.463240 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: seg1,dbid3: resolved address localhost.localdomain:6003 -> ::1:6003 family=10",,,,,,,0,,"ic_proxy_addr.c",203,
2023-06-08 02:56:16.463325 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: seg2,dbid4: resolved address localhost.localdomain:6004 -> ::1:6004 family=10",,,,,,,0,,"ic_proxy_addr.c",203,
2023-06-08 02:56:16.562728 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: setting up peer listener on localhost.localdomain:6002 (::1:6002 family=10)",,,,,,,0,,"ic_proxy_main.c",178,
2023-06-08 02:56:16.562879 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"WARNING","01000","ic-proxy: tcp: fail to listen: address already in use",,,,,,,0,,"ic_proxy_main.c",206,
2023-06-08 02:56:16.562996 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: peer[seg-1,dbid1 unknown:0->unknown:0]: registered",,,,,,,0,,"ic_proxy_peer.c",248,
2023-06-08 02:56:16.563098 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: setting up client listener on address /tmp/.s.PGSQL.ic_proxy.7002.236793",,,,,,,0,,"ic_proxy_main.c",325,
2023-06-08 02:56:16.563198 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: pipe: listening on socket 16",,,,,,,0,,"ic_proxy_main.c",355,
2023-06-08 02:56:16.563296 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: dev=64768, inode=583883, path=/tmp/.s.PGSQL.ic_proxy.7002.236793",,,,,,,0,,"ic_proxy_main.c",368,
2023-06-08 02:56:16.563396 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: peer[seg-1,dbid1 unknown:0->unknown:0]: fail to connect: connection refused",,,,,,,0,,"ic_proxy_peer.c",801,
2023-06-08 02:56:16.563496 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: peer[seg-1,dbid1 unknown:0->unknown:0]: closing",,,,,,,0,,"ic_proxy_peer.c",447,
2023-06-08 02:56:16.563594 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","peer[seg-1,dbid1 unknown:0->unknown:0]: closed",,,,,,,0,,"ic_proxy_peer.c",424,
2023-06-08 02:56:16.563694 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy peer[seg-1,dbid1 unknown:0->unknown:0]: unregistered",,,,,,,0,,"ic_proxy_peer.c",167,
2023-06-08 02:56:16.757138 EDT,"gpadmin","postgres",p236934,th1998638656,"127.0.0.1","44452",2023-06-08 02:56:16 EDT,0,con2,,seg0,,,,sx1,"LOG","00000","tried to terminate all (0) mpp backends except self",,,,,,"select * from gp_terminate_mpp_backends()",0,,"signalfuncs.c",222,
2023-06-08 02:56:17.563981 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: setting up peer listener on localhost.localdomain:6002 (::1:6002 family=10)",,,,,,,0,,"ic_proxy_main.c",178,
2023-06-08 02:56:17.564356 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: tcp: listening on socket 14",,,,,,,0,,"ic_proxy_main.c",212,
2023-06-08 02:56:17.714195 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: new peer to the server",,,,,,,0,,"ic_proxy_main.c",91,
2023-06-08 02:56:17.714222 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: the new peer is from ::1:47980",,,,,,,0,,"ic_proxy_main.c",133,
2023-06-08 02:56:17.714489 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: peer[seg2,dbid4 ::1:6002->::1:47980]: registered",,,,,,,0,,"ic_proxy_peer.c",248,
2023-06-08 02:56:33.683509 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: new client to the server",,,,,,,0,,"ic_proxy_main.c",284,
2023-06-08 02:56:33.683536 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: new client to the server",,,,,,,0,,"ic_proxy_main.c",284,
2023-06-08 02:56:33.683676 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: new client to the server",,,,,,,0,,"ic_proxy_main.c",284,
2023-06-08 02:56:33.683688 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: new client to the server",,,,,,,0,,"ic_proxy_main.c",284,
2023-06-08 02:56:33.683773 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: client[con7,cmd3,slice[2->1] seg0:dbid2:p236979->seg0:dbid2:p236984]: registered, 1 in total",,,,,,,0,,"ic_proxy_client.c",345,
2023-06-08 02:56:33.683792 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: client[con7,cmd3,slice[2->1] seg0:dbid2:p236979->seg1:dbid3:p236982]: registered, 2 in total",,,,,,,0,,"ic_proxy_client.c",345,
2023-06-08 02:56:33.683803 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: client[con7,cmd3,slice[2->1] seg0:dbid2:p236979->seg2:dbid4:p236983]: registered, 3 in total",,,,,,,0,,"ic_proxy_client.c",345,
2023-06-08 02:56:33.683815 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: client[con7,cmd3,slice[1->0] seg0:dbid2:p236979->seg-1:dbid1:p236972]: registered, 4 in total",,,,,,,0,,"ic_proxy_client.c",345,
2023-06-08 02:56:33.683834 EDT,"gpadmin","postgres",p236979,th1998638656,"127.0.0.1","28424",2023-06-08 02:56:33 EDT,0,con7,cmd3,seg0,slice1,,,sx1,"LOG","00000","SetupInterconnect+0ms: Activated 3 incoming, 1 outgoing routes.",,,,,,"SELECT count(*)  FROM J1_TBL CROSS JOIN J2_TBL;",0,,"ic_tcp.c",1882,
2023-06-08 02:56:33.684501 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: new client to the server",,,,,,,0,,"ic_proxy_main.c",284,
2023-06-08 02:56:33.684521 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: new client to the server",,,,,,,0,,"ic_proxy_main.c",284,
2023-06-08 02:56:33.684529 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: new client to the server",,,,,,,0,,"ic_proxy_main.c",284,
2023-06-08 02:56:33.684554 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: client[con7,cmd3,slice[2->1] seg0:dbid2:p236984->seg0:dbid2:p236979]: registered, 5 in total",,,,,,,0,,"ic_proxy_client.c",345,
2023-06-08 02:56:33.684566 EDT,,,p236844,th1998638656,,,,0,,,seg0,,,,,"LOG","00000","ic-proxy: client[con7,cmd3,slice[2->1] seg0:dbid2:p236984->seg1:dbid3:p236980]: registered, 6 in total",,,,,,,0,,"ic_pro [...]