[6X] Allow pg_upgrade --jobs to also run GPDB upgrade checks in parallel
greenplum-db/gpdb pull request #15698
Opened 2023-06-06 00:57 UTC by jimmyyih

A handful of our GPDB-specific upgrade checks can take a long time to run (specifically all the view ones that traverse parse trees) on a large production GPDB cluster. To reduce the runtime, we can take the same parallelization logic that already exists in pg_upgrade and implement something similar for the GPDB upgrade checks. We do not include the upstream Postgres upgrade checks to keep things simple but may do so in the future if needed.

Note: There's not much upgrade checks in GPDB main (7X) yet to implement this logic so just do it in 6X_STABLE only for now.  Can always forward-port later when we actually start working on 6-to-7 upgrade.

2023-06-07 19:30 UTC, kyeap-vmware requested changes

2023-06-07 19:30 UTC, kyeap-vmware commented on contrib/pg_upgrade/greenplum/check_gp.c
> +		pg_fatal("waitpid() failed: %s\n", strerror(errno));
I get a compile error when treating warnings as errors. Gets resolved by `#include <sys/wait.h>`

```
make -C contrib/pg_upgrade all
make[1]: Entering directory '/home/kyeap/workspace/gpdb6/contrib/pg_upgrade'
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -Werror=implicit-fallthrough=3 -Wno-format-truncation -Wno-stringop-truncation -g -ggdb -O0 -std=gnu99   -Werror=uninitialized -Werror=implicit-function-declaration -DFRONTEND -DDLSUFFIX=\".so\" -I. -I../../src/interfaces/libpq -I. -I. -I../../src/include -D_GNU_SOURCE -I/usr/include/libxml2   -c -o greenplum/check_gp.o greenplum/check_gp.c -MMD -MP -MF .deps/check_gp.Po
greenplum/check_gp.c: In function ‘parallel_checks_reap_child’:
greenplum/check_gp.c:150:17: error: implicit declaration of function ‘waitpid’ [-Werror=implicit-function-declaration]
  150 |         child = waitpid(-1, &work_status, wait_for_child ? 0 : WNOHANG);
      |                 ^~~~~~~
cc1: some warnings being treated as errors
```

2023-06-08 22:05 UTC, jimmyyih commented on contrib/pg_upgrade/greenplum/check_gp.c
> +		pg_fatal("waitpid() failed: %s\n", strerror(errno));
Thanks; I wasn't able to reproduce the compilation issue on MacOS but was able to reproduce it on my Rocky8 Docker container.  Fixed by adding the include similar to how it is in `contrib/pg_upgrade/parallel.c`.

2023-06-08 22:15 UTC, jimmyyih commented
Forgot to add what the output will look like now.  This is what it will look like:
Without parallelism (jobs = 0)...
```
Performing Consistency Checks on Old Live Server
------------------------------------------------
Checking cluster versions                                   ok 47.000ms
Creating a dump of all tablespace metadata.                 ok 14.151ms
Checking database user is a superuser                       ok 9.306ms
Checking database connection settings                       ok 28.674ms
Checking for prepared transactions                          ok 15.347ms
Checking for reg* system OID user data types                ok 80.244ms
Checking for contrib/isn with bigint-passing mismatch       ok 51.918ms

Starting parallel Greenplum checks (--jobs=0):
===============================================
Running: Checking for non-covering indexes on partitioned AO tables...
Checking for non-covering indexes on partitioned AO tables  ok 56.972ms
Running: Checking AO/CO parent partitions with pg_aoseg entries...
Checking AO/CO parent partitions with pg_aoseg entries      ok 69.372ms
Running: Checking for heterogeneous partitioned tables...
Checking for heterogeneous partitioned tables               ok 116.088ms
Running: Checking for indexes on partitioned tables...
Checking for indexes on partitioned tables                  ok 154.269ms
Running: Checking for foreign key constraints on root partitions...
Checking for foreign key constraints on root partitions     ok 69.086ms
Running: Checking for orphaned TOAST relations...
Checking for orphaned TOAST relations                       ok 41.648ms
Running: Checking for gphdfs external tables...
Checking for gphdfs external tables                         ok 65.639ms
Running: Checking for users assigned the gphdfs role...
Checking for users assigned the gphdfs role                 fatal
| Your installation contains roles that have gphdfs privileges.
| These privileges need to be revoked before upgrade.  A list
| of roles and their corresponding gphdfs privileges that
| must be revoked is provided in the file:
|       gphdfs_user_roles.txt

Running: Checking for unique or primary key constraints...
Checking for unique or primary key constraints              ok 93.371ms
Running: Checking array types derived from partitions...
Checking array types derived from partitions                ok 139.677ms
Running: Checking for large objects...
Checking for large objects                                  ok 40.670ms
Running: Checking for invalid indexes...
Checking for invalid indexes                                ok 38.641ms
Running: Checking for tables distributed on duplicated columns...
Checking for tables distributed on duplicated columns       ok 41.714ms
Running: Checking for views with lead/lag functions using bigint...
Checking for views with lead/lag functions using bigint     ok 527.145ms
Running: Checking for non-dumpable views with anyarray casts...
Checking for non-dumpable views with anyarray casts         ok 148.145ms
Running: Checking for non-dumpable views with unknown casts...
Checking for non-dumpable views with unknown casts          ok 161.048ms
Running: Checking for views referencing deprecated tables...
Checking for views referencing deprecated tables            ok 120.750ms
Running: Checking for views referencing deprecated columns...
Checking for views referencing deprecated columns           ok 149.738ms
===============================================

Checking for tsquery user columns                           ok 48.343ms
Checking for contrib/ltree                                  ok 51.128ms
Checking for hash partitioned tables                        ok 48.352ms
Checking for tsvector user columns                          ok 54.649ms
Checking for hash and GIN indexes                           ok 60.753ms
Checking for bpchar_pattern_ops indexes                     ok 91.139ms
Checking for presence of required libraries                 ok 15.256ms
Checking database user is a superuser                       ok 24.569ms
Checking for prepared transactions                          ok 17.458ms
```

With parallelism (jobs=4)...
```
Performing Consistency Checks on Old Live Server
------------------------------------------------
Checking cluster versions                                   ok 55.820ms
Creating a dump of all tablespace metadata.                 ok 21.736ms
Checking database user is a superuser                       ok 9.695ms
Checking database connection settings                       ok 27.970ms
Checking for prepared transactions                          ok 18.114ms
Checking for reg* system OID user data types                ok 78.932ms
Checking for contrib/isn with bigint-passing mismatch       ok 60.740ms

Starting parallel Greenplum checks (--jobs=4):
===============================================
Running: Checking for non-covering indexes on partitioned AO tables...
Running: Checking AO/CO parent partitions with pg_aoseg entries...
Running: Checking for heterogeneous partitioned tables...
Running: Checking for indexes on partitioned tables...
Checking for non-covering indexes on partitioned AO tables  ok 127.881ms
Running: Checking for foreign key constraints on root partitions...
Checking AO/CO parent partitions with pg_aoseg entries      ok 202.687ms
Running: Checking for orphaned TOAST relations...
Checking for heterogeneous partitioned tables               ok 253.194ms
Running: Checking for gphdfs external tables...
Checking for foreign key constraints on root partitions     ok 180.710ms
Running: Checking for users assigned the gphdfs role...
Checking for orphaned TOAST relations                       ok 110.790ms
Running: Checking for unique or primary key constraints...
Checking for indexes on partitioned tables                  ok 339.392ms
Running: Checking array types derived from partitions...
Checking for users assigned the gphdfs role                 fatal
| Your installation contains roles that have gphdfs privileges.
| These privileges need to be revoked before upgrade.  A list
| of roles and their corresponding gphdfs privileges that
| must be revoked is provided in the file:
| 	gphdfs_user_roles.txt

Running: Checking for large objects...
Checking for gphdfs external tables                         ok 176.745ms
Running: Checking for invalid indexes...
Checking for large objects                                  ok 79.259ms
Running: Checking for tables distributed on duplicated columns...
Checking for unique or primary key constraints              ok 171.168ms
Running: Checking for views with lead/lag functions using bigint...
Checking for invalid indexes                                ok 95.484ms
Running: Checking for non-dumpable views with anyarray casts...
Checking for tables distributed on duplicated columns       ok 92.736ms
Running: Checking for non-dumpable views with unknown casts...
Checking array types derived from partitions                ok 293.538ms
Running: Checking for views referencing deprecated tables...
Checking for non-dumpable views with anyarray casts         ok 247.976ms
Running: Checking for views referencing deprecated columns...
Checking for non-dumpable views with unknown casts          ok 203.299ms
Checking for views referencing deprecated tables            ok 229.188ms
Checking for views referencing deprecated columns           ok 205.470ms
Checking for views with lead/lag functions using bigint     ok 682.045ms
===============================================

Checking for tsquery user columns                           ok 61.181ms
Checking for contrib/ltree                                  ok 58.943ms
Checking for hash partitioned tables                        ok 61.584ms
Checking for tsvector user columns                          ok 80.037ms
Checking for hash and GIN indexes                           ok 83.327ms
Checking for bpchar_pattern_ops indexes                     ok 102.251ms
Checking for presence of required libraries       [...]

2023-06-09 01:34 UTC, kalensk commented
To me it looks a bit out of  place to see the ` (--jobs=4):` in the header output. I'd remove it in favor of keeping it clean with just `Starting Parallel Greenplum Checks`, with each of the words capitalized. Not a huge deal either way though.

The gpupgrade docs or similar seem like a good place to explain that parallel checks are influenced by the gpupgrade `--pg-upgrade-jobs` value.

2023-06-12 23:44 UTC, jimmyyih commented
> To me it looks a bit out of place to see the ` (--jobs=4):` in the header output. I'd remove it in favor of keeping it clean with just `Starting Parallel Greenplum Checks`, with each of the words capitalized. Not a huge deal either way though.
> 
> The gpupgrade docs or similar seem like a good place to explain that parallel checks are influenced by the gpupgrade `--pg-upgrade-jobs` value.

Sure, updated.  It'll look like this now:
```
Starting Parallel Greenplum Checks
==================================
Running: Checking for non-covering indexes on partitioned AO tables...
Checking for non-covering indexes on partitioned AO tables  ok 65.491ms
Running: Checking AO/CO parent partitions with pg_aoseg entries...
Checking AO/CO parent partitions with pg_aoseg entries      ok 90.862ms
Running: Checking for heterogeneous partitioned tables...
Checking for heterogeneous partitioned tables               ok 133.781ms
Running: Checking for indexes on partitioned tables...
Checking for indexes on partitioned tables                  ok 175.157ms
Running: Checking for foreign key constraints on root partitions...
Checking for foreign key constraints on root partitions     ok 83.858ms
Running: Checking for orphaned TOAST relations...
Checking for orphaned TOAST relations                       ok 61.456ms
Running: Checking for gphdfs external tables...
Checking for gphdfs external tables                         ok 73.965ms
Running: Checking for users assigned the gphdfs role...
Checking for users assigned the gphdfs role                 fatal
| Your installation contains roles that have gphdfs privileges.
| These privileges need to be revoked before upgrade.  A list
| of roles and their corresponding gphdfs privileges that
| must be revoked is provided in the file:
| 	gphdfs_user_roles.txt

Running: Checking for unique or primary key constraints...
Checking for unique or primary key constraints              ok 113.354ms
Running: Checking array types derived from partitions...
Checking array types derived from partitions                ok 168.970ms
Running: Checking for large objects...
Checking for large objects                                  ok 51.890ms
Running: Checking for invalid indexes...
Checking for invalid indexes                                ok 47.221ms
Running: Checking for tables distributed on duplicated columns...
Checking for tables distributed on duplicated columns       ok 51.931ms
Running: Checking for views with lead/lag functions using bigint...
Checking for views with lead/lag functions using bigint     ok 595.071ms
Running: Checking for non-dumpable views with anyarray casts...
Checking for non-dumpable views with anyarray casts         ok 167.622ms
Running: Checking for non-dumpable views with unknown casts...
Checking for non-dumpable views with unknown casts          ok 163.046ms
Running: Checking for views referencing deprecated tables...
Checking for views referencing deprecated tables            ok 166.689ms
Running: Checking for views referencing deprecated columns...
Checking for views referencing deprecated columns           ok 185.048ms
==================================
```
Main thought for adding the jobs info in the output was to make it easier to see what parallelism it was set at instead of having to cross-reference with other log files when looking at collected logs; but I'm fine with removing it.

2023-06-14 00:36 UTC, kyeap-vmware approved these changes

2023-06-14 01:38 UTC, kalensk commented on contrib/pg_upgrade/pg_upgrade.h
> +__attribute__((format(PG_PRINTF_ATTRIBUTE, 2, 3)));
Interesting. Is there a way to update the existing functions to use the "parallel" implementations leaving just one set of functions? That way both the parallel and non-parallel use the same function for simplicity and ease. Keeps things simple and extensible.


Alternatively, I would have overloaded the existing functions. That is, kept the existing naming with the new parameters such as instead of `parallel_check_ok` call it `check_ok`, and `parallel_gp_fatal_log` had `gp_fatal_log`, etc. If needed a comment above the function names describing their use case and allowing people to see the different usage/pattern in `check_gp.c` vs. `check.c`. 

Not a problem just an observation.

2023-06-14 01:38 UTC, kalensk commented on contrib/pg_upgrade/greenplum/check_gp.c
> +parallel_checks_reap_child(bool wait_for_child)
Is there a reason why `check_greenplum_parallel_jobs` isn't passed to this function to avoid a global variable? Or is this a known pattern in the C code?

Multiple threads aren't mutating `check_greenplum_parallel_jobs` since its just a plain `int`.

2023-06-14 01:39 UTC, kalensk commented on contrib/pg_upgrade/greenplum/check_gp.c
> +	char	   *test_description = "Checking for online expansion status";
Not a big deal but maybe something like `check_name`, `name`, or even `check_description` instead.

2023-06-14 01:48 UTC, kalensk commented on contrib/pg_upgrade/greenplum/check_gp.c
> + */
Just thinking out loud, wondering if there is a way of making the parallel code generic to work for both `parallel_check_greenplum` and `parallel_checks_reap_child` and `parallel_transfer_all_new_dbs` and `reap_child`. I guess C doesn't make it to easy and there are only two places at the moment. Might be nice otherwise.

2023-06-15 22:39 UTC, jimmyyih commented on contrib/pg_upgrade/greenplum/check_gp.c
> +parallel_checks_reap_child(bool wait_for_child)
> Is there a reason why check_greenplum_parallel_jobs isn't passed to this function to avoid a global variable? Or is this a known pattern in the C code?

Using a global counter is cleaner than passing around the address of a locally scoped counter here and is common.  It also matches with Postgres pg_upgrade logic (see `contrib/pg_upgrade/parallel.c` where this logic was inspired from).  Another example is the timer in `contrib/pg_upgrade/util.c` which is used to record the individual start/stop of each check.

> I guess multiple threads aren't mutating check_greenplum_parallel_jobs since its just a plain int.

There's no threading so it wouldn't matter.  The parallelism is done with forking which will create individual separate copies of the globals which can only be shared via IPC shared memory (which we don't do here since it's not needed).  The parent process will increment/decrement its counter without worry.

2023-06-15 23:02 UTC, jimmyyih commented on contrib/pg_upgrade/greenplum/check_gp.c
> + */
> I guess C doesn't make it to easy

Correct, it would not look clean at all... especially when having to deal with upstream Postgres merging which unfortunately disincentivizes us from building something more generic... otherwise I would've probably spent time to do so.

> there are only two places at the moment.

With this PR, it'll be three.  The `reap_child` call is for both `parallel_transfer_all_new_dbs` and `parallel_exec_prog`.  That generic works whereas `parallel_check_greenplum` and `parallel_checks_reap_child` has their own unique requirements to enable the GPDB checks to run completely without exiting early from a fatal.

2023-06-15 23:24 UTC, jimmyyih commented on contrib/pg_upgrade/pg_upgrade.h
> +__attribute__((format(PG_PRINTF_ATTRIBUTE, 2, 3)));
> Is there a way to update the existing functions to use the "parallel" implementations leaving just one set of functions?

There are but it would look messy and hacky.  Having this separate function was much more cleaner to work with for the parallelism logic.

> I would have overloaded the existing functions

Overloading functions is generally better for functions that need generic arg type handling (e.g. `floor(int)`, `floor(float)`) to do the exact same logic.  Overloading variadic functions like `gp_fatal_log` can get really, really messy and would likely cause issues.  I would highly recommend not doing that or it would at least need extreme care.  For example, would `gp_fatal_log("abc", "abc2", "abc3")` call `gp_fatal_log(string, ...)` or `gp_fatal_log(string, string, ...)`?

2023-06-15 23:30 UTC, jimmyyih commented on contrib/pg_upgrade/greenplum/check_gp.c
> +	char	   *test_description = "Checking for online expansion status";
Sure, that makes sense since we call these checks instead of tests.  Changed to `check_name`.

2023-06-20 06:17 UTC, kalensk approved these changes

2023-06-22 17:09 UTC, merged