Docs: modified documentation so references to postgis packages pivota…
greenplum-db/gpdb pull request #15836
Opened 2023-06-23 13:04 UTC by mperezfuster

Current GPDB 6 documentation pages refer to PostGIS pivotal.3 packages where later versions are available:
https://docs.vmware.com/en/VMware-Greenplum/6/greenplum-database/install_guide-platform-requirements-overview.html
https://docs.vmware.com/en/VMware-Greenplum/6/greenplum-database/analytics-postgis-upgrade.html
This has caused some confusion among customers when trying to upgrade PostGIS version.
With the exception of pivotal.1 and pivotal.2, the rest of the pivotal.x package mentions can be applied to any recent versions (ie we can upgrade to PostGIS 2.5.4+pivotal.8 and not just to PostGIS 2.5.4 pivotal.3).
I modified the references to pivotal.3 to include later versions. Let me know if it is clear enough or it should be explained in a different way.

2023-06-23 17:31 UTC, dyozie requested changes

2023-06-23 17:31 UTC, dyozie commented on gpdb-doc/markdown/analytics/postgis-upgrade.html.md
> +-   [Upgrading from PostGIS 2.1.5 to the PostGIS 2.5.4 pivotal.3 (and onwards) Package](#topic_zgw_v5x_3mb)
and onwards -> and later

(global change)

2023-06-26 17:26 UTC, dyozie approved these changes

2023-06-27 22:57 UTC, lisakowen approved these changes
looks good.  wondering if we wouldn't want to just use a plus sign instead of (and later), i.e. "Upgrading from PostGIS 2.1.5 to a PostGIS 2.5.4 pivotal.3+ Package"

2023-06-28 08:23 UTC, mperezfuster commented
> looks good. wondering if we wouldn't want to just use a plus sign instead of (and later), i.e. "Upgrading from PostGIS 2.1.5 to a PostGIS 2.5.4 pivotal.3+ Package"

@lisakowen I thought about that but I noticed that the package names have the format `postgis-2.5.4+pivotal.3.build.1` and have already a plus sign and it may have looked confusing?

2023-06-28 16:17 UTC, lisakowen commented
yeah, i agree that could be confusing with the plus sign being a component of the download file name.

2023-06-30 07:13 UTC, nimish350 commented
LGTM +1

2023-06-30 07:47 UTC, shrakesh approved these changes
LGTM +1

2023-06-30 15:28 UTC, merged