Docs advanced password check
greenplum-db/gpdb pull request #15833
Opened 2023-06-23 09:01 UTC by mperezfuster

Documenting new features for advanced_password_check module for 6.25.0.
Review site: https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-advanced_password_check/greenplum-database/ref_guide-modules-adv_passwd_check.html
@radarwave Let me know if we should cherry-pick all these changes to 7.x as well.

2023-06-23 18:36 UTC, dyozie requested changes

2023-06-23 18:36 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +The `advanced_password_check` module provides no SQL-accessible functions. To use it, enable the extension as a preloaded library and restart Greenplum Database server:
Greenplum Database server -> Greenplum Database

2023-06-23 18:36 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +-   Set a maximum password age before it requires renewing.
it requires renewing -> the password expires

2023-06-23 18:36 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +-   Set rules for reusing an old password: number of days or number of previous passwords before a user can reuse a password.
number -> the number

2023-06-23 18:36 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +-   Set maximum number of failed log in attempts before a user is locked, and number of minutes the user remains locked.
Set maximum -> Set the maximum
and number -> and the number

2023-06-23 18:36 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +|lockout_duration|int|0|Number of minutes a user is locked after reaching password_login_attempts. If set to 0, user is locked indefinitely.|
Number -> The number
user -> the user

2023-06-23 18:36 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +|maximum\_length|int|15|The maximum allowable length of Greenplum Database password.|
of Greenplum -> of a Greenplum

2023-06-23 18:36 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +|password_login_attempts|int|0|Number of failed log in attempts before a user is locked. If set to 0, this feature is disabled.|
Number -> The number

2023-06-23 18:36 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +|password_max_age|int|0|The maximum amount of days before the password expires. If set to 0, password does not expire.|
, password -> , the password

2023-06-23 18:36 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +|password_reuse_days|int|0|Number of days before a user can reuse a password. If set to 0, user can reuse any password.|
Number -> The number
, user -> , the user

x2

2023-06-23 18:36 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +|password_reuse_days|int|0|Number of days before a user can reuse a password. If set to 0, user can reuse any password.|
user must not reuse -> a user cannot reuse

2023-06-23 18:36 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +|`manage_exception_list(action, role_name, exception_type)`|- `action` can be *add*, *remove*, or *show* <br>- `role_name`<br>- `exception_type` can be *password_max_age*, *password_reuse_days*, *pas
Seems like you should remove role_name from the Description, since it just repeats the option with no further info?

2023-06-23 18:36 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +|`unblock_account(role_name)`|`role_name`|Unblocks a user.|
user -> role

?

2023-06-23 18:36 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +For example, add the user `sales` to the exception list for `password_max_age`, so the user does not have a password expiration date:
add -> to add

2023-06-26 08:19 UTC, mperezfuster commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +|`manage_exception_list(action, role_name, exception_type)`|- `action` can be *add*, *remove*, or *show* <br>- `role_name`<br>- `exception_type` can be *password_max_age*, *password_reuse_days*, *pas
It's not on the description column but the argument value one. I have them there so it's listed as a required argument. I could add a short description if that makes it look better?

2023-06-27 23:18 UTC, lisakowen commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +gpconfig -c shared_preload_libraries -v advanced_password_check
i think this command will set shared_preload_libraries to advanced_password_check, and will lose other libraries that had been previously set here.  i think we'd want to show what it is currently set to then retain those settings, something like:
```
gpconfig -s shared_preload_libraries
... output
gpconfig -c shared_preload_libraries -v <other_libraries>,advanced_password_check
```

2023-06-27 23:18 UTC, lisakowen commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +-   Set rules for reusing an old password: the number of days or number of previous passwords before a user can reuse a password.
or number of -> or the number of ?

2023-06-27 23:18 UTC, lisakowen commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +-   Set the maximum number of failed log in attempts before a user is locked, and the number of minutes the user remains locked.
log in -> login (log in is a verb) ?

2023-06-27 23:18 UTC, lisakowen commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +|password_max_age|int|0|The maximum amount of days before the password expires. If set to 0, the password does not expire.|
amount of -> number ?

2023-06-27 23:18 UTC, lisakowen commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +gpconfig -c advanced_password_check.lockoout_duration -v 60
lockoout_duration -> lockout_duration

2023-06-27 23:18 UTC, lisakowen commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +-   The user must be blocked during an hour after three unsuccessful log in attempts.
what about "The user must be blocked for an hour after the third of three unsuccessful log in attempts."?

2023-06-27 23:18 UTC, lisakowen commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +
i don't think you need to use the term "user-defined" to qualify function after the table.

2023-06-27 23:18 UTC, lisakowen commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +Use the `manage_exception_list()` user-defined function to manage the exception list for a password policy. The users within the exception list do not enforce the rules set for the policy.
The users within the exception list do not enforce the rules set for the policy -> Greenplum does not enforce the rules set for the policy for any user specified in the exception list. ?

2023-06-27 23:18 UTC, lisakowen commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +|`manage_exception_list(action, role_name, exception_type)`|- `action` can be *add*, *remove*, or *show* <br>- `role_name`<br>- `exception_type` can be *password_max_age*, *password_reuse_days*, *pas
this confused me a bit.  the exception_types are fixed, not sure why they are in italics here.  and when they are actually used in a command, they must be single-quoted strings.  same for the actions.

2023-06-28 08:36 UTC, mperezfuster commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +|`manage_exception_list(action, role_name, exception_type)`|- `action` can be *add*, *remove*, or *show* <br>- `role_name`<br>- `exception_type` can be *password_max_age*, *password_reuse_days*, *pas
thanks Lisa, I have been trying different things with the formatting within this table. Would you say I should have them single-quoted and also code formatted?

2023-06-28 08:40 UTC, mperezfuster commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +gpconfig -c shared_preload_libraries -v advanced_password_check
@liuxueyang can you confirm this please?

2023-06-28 09:01 UTC, liuxueyang commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +gpconfig -c shared_preload_libraries -v advanced_password_check
@mperezfuster The comment by @lisakowen is more appropriate.

2023-06-28 09:09 UTC, liuxueyang commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
>  -   The password must contain at least one of the default special characters.
Missing config for restrict_special in the snippet below.

2023-06-28 09:49 UTC, mperezfuster commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +gpconfig -c shared_preload_libraries -v advanced_password_check
how about now?

2023-06-28 09:57 UTC, mperezfuster commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
>  -   The password must contain at least one of the default special characters.
Do you mean that we didn't give provide the gpconfig command to set restrict_special? If the default value is true we shouldn't have to specify it explicitly if I am correct?

2023-06-28 14:38 UTC, lisakowen commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +|`manage_exception_list(action, role_name, exception_type)`|- `action` can be *add*, *remove*, or *show* <br>- `role_name`<br>- `exception_type` can be *password_max_age*, *password_reuse_days*, *pas
what about code-fonting all of the literals (the actions and the exception types) without single quotes, and in the Description state something like "Specify all function arguments as single-quoted strings."?

2023-06-28 14:38 UTC, lisakowen approved these changes

2023-06-29 02:31 UTC, liuxueyang approved these changes

2023-06-29 08:48 UTC, radarwave commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +|password_login_attempts|int|0|The number of failed login attempts before a user is locked. If set to 0, this feature is disabled.|
Could it be better to say 'consecutive failed login attempts'?

2023-06-29 08:48 UTC, radarwave commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +|lockout_duration|int|0|The number of minutes a user is locked after reaching password_login_attempts. If set to 0, the user is locked indefinitely.|
Better to sort the sequence of GUCs list by different kinds.

2023-06-29 08:48 UTC, radarwave approved these changes

2023-07-05 14:51 UTC, lisakowen commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +> **Note** The password history information is stored in the Greenplum master host only. In the event of a primary master failure, if you activate the standby master host, the `advanced_password_modu
advanced_password_module -> advanced_password_check module ?

"... information, and it will affect any server configuration parameter or UDFs that involve password history information." -> what about something like "... data. This includes information returned by the server configuration parameters and UDFs that access password history data.

2023-07-05 14:51 UTC, lisakowen commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +gpconfig -c shared_preload_libraries -v <other_libraries>,advanced_password_check
i think the -v option value should be in single quotes:  '<other_libraries>,advanced_password_check'

2023-07-05 21:46 UTC, dyozie approved these changes

2023-07-05 21:46 UTC, merged