Docs: added failedHostname column to gprecoverseg input file
greenplum-db/gpdb pull request #15908
Opened 2023-07-03 12:30 UTC by mperezfuster

PR https://github.com/greenplum-db/gpdb/pull/15566 introduces a new column `failedHostfile` to the input file for gprecoverseg. This PR modifies the documentation so the new column is introduced.

2023-07-03 17:32 UTC, piyushc01 commented on gpdb-doc/markdown/admin_guide/highavail/topics/g-recovering-from-segment-failures.html.md
> +    1.  Manually create a `recover_config_file` file in a location of your choice, where each segment to recover has its own line with format `failedHostname|failedAddress|failedPort|failedDataDirect
Host-name is an optional parameter. Newly introduced changes implement support to specify hostname otherwise existing options are also supported. 

The supported format is: 
`failedHostname|failedAddress|failedPort|failedDataDirectory`
And 
`failedHostname|failedAddress|failedPort|failedDataDirectory SPACE failoverHostname|failoverAddress|failoverPort|failoverDataDirectory`

And previously supported recovery config options with address, port and data-directory are also valid.

2023-07-05 14:59 UTC, dyozie commented on gpdb-doc/markdown/utility_guide/ref/gprecoverseg.html.md
> +By default, a failed segment is recovered in place, meaning that the system brings the segment back online on the same host and data directory location on which it was originally configured. In this
Should this be failed_host_name throughout (with an extra underscore)? That's the format I saw in the engineering PR and it also matches failed_host_address.

2023-07-06 05:36 UTC, kpraveen457 requested changes

2023-07-06 05:36 UTC, kpraveen457 commented on gpdb-doc/markdown/utility_guide/ref/gprecoverseg.html.md
> +<failed_host_name>|<failed_host_address>|<port>|<data_directory><SPACE><recovery_host_address>|<port>|<data_directory>
I think <recovery_host_name> is missing out on the target segment.
It should be like `<failed_host_name>|<failed_host_address>|<port>|<data_directory><SPACE><recovery_host_name>|<recovery_host_address>|<port>|<data_directory>`

2023-07-06 09:08 UTC, piyushc01 commented on gpdb-doc/markdown/admin_guide/highavail/topics/g-recovering-from-segment-failures.html.md
> +        failedHostname1|failedAddress1|failedPort1|failedDataDirectory1<SPACE>failedHostname2|failedAddress2|failedPort2|failedDataDirectory2
```suggestion
        failedHostname1|failedAddress1|failedPort1|failedDataDirectory1<SPACE>recoverHostname2|recoveryAddress2|recoveryPort2|recoveryDataDirectory2
```

2023-07-14 15:33 UTC, dyozie approved these changes

2023-07-14 15:44 UTC, merged