Docs: added new features to advanced_passsword_check module
greenplum-db/gpdb pull request #15936
Opened 2023-07-06 14:33 UTC by mperezfuster

This PR ports the changes made in PR https://github.com/greenplum-db/gpdb/pull/15833 for 6X_STABLE branch to the main branch.

2023-07-06 14:47 UTC, dyozie requested changes

2023-07-06 14:47 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +---
Just FYI - for regular .md files it's not necessary to have the H1 as a metadata block like this.

2023-07-06 14:47 UTC, dyozie commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +> **Note** The password history information is stored in the Greenplum master host only. In the event of a primary master failure, if you activate the standby master host, the `advanced_password_chec
Global change master -> coordinator for this PR into main.

2023-07-14 03:35 UTC, radarwave commented on gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
> +|lockout_duration|int|0|The number of minutes a user is locked after reaching password_login_attempts. If set to 0, the user is locked indefinitely.|
Can we sort the parameters in this table, to make the previous release password policy on the top and the newly added features on the bottom?

And related parameters should be together for easy finding. For example, lockout_duration can not exist on its own, it's related to password_login_attempts.

2023-07-18 02:38 UTC, liuxueyang commented
I've added a section about upgrade section in the document. We need to add that now. Thanks

2023-07-31 08:50 UTC, liuxueyang approved these changes

2023-07-31 18:46 UTC, dyozie approved these changes

2023-07-31 18:46 UTC, merged