Docs gpv reference
greenplum-db/gpdb pull request #16051
Opened 2023-07-24 11:52 UTC by mperezfuster

The Greenplum Virtual Appliance introduces the `gpv` utility. This PR adds the gpv commands to the Greenplum utility reference guide.

Review site:
https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/gpv-gva/greenplum-database/utility_guide-ref-gpv.html
Few points:
- The section "Required Inputs" lists all the data user needs to know before starting with the configuration. We decided to bring the table to the reference pages and not the narrative pages in order to have it in one place only, and since the table items are mapped into the command options and sub-options, any future changes to the commands would only have to be reflected on this page.
- How to distribute the gpv reference pages? Currently they are split into three different subpages due to how extensive `gpv config` is. But the other two are very small so maybe it makes more sense to have everything together on one reference page?
- How to format the examples, in particular for the `gpv config` settings and sub-settings?
- @kmacoskey I will need advice on what to do with the section "*Greenplum performs best with jumbo frames. The recommended MTU is 9000 if the VDS supports it. If it's less than 9000, you need to adjust the server configuration parameter [gp_max_packet_size](https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/gpv-gva/greenplum-database/ref_guide-config_params-guc-list.html#gp_max_packet_size) manually.". How do we need to edit it?

2023-07-24 21:48 UTC, dyozie approved these changes

2023-07-25 01:22 UTC, dyozie requested changes

2023-07-25 01:24 UTC, dyozie requested changes

2023-07-25 01:24 UTC, dyozie commented on gpdb-doc/markdown/utility_guide/ref/gpv-config.html.md
> +gpv config <command>
I think calling out the different syntax options here would clarify things:

gpv config list
gpv config set 
gpv config init <file_name>

2023-07-25 02:08 UTC, dyozie requested changes

2023-07-25 02:08 UTC, dyozie commented on gpdb-doc/markdown/utility_guide/ref/gpv-config.html.md
> +gpv config set <area>
The level of nesting with this command is a hot mess. I think we should try to summarize the number of nesting levels here to help avoid confusion:

gpv config set database <option> <value>
    | config set vm <option> <value>
    | config set vsphere <option> <value>
    | config set network base-vm <option> <value>
    | config set network gp-virtual-etl-bar <option> <value>
    | config set network gp-virtual-external <option> <value>
    | config set network gp-virtual-internal <option> <value>

2023-08-16 17:52 UTC, kmacoskey approved these changes

2023-08-31 07:35 UTC, RanitGoyal reviewed
These comments are based on the finding of hallway testing [GPV-1720](https://jira.eng.vmware.com/browse/GPV-1720)

2023-08-31 07:35 UTC, RanitGoyal commented on gpdb-doc/markdown/utility_guide/ref/gpv.html.md
> +|Number of Primay Segment virtual machines | The number of virtual machines for the primary segments. <br/> - For a `mirrored` deployment type the value is `number of primary segments * 2 + 2`. <br/>
Number of Primary Segments virtual machine is a duplicate entry with configurations paramters for the virtual machine, we can get rid of it from here, it has to be part of vm configurations only

2023-08-31 07:35 UTC, RanitGoyal commented on gpdb-doc/markdown/utility_guide/ref/gpv.html.md
> +|Storage name|The datastore name for this deployment|
Storage policy is also a parameter under vsphere, it will be good to add it

2023-08-31 07:35 UTC, RanitGoyal commented on gpdb-doc/markdown/utility_guide/ref/gpv.html.md
> +## <a id="exs"></a>Examples
As per discussion in hallway testing this section can we removed.

2023-08-31 07:35 UTC, RanitGoyal commented on gpdb-doc/markdown/utility_guide/ref/gpv.html.md
> +|number of primary segment VMs|The number of virtual machines for the primary segments. <br/> - for `mirrored` the total number of virtual machines is `number of primary segments * 2 + 2`. <br/> - fo
Simplify the description of number of primary segments, and move the configurations from gpv page to gpv config page. refer the story link [GPV-1783](https://jira.eng.vmware.com/browse/GPV-1783) check the utility section mentioned in description of the story

2023-08-31 08:45 UTC, mperezfuster commented on gpdb-doc/markdown/utility_guide/ref/gpv.html.md
> +## <a id="exs"></a>Examples
Is there a particular reason why we want the example section removed? We usually have this section at the end of every command reference page.

2023-08-31 08:52 UTC, mperezfuster commented on gpdb-doc/markdown/utility_guide/ref/gpv.html.md
> +|number of primary segment VMs|The number of virtual machines for the primary segments. <br/> - for `mirrored` the total number of virtual machines is `number of primary segments * 2 + 2`. <br/> - fo
I am happy to add the calculations on the gpv config page as well, but I think it's important to keep it on this table, as we ask users to have this information ready beforehand when [Configuring the virtual machine template](https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/gpv-gva/greenplum-database/vsphere-deploying-greenplum-on-vsphere.html#configuring-the-virtual-machine-base-template).

2023-08-31 09:01 UTC, RanitGoyal commented on gpdb-doc/markdown/utility_guide/ref/gpv.html.md
> +## <a id="exs"></a>Examples
@djianwen-vmware can you please address, as you have better context on the findings.

2023-08-31 15:47 UTC, xinzweb commented on gpdb-doc/markdown/utility_guide/ref/gpv.html.md
> +-version
```suggestion
version
```

There is no `-` before the `version. Thanks.

2023-08-31 15:52 UTC, xinzweb commented on gpdb-doc/markdown/utility_guide/ref/gpv.html.md
> +|number of primary segment VMs|The number of virtual machines for the primary segments. <br/> - for `mirrored` the total number of virtual machines is `number of primary segments * 2 + 2`. <br/> - fo
We will remove the `mirrored` and `mirrorless` computations, since those are misleading. We only care about the primary VMs.

Also, as we discussed in the NA standup, we still think the table should be moved to the `gpv config`.

Yes, those informations are important to have before the [Configuring the virtual machine template](https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/gpv-gva/greenplum-database/vsphere-deploying-greenplum-on-vsphere.html#configuring-the-virtual-machine-base-template). But, those information should already in the pre-requisite page where the customer need to collect.

Thanks.

2023-08-31 15:59 UTC, mperezfuster commented on gpdb-doc/markdown/utility_guide/ref/gpv.html.md
> +|number of primary segment VMs|The number of virtual machines for the primary segments. <br/> - for `mirrored` the total number of virtual machines is `number of primary segments * 2 + 2`. <br/> - fo
The prerequisites page does not list all this information that user needs to collect, or at least it does not exactly identify the name of the equivalent `gpv` inputs. Myself and @kmacoskey agreed that it would be best to have one single table that collects this information as command options can change over time, so we don't have duplicated lists/tables of information to collect that can get out of sync. I am happy to move it to `gpv config` subpage, but we should always point to a single list of data to collect, if that makes sense?

2023-09-01 14:23 UTC, kmacoskey commented on gpdb-doc/markdown/utility_guide/ref/gpv.html.md
> +|number of primary segment VMs|The number of virtual machines for the primary segments. <br/> - for `mirrored` the total number of virtual machines is `number of primary segments * 2 + 2`. <br/> - fo
👍

2023-09-01 14:26 UTC, xinzweb commented on gpdb-doc/markdown/utility_guide/ref/gpv.html.md
> +|number of primary segment VMs|The number of virtual machines for the primary segments. <br/> - for `mirrored` the total number of virtual machines is `number of primary segments * 2 + 2`. <br/> - fo
make sense. Let's do it. Thanks

2023-09-01 14:41 UTC, mperezfuster commented on gpdb-doc/markdown/utility_guide/ref/gpv.html.md
> +|number of primary segment VMs|The number of virtual machines for the primary segments. <br/> - for `mirrored` the total number of virtual machines is `number of primary segments * 2 + 2`. <br/> - fo
Just to confirm, do we move the table to gpv config or leave it here?

2023-09-05 18:37 UTC, kmacoskey commented on gpdb-doc/markdown/utility_guide/ref/gpv.html.md
> +|number of primary segment VMs|The number of virtual machines for the primary segments. <br/> - for `mirrored` the total number of virtual machines is `number of primary segments * 2 + 2`. <br/> - fo
It can be moved to gpv config

2023-09-06 22:00 UTC, dyozie approved these changes

2023-09-06 22:01 UTC, merged