Add stats info for Vars in CTEs.
greenplum-db/gpdb pull request #16178
Opened 2023-08-09 07:39 UTC by Aegeaner

In the function selfuncs.c:eqjoinsel  it uses the number of the distinct values of the two join variables to estimate join size, and in the function  `selfuncs.c:get_variable_numdistinct`  return a default value `DEFAULT_NUM_DISTINCT` (200 in Postgres and 1000 in Greenplum),  with the default value, you can never expect a good plan.

A mini-repro is:
```sql
postgres=# create table t(x int, y int);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'x' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
postgres=# insert into t select i, i from generate_series(1, 100000) i;
INSERT 0 100000
postgres=# anaylze;
postgres=#  explain analyze with cte(x,y,z) as  (select *, random() from t) select * from cte m, cte n where m.x=n.y ;
```
Before the patch, we got a plan with bad join size estimation:
```sql
                                                                     QUERY PLAN                                                                      
-----------------------------------------------------------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)  (cost=870.33..307629.56 rows=10000000 width=32) (actual time=25.434..118.804 rows=100000 loops=1)
   ->  Hash Join  (cost=870.33..174296.22 rows=3333333 width=32) (actual time=24.784..85.076 rows=33462 loops=1)
         Hash Cond: (t.y = t_1.x)
         Extra Text: (seg0)   Hash chain length 1.0 avg, 3 max, using 32439 of 524288 buckets.
         ->  Redistribute Motion 3:3  (slice2; segments: 3)  (cost=0.00..1120.33 rows=33333 width=16) (actual time=0.072..18.581 rows=33462 loops=1)
               Hash Key: t.y
               ->  Seq Scan on t  (cost=0.00..453.67 rows=33333 width=16) (actual time=0.057..11.490 rows=33462 loops=1)
         ->  Hash  (cost=453.67..453.67 rows=33333 width=16) (actual time=24.105..24.106 rows=33462 loops=1)
               Buckets: 524288  Batches: 1  Memory Usage: 5665kB
               ->  Seq Scan on t t_1  (cost=0.00..453.67 rows=33333 width=16) (actual time=0.037..11.040 rows=33462 loops=1)
 Optimizer: Postgres query optimizer
 Planning Time: 0.667 ms
```

After the patch applied, we got:
```sql
                                                                     QUERY PLAN                                                                      
-----------------------------------------------------------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)  (cost=870.33..3782.33 rows=100000 width=32) (actual time=28.715..88.846 rows=100000 loops=1)
   ->  Hash Join  (cost=870.33..2449.00 rows=33333 width=32) (actual time=27.515..70.070 rows=33462 loops=1)
         Hash Cond: (t.y = t_1.x)
         Extra Text: (seg0)   Hash chain length 1.0 avg, 3 max, using 32439 of 524288 buckets.
         ->  Redistribute Motion 3:3  (slice2; segments: 3)  (cost=0.00..1120.33 rows=33333 width=16) (actual time=0.074..16.497 rows=33462 loops=1)
               Hash Key: t.y
               ->  Seq Scan on t  (cost=0.00..453.67 rows=33333 width=16) (actual time=0.132..10.108 rows=33462 loops=1)
         ->  Hash  (cost=453.67..453.67 rows=33333 width=16) (actual time=25.522..25.523 rows=33462 loops=1)
               Buckets: 524288  Batches: 1  Memory Usage: 5665kB
               ->  Seq Scan on t t_1  (cost=0.00..453.67 rows=33333 width=16) (actual time=0.072..11.546 rows=33462 loops=1)
 Optimizer: Postgres query optimizer
 Planning Time: 2.570 ms
```

The join size estimation on the upper of CTE scans became much accurate.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2023-08-09 08:04 UTC, Aegeaner commented
A temporary dev pipeline for the PR: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/rocky9

2023-08-09 08:20 UTC, Aegeaner commented
> It seems that explain analyze Planning Time increases, from 0.667 ms to 2.570 ms?

It may because of I have run explain analyze for several times and the explain results got cached, so later explain commands all got average timing for about 0.5 ms.

2023-08-09 12:55 UTC, kainwen requested changes
-1.
I don't think this change is reasonable. How can we say Vars from CTE must be unique?

This is also an upstream problem and should firstly open discussion on upstream and then backport.

Please close all these kinds of PRs if there are no obvious upstream discussion results.

2023-08-10 09:30 UTC, Aegeaner commented
Found an interesting failing test case in my dev pipeline, which is part of test suite `src/test/regress/expected/rpt.out`:

* The Query:
```sql
create table with_test2 (id bigserial NOT NULL, isc varchar(15) NOT NULL,iscd varchar(15) NULL) DISTRIBUTED REPLICATED;
create table with_test3 (id numeric NULL, rc varchar(255) NULL,ri numeric NULL) DISTRIBUTED REPLICATED;
insert into with_test2 (isc,iscd) values ('CMN_BIN_YES', 'CMN_BIN_YES');
insert into with_test3 (id,rc,ri) values (113551,'CMN_BIN_YES',101991), (113552,'CMN_BIN_NO',101991), (113553,'CMN_BIN_ERR',101991), (113554,'CMN_BIN_NULL',101991);
explain
WITH
    t1 AS (SELECT * FROM with_test2),
    t2 AS (SELECT id, rc FROM with_test3 WHERE ri = 101991)
SELECT p.*FROM t1 p JOIN t2 r ON p.isc = r.rc JOIN t2 r1 ON p.iscd = r1.rc LIMIT 1;
```
* Plan given by main dev branch
```
                                               QUERY PLAN                                                
---------------------------------------------------------------------------------------------------------
 Gather Motion 1:1  (slice1; segments: 1)  (cost=390.63..390.63 rows=1 width=104)
   ->  Limit  (cost=332.63..390.63 rows=1 width=104)
         ->  Hash Join  (cost=332.63..739.49 rows=7 width=104)
               Hash Cond: ((with_test2.iscd)::text = (r1.rc)::text)
               ->  Hash Join  (cost=166.32..572.78 rows=129 width=104)
                     Hash Cond: ((with_test2.isc)::text = (r.rc)::text)
                     ->  Seq Scan on with_test2  (cost=0.00..344.00 rows=24400 width=104)
                     ->  Hash  (cost=166.25..166.25 rows=5 width=516)
                           ->  Subquery Scan on r  (cost=0.00..166.25 rows=5 width=516)
                                 ->  Seq Scan on with_test3  (cost=0.00..166.25 rows=5 width=548)
                                       Filter: (ri = '101991'::numeric)
               ->  Hash  (cost=166.25..166.25 rows=5 width=516)
                     ->  Subquery Scan on r1  (cost=0.00..166.25 rows=5 width=516)
                           ->  Seq Scan on with_test3 with_test3_1  (cost=0.00..166.25 rows=5 width=548)
                                 Filter: (ri = '101991'::numeric)
 Optimizer: Postgres query optimizer
(16 rows)
```
* Plan given by 6X_STABLE branch
```
                                              QUERY PLAN                                              
------------------------------------------------------------------------------------------------------
 Limit  (cost=0.16..0.23 rows=1 width=104)
   ->  Gather Motion 1:1  (slice1; segments: 1)  (cost=0.16..0.40 rows=4 width=104)
         ->  Hash Join  (cost=0.16..0.34 rows=4 width=104)
               Hash Cond: ((with_test2.iscd)::text = (r1.rc)::text)
               ->  Hash Join  (cost=0.03..0.16 rows=4 width=104)
                     Hash Cond: ((r.rc)::text = (with_test2.isc)::text)
                     ->  Subquery Scan on r  (cost=0.00..0.08 rows=4 width=516)
                           ->  Seq Scan on with_test3  (cost=0.00..1.05 rows=4 width=19)
                                 Filter: (ri = '101991'::numeric)
                     ->  Hash  (cost=0.02..0.02 rows=1 width=104)
                           ->  Seq Scan on with_test2  (cost=0.00..1.01 rows=1 width=32)
               ->  Hash  (cost=0.08..0.08 rows=2 width=516)
                     ->  Subquery Scan on r1  (cost=0.00..0.08 rows=4 width=516)
                           ->  Seq Scan on with_test3 with_test3_1  (cost=0.00..1.05 rows=4 width=19)
                                 Filter: (ri = '101991'::numeric)
 Optimizer: Postgres query optimizer
(16 rows)
```
* Plan given by this PR patch build
```
                                               QUERY PLAN                                                
---------------------------------------------------------------------------------------------------------
 Gather Motion 1:1  (slice1; segments: 1)  (cost=437.47..437.47 rows=1 width=104)
   ->  Limit  (cost=332.63..437.47 rows=1 width=104)
         ->  Hash Join  (cost=332.63..737.86 rows=4 width=104)
               Hash Cond: ((with_test2.iscd)::text = (r1.rc)::text)
               ->  Hash Join  (cost=166.32..571.47 rows=15 width=104)
                     Hash Cond: ((with_test2.isc)::text = (r.rc)::text)
                     ->  Seq Scan on with_test2  (cost=0.00..344.00 rows=24400 width=104)
                     ->  Hash  (cost=166.25..166.25 rows=5 width=516)
                           ->  Subquery Scan on r  (cost=0.00..166.25 rows=5 width=516)
                                 ->  Seq Scan on with_test3  (cost=0.00..166.25 rows=5 width=548)
                                       Filter: (ri = '101991'::numeric)
               ->  Hash  (cost=166.25..166.25 rows=5 width=516)
                     ->  Subquery Scan on r1  (cost=0.00..166.25 rows=5 width=516)
                           ->  Seq Scan on with_test3 with_test3_1  (cost=0.00..166.25 rows=5 width=548)
                                 Filter: (ri = '101991'::numeric)
 Optimizer: Postgres query optimizer
(16 rows)
```
* Conclusion
We can see main branch with this patch or 6X_STABLE branch can both give better estimation than main branch without this patch, which gave stats of the hash join size `rows=129`.

2023-08-10 09:40 UTC, Aegeaner commented
> How can we say Vars from CTE must be unique?
> 
The comments above said:
```
		/*
		 * If the Var represents a column of a VALUES RTE, assume it's unique.
		 * This could of course be very wrong, but it should tend to be true
		 * in well-written queries.  
		 * /
```
This is the method to estimate `RTE_VALUES` type, though it may be not accurate for `RTE_CTE` type, I think it would be better than the default `DEFAULT_NUM_DISTINCT` value.

2023-08-10 09:41 UTC, Aegeaner commented
> Please close all these kinds of PRs if there are no obvious upstream discussion results.

As no upstream discussion yet, convert to draft PR first.

2023-08-10 09:44 UTC, kainwen commented
> > How can we say Vars from CTE must be unique?
> 
> The comments above said:
> 
> ```
> 		/*
> 		 * If the Var represents a column of a VALUES RTE, assume it's unique.
> 		 * This could of course be very wrong, but it should tend to be true
> 		 * in well-written queries.  
> 		 * /
> ```
> 
> This is the method to estimate `RTE_VALUES` type, though it may be not accurate for `RTE_CTE` type, I think it would be better than the default `DEFAULT_NUM_DISTINCT` value.

`RTE_VALUES` is totally different from `RTE_CTE`.

2023-08-17 08:50 UTC, Aegeaner commented
Found a new approach to fix this issue, which seems better. See new PR https://github.com/greenplum-db/gpdb/pull/16229, close this one.

2023-08-17 08:50 UTC, closed without merging