Revise some docs about resource group
greenplum-db/gpdb pull request #16204
Opened 2023-08-15 02:56 UTC by SmartKeyerror

2023-08-15 08:34 UTC, funcode commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +    sudo usermod -aG root smart
Should smart be gpadmin?

2023-08-15 08:41 UTC, funcode commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
>      ```
Is there a way to switch back to v1 after setting it to v2?

2023-08-15 10:25 UTC, SmartKeyerror commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
>      ```
It's quite simple too:
```
sudo grubby --update-kernel=/boot/vmlinuz-$(uname -r) --args="systemd.unified_cgroup_hierarchy=0 systemd.legacy_systemd_cgroup_controller"
```

2023-08-15 14:33 UTC, lisakowen reviewed
general comment - if you use `1` for all step numbers, the correct step number will be auto-generated in the html.

2023-08-15 14:33 UTC, lisakowen commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +   ```
i think the command and the line with backticks following it should be indented one more space.

2023-08-15 14:33 UTC, lisakowen commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +    ```
end previous sentence with a colon?  and i don't think the commands need to be indented in this block.

2023-08-16 01:42 UTC, SmartKeyerror commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +    ```
I do not get your point, about the file format, I believe you're more familiar with it than me, could you change it from this PR directly?

2023-08-16 02:12 UTC, haolinw commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +    echo "+cpuset +io +cpu +memory" | sudo tee -a /sys/fs/cgroup/cgroup.subtree_control
Shouldn't we also need to grant /sys/fs/cgroup/cgroup.subtree_control proper permission before writing ? I did hit issue of no permission to write this file.

2023-08-16 02:15 UTC, haolinw commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +    echo "+cpuset +io +cpu +memory" | sudo tee -a /sys/fs/cgroup/cgroup.subtree_control
Oh I see, you are using sudo instead of "echo xxx >>", seems fine.

2023-08-16 06:28 UTC, funcode commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
>      ```
I suggest we mention it in the doc, in case users want to change it back.

2023-08-16 06:31 UTC, funcode commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +    echo "+cpuset +io +cpu +memory" | sudo tee -a /sys/fs/cgroup/cgroup.subtree_control
I'm afraid some big enterprise users won't like the idea to place gpadmin in the root group. If they do not accept this approach, are there any other ways to achieve the same purpose?

2023-08-16 06:32 UTC, funcode commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +    echo "+cpuset +io +cpu +memory" | sudo tee -a /sys/fs/cgroup/cgroup.subtree_control
Is the root group required? Will it work if gpadmin is in the sudoers list?

2023-08-16 09:31 UTC, mperezfuster requested changes
Some suggestions on comments

2023-08-16 09:31 UTC, mperezfuster commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
>      -   Redhat/Oracle/Rocky 8.x systems:
maybe we can remove this line as we don't differentiate between RH 7/8 and RH 6

2023-08-16 09:31 UTC, mperezfuster commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
>      -   Redhat/Oracle/Rocky 8.x systems:
same here, no need to specify OS

2023-08-16 09:31 UTC, mperezfuster commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +2. Reboot the system for the changes to take effect: `sudo reboot now`.
I suggest specifying the command in a new line to match the same pattern as the other steps:

2. Reboot the system for the changes to take effect: 
    ```
    sudo reboot now
    ```

2023-08-16 09:31 UTC, mperezfuster commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +    ```
Wording suggestion which also includes Lisa's suggestions:

Since resource groups manually manage cgroup files, the above settings may become ineffective after a system reboot. Consider adding the following bash script for `systemd` so it runs automatically during system startup:

``` 
sudo mkdir -p /sys/fs/cgroup/gpdb
sudo chmod -R 774 /sys/fs/cgroup/gpdb
sudo chmod g+w /sys/fs/cgroup/cgroup.procs

echo "+cpuset +io +cpu +memory" | sudo tee -a /sys/fs/cgroup/cgroup.subtree_control
```

2023-08-16 10:13 UTC, mperezfuster commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
>      This content configures CPU, CPU accounting, CPU core set, and memory control groups managed by the `gpadmin` user. Greenplum Database uses the memory control group only for those resource groups
Does this sentence still make sense? Should we remove it as it still references `MEMORY AUDITOR`

2023-08-18 01:34 UTC, SmartKeyerror commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
>      -   Redhat/Oracle/Rocky 8.x systems:
I do not change the content of this, just change the line number. Actually, I'm not clear about the behavior of specific OS, I would be extremely delighted if you could make direct edits to this PR.

2023-08-18 01:35 UTC, SmartKeyerror commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
>      -   Redhat/Oracle/Rocky 8.x systems:
Same as above.

2023-08-18 01:45 UTC, SmartKeyerror commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +    echo "+cpuset +io +cpu +memory" | sudo tee -a /sys/fs/cgroup/cgroup.subtree_control
It's just advice, the customer could use different ways to ensure the gpadmin has the correct permission to the file.

2023-08-24 09:06 UTC, mperezfuster commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
>      ```
I made changes to this, @SmartKeyerror let me know if this is correct

2023-08-24 13:47 UTC, Aegeaner commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +Since resource groups manually manage cgroup files, the above settings may become ineffective after a system reboot. Consider adding the following bash script for systemd so it runs automatically dur
There are Linux systems inited without `systemd`, they can instead choose to use `sysvinit`, `openrc` or `runit` etc.. See: https://wiki.gentoo.org/wiki/Comparison_of_init_systems

2023-08-24 16:54 UTC, deenav commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +echo "+cpuset +io +cpu +memory" | sudo tee -a /sys/fs/cgroup/cgroup.subtree_control
The flow should be other way. 
1. `echo "+cpuset +io +cpu +memory" | sudo tee -a /sys/fs/cgroup/cgroup.subtree_control` will create new set of files under `/sys/fs/cgroup/gpdb`. 
2. Then change the file permission for `/sys/fs/cgroup/gpdb`
```suggestion
echo "+cpuset +io +cpu +memory" | sudo tee -a /sys/fs/cgroup/cgroup.subtree_control
sudo chmod -R 774 /sys/fs/cgroup/gpdb
sudo chmod g+w /sys/fs/cgroup/cgroup.procs
```

2023-08-28 01:18 UTC, SmartKeyerror commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +echo "+cpuset +io +cpu +memory" | sudo tee -a /sys/fs/cgroup/cgroup.subtree_control
> echo "+cpuset +io +cpu +memory" | sudo tee -a /sys/fs/cgroup/cgroup.subtree_control will create new set of files (cpu.max, io.max, ..) under /sys/fs/cgroup/gpdb.

We must have corresponding files, such as cpu.max, io.max to control the resource usage, so we need to add those controllers into `/sys/fs/cgroup/cgroup.subtree_control `.

2023-08-28 01:21 UTC, SmartKeyerror commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
>      ```
It works fine in my local CentOS 8 environment.

2023-08-28 06:28 UTC, kainwen commented
Currently, Greenplum 7 plan to support the following OS:

```
rhel8,rocky8,oel8,rhel9,rocky9,oel9
```

So I think in our document to config Cgroup, we need to verify if the same document works for all the above OS.

* if yes, then we are good.
* if no, we need to write doc for each above OS on how to config cgroup

For other platforms, we just need to mention users need to do their own config.

2023-08-28 07:27 UTC, SmartKeyerror commented
> rhel8,rocky8,oel8,rhel9,rocky9,oel9

I don't think we need to verify all of this by hand, cause the action has little possibility of changing in a newer version than Cgoup v1. Such as Oracle Linux, it's official document just using oel8 as example to show how to enable cgroup v2:
[mount-cgroups-v2](https://docs.oracle.com/en/learn/ol-cgroup-v2/#mount-cgroups-v2). And oel9 refers to it: [Using cgroups v2 to Manage Resources for Users](https://docs.oracle.com/en/operating-systems/oracle-linux/9/osmanage/osmanage-ManagingResources.html#topic_xt4_4xw_rvb).

So I believe it's the same as rhel8/9 and rocky8/9.

2023-08-28 07:47 UTC, kainwen commented
> > rhel8,rocky8,oel8,rhel9,rocky9,oel9
> 
> I don't think we need to verify all of this by hand, cause the action has little possibility of changing in a newer version than Cgoup v1. Such as Oracle Linux, it's official document just using oel8 as example to show how to enable cgroup v2: [mount-cgroups-v2](https://docs.oracle.com/en/learn/ol-cgroup-v2/#mount-cgroups-v2). And oel9 refers to it: [Using cgroups v2 to Manage Resources for Users](https://docs.oracle.com/en/operating-systems/oracle-linux/9/osmanage/osmanage-ManagingResources.html#topic_xt4_4xw_rvb).
> 
> So I believe it's the same as rhel8/9 and rocky8/9.

Your reasoning steps are also a kind of verification. OK, no problem.

So the conclusion here is:

> the document here is correct for all the OS Greenplum 7 officially supported now (rhel8,rocky8,oel8,rhel9,rocky9,oel9
).

Thanks.

2023-08-28 11:52 UTC, mperezfuster approved these changes

2023-08-28 15:41 UTC, merged

2023-08-29 15:14 UTC, kmacoskey commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +7. To automatically recreate Greenplum Database required cgroup hierarchies and parameters when your system is restarted, configure your system to enable the Linux cgroup service daemon `cgconfig.ser
This has never been required before in Greenplum 6 or on <= RHEL 8. Why is it required now. 

Is this actually specific to RHEL 9 with cgroups v2  ? or is it specific to cgroups v2? 

Why are we saying this is an example? "For example". If this is required to ensure the configuration is persistent on reboot, then it's not an example it is the way we expect a user to configure their system.

2023-08-29 15:14 UTC, kmacoskey commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +                       echo '+cpuset +io +cpu +memory' | sudo tee -a /sys/fs/cgroup/cgroup.subtree_control; \
Why are we doing this at `/sys/fs/cgroup/cgroup.subtree_control`  ? 

Referring to Redhat 9 documentation, https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/managing_monitoring_and_updating_the_kernel/assembly_using-cgroupfs-to-manually-manage-cgroups_managing-monitoring-and-updating-the-kernel , that documentation shows that you:

>5. Enable the desired controllers for child cgroups of the Example control group:
> echo "+cpu +cpuset" >> /sys/fs/cgroup/Example/cgroup.subtree_control

Why isn't this command adding the controllers to `/sys/fs/cgroup/gpdb` ?

2023-08-29 15:14 UTC, kmacoskey commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +                       echo '+cpuset +io +cpu +memory' | sudo tee -a /sys/fs/cgroup/cgroup.subtree_control; \
Why are we using sudo ? This service is run as root (from the configuration above this line).

2023-08-29 15:14 UTC, kmacoskey commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +                       usermod -aG root gpadmin; \
Why is this line necessary?

2023-08-29 15:14 UTC, kmacoskey commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +   TimeoutStopSec=infinity
Why are we disabling timeout

2023-09-01 01:52 UTC, SmartKeyerror commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +If you want to switch from cgroup v2 to v1, run the following commands:
> This is confusing. We give documentation about how to switch from cgroup v2 to cgroup v1 or how to switch from cgroup v1 to cgroup v2 with no explanation as to why you would want to switch.

This is up to the customer.

> Do we mention anywhere about the default version of which cgroup version is enabled is different between Operating Systems versions. Where do we mention which version Greenplum requires.

I think it's hard to do that, since different kernel version has different default version. And Greenplum is using Cgroup to implement it's function, so we could not say "which version Greenplum requires.", Greenplum support Cgroup v1 and v2 both.

2023-09-10 13:28 UTC, kainwen commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +                       echo '+cpuset +io +cpu +memory' | sudo tee -a /sys/fs/cgroup/cgroup.subtree_control; \
> https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/managing_monitoring_and_updating_the_kernel/assembly_using-cgroupfs-to-manually-manage-cgroups_managing-monitoring-and-updating-the-kernel

When parent dir does not have the controller, child cannot add new. This is reasonable: admin parent dir don't want to you to use, you cannot.

2023-09-10 13:29 UTC, kainwen commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +                       echo '+cpuset +io +cpu +memory' | sudo tee -a /sys/fs/cgroup/cgroup.subtree_control; \
> Why are we using sudo ? This service is run as root (from the configuration above this line).

Resolved in https://github.com/greenplum-db/gpdb/pull/16327

2023-09-10 13:29 UTC, kainwen commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +                       chmod g+w /sys/fs/cgroup/cgroup.procs;"
> Why is this line necessary?

Resolved in https://github.com/greenplum-db/gpdb/pull/16327