DOCS: Document new option for specifying the directory to which gppkg writes temporary files
greenplum-db/gpdb pull request #16202
Opened 2023-08-15 00:43 UTC by VMWareJennyBeth

2023-08-15 07:42 UTC, Sasasu commented on gpdb-doc/markdown/utility_guide/ref/gppkg.html.md
> +-t | --temp
sorry, I did not update the document. the option should be `--tempdir` and the shortcut (`-t`) does not exist.

2023-08-15 07:42 UTC, Sasasu approved these changes

2023-08-15 13:54 UTC, Sasasu requested changes
please hold on. the env should be `TMPDIR` not `TEMPDIR`. I will ask others. and the API maybe get modified.

2023-08-15 14:08 UTC, Sasasu commented on gpdb-doc/markdown/utility_guide/ref/gppkg.html.md
> +-t | --temp
```suggestion
--tmpdir
```

2023-08-15 14:08 UTC, Sasasu approved these changes

2023-09-19 17:30 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/utility_guide/ref/gppkg.html.md
> +-t | --temp
@radarwave 

I'm confused. Why are we giving the user two ways to configure a temporary directory. Are we saying they can do it either through an environment variable or by passing a flag? Does one override the other? I need more information.

2023-09-19 18:25 UTC, dyozie approved these changes

2023-09-19 18:25 UTC, merged