[7X] Abort rebalance if replay lag is big on mirror
greenplum-db/gpdb pull request #16220
Opened 2023-08-16 13:46 UTC by Annu149

Issue: If there is a big gap between flush_lsn and replay_lsn on mirror then trigerring rebalance will cause a panic.

Fix: Added a check to WAL Replay Location of mirror. gprecoverseg rebalance should throw an exception if replay lag (flush_lsn - replay_lsn) on mirror is more than the default allowed limit (10 GB). ALLOWED_REPLAY_LAG (default value 10 GB) can be configured using flag --replay-lag with gprecoverseg -r. The check for the replay lag can also be disabled completely using the new flag --disable-replay-lag.

New flags:
--disbale-replay-lag: will turn off the replay_lag check during rebalance Usage:
gprecoverseg -r --disable-replay-lag

--replay-lag: will set the provided value as the new  allowed replay lag on mirror Usage:
gprecoverseg -r --replay-lag 2

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2023-08-23 06:30 UTC, kpraveen457 commented on gpMgmt/bin/gppylib/operations/rebalanceSegments.py
> +                replay_lag_in_bytes = replay_lag(segmentPair.primaryDB)
IMHO, should we rename `replay_lag_in_bytes` to `replay_lag_bytes` for readability?

2023-08-23 06:30 UTC, kpraveen457 commented on gpMgmt/bin/gppylib/operations/rebalanceSegments.py
> +    except Exception as ex:
I think we can use `except psycopg2.Error as ex:` to catch more specific exceptions as we are dealing with database operations here.

2023-08-24 06:51 UTC, kpraveen457 commented on gpMgmt/bin/gppylib/operations/rebalanceSegments.py
> +                if not self.disable_replay_lag and int(replay_lag_in_bytes) >= (self.replay_lag * 1024 * 1024 * 1024):
Do we only support `--replay-lag` falg in GB ?

2023-08-24 08:34 UTC, kpraveen457 commented on gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
> +
should also throw this exception for `--replay-lag`.

2023-08-24 08:34 UTC, kpraveen457 commented on gpMgmt/bin/gppylib/test/unit/test_unit_rebalance_segment.py
> +            self.subject.rebalance()
can we add one more UT in which `disable-replay-lag` is also mocked and used?

2023-08-24 08:34 UTC, kpraveen457 commented on gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
> +  Scenario: gprecoverseg errors out if invalid options are used with --disable-replay-lag
can we also add a behave test case in which when user uses`--replay-lag` it throws an exception and then he uses `--disable-replay-lag` to disable replay lag ?

2023-08-24 10:53 UTC, SunilS26 requested changes
Overall changes Looks good to me. Couple of minor comments

2023-08-24 10:53 UTC, SunilS26 commented on gpMgmt/bin/gppylib/commands/gp.py
> +# Maximum replay lag (in GBs) allowed on mirror when rebalancing the segments
Good to add some comment on how we came up with 10 GB as the default value, in future it is easy to reiterate this.May be add some points that this value was decided as it was close to 5min interval.

2023-08-24 10:53 UTC, SunilS26 commented on gpMgmt/bin/gppylib/operations/rebalanceSegments.py
> +                if not self.disable_replay_lag and int(replay_lag_in_bytes) >= (self.replay_lag * 1024 * 1024 * 1024):
if gprecoverseg is triggered with --disable_replay_lag, do we need to check replay lag ?
IMO let's check the replay lag(Query) only when replay lag is enabled.

2023-08-25 09:38 UTC, Annu149 commented on gpMgmt/bin/gppylib/operations/rebalanceSegments.py
> +                if not self.disable_replay_lag and int(replay_lag_in_bytes) >= (self.replay_lag * 1024 * 1024 * 1024):
Yes

2023-08-25 10:39 UTC, nimish350 commented on gpMgmt/bin/gppylib/operations/rebalanceSegments.py
> +                                        "mirror catchup on replay then trigger rebalance. Use --replay-lag to "
LGTM +1

2023-08-25 10:40 UTC, nimish350 commented on gpMgmt/bin/gppylib/operations/rebalanceSegments.py
> +
+1 LGTM

2023-08-28 06:41 UTC, SunilS26 approved these changes
LGTM!

2023-08-28 10:16 UTC, Annu149 commented on gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
> +
tried to add the above validation for --replay-lag as well but couldn't. Because we are assigning a default value of 10 GB to replay_lag so there is no way to know if user explicitly used --replay-lag or not. Even if --replay-lag is used with options other than -r it will not impact anything

2023-08-28 10:53 UTC, nimish350 reviewed
It looks like floating point [< 1Gb] is not supported with the --replay-lag flag:
```
[~/workspace/gpdb: {gprecoverseg_wal_replay_lag} ?]$ gprecoverseg -r --replay-lag 0.1 
Usage: gprecoverseg [--help] [options] 

gprecoverseg: error: option --replay-lag: invalid integer value: '0.1'
```

We should support floating point values to track MB specific values.

2023-08-28 16:46 UTC, shrakesh commented on gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
> +        And user can start transactions
is there any test to make sure that the default value of 10 GB is assigned to the replay leg?

2023-08-30 04:58 UTC, ravoorsh commented on gpMgmt/bin/gppylib/operations/rebalanceSegments.py
> +                    if int(replay_lag_in_bytes) >= (self.replay_lag * 1024 * 1024 * 1024):
The code seems to be assuming that the user will specify the replay_lg value in GBs only. Suppose the user specifies 500MB for example, the code will assume its in GBs and apply this formula, which could lead to inconsistencies.
It will be good to provide validation for the user input initially making sure the value is in GB, if nothing is specified we can assume its in GB.

2023-08-30 11:19 UTC, Annu149 commented on gpMgmt/bin/gppylib/operations/rebalanceSegments.py
> +                    if int(replay_lag_in_bytes) >= (self.replay_lag * 1024 * 1024 * 1024):
parser is already doing the validation if the provided replay_lag is of expected type or not.

```
[~/workspace/gpdb/gpMgmt: {gprecoverseg_wal_replay_lag} ?]$ gprecoverseg -ar --replay-lag 3MB
Usage: gprecoverseg [--help] [options]

gprecoverseg: error: option --replay-lag: invalid floating-point value: '3MB'
```

2023-08-31 10:56 UTC, Annu149 commented on gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
> +        And user can start transactions
Have added a debug message which prints the replay lag value provided by user or the default one. In the behave test added a step to make sure that gprecoverseg prints the same message with default value

2023-09-01 05:48 UTC, shrakesh approved these changes
LGTM

2023-09-01 07:50 UTC, nimish350 approved these changes
LGTM +1

2023-09-04 04:45 UTC, merged