Docs resgroups diskio
greenplum-db/gpdb pull request #16233
Opened 2023-08-17 10:02 UTC by mperezfuster

This PR documents the new limit for resource groups io_limit, which limits disk I/O.
There are changes to the narrative pages, the CREATE/ALTER RESOURCE GROUP reference pages, and the relevant gp_toolkit views.
Note there is another PR https://github.com/greenplum-db/gpdb/pull/16204 that is already addressing some changes for the narrative page Using Resource Groups. I have not included those changes in this PR.

@SmartKeyerror feel free to add other reviewers to this PR.

Review sites:

Using Resource Groups: https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-resgroups/greenplum-database/admin_guide-workload_mgmt_resgroups.html

System views: https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-resgroups/greenplum-database/ref_guide-system_catalogs-catalog_ref-views.html#gp_resgroup_iostats_per_host

SQL Commands: 
https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-resgroups/greenplum-database/ref_guide-sql_commands-CREATE_RESOURCE_GROUP.html
https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-resgroups/greenplum-database/ref_guide-sql_commands-ALTER_RESOURCE_GROUP.html

2023-08-17 19:23 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +|IO_LIMIT| The limit for the maximum read/write sequential disk I/O throughput, and maximum read/write I/O operations per second. Set the value on a per-tablespace basis.| [0-MAX] | -1 |
My understanding is that they can also set Disk I/O across all tablespaces in addition to per tablespace but I could totally be wrong.

2023-08-17 19:24 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +Greenplum Database leverages Linux control groups to implement disk I/O limits. The parameter `IO_LIMIT` limits the maximum read/write sequential disk I/O throughput, and the maximum read/write I/O o
Same comment as above about also being able to set for all tablespaces.

2023-08-17 19:25 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +When you create a resource group for a role, you provide a name and a CPU resource allocation mode (core or percentage). You can optionally provide a concurrent transaction limit, a memory limit, a C
missing space after "limits,"

2023-08-17 19:27 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_RESOURCE_GROUP.html.md
> +A resource group that you create to manage a user role identifies concurrent transaction, memory, CPU and disk I/O limits for the role when resource groups are enabled. You may assign such resource g
We use the serial comma. So add a comma after CPU in that list.

2023-08-17 19:27 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_RESOURCE_GROUP.html.md
> +:   Optional. The maximum read/write sequential disk I/O throughput, and the maximum read/write I/O operations per second for the queries assigned to a specific tablespace and resource group. When yo
speficy => specify

Also, same comment about setting Disk I/O for all tablespaces.

2023-08-18 10:19 UTC, mperezfuster commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +|IO_LIMIT| The limit for the maximum read/write sequential disk I/O throughput, and maximum read/write I/O operations per second. Set the value on a per-tablespace basis.| [0-MAX] | -1 |
@SmartKeyerror can you confirm if we can set the disk io limits without specifying a tablespace?

2023-08-22 01:55 UTC, RMTT requested changes

2023-08-22 01:55 UTC, RMTT commented on gpdb-doc/markdown/admin_guide/wlmgmt.html.md
> +|Disk I/O|None|Limit the maximum read/write sequential disk I/O throughput, and maximum read/write I/O operations per second|
diskio is not specific for `sequential` io , so i think `sequential` should be removed here.

2023-08-22 01:55 UTC, RMTT commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +|IO_LIMIT| The limit for the maximum read/write sequential disk I/O throughput, and maximum read/write I/O operations per second. Set the value on a per-tablespace basis.| [0-MAX] | -1 |
disk io limits must start with a tablespace, but you can use `*` as tablespace name which stand all tablespaces.

btw, `sequential` should be removed.

2023-08-22 01:55 UTC, RMTT commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +Greenplum Database leverages Linux control groups to implement disk I/O limits. The parameter `IO_LIMIT` limits the maximum read/write sequential disk I/O throughput, and the maximum read/write I/O o
`sequential` should be removed.

2023-08-22 01:55 UTC, RMTT commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_RESOURCE_GROUP.html.md
> +[IO_LIMIT='<tablespace_name>:wbps=<wbps_value>, rbps=<rbps_value>, wiops=<wiops_value>, riops=<riops_value>']
multiple tablespaces use `;` as separator, for example:

```
[IO_LIMIT='<tablespace_name>:wbps=<wbps_value>, rbps=<rbps_value>, wiops=<wiops_value>, riops=<riops_value>;<tablespace_name2>:wbps=<wbps_value>, rbps=<rbps_value>, wiops=<wiops_value>, riops=<riops_value>']
```

2023-08-22 01:55 UTC, RMTT commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_RESOURCE_GROUP.html.md
> +:   Optional. The maximum read/write sequential disk I/O throughput, and the maximum read/write I/O operations per second for the queries assigned to a specific tablespace and resource group. When yo
`sequential` should be removed.

2023-08-22 01:55 UTC, RMTT commented on gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-views.html.md
> + rsgname        | hostname | tablespace       | rbps (MB_read/s) | wbps (MB_wrtn/s) | riops (r/s) | wiops (w/s)
The column names have  changed:

`rbps (MB_read/s)` to `rbps`
`wbps (MB_wrtn/s)` to `wbps`
`riops (r/s)` to `riops`
`wiops (w/s)` to `wiops`

2023-08-22 17:52 UTC, deenav commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +Greenplum Database leverages Linux control groups to implement disk I/O limits. The parameter `IO_LIMIT` limits the maximum read/write sequential disk I/O throughput, and the maximum read/write I/O o
We should explicitly say that IO_LIMIT is supported only on `cgroup-v2`

The below warning will appear if user try to configure with 'cgroup' v1
```
# create resource group rg2 WITH (cpu_max_percent=20, io_limit='myspace:rbps=5,riops=1000');
WARNING:  resource group io limit only can be used in cgroup v2.  (seg5 192.168.121.4:6003 pid=127882)
```

2023-08-24 07:04 UTC, RMTT requested changes

2023-08-24 07:04 UTC, RMTT commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +|IO_LIMIT| The limit for the maximum read/write disk I/O throughput, and maximum read/write I/O operations per second. Set the value on a per-tablespace basis.| [0-MAX] | -1 |
The value range should be `[2, 4294967295]` or `MAX`.

2023-08-28 16:56 UTC, closed without merging