Docs: resource group modifications
greenplum-db/gpdb pull request #16321
Opened 2023-08-28 20:16 UTC by mperezfuster

This PR replaces https://github.com/greenplum-db/gpdb/pull/16233 due to git issues.
- Documents Disk i/o limits
- Adds view gp_resgroup_iostats_per_host and modifies existing views
- Other minor changes to Resource groups documentation

Review sites:

Using Resource Groups: https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-resgroups/greenplum-database/admin_guide-workload_mgmt_resgroups.html

System views: https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-resgroups/greenplum-database/ref_guide-system_catalogs-catalog_ref-views.html#gp_resgroup_iostats_per_host

SQL Commands:
https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-resgroups/greenplum-database/ref_guide-sql_commands-CREATE_RESOURCE_GROUP.html
https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-resgroups/greenplum-database/ref_guide-sql_commands-ALTER_RESOURCE_GROUP.html

2023-08-30 08:13 UTC, wenwangBJ commented
For the Line 297 content:
sudo grubby --update-kernel=ALL --args=“systemd.unified_cgroup_hierarchy=1”
 
Should change the quotes from “” to "", which are different ASCII character,  see below:
sudo grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=1"

2023-09-05 09:02 UTC, wenwangBJ commented
For the part, it's wrong:
"For example, for a high priority job that does not need too much CPU resources, configure the resource group with values CPU_MAX_PERCENT=10 and CPU_WEIGHT=500. For a low priority job that requires a high amount of CPU resources, configure the resource group with values CPU_MAX_PERCENT=90 and CPU_WEIGHT=10."

Reason:
These description isn't the right way for customer to config the reasonable CPU_MAX_PERCENT and CPU_WEIGHT. For the low priority job, the CPU_MAX_PERCENT should be set low value for not interruptting high priority job's work flow.

Suggestion:
Please check the document of "Resource Groups in Greenplum 7 Practical Guide" for the part "Introduction to CPU Management - Allocate CPU resources by resource percentage - Example" to correct scenarios.

2023-09-05 09:36 UTC, wenwangBJ commented
This part should be changed:
"3. With Q1 and Q2 still running, user ADHOC3 submits query Q3, using the default 500MB.
     Queries Q1 and Q2 have used 1300MB of the group's 1500MB. Therefore, Q3 must wait for Q1 or Q2 to complete before it can run."


Should Change to:
"3. With Q1 and Q2 still running, user ADHOC3 submits query Q3, using the default 500MB. Queries Q1 and Q2 have used 1300MB of the group's 1500MB.
    If there is enough memory resource for query Q3 in the segment, it will run normally that it would be limited by the special resource group memory config memory_limit. "

2023-09-07 03:24 UTC, wenwangBJ commented
Change all the IO_LIMIT value relative "MAX" to "max".
Because CGroup is case-sensitive and only accepts lowercase "max".

2023-09-07 03:36 UTC, wenwangBJ commented
In this line:
MEMORY_LIMIT | The memory limit value specified for the resource group. | Integer (MB) | -1 (not set)

Change from:
"-1 (not set)"

Change to:
"-1 (not set, simply use statement_mem as the memory limit for a single query.)"

2023-09-07 03:41 UTC, wenwangBJ commented
This line should be changed:
"If the parameter IO_LIMIT is set to -1, it means that rbps, wpbs, riops, and wiops are set to MAX, which means that there are no disk I/O limits."

Reason:
This is wrong description " the parameter IO_LIMIT is set to -1"

Suggest to change to:
"If io_limit is not set, the default value is used which means rpbs/wpbs/riops/wiops are all set to max, that means there is no limit.  At this time, through the gp_toolkit.gp_resgroup_config view, the io_limit displayed value is "-1" . "

2023-09-07 03:44 UTC, wenwangBJ commented
This example need to be updated:
"CREATE RESOURCE GROUP rgroup1 WITH (CONCURRENCY=20, CPU_MAX_PERCENT=20, MEMORY_LIMIT=25, CPU_WEIGHT=500, MIN_COST=50, 
  IO_LIMIT=’pg_default: wbps=1000, rbps=1000, wiops=100, riops=100’);"

Suggest change the "MEMORY_LIMIT=25" to "MEMORY_LIMIT=250".
Because it is an integer, unit: MB,  so the 25M is too small.

2023-09-07 03:46 UTC, wenwangBJ commented
Please add the relative part to the document: gp_toolkit.gp_resgroup_status_per_segment

2023-09-07 08:28 UTC, mperezfuster commented
> gp_resgroup_status_per_segment

@wenwangBJ I already added it, is there anything else you are missing for the view gp_resgroup_status_per_segment? Let me know if anything needs to be changed.

2023-09-19 14:44 UTC, wenwangBJ commented
For the relative part in gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md, some contents are old.
 
Please follow this PR as the latest and right content:
https://github.com/greenplum-db/gpdb/pull/16327

2023-09-19 15:01 UTC, wenwangBJ commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +The parameter `CPU_MAX_LIMIT` enforces a hard upper limit of CPU usage. For example, if it is set to 40%, it indicates that although the resource group can temporarily use some idle CPU resources fro
Change "CPU_MAX_LIMIT" to "CPU_MAX_PERCENT".

2023-09-19 15:13 UTC, wenwangBJ commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
>  The [gp\_resgroup\_status\_per\_host](../ref_guide/system_catalogs/catalog_ref-views.html#gp_resgroup_status_per_host) `gp_toolkit` system view enables you to view the real-time CPU and memory usage
Please add the relative part to the document: gp_toolkit.gp_resgroup_status_per_segment

2023-09-21 23:38 UTC, xinzweb commented on gpdb-doc/markdown/admin_guide/wlmgmt.html.md
>  |Concurrency|Managed at the query level|Managed at the transaction level|
Later on on the `queueing`, it's unclear about the `slot`. We can define the `slot` here. So the concurrency actually define the number of `slot` used later on in the `queueing` description.

I am thinking to put something like

```
The concurrency defines the number of `slots`. For Resource Queue, it's number of `query slots`. For Resource Group, it's number of `transaction slots`.
```

Feel free to break those down into the columns.

2023-09-21 23:42 UTC, xinzweb commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +You use resource groups to set and enforce CPU, memory, concurrent transaction limits, and disk I/O in Greenplum Database. Once you define a resource group, you assign the group to one or more Greenp
The first sentence I am thinking more like:

```
You use resource groups to manage and protect the resources allocations like CPU, memory, IO (footnote: cgroup V2 only), and transaction concurrency limit in Greenplum database.
```

2023-09-22 00:47 UTC, xinzweb requested changes
Please reconsider the new syntax for the IO_LIMIT. Thanks.

2023-09-22 00:47 UTC, xinzweb commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +When you limit disk I/O you speficy:
```suggestion
When you limit disk I/O you specify:
```

2023-09-22 00:47 UTC, xinzweb commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +
Maybe we can add some examples here, especially for the semantically consistent syntax of this IO limit.

Or, do we actually have a syntax grammar here we can share?

```
# all table spaces with write throughput limit 1000MB/sec
*: wbps=1000

# pg_default table space with read throughput limit 1000MB/sec
pg_default: wbps=max, rbps=1000, wiops=max, riops=max
# simpler syntax (if supported)
pg_default: rbps=1000
```

2023-09-22 00:47 UTC, xinzweb commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +- The values for `rpbs` and `wpbs` to limit the maximum read and write disk I/O throughput in the resource group, in MB/S. The default value is `max`, which means there is no limit.
Typo.

```suggestion
- The values for `rbps` and `wbps` to limit the maximum read and write disk I/O throughput in the resource group, in MB/sec. The default value is `max`, which means there is no limit. 
```

One more question, we used the same syntax, but different unit. The cgroup v2 is using `byte/sec` as unit. But here, with the same name, we changed the unit to `MB/sec`? Is this intentional?

2023-09-22 00:47 UTC, xinzweb commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +Greenplum Database resource groups use Linux Control Groups \(cgroups\) to manage CPU resources and disk I/O. There are two versions of cgroups: cgroup v1 and cgroup v2, which differ in the virtual f
Are we actually using `group_v2` as default? 
I believe we are using `none` as default.

A general comments, the v1 and v2 not only different from the file hierarchy, but also different on the controllers, constraints, delegation, security, etc. So, I just removed the sentence on hierarchy difference.

2023-09-22 00:47 UTC, xinzweb commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
>  After that, reboot your host and make the changes take effect.
Well, we already add `reboot now` for the `Ubuntu` system, then in this case, do we still ask them to `reboot`? 

If we ask them to reboot, maybe we don't need to add the `&& reboot now` above?

2023-09-22 00:47 UTC, xinzweb commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +    ls -l <cgroup_mount_point>/cpuacct/gpdb
we don't need this one. both `cpu` and `cpuacct` are pointing to the same location `cpu,cpuacct`.

2023-09-22 00:47 UTC, xinzweb commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +    If these directories exist and are owned by `gpadmin:gpadmin`, you have successfully configured cgroups for Greenplum Database CPU resource management.
```suggestion
    If these directories exist and are owned by `gpadmin:gpadmin`, you have successfully configured cgroups for Greenplum Database resource management.
```

I removed the `CPU`, since we also covered `memory` here (even though just for the reading purpose)

2023-09-22 00:47 UTC, xinzweb commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
>      ```
Shall we add the reason why we need this permission at the top level?

I am thinking something like

```
We have to enable gpadmin to access top level `cgroup.procs` since we need to move the Greenplum processes from user slices to `/sys/fs/cgroup/gpdb/` after cluster started in order to manage the postmaster services and all its auxiliary processes like checkpoint, bgwriter, wal writer etc.
```

2023-09-22 00:47 UTC, xinzweb commented on gpdb-doc/markdown/ref_guide/sql_commands/ALTER_RESOURCE_GROUP.html.md
> +[IO_LIMIT='<tablespace_name_1>:wbps=<wbps_value>, rbps=<rbps_value>, wiops=<wiops_value>, riops=<riops_value>;<tablespace_name_2>:wbps=<wbps_value>, rbps=<rbps_value>, wiops=<wiops_value>, riops=<rio
```suggestion
[ IO_LIMIT=' <tablespace_io_limit_spec> [; ...] ' ]

Where  <tablespace_io_limit_spec> is:
<tablespace_name> | <oid> : <io_limit_option_spec> [, ...]

Where <io_limit_option_spec> is:
wbps=<io_limit_option_value>
| rbps=<io_limit_option_value>
| wiops=<io_limit_option_value>
| riops=<io_limit_option_value>

Where <io_limit_option_vlaue> is:
<integer> | max
```

2023-09-22 00:47 UTC, xinzweb commented on gpdb-doc/markdown/ref_guide/sql_commands/ALTER_RESOURCE_GROUP.html.md
> +    - The values for `rpbs` and `wpbs` to limit the maximum read and write sequential disk I/O throughput in the resource group, in MB/S. The default value is `max`, which means there is no limit.
```suggestion
    - The values for `rbps` and `wbps` to limit the maximum read and write sequential disk I/O throughput in the resource group, in MB/S. The default value is `max`, which means there is no limit.
```

2023-09-22 00:47 UTC, xinzweb commented on gpdb-doc/markdown/ref_guide/sql_commands/ALTER_RESOURCE_GROUP.html.md
> +[IO_LIMIT='<tablespace_name_1>:wbps=<wbps_value>, rbps=<rbps_value>, wiops=<wiops_value>, riops=<riops_value>;<tablespace_name_2>:wbps=<wbps_value>, rbps=<rbps_value>, wiops=<wiops_value>, riops=<rio
maybe we can adjust this piece accordingly based on the above rewrite?

2023-09-22 00:47 UTC, xinzweb commented on gpdb-doc/markdown/ref_guide/sql_commands/ALTER_RESOURCE_GROUP.html.md
> +Set disk I/O limits for tablespaces `tablespace1` and a tablespace with oid 1663:
why do we need an oid 1663 here?

2023-09-22 00:47 UTC, xinzweb commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_RESOURCE_GROUP.html.md
> +[IO_LIMIT='<tablespace_name_1>:wbps=<wbps_value>, rbps=<rbps_value>, wiops=<wiops_value>, riops=<riops_value>;<tablespace_name_2>:wbps=<wbps_value>, rbps=<rbps_value>, wiops=<wiops_value>, riops=<rio
let's rewrite it as I shared above.

2023-09-22 00:47 UTC, xinzweb commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_RESOURCE_GROUP.html.md
> +    - The values for `rpbs` and `wpbs` to limit the maximum read and write disk I/O throughput in the resource group, in MB/S. The default value is `max`, which means there is no limit.
```suggestion
    - The values for `rbps` and `wbps` to limit the maximum read and write disk I/O throughput in the resource group, in MB/S. The default value is `max`, which means there is no limit.
```

2023-09-22 00:47 UTC, xinzweb commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_RESOURCE_GROUP.html.md
> +IO_LIMIT='<tablespace_name_1>:wbps=<wbps_value>, rbps=<rbps_value>, wiops=<wiops_value>, riops=<riops_value>;<tablespace_name_2>:wbps=<wbps_value>, rbps=<rbps_value>, wiops=<wiops_value>, riops=<riop
same

2023-09-22 08:51 UTC, wenwangBJ commented on gpdb-doc/markdown/ref_guide/sql_commands/ALTER_RESOURCE_GROUP.html.md
> +Set disk I/O limits for tablespaces `tablespace1` and a tablespace with oid 1663:
Not "and", but "or"
=======================
 tablespace or oid

2023-09-22 08:53 UTC, wenwangBJ commented on gpdb-doc/markdown/ref_guide/sql_commands/ALTER_RESOURCE_GROUP.html.md
> +Set disk I/O limits for tablespaces `tablespace1` and a tablespace with oid 1663:
This is a example of setting disk I/O limits for tablespaces and a tablespace oid. These two sentence have the same meaning:

- ALTER RESOURCE GROUP admin_group SET IO_LIMIT 'tablespace1:wbps=2000,wiops=2000;1663:rbps=2024,riops=2024';
- ALTER RESOURCE GROUP admin_group SET IO_LIMIT '1663:wbps=2000,wiops=2000;1663:rbps=2024,riops=2024';

2023-09-22 08:55 UTC, wenwangBJ commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_RESOURCE_GROUP.html.md
> +  MEMORY_LIMIT=150, CPU_MAX_PERCENT=25,
MEMORY_LIMIT=1500

2023-09-22 08:55 UTC, wenwangBJ commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_RESOURCE_GROUP.html.md
> +Create a resource group with a concurrent transaction limit of 20, a memory limit of 15, a CPU limit of 25, and disk I/O limits for a tablespace with oid 1663:
a memory limit of 1500

2023-09-22 08:57 UTC, wenwangBJ commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_RESOURCE_GROUP.html.md
>  Create a resource group with CPU and memory limit percentages of 35:
Create a resource group with CPU and memory limit percentages of 350 MB:

2023-09-22 08:58 UTC, wenwangBJ commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_RESOURCE_GROUP.html.md
Create a resource group with a concurrent transaction limit of 20, a memory limit of 1500 MB, a CPU limit of 25, and disk I/O limits for the `pg_default` tablespace:

2023-09-22 08:58 UTC, wenwangBJ commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_RESOURCE_GROUP.html.md
> +  MEMORY_LIMIT=150, CPU_MAX_PERCENT=25,
MEMORY_LIMIT=1500

2023-09-22 08:59 UTC, wenwangBJ commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_RESOURCE_GROUP.html.md
>  Create a resource group with a memory limit percentage of 11 to which you assign CPU core 1 on the coordinator host, and cores 1 to 3 on segment hosts:
a memory limit percentage of 110MB

2023-09-22 12:10 UTC, mperezfuster commented on gpdb-doc/markdown/admin_guide/wlmgmt.html.md
>  |Concurrency|Managed at the query level|Managed at the transaction level|
how about now?

2023-09-22 12:14 UTC, mperezfuster commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +|IO_LIMIT| The limit for the maximum read/write disk I/O throughput, and maximum read/write I/O operations per second. Set the value on a per-tablespace basis.| [2 - 4294967295 or `max`] | -1 |
@wenwangBJ @SmartKeyerror

2023-09-22 12:16 UTC, mperezfuster commented on gpdb-doc/markdown/ref_guide/sql_commands/ALTER_RESOURCE_GROUP.html.md
> +Set disk I/O limits for tablespaces `tablespace1` and a tablespace with oid 1663:
it's an example to show that we can either specify a tablespace by name or oid

2023-09-22 12:26 UTC, mperezfuster commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +
it should be on the CREATE/ALTER RESOURCE GROUP command reference pages, and down in the Examples section of this page too.

2023-09-22 12:28 UTC, mperezfuster commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +- The values for `rpbs` and `wpbs` to limit the maximum read and write disk I/O throughput in the resource group, in MB/S. The default value is `max`, which means there is no limit.
Thanks for spotting the typo. I'll let @wenwangBJ @SmartKeyerror answer the question.

2023-09-22 12:31 UTC, mperezfuster commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +Greenplum Database resource groups use Linux Control Groups \(cgroups\) to manage CPU resources and disk I/O. There are two versions of cgroups: cgroup v1 and cgroup v2, which differ in the virtual f
@wenwangBJ @SmartKeyerror can you answer the question regarding default cgroup version used?

2023-09-22 12:32 UTC, mperezfuster commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +Greenplum Database resource groups use Linux Control Groups \(cgroups\) to manage CPU resources and disk I/O. There are two versions of cgroups: cgroup v1 and cgroup v2, which differ in the virtual f
@xinzweb I believe you made a suggested change but I cannot see it here.

2023-09-22 12:33 UTC, mperezfuster commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
>      ```
@wenwangBJ @SmartKeyerror can you confirm?

2023-09-22 13:36 UTC, xinzweb commented on gpdb-doc/markdown/admin_guide/wlmgmt.html.md
>  |Concurrency|Managed at the query level|Managed at the transaction level|
Very good! Thanks.

2023-09-22 13:37 UTC, xinzweb commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +|IO_LIMIT| The limit for the maximum read/write disk I/O throughput, and maximum read/write I/O operations per second. Set the value on a per-tablespace basis.| [2 - 4294967295 or `max`] | -1 |
I saw the example later on. So, if we can get confirmation from the server team, then this can be resolved.

2023-09-22 13:46 UTC, xinzweb reviewed
Here are the additional comments, including some very minor format adjustments.

2023-09-22 13:46 UTC, xinzweb commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +|CONCURRENCY|The maximum number of concurrent transactions, including active and idle transactions, that are permitted in the resource group.| [0-[max_connections](../ref_guide/config_params/guc-list
```suggestion
|CONCURRENCY|The maximum number of concurrent transactions, including active and idle transactions, that are permitted in the resource group.| [0 - [max_connections](../ref_guide/config_params/guc-list.html#max_connections)] | 20 |
```

2023-09-22 13:46 UTC, xinzweb commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +|CPU_MAX_PERCENT|The maximum percentage of CPU resources the group can use.| [1-100] | -1 (not set)|
```suggestion
|CPU_MAX_PERCENT|The maximum percentage of CPU resources the group can use.| [1 - 100] | -1 (not set)|
```

2023-09-22 13:46 UTC, xinzweb commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
>  |CPU_WEIGHT|The scheduling priority of the resource group.| [1-500] | 100 |
```suggestion
|CPU_WEIGHT|The scheduling priority of the resource group.| [1 - 500] | 100 |
```

2023-09-22 13:46 UTC, xinzweb commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +
Yes, I saw those. Thanks.

2023-09-22 13:46 UTC, xinzweb commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +Greenplum Database resource groups use Linux Control Groups \(cgroups\) to manage CPU resources and disk I/O. There are two versions of cgroups: cgroup v1 and cgroup v2, which differ in the virtual f
```suggestion
Greenplum Database resource groups use Linux Control Groups \(cgroups\) to manage CPU resources and disk I/O. There are two versions of cgroups: cgroup v1 and cgroup v2. Greenplum Database 7 supports both versions. It only supports the parameter `IO_LIMIT` for cgroup v2. The version of Linux Control Groups shipped by default with your Linux distribution depends on the operating system version. For Enterprise Linux 8 and older, the default version is v1. For Enterprise Linux 9 and later, the default version is v2. For detailed information about cgroups, refer to the Control Groups documentation for your Linux distribution.
```

2023-09-22 13:46 UTC, xinzweb commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +Greenplum Database resource groups use Linux Control Groups \(cgroups\) to manage CPU resources and disk I/O. There are two versions of cgroups: cgroup v1 and cgroup v2, which differ in the virtual f
Let me try again to see if you can see the above changes.

2023-09-22 13:46 UTC, xinzweb commented on gpdb-doc/markdown/ref_guide/sql_commands/ALTER_RESOURCE_GROUP.html.md
> +Set disk I/O limits for tablespaces `tablespace1` and a tablespace with oid 1663:
Aha, I saw it. It's hidden inside the later part of the example. Thanks.

2023-09-25 11:52 UTC, mperezfuster commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +Greenplum Database resource groups use Linux Control Groups \(cgroups\) to manage CPU resources and disk I/O. There are two versions of cgroups: cgroup v1 and cgroup v2, which differ in the virtual f
I can see it now, let's see if the team can confirm about the default settings.

2023-09-25 11:52 UTC, mperezfuster commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +    ls -l <cgroup_mount_point>/cpuacct/gpdb
@SmartKeyerror can you confirm?

2023-09-26 00:59 UTC, SmartKeyerror commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +|IO_LIMIT| The limit for the maximum read/write disk I/O throughput, and maximum read/write I/O operations per second. Set the value on a per-tablespace basis.| [2 - 4294967295 or `max`] | -1 |
we do not design as that, so need to specify all the 4 options.

2023-09-26 00:59 UTC, SmartKeyerror commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +Greenplum Database resource groups use Linux Control Groups \(cgroups\) to manage CPU resources and disk I/O. There are two versions of cgroups: cgroup v1 and cgroup v2, which differ in the virtual f
Since the Cgroup needs to be configured well if the customer wants to use resource group, we want them quick get started, so set the default value to `none`.

2023-09-26 00:59 UTC, SmartKeyerror commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +    ls -l <cgroup_mount_point>/cpuacct/gpdb
Yeah, that's right, we just need to verify `<cgroup_mount_point>/cpu/gpdb`

2023-09-26 00:59 UTC, SmartKeyerror commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
>      ```
agree w/ Shine's comments.

2023-09-26 00:59 UTC, SmartKeyerror commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> -    sudo yum install libcgroup-tools
we need the `libcgroup-tools` to use the config file to control the creation of Cgroup dirs.

2023-09-26 03:33 UTC, wenwangBJ commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +The parameter `CPU_MAX_LIMIT` enforces a hard upper limit of CPU usage. For example, if it is set to 40%, it indicates that although the resource group can temporarily use some idle CPU resources fro
I didn't see this change in this PR, please update:
Change "CPU_MAX_LIMIT" to "CPU_MAX_PERCENT". We don't have "CPU_MAX_LIMIT"  in GP7 any more.

2023-09-26 03:33 UTC, wenwangBJ commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
>  The [gp\_resgroup\_status\_per\_host](../ref_guide/system_catalogs/catalog_ref-views.html#gp_resgroup_status_per_host) `gp_toolkit` system view enables you to view the real-time CPU and memory usage
Update the example due to the PR revert that not have <bypass> lines anymore, if you needed:
postgres=# select * from gp_toolkit.gp_resgroup_status_per_segment ;

groupid | groupname | segment_id | vmem_usage

---------+---------------------+------------+------------

6438 | admin_group         |         -1 |          8 
6438 | admin_group         |          0 |        141 
6438 | admin_group         |          1 |        133 
6438 | admin_group         |          2 |        133

2023-09-26 04:05 UTC, wenwangBJ commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +|IO_LIMIT| The limit for the maximum read/write disk I/O throughput, and maximum read/write I/O operations per second. Set the value on a per-tablespace basis.| [2 - 4294967295 or `max`] | -1 |
@xinzweb Yes, we can.

These sentences have the same meaning:
-  alter resource group rg1 set io_limit '1663:rbps=max';
- alter resource group rg1 set io_limit '1663:rbps=max,wbps=max,riops=max,wiops=max';

Another example, these sentences have the same meaning:
- create resource group rg5 with (concurrency=10, cpu_max_percent=10, io_limit='*:rbps=1000');
- create resource group rg5 with (concurrency=10, cpu_max_percent=10, io_limit='*:rbps=1000,,wbps=max,riops=max,wiops=max');

2023-09-26 04:11 UTC, wenwangBJ commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +- The values for `rpbs` and `wpbs` to limit the maximum read and write disk I/O throughput in the resource group, in MB/S. The default value is `max`, which means there is no limit.
Yes, we change the Unit to MB/sec for user to configure it easier and more understandable.

And the in the view gp_toolkit.gp_resgroup_iostats_per_host  still keep the Unit B/sec which after discussion with dev engineers.
eg:postgres=# select * from gp_toolkit.gp_resgroup_iostats_per_host ; 
    rsgname    | hostname | tablespace |   rbps   |   wbps   | riops | wiops  
---------------+----------+------------+----------+----------+-------+------- 
admin_group   | stable   | pg_default | 21356347 | 29369067 |   162 |    36

2023-09-26 04:13 UTC, wenwangBJ commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +Greenplum Database resource groups use Linux Control Groups \(cgroups\) to manage CPU resources and disk I/O. There are two versions of cgroups: cgroup v1 and cgroup v2, which differ in the virtual f
Now the default gp_resource_manager is none.

2023-09-26 04:15 UTC, wenwangBJ commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
>  After that, reboot your host and make the changes take effect.
@mperezfuster I think we have sync it for several rounds, please update all the relative contexts follow the PR:  https://github.com/greenplum-db/gpdb/pull/16327/files

2023-09-26 04:16 UTC, wenwangBJ commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +    ls -l <cgroup_mount_point>/cpuacct/gpdb
I think we have sync it for several rounds, please update all the relative contexts follow the PR: https://github.com/greenplum-db/gpdb/pull/16327/files

2023-09-26 04:17 UTC, wenwangBJ commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
>      ```
@mperezfuster  I think we have sync it for several rounds, please update all the relative contexts follow the PR: https://github.com/greenplum-db/gpdb/pull/16327/files

2023-09-26 04:19 UTC, wenwangBJ commented on gpdb-doc/markdown/ref_guide/sql_commands/ALTER_RESOURCE_GROUP.html.md
> +[IO_LIMIT='<tablespace_name_1>:wbps=<wbps_value>, rbps=<rbps_value>, wiops=<wiops_value>, riops=<riops_value>;<tablespace_name_2>:wbps=<wbps_value>, rbps=<rbps_value>, wiops=<wiops_value>, riops=<rio
Agree with @xinzweb,  please update

2023-09-26 04:24 UTC, wenwangBJ commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_RESOURCE_GROUP.html.md
>  Create a resource group with CPU and memory limit percentages of 35:
I didn't see it was changed in the document, please confirm it.

2023-09-26 04:25 UTC, wenwangBJ commented on gpdb-doc/markdown/ref_guide/sql_commands/CREATE_RESOURCE_GROUP.html.md
>  Create a resource group with a memory limit percentage of 11 to which you assign CPU core 1 on the coordinator host, and cores 1 to 3 on segment hosts:
Update: a memory limit of 110MB

2023-09-26 04:29 UTC, wenwangBJ commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +|IO_LIMIT| The limit for the maximum read/write disk I/O throughput, and maximum read/write I/O operations per second. Set the value on a per-tablespace basis.| [[2 - 4294967295 or `max`] | -1 |
If the parameter IO_LIMIT is not set, the default value for rbps, wpbs, riops, and wiopss is set to max, which means that there are no disk I/O limits. In this scenario, the gp_toolkit.gp_resgroup_config system view displays its value as -1.

2023-09-27 08:27 UTC, mperezfuster commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> -    sudo yum install libcgroup-tools
@SmartKeyerror this is already stated on the Platform Requirements page when installing Greenplum: https://docs.vmware.com/en/VMware-Greenplum/7/greenplum-database/install_guide-platform-requirements-overview.html#operating-systems

2023-09-27 09:55 UTC, wenwangBJ approved these changes
Look good to me. Thanks.

2023-09-27 17:32 UTC, merged