Change copyright of minirepro and gpsd
greenplum-db/gpdb pull request #16505
Opened 2023-09-26 12:52 UTC by DevChattopadhyay

Updating the copyright of minirepro and gpsd from `2007 - 2016 Pivotal` to `2007 - 2023 VMWare`

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2023-09-26 16:21 UTC, gpopt approved these changes
+1

2023-09-26 18:07 UTC, dgkimura approved these changes

2023-09-26 18:07 UTC, dgkimura commented on gpMgmt/bin/gpsd
> +                           '\n-- Copyright (C) 2007 - 2023 VMWare'
Would it make sense to generate using the current year (i.e. `timestamp.year`)?

2023-09-27 09:23 UTC, nimish350 commented
@kmacoskey Could you please review and approve this change?

2023-09-27 12:32 UTC, DevChattopadhyay commented on gpMgmt/bin/gpsd
> +                           '\n-- Copyright (C) 2007 - 2023 VMWare'
Thanks @dgkimura for pointing this out. I have made the required changes. Can you please take a second look and let me know if its fine now.

2023-09-27 16:44 UTC, kmacoskey requested changes
Copyright should stay the same. It denotes that changes were made between those dates from Pivotal. That is accurate. 

When we make new changes, then we add a new copyright line for VMware. Those copyright lines should look like this. The exact format and words are important. 

```
Copyright (c) [Year(s)] VMware, Inc. or its affiliates. All Rights Reserved.
```

As a different suggested change, I don't feel we need to include a copyright statement in the output of miniRepro or gpsd.  The changes to the code itself are what we are claiming a copyright on. The output of running that code doesn't need that.

2023-09-28 04:54 UTC, nimish350 commented
> Copyright should stay the same. It denotes that changes were made between those dates from Pivotal. That is accurate.
> 
> When we make new changes, then we add a new copyright line for VMware. Those copyright lines should look like this. The exact format and words are important.
> 
> ```
> Copyright (c) [Year(s)] VMware, Inc. or its affiliates. All Rights Reserved.
> ```
> 
> As a different suggested change, I don't feel we need to include a copyright statement in the output of miniRepro or gpsd. The changes to the code itself are what we are claiming a copyright on. The output of running that code doesn't need that.


Thank you @kmacoskey. We are going to remove the copyright statement from the output file and include it in the comments in the code itself.

2023-09-28 08:54 UTC, DevChattopadhyay commented
> Copyright should stay the same. It denotes that changes were made between those dates from Pivotal. That is accurate.
> 
> When we make new changes, then we add a new copyright line for VMware. Those copyright lines should look like this. The exact format and words are important.
> 
> ```
> Copyright (c) [Year(s)] VMware, Inc. or its affiliates. All Rights Reserved.
> ```
> 
> As a different suggested change, I don't feel we need to include a copyright statement in the output of miniRepro or gpsd. The changes to the code itself are what we are claiming a copyright on. The output of running that code doesn't need that.

Hello @kmacoskey 
I have updated as per your comments. Can you please take a look and approve it if it looks good

2023-09-28 14:25 UTC, kmacoskey approved these changes

2023-09-29 17:51 UTC, merged