docs - new gpfdist --ssl_verify_peer option and changes
greenplum-db/gpdb pull request #16519
Opened 2023-09-27 21:03 UTC by lisakowen

doc updates for https://github.com/greenplum-db/gpdb/pull/15980. new --ssl_verify_peer option to gpfdist.  its setting affects what cert files are required on the gpfdist side.  with verify_gpfdists_certs guc, also affects what cert files required on the greenplum side.

in this PR:
- update the gpfdists protocol page
- update the verify_gpfdists_cert guc description
- update the gpfdist ref page to add the new --ssl_verify_peer option and description, add an example (is it correct?)
- removed some repeated text that was already located in the verify_gpfdists_cert guc description

doc review site links:
- gpfdists protocol page:  https://docs-staging.vmware.com/en/draft/VMware-Greenplum/ssl_peer_verify/greenplum-database/GUID-admin_guide-external-g-gpfdists-protocol.html
- verify_gpfdists_cert guc description:  https://docs-staging.vmware.com/en/draft/VMware-Greenplum/ssl_peer_verify/greenplum-database/GUID-ref_guide-config_params-guc-list.html#verify_gpfdists_cert
- gpfdist utility ref page:  https://docs-staging.vmware.com/en/draft/VMware-Greenplum/ssl_peer_verify/greenplum-database/GUID-utility_guide-ref-gpfdist.html

2023-09-27 22:35 UTC, dyozie requested changes

2023-09-27 22:35 UTC, dyozie commented on gpdb-doc/markdown/admin_guide/external/g-gpfdists-protocol.html.md
> +The settings of the [verify_gpfdists_cert](../../ref_guide/config_params/guc-list.html#verify_gpfdists_cert) server configuration parameter (default value `true`) and the the [gpfdist](../../utility_
repeated word:  the the

2023-09-27 23:09 UTC, dyozie approved these changes

2023-09-30 01:18 UTC, RuiWang-vmw approved these changes

2023-10-02 15:35 UTC, merged