updated document workload_mgmt_resgroups to support cgroup v1 on rhel9
greenplum-db/gpdb pull request #16580
Opened 2023-10-12 08:18 UTC by Tao-T

libcgroup is official removed since RHEL9. A new service is provided in the document to support gpdb6 with cgroup v1 on RHEL 9.x

2023-10-12 15:16 UTC, mperezfuster approved these changes
I have submitted a couple of edits. Thanks!

2023-10-12 15:27 UTC, dyozie requested changes

2023-10-12 15:27 UTC, dyozie commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +1.  To automatically recreate Greenplum Database required cgroup hierarchies and parameters when your system is restarted, configure your system to enable the Linux cgroup service daemon `cgconfig.se
persisten -> persistent

2023-10-12 15:27 UTC, dyozie commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +2. Write the following content into `greenplum-cgroup-v1-config.service`, if the user is not `gpadmin`, replace it with the appropriate user.
, if -> . If

2023-10-13 03:20 UTC, Tao-T commented
For the commands mentioned in the document, `sudo` is not unified. Some are still prefixed with `sudo` while the others have `sudo` removed.

2023-10-13 03:31 UTC, haolinw commented
I have tried Redhat 9.x script on rocky9, it works fine.

2023-10-18 01:51 UTC, merged