Docs: perform os upgrade from el7 to el8
greenplum-db/gpdb pull request #16636
Opened 2023-10-23 11:09 UTC by mperezfuster

This PR creates a new page for performing an OS upgrade from EL 7 to 8 while maintaining the same version of Greenplum Database. It provides 3 different methods for performing this upgrade, including Performing an in-place simultaneous upgrade, which uses the new utility `upgrade_check.py` provided with 6.26.

It also brings up to date the contents of Synchronizing System Clocks on the page Configuring your Systems which is ported from the GPDB 7 documentation.

Staging site:

https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-os-upgrade/greenplum-database/install_guide-migrate-linux.html#operating-system-configuration-differences

2023-10-23 17:28 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +Major version upgrades of Linux operating systems are always a complex task in a Greenplum environment. You must balance the risks of the different upgrade methods, downtime, or not upgrading for you
You must balance the risks of the different upgrade methods, downtime, or not upgrading for your business. 

==>

You must weigh the risks of the different upgrade methods versus not upgrading at all, as well as consider the impact of the required downtime.

2023-10-23 17:29 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +The GNU C Library, commonly known as `glibc`, is the GNU Project's implementation of the C standard library. Between EL 7 and 8, the version of `glibc` changes from 2.17 to 2.28. This is a major chan
"and their collation"

What's being collated, exactly?

2023-10-23 17:37 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +Greenplum Backup and Restore supports many different options for storage locations. Including local, public cloud storage such as S3, and Dell EMC Data Domain through the use of the [gpbackup storage
Greenplum Backup and Restore supports many different options for storage locations. Including

==>

Greenplum Backup and Restore supports many different options for storage locations, including

2023-10-23 17:38 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +The advantages of this method are different options for storage locations, and migration issues not impacting the source cluster. The disadvantage of this method is that it requires two separate Gree
locations,

==>

locations

2023-10-23 17:39 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +The overall process of this upgrade method consists of:
The overall process of this upgrade method consists of:

==>

As part of the overall process of this upgrade method, you:

2023-10-23 17:41 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +- Run the `upgrade_check.py` utility to perform the pre-check scripts to get the details of any objects that can potentially have data impact from upgrade.
Run the `upgrade_check.py` utility to perform the pre-check scripts to get the details of any objects that can potentially have data impact from upgrade.

==> 

Run the `upgrade_check.py` utility to perform pre-check scripts; these scripts report information on any objects whose data the upgrade might affect.

2023-10-23 17:42 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +Before you begin with the upgrade, connect to each database in your Greenplum Database cluster, and run the following commands:
begin with ==> begin

2023-10-23 17:43 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +Range-partitioned tables using collatable data types in the partition key must be checked to verify that all rows are still in the correct partitions.
Range-partitioned tables using collatable data types in the partition key must be checked

==> 

You must check range-partitioned tables using collatable data types in the partition key

2023-10-23 17:45 UTC, VMWareJennyBeth commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +When you prepare your operating system environment for Greenplum Database software installation, there are different configuration options depending on the version of your operating system. Detailed
Detailed documentation already exists in the pages [Configuring Your Systems](install_guide-prep_os.html) and [Using Resource Groups](../admin_guide/workload_mgmt_resgroups.html#topic71717999).

==> 

See [Configuring Your Systems](install_guide-prep_os.html) and [Using Resource Groups](../admin_guide/workload_mgmt_resgroups.html#topic71717999) for detailed documentation on.

2023-10-23 17:47 UTC, VMWareJennyBeth requested changes
Such beautiful and clear writing, @mperezfuster. 

Just a handful of suggestions.

2023-10-24 07:28 UTC, z-wenlin commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +You may modify the name of the output files if using more than one database. For example, `index-database_name.out`, `table-database_name.out`.
Actually, the `precheck-index` and `precheck-table` will iterate all the databases and do the checking automatically, no need to connect to each database by users, and the output file will include multiple database results if using more than one database.

2023-10-24 07:28 UTC, z-wenlin commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +In order to address the issues caused to the range-partitioned tables, the utility recreates the affected tables at a later step. This can result in additional space requirements for your database, s
maybe change recreates to rebuild?

2023-10-24 07:28 UTC, z-wenlin commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +Run the `upgrade_check.py` utility with the `migrate` subcommand for each database to reindex the necessary indexes. Modify the input file name if required.
the `migrate` subcommand will parse the content in the specified output files and it will connect to each database and run the `reindex XXX` command or rebuild the partition table commands. No need to connect to each Database manually. 

The output content in the file looks like:
```
$ cat index.out
\c  postgres
-- catalog indexrelid: 3597 | index name: pg_seclabel_object_index | table name: pg_seclabel | collname: default | indexdef:  CREATE UNIQUE INDEX pg_seclabel_object_index ON pg_catalog.pg_seclabel USING btree (objoid, classoid, objsubid, provider)
reindex index pg_seclabel_object_index;

-- catalog indexrelid: 3593 | index name: pg_shseclabel_object_index | table name: pg_shseclabel | collname: default | indexdef:  CREATE UNIQUE INDEX pg_shseclabel_object_index ON pg_catalog.pg_shseclabel USING btree (objoid, classoid, provider)
reindex index pg_shseclabel_object_index;

\c  test
-- indexrelid: 16512 | index name: testupgrade.hash_idx1 | table name: testupgrade.hash_test1 | collname: default | indexdef:  CREATE INDEX hash_idx1 ON testupgrade.hash_test1 USING btree (content)
reindex index testupgrade.hash_idx1;
```

2023-10-24 07:28 UTC, z-wenlin commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +
There is an example of this case
> Similarly, in a partitioned table, a query could look in the wrong partition and an update could write to the wrong partition.
```
CREATE TABLE partition_range_test_3(id int, date text) DISTRIBUTED BY (id)
PARTITION BY RANGE (date)
      (
        PARTITION jan START ('01') INCLUSIVE,
        PARTITION feb START ('"02"') INCLUSIVE,
        PARTITION mar START ('"03"') INCLUSIVE );

insert into partition_range_test_3 values (1, '01'), (1, '"01"'), (1, '"02"'), (1, '02'), (1, '03'), (1, '"03"'), (1, '04'), (1, '"04"');

testupgrade=# \dS+ partition_range_test_3;
                Table "public.partition_range_test_3"
 Column |  Type   | Modifiers | Storage  | Stats target | Description
--------+---------+-----------+----------+--------------+-------------
 id     | integer |           | plain    |              |
 date   | text    |           | extended |              |
Child tables: partition_range_test_3_1_prt_feb,
              partition_range_test_3_1_prt_jan,
              partition_range_test_3_1_prt_mar
Distributed by: (id)
Partition by: (date)

testupgrade=# select * from partition_range_test_3 order by date;
 id | date
----+------
  1 | "01"
  1 | 01
  1 | "02"
  1 | 02
  1 | "03"
  1 | 03
  1 | "04"
  1 | 04
(8 rows)

testupgrade=# select * from partition_range_test_3_1_prt_jan ;
 id | date
----+------
  1 | 01
  1 | "01"
  1 | 02
(3 rows)

testupgrade=# select * from partition_range_test_3_1_prt_feb ;
 id | date
----+------
  1 | "02"
  1 | 03
(2 rows)

testupgrade=# select * from partition_range_test_3_1_prt_mar ;
 id | date
----+------
  1 | "03"
  1 | 04
  1 | "04"
(3 rows)

--- !! wrong results here !!--------
testupgrade=# select * from partition_range_test_3 where date='03';
 id | date
----+------
(0 rows)

testupgrade=# explain select * from partition_range_test_3 where date='03';
                                           QUERY PLAN
------------------------------------------------------------------------------------------------
 Gather Motion 4:1  (slice1; segments: 4)  (cost=0.00..720.00 rows=50 width=36)
   ->  Append  (cost=0.00..720.00 rows=13 width=36)
         ->  Seq Scan on partition_range_test_3_1_prt_mar  (cost=0.00..720.00 rows=13 width=36)
               Filter: (date = '03'::text)
 Optimizer: Postgres query optimizer
(5 rows)

testupgrade=# select * from partition_range_test_3_1_prt_mar;
 id | date
----+------
  1 | "03"
  1 | 04
  1 | "04"
(3 rows)

testupgrade=# select * from partition_range_test_3_1_prt_feb ;
 id | date
----+------
  1 | "02"
  1 | 03
(2 rows)

--- !! wrong results with orca !! ----
testupgrade=# select * from partition_range_test_3 where date='03';
 id | date
----+------
(0 rows)

testupgrade=# explain select * from partition_range_test_3 where date='03';
                                                      QUERY PLAN
----------------------------------------------------------------------------------------------------------------------
 Gather Motion 4:1  (slice1; segments: 4)  (cost=0.00..431.00 rows=1 width=12)
   ->  Sequence  (cost=0.00..431.00 rows=1 width=12)
         ->  Partition Selector for partition_range_test_3 (dynamic scan id: 1)  (cost=10.00..100.00 rows=25 width=4)
               Partitions selected: 1 (out of 3)
         ->  Dynamic Seq Scan on partition_range_test_3 (dynamic scan id: 1)  (cost=0.00..431.00 rows=1 width=12)
               Filter: (date = '03'::text)
 Optimizer: Pivotal Optimizer (GPORCA)
(7 rows)
```

2023-10-25 10:46 UTC, mperezfuster commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +The GNU C Library, commonly known as `glibc`, is the GNU Project's implementation of the C standard library. Between EL 7 and 8, the version of `glibc` changes from 2.17 to 2.28. This is a major chan
I have added a short explanation, let me know if it looks OK.

2023-10-25 10:48 UTC, mperezfuster commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +The advantages of this method are different options for storage locations, and migration issues not impacting the source cluster. The disadvantage of this method is that it requires two separate Gree
are you sure? They are different advantages:
1. different options for storage locations
2. migration issues don't impact source cluster

2023-10-25 10:56 UTC, mperezfuster commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +
@z-wenlin thank you. I took some snippets from that example as it looks a bit too long for the documentation. Is what I added correct and illustrative?

2023-10-26 08:38 UTC, RuiWang-vmw commented
LGTM, but do we need to mention that in the gpcopy doc or not?

2023-11-01 23:21 UTC, soumyadeep2007 approved these changes
LGTM!

2023-11-01 23:21 UTC, soumyadeep2007 commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +The GNU C Library, commonly known as `glibc`, is the GNU Project's implementation of the C standard library. Between EL 7 and 8, the version of `glibc` changes from 2.17 to 2.28. This is a major chan
collation -> collations.

2023-11-01 23:21 UTC, soumyadeep2007 commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +> **Note** In-Place upgrades with the Leapp utility are not supported with Rocky Linux. You must use a logical replication method such as Greenplum Copy or Greenplum Backup and Restore instead.
I would refrain from using the term "logical replication" as it refers to the Logical Replication PG feature. Just say "you must use Greenplum Copy or Greenplum Backup and Restore instead"

2023-11-02 01:43 UTC, z-wenlin commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +
Yes, it is also correct, but I think this example is more illustrative than the example that added one. Maybe we could replace that example with this one.
This is the short version of the above example.
```
CREATE TABLE partition_range_test_3(id int, date text) DISTRIBUTED BY (id)
PARTITION BY RANGE (date)
      (
        PARTITION jan START ('01') INCLUSIVE,
        PARTITION feb START ('"02"') INCLUSIVE,
        PARTITION mar START ('"03"') INCLUSIVE );

insert into partition_range_test_3 values (1, '01'), (1, '"01"'), (1, '"02"'), (1, '02'), (1, '03'), (1, '"03"'), (1, '04'), (1, '"04"');

--- !! wrong results here !!--------
=# select * from partition_range_test_3 where date='03';
 id | date
----+------
(0 rows)

=# explain select * from partition_range_test_3 where date='03';
                                           QUERY PLAN
------------------------------------------------------------------------------------------------
 Gather Motion 4:1  (slice1; segments: 4)  (cost=0.00..720.00 rows=50 width=36)
   ->  Append  (cost=0.00..720.00 rows=13 width=36)
         ->  Seq Scan on partition_range_test_3_1_prt_mar  (cost=0.00..720.00 rows=13 width=36)
               Filter: (date = '03'::text)
 Optimizer: Postgres query optimizer
(5 rows)

=# select * from partition_range_test_3_1_prt_mar;
 id | date
----+------
  1 | "03"
  1 | 04
  1 | "04"
(3 rows)

=# select * from partition_range_test_3_1_prt_feb ;
 id | date
----+------
  1 | "02"
  1 | 03
(2 rows)
```

2023-11-02 11:31 UTC, mperezfuster commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +
thank you, this is great

2023-11-13 19:16 UTC, kmacoskey requested changes

2023-11-13 19:16 UTC, kmacoskey commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +- Databases or table columns using the `C` or `POSIX` locales are not affected. All other locales are potentially affected.
```suggestion
- When using an in-place upgrade method, databases or table columns using the `C` or `POSIX` locales are not affected. All other locales are potentially affected.
```

May want to shift this up one bullet point.

2023-11-13 19:16 UTC, kmacoskey commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +- Using Greenplum Backup and Restore to copy from Greenplum on EL 7 to a separate Greenplum on EL 8.
```suggestion
- Using Greenplum Backup and Restore to restore a backup taken from Greenplum on EL 7 to a separate Greenplum on EL 8.
```

2023-11-13 19:16 UTC, kmacoskey commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +- Using the Leapp utility to perform an in-place, simultaneous upgrade of EL 7 to EL 8 for all Greenplum hosts in a cluster.
```suggestion
- Using operating system vendor supported utilities, such as `leapp` to perform an in-place, simultaneous upgrade of EL 7 to EL 8 for all Greenplum hosts in a cluster then following the required post upgrade steps.
```

2023-11-13 19:16 UTC, kmacoskey commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +
In some sort of warning box:

```suggestion
Greenplum does not support a rolling upgrade, such that some Greenplum Segment Hosts are operating with EL 7 and others with EL 8. All Segment Hosts must be upgraded together or otherwise before Greenplum is started and workload continued after an upgrade. ```

2023-11-13 19:16 UTC, kmacoskey commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +This utility is compatible with the Greenplum Database cluster from the source and destination running on different operating systems, including EL 7 to EL 8. The `glibc` changes are not relevant for
```suggestion
This utility is compatible with the Greenplum Database cluster from the source and destination running on different operating systems, including EL 7 to EL 8. The `glibc` changes are not relevant for this migration method because the data is rewritten on copy to the target cluster, which addresses any locale sorting changes. However, since Greenplum Copy enables the option `-parallelize-leaf-partitions` by default, which copies the leaf partition tables of a partitioned table in parallel, it may lead to data being copied to an incorrect partition caused by the `glibc` changes. You must disable this option so that the table is copied as one single table based on the root partition table. 
```

2023-11-13 19:16 UTC, kmacoskey commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +- Create a new Greenplum cluster on the EL 8 systems with no data.
```suggestion
- Create a new Greenplum cluster using EL 8 with no data
```

2023-11-13 19:16 UTC, kmacoskey commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +The utility is compatible with the Greenplum Database cluster from the source and destination running on different operating systems, including EL 7 to EL 8. The `glibc` changes are not relevant for
```suggestion
The utility is compatible with the Greenplum Database cluster from the source and destination running on different operating systems, including EL 7 to EL 8. The `glibc` changes are not relevant for this migration method because the data is rewritten on the new cluster, which addresses any locale sorting changes. However, if the backup command includes the option `--leaf-partition-data`, it creates one data file per leaf partition, instead of one data file for the entire table. In this situation, when you restore the partition data to the upgraded cluster, the utility copies the data directly into the leaf partitions, which may lead to data being copied into an incorrect partition caused by the `glibc` changes. Therefore, you must ensure that the backup command does not use the option `--leaf-partition-data` so partitioned tables are copied as a single data file.
```

2023-11-13 19:16 UTC, kmacoskey commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +- Create a new Greenplum cluster on the EL 8 systems with no data.
```suggestion
- Create a new Greenplum cluster using EL 8 with no data
```

2023-11-13 19:16 UTC, kmacoskey commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +> **Note** In-Place upgrades with the Leapp utility are not supported with Rocky Linux. You must use Greenplum Copy or Greenplum Backup and Restore instead.
```suggestion
> **Note** In-Place upgrades with the Leapp utility are not supported with Rocky or CentOS Linux. You must use Greenplum Copy or Greenplum Backup and Restore instead.
```

2023-11-13 19:16 UTC, kmacoskey commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +- Address any required operating system configuration differences and start the Greenplum cluster.
```suggestion
- Address any [Operating System Configuration Differences](#os_config).
```

2023-11-13 19:16 UTC, kmacoskey commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +- Follow the required steps for fixing the data that is impacted by the `glibc` locale sorting changes.
```suggestion
- Follow the required steps given by the `upgrade_check.py` for fixing the data that is impacted by the `glibc` locale sorting changes.
```

2023-11-13 19:16 UTC, kmacoskey commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +> **Important** We recommend you take a backup of your cluster before proceeding with this method, as you will not be able to recover the database if the upgrade does not complete successfully.
We may as well want to recommend being prepared to contact your operating system vendor for any issues encountered with the `leapp` utility.

2023-11-15 11:00 UTC, mperezfuster commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +- Address any required operating system configuration differences and start the Greenplum cluster.
I link to the section when I provide the detail instructions, I thought it be easier to just outline what it's done in order to prevent jumping across the document at this stage.

2023-11-15 15:50 UTC, kmacoskey commented on gpdb-doc/markdown/install_guide/migrate-linux.html.md
> +- Address any required operating system configuration differences and start the Greenplum cluster.
Ok, good choice.

2023-11-16 21:59 UTC, merged