Retry gang creation for non-recovery failures
greenplum-db/gpdb pull request #16693
Opened 2023-11-04 00:54 UTC by soumyadeep2007

Before this commit, any error from a segment that is unrelated to
recovery, would result in an immediate termination with the following:

ereport(ERROR, (errcode(ERRCODE_GP_INTERCONNECTION_ERROR),
	errmsg("failed to acquire resources on one or more segments"),
	errdetail("%s (%s)", PQerrorMessage(segdbDesc->conn), segdbDesc->whoami)));

In other words, this termination did not respect
gp_gang_creation_retry_count. From now on, we exhaust the retries first,
before emitting this ERROR.

Co-authored-by: Ashwin Agrawal <aashwin@vmware.com>

2023-11-06 14:22 UTC, xinzweb requested changes
I cannot wait to see this patch committed to add more resilience to the gang formation.

There is a minor issue on counting the retries, would you please double check? Thanks.

2023-11-06 14:22 UTC, xinzweb commented on src/backend/cdb/dispatcher/cdbgang_async.c
> +	int		other_failures;
```suggestion
	int		other_failures = 0;
```
Do we also want to initialize it to 0?

2023-11-06 14:22 UTC, xinzweb commented on src/backend/cdb/dispatcher/cdbgang_async.c
> +								create_gang_retry_counter++ >= gp_gang_creation_retry_count)
We have retry++ in line 365 below, do we still need to do the increment here?

2023-11-06 16:54 UTC, soumyadeep2007 commented on src/backend/cdb/dispatcher/cdbgang_async.c
> +	int		other_failures;
Actually, `other_failures = 0;` is initialized a few lines below under the `create_gang_retry` goto label.
So, we don't need it here.

2023-11-06 17:03 UTC, soumyadeep2007 commented on src/backend/cdb/dispatcher/cdbgang_async.c
> +								create_gang_retry_counter++ >= gp_gang_creation_retry_count)
My bad! Corrected!

2023-11-07 17:12 UTC, huansong approved these changes
LGTM!

2023-11-08 19:26 UTC, soumyadeep2007 commented on src/backend/cdb/dispatcher/cdbgang_async.c
> +								errmsg("failed to acquire resources on one or more segments: fault injector"),
I don't see any occurrences of `failed to acquire resources on one or more segments` messages which can error out due to a fault injection message. I think this is the only site. All others are very specific cases unrelated to fault injection failures.

2023-11-08 19:50 UTC, huansong commented on src/backend/cdb/dispatcher/cdbgang_async.c
> +								errmsg("failed to acquire resources on one or more segments: fault injector"),
Sorry I wasn't clear - I meant adding similar notion for other failed reasons, besides the `fault injector` one. For example, the other ERROR added in this PR can be specified as `failed to acquire resources on one or more segments: other reason`. There are just so many `failed to acquire resources on one or more segments` messages that make it not very useful. Your addition of `fault injector` reminded me that we could add that for the other ones, such as:
```
if (cdbconn_isBadConnection(segdbDesc))
                                ereport(ERROR, (errcode(ERRCODE_GP_INTERCONNECTION_ERROR),
                                                                errmsg("failed to acquire resources on one or more segments: bad connection")
......
if (poll_timeout == 0)
                                ereport(ERROR, (errcode(ERRCODE_GP_INTERCONNECTION_ERROR),
                                                                errmsg("failed to acquire resources on one or more segments: poll timeout"),
```
etc. just for some more info when a related issue is being reported.

2023-11-08 19:56 UTC, soumyadeep2007 commented on src/backend/cdb/dispatcher/cdbgang_async.c
> +								errmsg("failed to acquire resources on one or more segments: fault injector"),
Oh I get it. Fair point, will add.

2023-11-08 20:04 UTC, soumyadeep2007 commented on src/backend/cdb/dispatcher/cdbgang_async.c
> +								errmsg("failed to acquire resources on one or more segments: fault injector"),
On second thought, the sheer pain of having to update all manner of tests is making me have second thoughts.
We do have good errdetail and frankly that is what the errdetail is for. It would be kind of redundant to say for instance:
```
errmsg("failed to acquire resources on one or more segments: in reset/recovery"),
								errdetail("Segments are in reset/recovery mode.")));
```

2023-11-08 20:22 UTC, soumyadeep2007 commented on src/backend/cdb/dispatcher/cdbgang_async.c
> +#include "libpq/libpq-be.h"
Good catch. Removed it, sometimes IDEs are a pain!

2023-11-08 20:23 UTC, huansong commented on src/backend/cdb/dispatcher/cdbgang_async.c
> +								errmsg("failed to acquire resources on one or more segments: fault injector"),
Yes that's true. The cost & benefit doesn't really match. The benefit is tiny as only for those w/o a clear `errdetail`. Let's forget about it.

2023-11-15 17:10 UTC, xinzweb reviewed
It's a very minor habit on the local variable initialization. I will leave that to you to figure out which style is better. Thanks. 

The rest are good to go from my side. Thanks.

2023-11-15 17:10 UTC, xinzweb commented on src/backend/cdb/dispatcher/cdbgang_async.c
> +	int		other_failures;
I saw that, but we also have the `successful_connections` initialized in the `create_gang_retry` block, and also initialized here.

I like the consistency of the coding style, as well as a clear initialization to the local variables in the function.

2023-11-15 17:21 UTC, soumyadeep2007 commented on src/backend/cdb/dispatcher/cdbgang_async.c
> +	int		other_failures;
Sounds good, made the change!

2023-11-15 17:26 UTC, merged