Resolve FIXME in create_ctescan_path()  in pathnode.c.
greenplum-db/gpdb pull request #16749
Opened 2023-11-17 10:01 UTC by Aegeaner

Here in `create_ctescan_path()`, we only pass the `Subpath` not Null when the CTE is not shared:
https://github.com/greenplum-db/gpdb/blob/7ef0db993d850268bc8c365f8d8728345ce1f11a/src/backend/optimizer/path/allpaths.c#L3105

So it's safe to remove this fixme.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2023-12-06 06:22 UTC, adam8157 requested changes
I don't get this PR, the comment says "We can't extract these two values from the subplan", but the FIXME and your investigation say "We do have the subpath in some cases".

So this PR is supposed to do things like this (if the subpath exists and it should use the subpath's values), but not just remove the FIXME:

```
	pathnode->motionHazard = subpath->motionHazard;
	pathnode->rescannable = subpath->rescannable;
```

2023-12-08 07:05 UTC, Aegeaner commented
Dev pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-cost_unshared_ctescan-rocky8

Need minor fix for regression test.

2023-12-08 07:36 UTC, adam8157 approved these changes

2023-12-11 08:02 UTC, avamingli commented on src/test/regress/expected/subselect.out
> + Settings: gp_cte_sharing = 'on'
Hi, why Materialize is missed here?

2023-12-11 08:30 UTC, Aegeaner commented on src/test/regress/expected/subselect.out
> + Settings: gp_cte_sharing = 'on'
@avamingli After this patch, when creating nestloop plan for this test case, the `best_path->innerjoinpath` has `motionHazard` as `false` and `rescannable` as `true`, so it will not create a `Material` node there:
https://github.com/greenplum-db/gpdb/blob/1f362cec299302c43bcf2773d6e199dfcfba3ef8/src/backend/optimizer/plan/createplan.c#L4892-L4893

2023-12-12 07:58 UTC, z-wenlin commented on src/test/regress/expected/subselect.out
> + Settings: gp_cte_sharing = 'on'
Are the settings needed?

2023-12-12 08:48 UTC, Aegeaner commented on src/test/regress/expected/subselect.out
> + Settings: gp_cte_sharing = 'on'
Yes, because before this group of inline CTE test cases, it has turned the GUC `gp_cte_sharing` to `on`, which is modified from the default value `off`, and this is a verbose mode `Explain` statement, so the modified settings would be printed out:
https://github.com/greenplum-db/gpdb/blob/42ffb9a2c56eb9957446bce5d67972616c0c20ff/src/test/regress/expected/subselect.out#L1641

2023-12-12 11:36 UTC, Aegeaner commented
The dev pipeline is green now, so I will merge this PR.

2023-12-12 11:37 UTC, merged