Docs: add PL/Container support with Resource Groups back
greenplum-db/gpdb pull request #16886
Opened 2023-12-20 17:07 UTC by mperezfuster

This PR reintroduces PL/Container support with Resource Groups. 
It aligns most of the GPDB 7 documentation to what GPDB 6 supported, plus a few additions:

- New guc gp_resource_group_cgroup_parent
- Modification of the bash script for resource groups using cgroup v2 to automatically start during system startup.

Questions:
- Can you provide an example of creating a resource group for the `CREATE RESOURCE GROUP` reference page that uses PL/Container? The previous examples used memory auditor.
- Can you review  the page gpdb-doc/markdown/analytics/pl_container_using.html.md to help adapt concepts to the GPDB 7 resource group concepts? I only ported back the changes that were removed on https://github.com/greenplum-db/gpdb/pull/16490 so it needs some editing. Especially around memory management.
- Regarding GUC `gp_resource_group_cgroup_parent`, can you confirm that the default value, parameter categories, explanation, etc are correct?

Any other changes I might have missed please let me know
Staging site:
https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-plcontainer/greenplum-database/admin_guide-workload_mgmt_resgroups.html
https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-plcontainer/greenplum-database/analytics-pl_container.html
https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-plcontainer/greenplum-database/ref_guide-config_params-guc-list.html#gp_resource_group_cgroup_parent

2023-12-21 07:31 UTC, RMTT requested changes

2023-12-21 07:31 UTC, RMTT commented on gpdb-doc/markdown/analytics/pl_container_using.html.md
> +Resource groups for external components such as PL/Container use Linux control groups \(cgroups\) to manage component-level use of memory and CPU resources. When you manage PL/Container resources wit
This paragraph is unnecessary:
```
When you manage PL/Container resources with resource groups, you configure both a memory limit and a CPU limit that Greenplum Database applies to all container instances that share the same PL/Container runtime configuration.
```

2023-12-21 07:31 UTC, RMTT commented on gpdb-doc/markdown/analytics/pl_container_using.html.md
> +When you create a resource group to manage the resources of a PL/Container runtime, you must specify `MEMORY_AUDITOR=cgroup` and `CONCURRENCY=0` in addition to the required CPU and memory limits. For
This paragraph can be deleted:
```
When you create a resource group to manage the resources of a PL/Container runtime, you must specify `MEMORY_AUDITOR=cgroup` and `CONCURRENCY=0` in addition to the required CPU and memory limits.
```

2023-12-21 07:31 UTC, RMTT commented on gpdb-doc/markdown/analytics/pl_container_using.html.md
> +                                                  CPU_RATE_LIMIT=10, MEMORY_LIMIT=10);
```
CREATE RESOURCE GROUP plpy_run1_rg WITH (CONCURRENCY=10, CPU_MAX_PERCENT=10, MEMORY_LIMIT=10);
```

2023-12-21 07:31 UTC, RMTT commented on gpdb-doc/markdown/analytics/pl_container_using.html.md
> +PL/Container does not use the `MEMORY_SHARED_QUOTA` and `MEMORY_SPILL_RATIO` resource group memory limits. Refer to the [CREATE RESOURCE GROUP](../ref_guide/sql_commands/CREATE_RESOURCE_GROUP.html) r
This paragraph can be deleted.

2023-12-21 07:31 UTC, RMTT commented on gpdb-doc/markdown/analytics/pl_container_using.html.md
> +After you assign a resource group to a PL/Container runtime, all container instances that share the same runtime configuration are subject to the memory limit and the CPU limit that you configured fo
This paragraph should be changed to:
```
After you assign a resource group to a PL/Container runtime, all container instances that share the same runtime configuration are subject to the CPU limit that you configured for the group.
```

2023-12-21 07:31 UTC, RMTT commented on gpdb-doc/markdown/analytics/pl_container_using.html.md
> +Perform the following procedure to configure PL/Container to use Greenplum Database resource groups for CPU and memory resource management:
remove memory related:
```
Perform the following procedure to configure PL/Container to use Greenplum Database resource groups for CPU resource management:
```

2023-12-21 07:31 UTC, RMTT commented on gpdb-doc/markdown/analytics/pl_container_using.html.md
> +    > **Note** If you have previously configured and enabled resource groups in your deployment, ensure that the Greenplum Database resource group `gpdb.conf` cgroups configuration file includes a `m
This paragraph can be deleted.

2023-12-21 07:31 UTC, RMTT commented on gpdb-doc/markdown/analytics/pl_container_using.html.md
> +2.  Analyze the resource usage of your Greenplum Database deployment. Determine the percentage of resource group CPU and memory resources that you want to allocate to PL/Container Docker containers.
remove memory related:
```
Analyze the resource usage of your Greenplum Database deployment. Determine the percentage of resource group CPU resources that you want to allocate to PL/Container Docker containers.
```

2023-12-21 07:31 UTC, RMTT commented on gpdb-doc/markdown/analytics/pl_container_using.html.md
> +3.  Determine how you want to distribute the total PL/Container CPU and memory resources that you identified in the step above among the PL/Container runtimes. Identify:
remove memory related:
```
Determine how you want to distribute the total PL/Container CPU resources that you identified in the step above among the PL/Container runtimes.
```

2023-12-21 07:31 UTC, RMTT commented on gpdb-doc/markdown/analytics/pl_container_using.html.md
> +    -   The percentage of memory and CPU resources to allocate to each resource group.
remove memory related:
```
The percentage of CPU resources to allocate to each resource group.
```

2023-12-21 07:31 UTC, RMTT commented on gpdb-doc/markdown/analytics/pl_container_using.html.md
> +4.  Create the PL/Container resource groups that you identified in the step above. For example, suppose that you choose to allocate 25% of both memory and CPU Greenplum Database resources to PL/Conta
remove memory related:

```
Create the PL/Container resource groups that you identified in the step above. For example, suppose that you choose to allocate 25% of  CPU Greenplum Database resources to PL/Container. If you further split these resources among 2 resource groups 60/40, the following SQL commands create the resource groups:
```

2023-12-21 07:31 UTC, RMTT commented on gpdb-doc/markdown/analytics/pl_container_using.html.md
> +                                               CPU_RATE_LIMIT=15, MEMORY_LIMIT=15);
This query should be:
```
CREATE RESOURCE GROUP plr_run1_rg WITH (CONCURRENCY=0,
                                                                                   CPU_MAX_PERCENT=15);
```

2023-12-21 07:31 UTC, RMTT commented on gpdb-doc/markdown/analytics/pl_container_using.html.md
> +                                              CPU_RATE_LIMIT=10, MEMORY_LIMIT=10);
This query should be:
```
CREATE RESOURCE GROUP plr_run1_rg WITH (CONCURRENCY=0,
                                                                                   CPU_MAX_PERCENT=10);
```

2023-12-21 07:31 UTC, RMTT commented on gpdb-doc/markdown/ref_guide/sql_commands/ALTER_RESOURCE_GROUP.html.md
> +When you increase the memory limit of a resource group that you create for external components, the new resource limit is phased in as system memory resources become available. If you decrease the me
The lines  can be deleted:

> For example, if you decrease the memory limit of a resource group that you create for a  PL/Container runtime, queries in a running container may fail with an out of memory error.

2023-12-21 07:31 UTC, RMTT commented on gpdb-doc/markdown/analytics/pl_container_using.html.md
> +With PL/Container 1.2.0 and later, you can use Greenplum Database resource groups to manage and limit the total CPU and memory resources of containers in PL/Container runtimes. For more information a
remove memory related:

> With PL/Container 1.2.0 and later, you can use Greenplum Database resource groups to manage and limit the total CPU resources of containers in PL/Container runtimes.

2023-12-21 07:34 UTC, RMTT commented
For your questions:

> Can you provide an example of creating a resource group for the CREATE RESOURCE GROUP reference page that uses PL/Container? The previous examples used memory auditor.

and 

> Can you review the page gpdb-doc/markdown/analytics/pl_container_using.html.md to help adapt concepts to the GPDB 7 resource group concepts? I only ported back the changes that were removed on https://github.com/greenplum-db/gpdb/pull/16490 so it needs some editing. Especially around memory management.

i have updated it in the review comments.

> Regarding GUC gp_resource_group_cgroup_parent, can you confirm that the default value, parameter categories, explanation, etc are correct?

it's correct.


 thanks for you work.

2023-12-21 10:36 UTC, RMTT commented on gpdb-doc/markdown/analytics/pl_container_using.html.md
> +With PL/Container 1.2.0 and later, you can use Greenplum Database resource groups to manage and limit the total CPU and memory resources of containers in PL/Container runtimes. For more information a
plcontainer will support resource group with gpdb7 from `2.4.0`, so the version here should be `2.4.0`.

2024-01-09 09:16 UTC, RMTT approved these changes

2024-01-11 08:55 UTC, RMTT requested changes

2024-01-11 08:55 UTC, RMTT commented on gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
> +2. Write the following content into `gpdb-service`, if the user is not `gpadmin`, replace it with the appropriate user.
`gpdb-service` -> `gpdb.service`

2024-01-11 09:50 UTC, wenwangBJ approved these changes
LGTM

2024-01-11 10:05 UTC, RMTT approved these changes

2024-01-11 12:28 UTC, merged