Initialise GPDB cluster using `gp` utility
greenplum-db/gpdb pull request #16900
Opened 2023-12-22 10:45 UTC by jnihal

Following `gp services` framework [PR](https://github.com/greenplum-db/gpdb/pull/15563), here's the functionality to initialize the cluster using the underlying framework. Current PR covers the following:
- Cluster initialization with the provided configuration
- Unit tests for most of the code-path
- Support for JSON, YAML, and TOML config files

**High-level flow**:
1. Invoke CLI: `gp init cluster <config-file>`
2. Config Validation: Validates input configuration
3. Request to hub:  RPC on Hub to initialize the cluster
4. Hub side validation: Validate the host environment on each host
5. Create Coordinator: Create the coordinator and register primaries
6. Create Primaries
7. Start Cluster

**The program flow:**
- cli/init.go: Starting point for init command command `gp init cluster`. Performs basic flag checks, and config file validity checks. Forms cluster creation request and makes a call to RPC service on Hub to create the cluster.
- hub/make_cluster.go: Starting point for MakeCluster RPC to create the actual cluster
- MakeCluster calls for Validating host environment where multiple checks are done returning error/warning
- MakeCluster creates coordinator segment followed by the start segment
- Registering primaries
- Make Cluster creates primary segments in parallel on all hosts
- Stop coordinator
- Start the cluster using `gpstart`
- Create GPDB extensions
- Import collations
- Setup GPDB superuser password

### Example

**Setup Pre-requisites:**
Make sure that the gp services are configured and started before beginning with the cluster initialization. Steps to setup gp services is as follows:

```
make; make install
gp configure <configure options like certs, host-list etc>
gp start services

```
Check status of the gp services using:
```
gp status services
```
All the services must be running.
All the hosts part of GPDB cluster has a running agent service.

**Initialising cluster:**
```
gp init cluster cluster-config.json

gp init cluster <input-config-file> [--force]

input-config-file : json/yaml/toml file containing the cluster configuration.
--force flag : overide previous installation by deleting existing data-directories.

```

**Sample input configuration file**
(Please replace the hostname with the actual hostname):
```
{
   "cluster-name":"GPDB",
   "encoding":"Unicode",
   "hba-hostnames":true,
   "su-password":"gparray",
   "data-checksums":true,
   "locale":{
      "lc-all":"en_US.UTF-8",
      "lc-collate":"en_US.UTF-8",
      "lc-ctype":"en_US.UTF-8",
      "lc-messages":"en_US.UTF-8",
      "lc-monetary":"en_US.UTF-8",
      "lc-numeric":"en_US.UTF-8",
      "lc-time":"en_US.UTF-8"
   },
   "common-config":{
      "shared_buffers":"128000kB"
   },
   "coordinator-config":{
      "max_connections":50
   },
   "segment-config":{
      "max_connections":150,
      "debug_pretty_print":"off",
      "log_min_messages":"warning"
   },
   "coordinator":{
      "hostname":"host-1",
      "address":"host-1",
      "port":7000,
      "data-directory":"/tmp/demo/0"
   },
   "primary-segments-array":[
      {
         "hostname":"host-1",
         "address":"host-1",
         "port":7002,
         "data-directory":"/tmp/demo/1"
      },
      {
         "hostname":"host-1",
         "address":"host-1",
         "port":7003,
         "data-directory":"/tmp/demo/2"
      },
      {
         "hostname":"host-1",
         "address":"host-1",
         "port":7004,
         "data-directory":"/tmp/demo/3"
      },
      {
         "hostname":"host-1",
         "address":"host-1",
         "port":7005,
         "data-directory":"/tmp/demo/4"
      }
   ]
}
```

### Testing
- Creating multi segment cluster on localhost
- Creating multi host multi segment setup
- Support of YAML, TOML, JSON files

**Following things will be covered in the future PR -**
- Support for mirrors
- Support for expandable config file
- Functional tests for `gp init` command
- Generate sample config file using the `-o` option

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2024-01-11 09:30 UTC, shrakesh commented on gpMgmt/bin/go-tools/utils/command_utils.go
> +func GetGphomeUtilityPath(gphome, utility string) string {
nit: s/GetGphomeUtilityPath/GetGpUtilityPath

2024-01-11 09:32 UTC, shrakesh commented on gpMgmt/bin/go-tools/utils/greenplum/commands_test.go
> +	"os/exec"
os/exec imported and not used

2024-01-11 09:33 UTC, shrakesh commented on gpMgmt/bin/go-tools/utils/greenplum/gparray.go
> +type Segment struct {
update the segment sequence and name the same as gp_segment_configuration

2024-01-11 09:36 UTC, shrakesh commented on gpMgmt/bin/go-tools/utils/greenplum/gparray.go
> +	return seg.ContentId >= 0 && ((seg.Role == constants.RolePrimary) || (seg.PrefRole == constants.RolePrimary))
is it really required to check both, either we should check the current role or the preferred role.

2024-01-11 09:39 UTC, shrakesh commented on gpMgmt/bin/go-tools/utils/greenplum/gparray.go
> +func (gpArray *GpArray) ReadGpSegmentConfig(conn *dbconn.DBConn) error {
we have api in gp-common-go-libs to get the segment configuration from the database, may be we can check that if that can be use here.

clean the commented code if not needed.

2024-01-11 09:53 UTC, shrakesh commented on gpMgmt/bin/go-tools/utils/greenplum/gparray.go
> +		fmt.Println(addSegmentQuery)
was this added for debug purpose, remove if not needed.

2024-01-15 08:57 UTC, shrakesh commented on gpMgmt/bin/go-tools/utils/sys_utils.go
> +	return
I think it should be the return result instead of just return.

2024-01-15 09:10 UTC, Annu149 commented on gpMgmt/bin/go-tools/cli/init.go
> +func InitClusterServiceFn(hubConfig *hub.Config, inputConfigFile string, force, verbose bool) error {
hubConfig parameter not required

2024-01-15 09:27 UTC, shrakesh commented on gpMgmt/bin/go-tools/utils/sys_utils_test.go
> +		file, err := os.CreateTemp("", "")
as far as I understand we expect utils.WriteLinesToFile() to create a file. do we required to create the file and pass the name? 
did it not work if we only passed the file name to function utils.WriteLinesToFile()

2024-01-15 09:32 UTC, shrakesh commented on gpMgmt/bin/go-tools/utils/sys_utils.go
> +	_, err = file.WriteString(strings.Join(lines, "\n"))
are we expecting that line in lines will not have /n at the end of the file. do we need to join if the line has a new line character at the end?

2024-01-15 10:03 UTC, shrakesh commented on gpMgmt/bin/go-tools/utils/postgres/update_conf_files.go
> +				if !overwrite {
in first look, I see there is for loop inside for loop and then pattern matching. 
which is almost n^2 ( for nested for loop) and ~n^2 for pattern matching. 
 can we improve this, I can see that we can break iterating through configParams once we found a match, surely there will be more way to improve the complexity.

2024-01-15 10:27 UTC, ravoorsh requested changes

2024-01-15 10:29 UTC, ravoorsh commented
Some generic comments:

1. Please add a diagram to explain the flow in description.
2. In program flow, add files so that it becomes easier to review.
3. Add code comments where appropriate.

2024-01-16 09:27 UTC, shrakesh commented on gpMgmt/bin/go-tools/utils/postgres/update_conf_files.go
> +	if _, err := strconv.ParseFloat(value, 64); err == nil {
I feel the function is confusing to me, the function name is quoteString, and it should be supposed to quote the string.  but here in some portions, we are doing string to float and returning float64 as a string.

2024-01-16 09:27 UTC, piyushc01 commented on gpMgmt/bin/go-tools/utils/greenplum/commands_test.go
> +	"os/exec"
in use at : 
https://github.com/greenplum-db/gpdb/blob/a75fde7c92fdf5e3446aa9b810bdcf2c93f6a628/gpMgmt/bin/go-tools/utils/greenplum/commands_test.go#L86

2024-01-16 09:37 UTC, jnihal commented on gpMgmt/bin/go-tools/cli/init.go
> +		return &idl.MakeClusterRequest{}, fmt.Errorf("error while reading config file: %w", err)
Can we remove the `error` prefix and format the error messages as `failed to read config file` or `not able to read config file`. Since these messages are printed using `gplog.Error()`, the `error` term would become redundant.

2024-01-16 09:37 UTC, jnihal commented on gpMgmt/bin/go-tools/cli/init.go
> +	if _, ok := request.ClusterParams.CoordinatorConfig["max_connections"]; !ok {
What if the user provided this value in the `common config`? That value can still be applied to the coordinator as well.

2024-01-16 09:37 UTC, jnihal commented on gpMgmt/bin/go-tools/cli/init.go
> +		return fmt.Errorf("error parsing max_connections from json: %v", err)
Can we put the value we are trying to convert in the error message so that user has more context. And also can we rephrase it to something like `invalid value %s for max_connections, must be an integer`.

2024-01-16 09:37 UTC, jnihal commented on gpMgmt/bin/go-tools/cli/init.go
> +	hostToPortDataDirectory := make(map[string]map[string]bool)
We can create a map with an integer type, right? Instead of converting the port value to a string later. And also we should check the port values against the host address as each address can have their own port range and a host can have multiple addresses.

2024-01-16 10:32 UTC, piyushc01 commented on gpMgmt/bin/go-tools/utils/greenplum/gparray.go
> +	return seg.ContentId >= 0 && ((seg.Role == constants.RolePrimary) || (seg.PrefRole == constants.RolePrimary))
Renaming function to `isSegmentActingPrimary` and will check only for the current role (i.e. seg.Role) if primary.

2024-01-17 10:59 UTC, piyushc01 commented on gpMgmt/bin/go-tools/utils/greenplum/gparray.go
> +type Segment struct {
updated

2024-01-17 11:00 UTC, piyushc01 commented on gpMgmt/bin/go-tools/utils/command_utils.go
> +func GetGphomeUtilityPath(gphome, utility string) string {
Updated

2024-01-17 11:00 UTC, piyushc01 commented on gpMgmt/bin/go-tools/utils/greenplum/gparray.go
> +	return seg.ContentId >= 0 && ((seg.Role == constants.RolePrimary) || (seg.PrefRole == constants.RolePrimary))
updated.

2024-01-17 11:00 UTC, piyushc01 commented on gpMgmt/bin/go-tools/utils/greenplum/gparray.go
> +		fmt.Println(addSegmentQuery)
Removery the printLn

2024-01-17 11:01 UTC, piyushc01 commented on gpMgmt/bin/go-tools/utils/sys_utils.go
> +	file, err := System.Create(filename)
Added more details to the function along with an explanation.

2024-01-17 11:02 UTC, piyushc01 commented on gpMgmt/bin/go-tools/utils/sys_utils_test.go
> +		file, err := os.CreateTemp("", "")
Updated the tests

2024-01-17 11:03 UTC, piyushc01 commented on gpMgmt/bin/go-tools/utils/postgres/update_conf_files.go
> +	if _, err := strconv.ParseFloat(value, 64); err == nil {
Updated with description and function name to `quoteIfString`. 
Quotes to be added only if its a string and not a number.

2024-01-19 06:47 UTC, piyushc01 commented on gpMgmt/bin/go-tools/utils/greenplum/gparray.go
> +func (gpArray *GpArray) ReadGpSegmentConfig(conn *dbconn.DBConn) error {
Cleaned the code. 
Will be a good idea to put this in go-common-libs.

2024-01-22 12:14 UTC, piyushc01 commented on gpMgmt/bin/go-tools/cli/init.go
> +func InitClusterServiceFn(hubConfig *hub.Config, inputConfigFile string, force, verbose bool) error {
updated

2024-01-22 12:15 UTC, piyushc01 commented on gpMgmt/bin/go-tools/cli/init.go
> +	initCmd.PersistentFlags().Bool("force", false, "Create cluster forcefully by overwriting existing directories")
Updated

2024-01-22 12:16 UTC, piyushc01 commented on gpMgmt/bin/go-tools/utils/sys_utils.go
> +	_, err = file.WriteString(strings.Join(lines, "\n"))
I have updated the function description. 
Function expected to overwrite the file.

2024-01-22 12:16 UTC, piyushc01 commented on gpMgmt/bin/go-tools/cli/init.go
> +	OsStat                               = os.Stat
Done

2024-01-22 12:17 UTC, piyushc01 commented on gpMgmt/bin/go-tools/cli/init.go
> +	if len(args) == 0 {
Need this to check if the input file-name is provided. 
Also this checks if any extra arguments provided.

2024-01-23 10:35 UTC, jnihal commented on gpMgmt/bin/go-tools/cli/init.go
> +func ValidateInputConfigAndSetDefaultsFn(request *idl.MakeClusterRequest) error {
I do not see any checks for locale here, if the user does not provide any value are we setting any defaults and if not should not we prompt the user to enter it?

2024-01-23 10:35 UTC, jnihal commented on gpMgmt/bin/go-tools/agent/validate_host_env.go
> +	codesetAndModifier := strings.Split(localeSplit[1], "@")
There should be a check to guarantee the number of result returned by the `Split()` method is greater than 1 before we index it, or else this might lead to panic.

2024-01-23 10:45 UTC, jnihal commented on gpMgmt/bin/go-tools/cli/init.go
> +	if err := viper.Unmarshal(&config); err != nil {
use `UnmarshalExact()` to make sure that the user cannot give any invalid keys.

2024-01-23 10:50 UTC, piyushc01 commented on gpMgmt/bin/go-tools/cli/init.go
> +	hostnames = append(hostnames, request.GpArray.Coordinator.HostName)
the `request` is an IDL structure  (used by gRPC) that is auto-generated from the proto file. 
In the function, we are extracting details from the RPC request to process further.

2024-01-23 11:31 UTC, piyushc01 commented on gpMgmt/bin/go-tools/cli/init.go
> +	if len(request.GpArray.Primaries) == 0 {
Done

2024-01-23 11:31 UTC, piyushc01 commented on gpMgmt/bin/go-tools/cli/init.go
> +		return &idl.MakeClusterRequest{}, fmt.Errorf("error while reading config file: %w", err)
Done

2024-01-23 11:32 UTC, piyushc01 commented on gpMgmt/bin/go-tools/cli/init.go
> +		return fmt.Errorf("error parsing max_connections from json: %v", err)
Done

2024-01-23 11:36 UTC, piyushc01 commented on gpMgmt/bin/go-tools/utils/sys_utils.go
> +	return
The function had a named return value hence not specific return value was required. 
Updated function definition to return value and added unit tests around the same.

2024-01-24 05:40 UTC, piyushc01 commented on gpMgmt/bin/go-tools/cli/init.go
> +	if _, ok := request.ClusterParams.CoordinatorConfig["max_connections"]; !ok {
Updated to check max connects from common-config. 
Precedence will be given to Coordinator-config if both are provided.

2024-01-24 12:32 UTC, piyushc01 commented on gpMgmt/bin/go-tools/agent/validate_host_env.go
> +	codesetAndModifier := strings.Split(localeSplit[1], "@")
Updated function to check split lenth.

2024-01-24 12:34 UTC, piyushc01 commented on gpMgmt/bin/go-tools/cli/init.go
> +	hostToPortDataDirectory := make(map[string]map[string]bool)
Updated to make use of 2 maps. 
For the directory, check for the host-name. 
In the case of port, checking for address as socket can be created per address-port.

2024-01-24 12:36 UTC, piyushc01 commented on gpMgmt/bin/go-tools/cli/init.go
> +	hostToPortDataDirectory := make(map[string]map[string]bool)
@jnihal we might want to check if Greenplum/Postgress supports having multiple ports on a host. 
If not supported in Greenplum, we can modify the check to validate on host-name instead of address.

2024-01-30 10:00 UTC, jnihal commented on gpMgmt/bin/go-tools/cli/init.go
> +		if hostToDataDirectory[primary.HostName][primary.DataDirectory] {
The inside map does not have memory assigned with data-directory as key value, which might lead to segmentation fault and panic the server.
We should instead use `if _, ok := hostToDataDirectory[primary.HostName][primary.DataDirectory]; ok {`

2024-01-30 10:01 UTC, jnihal commented on gpMgmt/bin/go-tools/cli/init.go
> +	if _, ok := request.ClusterParams.CommonConfig["shared_buffers"]; !ok {
Similar comments as `max_connections`, what if the user provides through `coordinator-config` or `segment-config`?

2024-01-30 10:06 UTC, jnihal commented on gpMgmt/bin/go-tools/cli/init.go
> +		} else {
Why do we need to set the value again in `coordinator-config`?

2024-02-05 06:44 UTC, piyushc01 commented on gpMgmt/bin/go-tools/utils/postgres/update_conf_files.go
> +				if !overwrite {
Updated code to skip commented lines and break when a match is found from the map.

2024-02-08 06:21 UTC, shrakesh commented on gpMgmt/bin/go-tools/utils/postgres/update_conf_files.go
> +	gplog.Info("Updating %s for data directory %s with: %s", postgresqlConfFile, pgdata, configParams)
can this message be logged as debug instead of info?

2024-02-08 06:45 UTC, shrakesh commented on gpMgmt/bin/go-tools/utils/postgres/update_conf_files.go
> +	file, err := utils.System.Create(postgresInternalConfFilePath)
internal.auto.conf file gets created by the server in initdb action. recreating it may cause an issue if the server starts putting any content on the file.  try to avoid recreation of file and just append the content.

2024-02-08 07:27 UTC, jnihal commented on gpMgmt/bin/go-tools/cli/init.go
> +	}
Since we are checking this value across the segments, this check should only belong in the `agent` and we should remove this from the `CLI`

2024-02-08 07:27 UTC, jnihal commented on gpMgmt/bin/go-tools/cli/init.go
> +	}
We should not populate the `hostname` value as `host-address`. Host address corresponds to the individual network interfaces belonging to a host. Let us say we have a host named `sdw1` with 2 addresses `sdw1-1` and `sdw1-2` and the user does not populate the hostname field. By following this logic, the hostname will be assigned 2 different values even though they belong to the same host and this might cause unexpected behavior like - for example, during validation of data directories, if the user has given the same data directories for both `sdw1-1` and `sdw1-2`, the validation would succeed as the hostname would be different but it is not true since both of the data directories will be created on the same host.

2024-02-08 07:27 UTC, jnihal commented on gpMgmt/bin/go-tools/cli/init.go
> +	}
Move these checks to `line 246` just after we have checked if the segment details are provided and before we start validating the postgres config parameters and checking if `gp services` are enabled.

2024-02-08 08:45 UTC, jnihal commented on gpMgmt/bin/go-tools/cli/init.go
> +	cmd := utils.System.ExecCommand(fmt.Sprintf("/usr/bin/locale"))
Use `filepath.Join()`

2024-02-14 05:48 UTC, shrakesh commented on gpMgmt/bin/go-tools/agent/validate_host_env.go
> +			gplog.Error("failed to get user name Error:%v. Current user is a root user. Can't create cluster under root", err)
can create a common string using fmt.Scanf to avoid duplication of strings. this will avoid duplicate edits in case of updating of the error message and also will not appear multiple times when we do an error-based search on the source code.

2024-02-14 05:49 UTC, shrakesh commented on gpMgmt/bin/go-tools/agent/validate_host_env.go
> +	pgVersionErr := VerifyPgVersion(request.GpVersion, s.GpHome)
can we check if we can break the checks into small generic utilities?

2024-02-14 06:04 UTC, shrakesh commented on gpMgmt/bin/go-tools/constants/constants.go
> +func GetDefaultHubLogDir() string {
IMO we should move this function to another utility file. this file is supposed to be to declare the constants only.

2024-02-21 06:34 UTC, piyushc01 commented on gpMgmt/bin/go-tools/cli/init.go
> +	hostToPortDataDirectory := make(map[string]map[string]bool)
with @jnihal as confirmed, GPDB does not support listening on individual ports and always creates sockets on all (*) interfaces. In the function `CheckForDuplicatPortAndDataDirectoryFn` we should check for ports across host and not on individual address.

2024-02-28 10:29 UTC, piyushc01 commented on gpMgmt/bin/go-tools/cli/init.go
> +	hostToPortDataDirectory := make(map[string]map[string]bool)
Updated the validation to check the port in use on all the host interfaces.

2024-03-04 05:24 UTC, shrakesh commented on gpMgmt/bin/go-tools/go.mod
>  	github.com/greenplum-db/gp-common-go-libs v1.0.11
We can update this to latest version of gp-common-go-libs ([v1.0.15](https://github.com/greenplum-db/gp-common-go-libs/releases/tag/v1.0.15))

2024-03-04 12:13 UTC, shrakesh commented on gpMgmt/bin/go-tools/Makefile
> +	go test -v -count=1 $(TEST_PACKAGES) -timeout 0 -p 1 -args -hostfile=$(FILE)
A meaning full error or default value should be provided if the user running make integration without hostfile name parameter

2024-03-04 12:14 UTC, shrakesh commented on gpMgmt/bin/go-tools/Makefile
> +integration: TEST_PACKAGES := $(shell go list ./test/integration/... | grep -E $(UTILITY))
not able to get why we are using the UTILITY empty string, is it for future purposes?

2024-03-04 12:16 UTC, shrakesh commented on gpMgmt/bin/go-tools/agent/make_segment.go
> +		Locale:        locale.LcAll,
can we have a separate structure for locale related parameters?

2024-03-04 12:16 UTC, shrakesh commented on gpMgmt/bin/go-tools/agent/make_segment.go
> +Followed by updating the configuration (pg_hba.conf, postgresql.con)
nit: postgresql.con -> postgresql.conf

2024-03-04 12:20 UTC, shrakesh commented on gpMgmt/bin/go-tools/utils/postgres/commands.go
> +func (cmd *Initdb) BuildExecCommand(gphome string) *exec.Cmd {
nit : gphome -> gpHome (other places as well)

2024-03-04 12:23 UTC, shrakesh commented on gpMgmt/bin/go-tools/utils/postgres/commands.go
> +type PgCtlStart struct {
can we add some list in some comments to quickly check what command is implemented. this file will grow and later point of time it will be difficult to trace. 
Can we do something to quickly search what commands/RPC call is implemented?

2024-03-04 12:24 UTC, shrakesh commented on gpMgmt/bin/go-tools/utils/command_utils.go
> +	}
should it be an error/warning  in case of default or no matching type

2024-03-04 12:25 UTC, shrakesh commented on gpMgmt/bin/go-tools/utils/command_utils.go
> +	return path.Join(gphome, "bin", utility)
what if the utility is not present in the path, can we add a path check?

2024-03-04 12:27 UTC, shrakesh commented on gpMgmt/bin/go-tools/utils/command_utils.go
> +	gpSourceFilePath := filepath.Join(gphome, "greenplum_path.sh")
what if the greenplum_path.sh file is not present, can we add a check or we relying on command output ?

2024-03-04 12:28 UTC, shrakesh commented on gpMgmt/bin/go-tools/utils/command_utils.go
> +		return stdout, err
nit: else block is not required we can directly return stdout, err

2024-03-04 13:00 UTC, shrakesh commented on gpMgmt/bin/go-tools/utils/postgres/update_conf_files.go
> +	for scanner.Scan() {
as far as i can understand we are just adding coordinator entries and access entries to the end of the file.  for that do we need to really read the complete file or is there any better way in go to just add new entries at the end?

2024-03-04 15:20 UTC, shrakesh commented on gpMgmt/bin/go-tools/agent/start_segment.go
> +		Logfile: filepath.Join(in.DataDir, "log", "startup.log"),
consider a request to land the startup.log into the guc set by log_directory or next to where gpsegstart's log is configured.

2024-03-04 15:35 UTC, shrakesh commented on gpMgmt/bin/go-tools/agent/validate_host_env.go
> +	pgVersionErr := VerifyPgVersion(request.GpVersion, s.GpHome)
the naming at pgVersionErr := VerifyPgVersion(request.GpVersion, s.GpHome)
is confusing to me as internally we are validating only gp version with given gp version. GetPostgresGpVersion() internally calls postgres --gp-version to get the gp version.

2024-03-04 15:39 UTC, shrakesh commented on gpMgmt/bin/go-tools/agent/validate_host_env.go
> +			gplog.Error("Directory:%s Error checking if empty:%s", dir, err.Error())
is there any reason why we are considering dir as nonempty if we get an error from CheckDirEmpty()?

2024-03-04 15:47 UTC, shrakesh commented on gpMgmt/bin/go-tools/agent/validate_host_env.go
> +	if len(nonEmptyDirList) > 0 && !forced {
in case of !forced we only need to check if any of the directory is not empty(bool check) to error out. in this case we will not required to collect all the nonempty directory unnecessary. 
 we can just check first nonempty directory and return if found any. 
 
 in case of forced can we clean out all the given directories?  this will avoid fetching list. this can optimize few cycles. 
 just a suggestion, I will leave this up to you.

2024-03-04 15:53 UTC, shrakesh commented on gpMgmt/bin/go-tools/agent/validate_host_env.go
> +		gplog.Info("Got error while validating locale %v", err)
i feel there is no consistency when we are putting info/verbose message in this function during most of the checks. can we revisit and check when  is reasonable to have  info/verbose message and when not.

2024-03-04 16:22 UTC, shrakesh commented on gpMgmt/bin/go-tools/agent/validate_host_env.go
> +
from function GetPostgresGpVersion() which internally runs below command and get following output. 
postgres --gp-version
postgres (Greenplum Database) 7.1.0+dev.143.g456f6cf400f build dev

to validate version are we trying to compare the output of the command or only the version number ?

2024-03-04 16:26 UTC, shrakesh commented on gpMgmt/bin/go-tools/agent/validate_host_env.go
> +			switch v := addr.(type) {
if we are not expecting any case for type and it will be only 1 case in switch, can we convert it to if case just to make simple.

2024-03-04 16:38 UTC, shrakesh commented on gpMgmt/bin/go-tools/agent/validate_host_env.go
> +	var ipList []string
line 201, 204, 205 can be combine 
ipList := []string{"0.0.0.0", "::"}

2024-03-04 16:41 UTC, shrakesh commented on gpMgmt/bin/go-tools/agent/validate_host_env.go
> +			listener.Close()
this should be in differ because we have return statement before listner.Close() this can keep port open accidently.

2024-03-04 16:43 UTC, shrakesh commented on gpMgmt/bin/go-tools/agent/validate_host_env.go
> +			listener, err := net.Listen("tcp", net.JoinHostPort(ip, port))
inner for loop can be a separate utility function to check port in use. 

similar we can have a extracted code from line 221-222 to make a utility function to get ipaddrs

2024-03-05 05:36 UTC, shrakesh commented on gpMgmt/bin/go-tools/agent/validate_host_env.go
> +	return ""
nit : return "" -> return s 

same can be at line 407

2024-03-05 06:45 UTC, shrakesh commented on gpMgmt/bin/go-tools/cli/init.go
> +	if segment.HostName == "" && segment.HostAddress == "" {
I feel the first check is redundant, do we really need to have ?
 segment.HostName == "" && segment.HostAddress == ""
 As we are checking both individually

2024-03-05 06:50 UTC, shrakesh commented on gpMgmt/bin/go-tools/cli/init.go
> +	hostnames = []string{}
can we combine line 394 and 395

2024-03-05 09:51 UTC, jnihal commented on gpMgmt/bin/go-tools/cli/init.go
> +	if segment.HostName == "" && segment.HostAddress == "" {
We need this check to know when both hostname and address is not given and error out.

2024-03-05 12:44 UTC, shrakesh commented on gpMgmt/bin/go-tools/cli/init.go
> +		request.ClusterParams.Encoding = "UTF-8"
request.ClusterParams.Encoding = "UTF-8" this should be 
  request.ClusterParams.Encoding = constants.DefaultEncoding

2024-03-06 05:59 UTC, shrakesh commented on gpMgmt/bin/go-tools/utils/greenplum/commands.go
> +	gpstart = "gpstart"
out of curiosity why we need to call greenplum commands to start and stop after cluster setup. 
1. can we utilize the pg_ctl RPC to start/stop segment as this is internal call and options are fix. 
2. if we go with rpc call to start/stop the performance would be better than current gpstart/gpstop command. 
3. for the future this will set up a base for start/stop rewriting.  
can we think of to adhere with rpc call as much as possible?

2024-03-06 06:06 UTC, shrakesh commented on gpMgmt/bin/go-tools/utils/greenplum/gparray.go
> +	conn := dbconn.NewDBConn("template1", user.Username, host, port)
We have a constant defined as DefaultDbName for template1, can we use that for all the instances instead of template1 hardcode value, the DefaultDbName is not yet used any where.

2024-03-06 06:08 UTC, shrakesh commented on gpMgmt/bin/go-tools/constants/constants.go
> +	SecurityLimitsConf  = "/etc/security/limits.conf"
is there a plan to use SecurityLimitsConf and SecurityLimitsdDir as these constants are not being used anywhere till now. 
same with DefaultDbName it is defined but not utilized.

2024-03-06 06:21 UTC, shrakesh commented on gpMgmt/bin/go-tools/utils/greenplum/gparray.go
> +	_, err := conn.Exec(fmt.Sprintf(addCoordinatorQuery, int(seg.Port), seg.HostName, seg.HostAddress, seg.DataDirectory))
do we need to type cast int(seg.Port), in the segment structure the type of port is already uint32.

2024-03-06 06:27 UTC, shrakesh commented on gpMgmt/bin/go-tools/utils/greenplum/utils.go
> +func GetPostgresGpVersion(gphome string) (string, error) {
i found this a little confusing with the name of the function and return output. 
output return of postgres --gp-version would be 
postgres (Greenplum Database) 7.1.0+dev.143.g456f6cf400f build dev
so are we looking for substring  7.1.0  or complete version string ?

2024-03-06 09:32 UTC, piyushc01 commented on gpMgmt/bin/go-tools/agent/make_segment.go
> +func (s *Server) MakeSegment(ctx context.Context, request *idl.MakeSegmentRequest) (*idl.MakeSegmentReply, error) {
that's the standard practice in go which we are also following

2024-03-06 10:58 UTC, piyushc01 commented on gpMgmt/bin/go-tools/agent/validate_host_env.go
> +			gplog.Error("Directory:%s Error checking if empty:%s", dir, err.Error())
Updating to return error when fails to open the directory itself

2024-03-06 15:55 UTC, shrakesh commented on gpMgmt/bin/go-tools/utils/postgres/update_conf_files.go
> +				line = fmt.Sprintf("%s = %s", key, quoteIfString(value))
here in case of !overwrite we are commenting out existing key value pair and adding a new at the next line. in this case the commented settings will be accumulating mostly in case of mirror promotion or gprecoverseg where we update the port after recovery. 

the other problem is this accumulating commented key=value may create an issue while updating config with gp commands where we are using sed utility to update the config file.

2024-03-06 15:58 UTC, shrakesh commented on gpMgmt/bin/go-tools/utils/postgres/update_conf_files.go
> +	} else {
nit: else block is not required we can directly return fmt.Sprintf("'%s'", value) at the end of the function.

2024-03-07 06:01 UTC, jnihal commented on gpMgmt/bin/go-tools/Makefile
> +	go test -v -count=1 $(TEST_PACKAGES) -timeout 0 -p 1 -args -hostfile=$(FILE)
If the hostfile is not provided, it will run the tests on localhost - https://github.com/greenplum-db/gpdb/blob/bc53451c1466fbbc4f108cf67a38e9207b97fdd6/gpMgmt/bin/go-tools/test/integration/configure/configure_suite_test.go#L64

2024-03-07 06:03 UTC, jnihal commented on gpMgmt/bin/go-tools/Makefile
> +integration: TEST_PACKAGES := $(shell go list ./test/integration/... | grep -E $(UTILITY))
This is initialising the variable in the Makefile, we could then use it as `make integration UTILITY=start` for example to run start related tests.

2024-03-07 06:05 UTC, jnihal commented on gpMgmt/bin/go-tools/agent/make_segment.go
> +		Locale:        locale.LcAll,
The input request comes in the form of idl data type (protobuf structure), and we would need to convert it into a GoLang structure in a similar way by assigning each value, so instead better to assign them directly.

2024-03-07 06:09 UTC, jnihal commented on gpMgmt/bin/go-tools/utils/command_utils.go
> +	return path.Join(gphome, "bin", utility)
The purpose of this function is to just construct the path, adding an error check here would complicate things as we would need to add error checks for each calling function.
Anyways we will get an appropriate error when we run the command using `exec.Command`.
```
exec: "utility": executable file not found in $PATH
```

2024-03-07 06:10 UTC, jnihal commented on gpMgmt/bin/go-tools/utils/command_utils.go
> +	gpSourceFilePath := filepath.Join(gphome, "greenplum_path.sh")
We are relying on the command output, which would indicate if the path is not present.

2024-03-07 06:11 UTC, jnihal commented on gpMgmt/bin/go-tools/utils/command_utils.go
> +	err := cmd.Run()
In Golang, the `err` value we get is usually an error code (`exit status 1` for example), so no need to check.

2024-03-07 06:15 UTC, piyushc01 commented on gpMgmt/bin/go-tools/hub/make_cluster.go
> +	createDbQuery := fmt.Sprintf("CREATE DATABASE %s", dbname)
Add quotes to the dname in the query. 
Currently, DB creation fails with following error if there's a hyphen in the DB name: 
```
[INFO]:-Creating database "gpdb-1234"
[ERROR]:-ERROR: syntax error at or near "-" (SQLSTATE 42601)
```

```suggestion
	createDbQuery := fmt.Sprintf("CREATE DATABASE \"%s\"", dbname)
```

2024-03-07 06:24 UTC, piyushc01 commented on gpMgmt/bin/go-tools/agent/validate_host_env.go
> +	if len(nonEmptyDirList) > 0 && !forced {
It is better not to delete blindly. 
It is better if we delete only those that are non-empty

2024-03-07 07:35 UTC, jnihal commented on gpMgmt/bin/go-tools/utils/command_utils.go
> +	}
Refactored the way we build commands. In case of an unsupported type, an error will be logged.

2024-03-07 07:35 UTC, jnihal commented on gpMgmt/bin/go-tools/utils/postgres/update_conf_files.go
> +	for scanner.Scan() {
Good finding, updated the code to just append the lines.

2024-03-07 08:08 UTC, piyushc01 commented on gpMgmt/bin/go-tools/hub/make_cluster.go
> +	alterPasswdQuery := fmt.Sprintf("ALTER USER %s WITH PASSWORD '%s'", user.Username, passwd)
Add quotes to user string, can throw an error when there's a hyphen in the user-name.

```suggestion
	alterPasswdQuery := fmt.Sprintf("ALTER USER \"%s\" WITH PASSWORD '%s'", user.Username, passwd)
```

2024-03-07 08:51 UTC, piyushc01 commented on gpMgmt/bin/go-tools/agent/validate_host_env.go
> +			switch v := addr.(type) {
`.type` is allowed to be used only with a switch hence mandatory to use a switch here

2024-03-07 09:40 UTC, piyushc01 commented on gpMgmt/bin/go-tools/agent/validate_host_env.go
> +		return &idl.ValidateHostEnvReply{}, fmt.Errorf("user:%s is a root user, Can't create cluster under root user", userInfo.Name)
On line 49, we try to get the current user name, and if that fails, we report an error along with a root user error. 
If we successfully get the user-name, we add the current user-name to the returns error message. 
In both cases, we need to return the error to CLI.

2024-03-07 09:53 UTC, piyushc01 commented on gpMgmt/bin/go-tools/agent/validate_host_env.go
> +	}
here we list all the ports of the host that are already in use hence not returning immediately and continuing checking for other ports.

2024-03-07 10:23 UTC, piyushc01 commented on gpMgmt/bin/go-tools/agent/validate_host_env.go
> +	pgVersionErr := VerifyPgVersion(request.GpVersion, s.GpHome)
updated

2024-03-07 10:25 UTC, piyushc01 commented on gpMgmt/bin/go-tools/agent/validate_host_env.go
> +	return ""
updated

2024-03-07 10:25 UTC, piyushc01 commented on gpMgmt/bin/go-tools/agent/validate_host_env.go
> +		gplog.Error("Postgres gp-version validation failed:%v", pgVersionErr)
updated the descitpion

2024-03-07 10:25 UTC, piyushc01 commented on gpMgmt/bin/go-tools/agent/validate_host_env.go
> +		gplog.Verbose("Forced init. Deleting non-empty directories:%s", dirList)
updated

2024-03-07 10:26 UTC, piyushc01 commented on gpMgmt/bin/go-tools/agent/validate_host_env.go
> +		return fmt.Errorf("error getting file info:%v", err)
updated

2024-03-07 10:49 UTC, piyushc01 commented on gpMgmt/bin/go-tools/utils/greenplum/utils.go
> +func GetPostgresGpVersion(gphome string) (string, error) {
Checking for the entire version as we need to make sure all the hosts in the cluster are on same GPDB build and version.

2024-03-07 10:50 UTC, piyushc01 commented on gpMgmt/bin/go-tools/utils/greenplum/utils.go
> +func GetPostgresGpVersion(gphome string) (string, error) {
Updated variable name to reflect GP version.

2024-03-08 10:59 UTC, piyushc01 commented on gpMgmt/bin/go-tools/utils/postgres/commands.go
> +type PgCtlStart struct {
functions are already categorised to distinguish the usage

2024-03-08 11:01 UTC, piyushc01 commented on gpMgmt/bin/go-tools/agent/start_segment.go
> +		Logfile: filepath.Join(in.DataDir, "log", "startup.log"),
guc is not set when instance is created using initdb. 
We can look at this when implementing gpstart.

2024-03-08 11:02 UTC, piyushc01 commented on gpMgmt/bin/go-tools/agent/validate_host_env.go
> +		gplog.Info("Got error while validating locale %v", err)
updated codebase to use a common utility function for logging the error. 
removed verbose/info messages. Hub and agent will now only have debug/warning/error messages.

2024-03-08 11:03 UTC, piyushc01 commented on gpMgmt/bin/go-tools/utils/greenplum/commands.go
> +	gpstart = "gpstart"
as gpstart is doing many other checks that start the segments and also perform certain initialization steps, it is better to take it as a separate PR.

2024-03-11 10:47 UTC, piyushc01 commented on gpMgmt/bin/go-tools/cli/init.go
> +	if segment.HostName == "" && segment.HostAddress == "" {
updated the check

2024-03-11 10:47 UTC, piyushc01 commented on gpMgmt/bin/go-tools/agent/validate_host_env.go
> +			listener.Close()
updated

2024-03-11 11:37 UTC, shrakesh approved these changes
LGTM. 
Pipeline is green, reviewed all resolved comments.

2024-03-11 19:23 UTC, Annu149 approved these changes
Thanks for addressing all the comments. 
Looks good to me

2024-03-12 02:55 UTC, ravoorsh approved these changes
LGTM

2024-03-12 10:45 UTC, piyushc01 commented on gpMgmt/bin/go-tools/agent/make_segment.go
> +MakeSegment implements RP to crate single instance of segment
fixed

2024-03-12 10:50 UTC, piyushc01 commented on gpMgmt/bin/go-tools/agent/validate_host_env.go
> +			strErr := fmt.Sprintf("error getting list of addreses for interface %s. Error:%v", iface.Name, err)
updated

2024-03-26 07:27 UTC, merged