fix flakyness in gpmovemirror demo cluster without-assert build
greenplum-db/gpdb pull request #17071
Opened 2024-02-08 03:41 UTC by SunilS26

gpmovemirror demo cluster was flaky and failing at below test "gpmovemirrors gives warning if pg_basebackup is already running for all mirrors to be moved ".

In the above test the gprecoverseg is triggered for inplace mirror recovery in asynchronous mode and then parallely gpmovemirror is triggered for the same set of mirror's. Since gprecoverseg is running in background the mirror data directory is not consistent and gomovemirror will calculates the size of the mirror data directory before invoking gprecoverseg, which was falking out sometimes in gpdb without-assert build.

Hence the changes are done so that the original intention of the test is met to fix this flakynes.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2024-02-08 06:20 UTC, Annu149 requested changes

2024-02-08 06:20 UTC, Annu149 commented on gpMgmt/test/behave/mgmt_utils/gpmovemirrors.feature
> -    And check if mirrors on content 0,1,2 are in their original configuration
We can add step "And check if mirrors on content 0,1,2 are moved to new location on input file" to verify movement of mirrors

2024-02-08 06:20 UTC, Annu149 commented on gpMgmt/test/behave/mgmt_utils/gpmovemirrors.feature
> -    And check if mirrors on content 0,1,2 are in their original configuration
Also Can we move line 350 and 351(where checking for return codes) above 349 (Then gprecoverseg should print "Found pg_basebackup running for segments with contentIds [0, 1, 2], skipping recovery of these segments" to logfile) ? This will help us easily understand what has failed (gpmovemirrors/gprecoverseg) in future. And if the utility has failed it will not go ahead and check for output.

2024-02-08 06:20 UTC, Annu149 commented on gpMgmt/test/behave/mgmt_utils/gpmovemirrors.feature
> +    When the user asynchronously runs gprecoverseg with input file and additional args "-aF" and the process is saved
here -F is redundant , anyway full recovery will happen

2024-02-08 11:53 UTC, SunilS26 commented on gpMgmt/test/behave/mgmt_utils/gpmovemirrors.feature
> -    And check if mirrors on content 0,1,2 are in their original configuration
> We can add step "And check if mirrors on content 0,1,2 are moved to new location on input file" to verify movement of mirrors

This will compare   gpmovemirror configuration file location, which will not happen.

2024-02-09 04:34 UTC, Annu149 commented on gpMgmt/test/behave/mgmt_utils/gpmovemirrors.feature
> -    And check if mirrors on content 0,1,2 are in their original configuration
ohh yes, mirrors will not move. thanks

2024-02-09 06:02 UTC, Annu149 approved these changes
Looks good to me

2024-02-09 06:10 UTC, merged