Add hint message for MTU settings when IC reports ERROR "Failed to send packet"
greenplum-db/gpdb pull request #17164
Opened 2024-03-07 09:04 UTC by z-wenlin

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2024-03-07 09:39 UTC, interma requested changes
just needs small improvement.

2024-03-07 09:39 UTC, interma commented on src/backend/cdb/motion/ic_udpifc.c
> +		char errDetail[100];
It's an uninitialized variable in the stack.
And let's use `errhint()` for the details here.
(You can find many examples in code)

2024-03-11 06:32 UTC, interma commented on src/backend/cdb/motion/ic_udpifc.c
> +				buf->pkt->seq == 1 ? errhint("Check the MTU configuration and the GUC gp_max_packet_size,set the same MTU values across the cluster and gp_max_packet_size less than the MTU value.") : 0));
looks missing a space between `... gp_max_packet_size,set the same ...`.

2024-03-11 06:32 UTC, interma approved these changes
LGTM

2024-03-11 21:03 UTC, soumyadeep2007 commented on src/backend/cdb/motion/ic_udpifc.c
> +				buf->pkt->seq == 1 ? errhint("Check the MTU configuration and the GUC gp_max_packet_size,set the same MTU values across the cluster and gp_max_packet_size less than the MTU value.") : 0));
There are a few things here:

(1) There is nothing definitive here that indicates that there were MTU related errors. It could have been **some other issue** as well with sending packets and `seq == 1` could be true.
(2) Did we investigate why we don't ERROR out and print `Message too long` (EMSGSIZE):
```
ereport(ERROR, (errcode(ERRCODE_GP_INTERCONNECTION_ERROR),
						errmsg("Interconnect error writing an outgoing packet: %m"),
						errdetail("error during sendto() call (error:%d).\n"
								  "For Remote Connection: contentId=%d at %s",
								  errno, conn->remoteContentId,
								  conn->remoteHostAndPort)));
```
when MTU is too large. If we can make it ERROR out here (with the HINT added iff we get EMSGSIZE), our problem is solved.

2024-03-12 05:16 UTC, soumyadeep2007 commented on src/backend/cdb/motion/ic_udpifc.c
> +				buf->pkt->seq == 1 ? errhint("Check the MTU configuration and the GUC gp_max_packet_size,set the same MTU values across the cluster and gp_max_packet_size less than the MTU value.") : 0));
To add on to my comments above, one additional observation is that "there is no need to retry if it is a MTU related issue, we should fail on the first send"

2024-03-13 08:12 UTC, z-wenlin commented on src/backend/cdb/motion/ic_udpifc.c
> +				buf->pkt->seq == 1 ? errhint("Check the MTU configuration and the GUC gp_max_packet_size,set the same MTU values across the cluster and gp_max_packet_size less than the MTU value.") : 0));
I thought the reason we don't error out is that `sendto()` returns the positive number so it doesn't go to the error flow before,  just like you mentioned in Slack. 
Also referenced the https://stackoverflow.com/questions/11809727/sendto-returns-values-greater-than-mtu-on-sock-dgram-udp-socket
But later I wrote some UDP sockets demo and found that for this kind of `EMSGSIZE`, the n would be -1
```
bytes sent: -1
Could not send message: Message too long
```
I agree that we could error out if we get the `EMSGSIZE` error, but the `sendto()` return value maybe depends on the different platform. Some network equipment in between will discard fragmented packets, while some will pass them through. 

Maybe we could add the check for this kind of error `EMSGSIZE`, if the error happens, we will give a hint about MTU and stop the retry.

2024-03-13 19:16 UTC, soumyadeep2007 commented on src/backend/cdb/motion/ic_udpifc.c
> +		 * single datagram, which might be due to MTU problem. Give a hint and stop retry.
Slightly reword:
```
Network equipment may drop packets with size bigger than MTU, which the OS may or may not detect.
If the OS does detect it, we would get EMSGSIZE here. So, bail with a HINT about checking MTU.
```

2024-03-13 19:16 UTC, soumyadeep2007 commented on src/backend/cdb/motion/ic_udpifc.c
> +				buf->pkt->seq == 1 ? errhint("Check the MTU configuration and the GUC gp_max_packet_size,set the same MTU values across the cluster and gp_max_packet_size less than the MTU value.") : 0));
At a high level I see 2 issues:
(1) MTU setting is incompatible on network interfaces lying inside GP hosts
(2) MTU setting is incompatible on on network interfaces lying inside intermediate network equipment (routers/switches)

> I thought the reason we don't error out is that sendto() returns the positive number so it doesn't go to the error flow before, just like you mentioned in Slack.

That was my theory. It wasn't confirmed. :) 

> But later I wrote some UDP sockets demo and found that for this kind of EMSGSIZE, the n would be -1

Thank you for running this experiment. Yes, according to the [man page](https://man7.org/linux/man-pages/man3/sendto.3p.html):
```
Upon successful completion, sendto() shall return the number of
       bytes sent. Otherwise, -1 shall be returned and [errno](https://man7.org/linux/man-pages/man3/errno.3.html) set to
       indicate the error.
```

And that is how system calls should behave. They usually all return -1 on error.

> Some network equipment in between will discard fragmented packets, while some will pass them through.

**I think this is what happened in the field reported case, i.e. issue number (2)**. Also the following statement from the [glibc manual](https://www.gnu.org/software/libc/manual/html_node/Sending-Datagrams.html) shows that error reporting from `sendto` is not necessarily reliable:
```
The return value and error conditions are also the same as for send, but you cannot rely on the
system to detect errors and report them; the most common error is that the packet is lost or there
is no-one at the specified address to receive it, and the operating system on your machine usually
does not know this.
```

**What that means is we can't detect failure type (2) in our socket code, which relies on the host OS.**
`ioctl(socketfd, SIOCGIFMTU)`: This can't either as this can only detect (1) and with our code we already detect (1).

I think we need to design something in gpcheckperf that does a cluster wide test, taking the equipment into account. What we have for this PR is okay to go in. The ^ is a bigger effort.

2024-03-13 19:18 UTC, soumyadeep2007 reviewed
We should write a fault injection test (maybe in icudp_full.sql) by modifying `testmode_sendto` and have a new `FINC_PKT_TOO_LONG` to simulate a `ERRMSGSIZE`.

2024-03-14 07:05 UTC, z-wenlin commented on src/backend/cdb/motion/ic_udpifc.c
> +				buf->pkt->seq == 1 ? errhint("Check the MTU configuration and the GUC gp_max_packet_size,set the same MTU values across the cluster and gp_max_packet_size less than the MTU value.") : 0));
Thanks Deep for your detailed suggestions. The minor tweaks have been fixed and I'll keep looking at the test case part.

2024-03-18 06:51 UTC, interma requested changes
In our offline test, we found some risks to ereprot log in the IC thread. 
Wenlin is working on fixing it.

2024-03-29 00:29 UTC, interma approved these changes
LGTM

2024-03-29 00:29 UTC, interma commented on src/include/cdb/cdbicudpfaultinjection.h
> +			if (!FINC_HAS_FAULT(fault_type))
It's better to add `is_pkt` condition like `if (!FINC_HAS_FAULT(fault_type) || !is_pkt)`, just in case (because we only focused on the package sending scenario in this PR).

2024-03-29 00:31 UTC, interma commented
In the process of this PR, we found it's no need to introduce an unlimited retry in the previous commit: https://github.com/greenplum-db/gpdb/commit/8cefc62f1b15d563a0f30647dccf4fc990c85b3b 

We will open another PR to refactor it later.

2024-04-07 01:54 UTC, merged