Fix bug for RestoreSnapshot()
greenplum-db/gpdb pull request #17259
Opened 2024-03-27 07:50 UTC by zhrt123

This PR fix bug: snapshot is uninitialized after allocation, and some fields are used without initials:
- haveDistribSnapshot
- speculativeToken
- ph_node

2024-03-27 08:42 UTC, adam8157 commented on src/backend/utils/time/snapmgr.c
> +	memset(snapshot, 0, sizeof(SnapshotData));
`MemoryContextAllocZero()`

2024-03-27 08:46 UTC, haolinw commented
Is that GPDB specific change for Upstream base code ? If so, please add comments such as "GPDB specific code ..." to clarify the purpose.

2024-03-27 08:47 UTC, adam8157 requested changes
These variables should be stored into and restored from `serialized_snapshot`, setting them to 0/false lost the information.

2024-03-28 07:19 UTC, zhrt123 commented
> Is that GPDB specific change for Upstream base code ? If so, please add comments such as "GPDB specific code ..." to clarify the purpose.

I will do it.

2024-03-28 07:21 UTC, zhrt123 commented on src/backend/utils/time/snapmgr.c
> +	memset(snapshot, 0, sizeof(SnapshotData));
This may create conflict with upstream, do we need to make this change?

2024-03-28 07:23 UTC, zhrt123 commented
> These variables should be stored into and restored from `serialized_snapshot`, setting them to 0/false lost the information.

hmm, we just set them to 0 when allocating the memory. Shall we store them when serializing snapshots?

2024-03-28 10:14 UTC, kainwen commented
Reading the commit message, it seems this PR is only for parallel workers. Given the fact that we still don't decide to fully support parallel workers yet. I don't think we should ship this as a separate PR.

Or, would you please create a case that current GPDB can hit the bug?

2024-03-29 04:53 UTC, zhrt123 commented
> Reading the commit message, it seems this PR is only for parallel workers. Given the fact that we still don't decide to fully support parallel workers yet. I don't think we should ship this as a separate PR.
> 
> Or, would you please create a case that current GPDB can hit the bug?

Not yet. But it still is a bug in a general function. Engineers who use this function may be affected and they need to find the bug and re-fix it.

2024-03-30 01:22 UTC, kainwen commented
> > Reading the commit message, it seems this PR is only for parallel workers. Given the fact that we still don't decide to fully support parallel workers yet. I don't think we should ship this as a separate PR.
> > Or, would you please create a case that current GPDB can hit the bug?
> 
> Not yet. But it still is a bug in a general function. Engineers who use this function may be affected and they need to find the bug and re-fix it.

Is it possible to create a case that trigger this BUG?

2024-04-01 03:23 UTC, zhrt123 commented
> > > Reading the commit message, it seems this PR is only for parallel workers. Given the fact that we still don't decide to fully support parallel workers yet. I don't think we should ship this as a separate PR.
> > > Or, would you please create a case that current GPDB can hit the bug?
> > 
> > 
> > Not yet. But it still is a bug in a general function. Engineers who use this function may be affected and they need to find the bug and re-fix it.
> 
> Is it possible to create a case that trigger this BUG?

hmm, currently no scene can trigger this bug in gpdb... We need to create a bgworker and pass the snapshot to this bgworker. Shall we add some C code to apply this test?

2024-04-01 05:38 UTC, kainwen commented
> > > > Reading the commit message, it seems this PR is only for parallel workers. Given the fact that we still don't decide to fully support parallel workers yet. I don't think we should ship this as a separate PR.
> > > > Or, would you please create a case that current GPDB can hit the bug?
> > > 
> > > 
> > > Not yet. But it still is a bug in a general function. Engineers who use this function may be affected and they need to find the bug and re-fix it.
> > 
> > 
> > Is it possible to create a case that trigger this BUG?
> 
> Currently, no scene can trigger this bug in gpdb... We need to create a bgworker and pass the snapshot to this bgworker. Shall we add some C code to apply this test? @kainwen

GDD and auto analyze (auto vacuum) will create bgworker, would you please  try to help verify those? @zhrt123

2024-04-01 11:24 UTC, adam8157 commented on src/backend/utils/time/snapmgr.c
> +	memset(snapshot, 0, sizeof(SnapshotData));
Upstream restores the snapshot with `speculativeToken` and `ph_node` uninitialized, worth submitting a patch.

2024-04-01 11:31 UTC, adam8157 commented
The `pg_export_snapshot()/ExportSnapshot()` handles `haveDistribSnapshot` well, I agree `SerializeSnapshot()` and `RestoreSnapshot()` generally should do that too.

It's just better to have a thing that proves it works, suggest having a case or converting this PR to a separate commit of your WIP parallel-worker-related PR.

2024-04-18 05:38 UTC, closed without merging