[gpinitsystem2.0]Added functional tests for expansion support
greenplum-db/gpdb pull request #17411
Opened 2024-04-29 09:31 UTC by srividyaky

This commit adds functional tests for expansion support changes pushed in the  PR 
https://github.com/greenplum-db/gpdb/pull/17335

init_cluster_config_validation_test.go - This contains tests related to the input init config provided with support for mirrors and functions to form default config with primary and mirror support
init_cluster_db_validation_test.go - This contains tests related to the database configuration checks after the cluster is successfully initialized with mirror support

2024-04-30 09:03 UTC, c0dehu1k requested changes

2024-04-30 09:03 UTC, c0dehu1k commented on gpMgmt/bin/go-tools/test/integration/init_cluster/init_cluster_config_validation_test.go
> +	t.Run("validate expansion with no coordinator details", func(t *testing.T) {
configFile := testutils.GetTempFile(t, "config.json")
		config := GetDefaultExpansionConfig(t)

		if err := config.WriteConfigAs(configFile); err != nil {
			t.Fatalf("failed to write config to file: %v", err)
		}

		result, err := testutils.RunInitCluster(configFile)
		if e, ok := err.(*exec.ExitError); !ok || e.ExitCode() != 1 {
			t.Fatalf("got %v, want exit status 1", err)
		}

These lines of code are repeated in every test case.. We should move it to utility functions.

2024-05-02 09:28 UTC, piyushc01 commented on gpMgmt/bin/go-tools/test/integration/init_cluster/init_cluster_config_validation_test.go
> +	t.Run("verify expansion without mirror support", func(t *testing.T) {
Expansion when mirrors are also specified.

2024-05-02 09:31 UTC, piyushc01 commented on gpMgmt/bin/go-tools/test/integration/init_cluster/init_cluster_config_validation_test.go
> +	t.Run("verify expansion without mirror support", func(t *testing.T) {
Expansion when mirror-base-port specified and not specified. 
Returns error when an expansion parameter is present and segment-array is also specified.

2024-05-02 09:31 UTC, piyushc01 commented on gpMgmt/bin/go-tools/test/integration/init_cluster/init_cluster_config_validation_test.go
> +	t.Run("verify expansion without mirror support", func(t *testing.T) {
detects multi-home when provided

2024-05-02 09:33 UTC, piyushc01 commented on gpMgmt/bin/go-tools/test/integration/init_cluster/init_cluster_config_validation_test.go
> +	t.Run("verify expansion without mirror support", func(t *testing.T) {
returns error when multi-home env, host have different number of interfaces e.g.:
sdw1: sdw1-1, sdw1-2
sdw2: sdw2-1, sdw2-2, sdw2-3
sdw3: sdw3-1, sdw3-2, sdw3-3

2024-05-15 07:17 UTC, srividyaky commented
updated in new PR

https://github.com/greenplum-db/gpdb/pull/17431

2024-05-15 07:17 UTC, closed without merging